In [30]:
import pandas as pd
import numpy as np

import glob
import re
import requests
import io
import os

In [31]:
interaction_data = pd.read_pickle("${SPARK_ACQUISITION_ROOT}/kinase_ml/data/interactions/interaction_exp.pkl")

In [32]:
interaction_data.head()

  substrate  kinase p_ind p_aa
0    P34901  Q05655   183    S
1    Q9UQL6  Q05655   259    S
2  P18433-2  Q05655   204    S
3    P61978  Q05655   302    S
4    P35570  Q05655   612    S

In [33]:
print("number of interactions experimentally validated to be queried")
print(interaction_data.shape[0])

number of interactions experimentally validated to be queried
55398

In [34]:
print("number of unique kinase accession to be queried")
unique_kinases = list(set(interaction_data["kinase"].values))
print(len(unique_kinases))

number of unique kinase accession to be queried
2331

In [35]:
print("number of unique phosphosite accession to be queried")
unique_substrates = list(set(interaction_data["substrate"].values))
print(len(unique_substrates))

number of unique phosphosite accession to be queried
7663

In [36]:
phosphosite_xl = pd.read_pickle("${SPARK_ACQUISITION_ROOT}/kinase_ml/data/pretraining/phosphosite_xl.pkl")
phosxl = list(set(phosphosite_xl["uniprot"]))

In [37]:
substrate_in_xl = [substrate in phosxl for substrate in unique_substrates]

In [38]:
interaction_data_mapped = pd.merge(interaction_data,phosphosite_xl,left_on = "substrate",right_on = "uniprot")

In [39]:
interaction_data_mapped = interaction_data_mapped.loc[:,["substrate","kinase","p_ind","p_aa","sequence"]].drop_duplicates()
interaction_data_mapped

,substrate,kinase,p_ind,p_aa,sequence
0,P34901,Q05655,183,S,MAPVCLFAPLLLLLLGGFPVAPGESIRETEVIDPQDLLEGRYFSGA...
3,P34901,P17252,183,S,MAPVCLFAPLLLLLLGGFPVAPGESIRETEVIDPQDLLEGRYFSGA...
6,P34901,P17252,183,S,MAPVCLFAPLLLLLLGGFPVAPGESIRETEVIDPQDLLEGRYFSGA...
9,P34901,Q05655,183,S,MAPVCLFAPLLLLLLGGFPVAPGESIRETEVIDPQDLLEGRYFSGA...
12,Q9UQL6,Q05655,259,S,MNSPNESDGMSGREPSLEILPRTSLHSIPVTVEVKPVLPRAMPSSM...
...,...,...,...,...,...
2301946,Q91Z79,P20444,760,S,MMCEVMPTISEDGRRGSALGPDDAGGELERLMVTMLTERERLLETL...
2301969,P26048,P05132,359,S,MKTKLSTCNVWSLLLVLLVWDPVRLVLANIQEDEAKNNITIFTRIL...
2301974,O35085,P05132,266,S,MSNQYQEEGCSERPECKSKSPTLLSSYCIDSILGRRSPCKMRLLGA...
2301979,Q8C4Q6,P05132,161,S,MSEVTRSLLQRWGASLRRGADFDSWGQLVEAIDEYQILARHLQKEA...
2301988,A2AHC3,Q05512,1464,S,MVDAGGRCAAEGWRRMEAPPEGADLVPLDRYDAARAKIAANLQWIC...

In [40]:
print("number of unique phosphosite accession mapped now")
mapped_substrates = list(set(interaction_data_mapped["substrate"].values))
print(len(mapped_substrates))

number of unique phosphosite accession mapped now
6287

In [47]:
problem_accs = []
for i in range(interaction_data_mapped.shape[0]):
    s = interaction_data_mapped.iloc[i,:]
    if not ( s["sequence"][int(s["p_ind"])-1] == s["p_aa"]):
        print(s["sequence"])
        print(int(s["p_ind"])-1)
        problem_accs.append(s["substrate"])

MPRYGASLRQSCPRSGREQGQDGTAGAPGLLWMGLVLALALALALALSDSRVLWAPAEAHPLSPQGHPARLHRIVPRLRDVFGWGNLTCPICKGLFTAINLGLKKEPNVARVGSVAIKLCNLLKIAPPAVCQSIVHLFEDDMVEVWRRSVLSPSEACGLLLGSTCGHWDIFSSWNISLPTVPKPPPKPPSPPAPGAPVSRILFLTDLHWDHDYLEGTDPDCADPLCCRRGSGLPPASRPGAGYWGEYSKCDLPLRTLESLLSGLGPAGPFDMVYWTGDIPAHDVWHQTRQDQLRALTTVTALVRKFLGPVPVYPAVGNHESTPVNSFPPPFIEGNHSSRWLYEAMAKAWEPWLPAEALRTLRIGGFYALSPYPGLRLISLNMNFCSRENFWLLINSTDPAGQLQWLVGELQAAEDRGDKVHIIGHIPPGHCLKSWSWNYYRIVARYENTLAAQFFGHTHVDEFEVFYDEETLSRPLAVAFLAPSATTYIGLNPGYRVYQIDGNYSGSSHVVLDHETYILNLTQANIPGAIPHWQLLYRARETYGLPNTLPTAWHNLVYRMRGDMQLFQTFWFLYHKGHPPSEPCGTPCRLATLCAQLSARADSPALCRHLMPDGSLPEAQSLWPRPLFC
509
MPRYGASLRQSCPRSGREQGQDGTAGAPGLLWMGLVLALALALALALSDSRVLWAPAEAHPLSPQGHPARLHRIVPRLRDVFGWGNLTCPICKGLFTAINLGLKKEPNVARVGSVAIKLCNLLKIAPPAVCQSIVHLFEDDMVEVWRRSVLSPSEACGLLLGSTCGHWDIFSSWNISLPTVPKPPPKPPSPPAPGAPVSRILFLTDLHWDHDYLEGTDPDCADPLCCRRGSGLPPASRPGAGYWGEYSKCDLPLRTLESLLSGLGPAGPFDMVYWTGDIPAHDVWHQTRQDQLRALTTVTALVRKFLGPVPVYPAVGNHESTPVNSFPPPFIEGNHSSRWLYEAMAKAWEPWLPAEALRTLRIGGFYALSPYPGLRLISLNMNFCSRENFWLLINSTDPAGQLQWLVGELQAAEDRGDKVHIIGHIPPGHCLKSWSWNYYRIVARYENTLAAQFFGHTHVDEFEVFYDEETLSRPLAVAFLAPSATTYIGLNPGYRVYQIDGNYSGSSHVVLDHETYILNLTQANIPGAIPHWQLLYRARETYGLPNTLPTAWHNLVYRMRGDMQLFQTFWFLYHKGHPPSEPCGTPCRLATLCAQLSARADSPALCRHLMPDGSLPEAQSLWPRPLFC
509
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
44
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
10
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
2
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
10
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
40
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
5
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
2
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
44
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
5
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
44
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
40
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
2
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
44
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
44
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
2
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
10
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
2
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
40
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
40
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
40
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
5
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
5
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
44
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
10
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
2
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
5
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
2
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
40
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
27
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
10
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
2
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
5
MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA
9
MSGSTQPVAQTWRATEPRYPPHSLSYPVQIARTHTDVGLLEYQHHSRDYASHLSPGSIIQPQRRRPSLLSEFQPGNERSQELHLRPESHSYLPELGKSEMEFIESKRPRLELLPDPLLRPSPLLATGQPAGSEDLTKDRSLTGKLEPVSPPSPPHTDPELELVPPRLSKEELIQNMDRVDREITMVEQQISKLKKKQQQLEEEAAKPPEPEKPVSPPPIESKHRSLVQIIYDENRKKAEAAHRILEGLGPQVELPLYNQPSDTRQYHENIKINQAMRKKLILYFKRRNHARKQWEQKFCQRYDQLMEAWEKKVERIENNPRRRAKESKVREYYEKQFPEIRKQRELQERMQSRVGQRGSGLSMSAARSEHEVSEIIDGLSEQENLEKQMRQLAVIPPMLYDADQQRIKFINMNGLMADPMKVYKDRQVMNMWSEQEKETFREKFMQHPKNFGLIASFLERKTVAECVLYYYLTKKNENYKSLVRRSYRRRGKSQQQQQQQQQQQQQQQQQPMPRSSQEEKDEKEKEKEAEKEEEKPEVENDKEDLLKEKTDDTSGEDNDEKEAVASKGRKTANSQGRRKGRITRSMANEANSEEAITPQQSAELASMELNESSRWTEEEMETAKKGLLEHGRNWSAIARMVGSKTVSQCKNFYFNYKKRQNLDEILQQHKLKMEKERNARRKKKKAPAAASEEAAFPPVVEDEEMEASGVSGNEEEMVEEAEALHASGNEVPRGECSGPATVNNSSDTESIPSPHTEAAKDTGQNGPKPPATLGADGPPPGPPTPPPEDIPAPTEPTPASEATGAPTPPPAPPSPSAPPPVVPKEEKEEETAAAPPVEEGEEQKPPAAEELAVDTGKAEEPVKSECTEEAEEGPAKGKDAEAAEATAEGALKAEKKEGGSGRATTAKSSGAPQDSDSSATCSADEVDEAEGGDKNRLLSPRPSLLTPTGDPRANASPQKPLDLKQLKQRAAAIPPIQVTKVHEPPREDAAPTKPAPPAPPPPQNLQPESDAPQQPGSSPRGKSRSPAPPADKEAEKPVFFPAFAAEAQKLPGDPPCWTSGLPFPVPPREVIKASPHAPDPSAFSYAPPGHPLPLGLHDTARPVLPRPPTISNPPPLISSAKHPSVLERQIGAISQGMSVQLHVPYSEHAKAPVGPVTMGLPLPMDPKKLAPFSGVKQEQLSPRGQAGPPESLGVPTAQEASVLRGTALGSVPGGSITKGIPSTRVPSDSAITYRGSITHGTPADVLYKGTITRIIGEDSPSRLDRGREDSLPKGHVIYEGKKGHVLSYEGGMSVTQCSKEDGRSSSGPPHETAAPKRTYDMMEGRVGRAISSASIEGLMGRAIPPERHSPHHLKEQHHIRGSITQGIPRSYVEAQEDYLRREAKLLKREGTPPPPPPSRDLTEAYKTQALGPLKLKPAHEGLVATVKEAGRSIHEIPREELRHTPELPLAPRPLKEGSITQGTPLKYDTGASTTGSKKHDVRSLIGSPGRTFPPVHPLDVMADARALERACYEESLKSRPGTASSSGGSIARGAPVIVPELGKPRQSPLTYEDHGAPFAGHLPRGSPVTTREPTPRLQEGSLSSSKASQDRKLTSTPREIAKSPHSTVPEHHPHPISPYEHLLRGVSGVDLYRSHIPLAFDPTSIPRGIPLDAAAAYYLPRHLAPNPTYPHLYPPYLIRGYPDTAALENRQTIINDYITSQQMHHNAATAMAQRADMLRGLSPRESSLALNYAAGPRGIIDLSQVPHLPVLVPPTPGTPATAMDRLAYLPTAPQPFSSRHSSSPLSPGGPTHLTKPTTTSSSERERDRDRERDRDREREKSILTSTTTVEHAPIWRPGTEQSSGSSGSSGGGGGSSSRPASHSHAHQHSPISPRTQDALQQRPSVLHNTGMKGIITAVEPSTPTVLRSTSTSSPVRPAATFPPATHCPLGGTLDGVYPTLMEPVLLPKEAPRVARPERPRADTGHAFLAKPPARSGLEPASSPSKGSEPRPLVPPVSGHATIARTPAKNLAPHHASPDPPAPPASASDPHREKTQSKPFSIQELELRSLGYHGSSYSPEGVEPVSPVSSPSLTHDKGLPKHLEELDKSHLEGELRPKQPGPVKLGGEAAHLPHLRPLPESQPSSSPLLQTAPGVKGHQRVVTLAQHISEVITQDYTRHHPQQLSAPLPAPLYSFPGASCPVLDLRRPPSDLYLPPPDHGAPARGSPHSEGGKRSPEPNKTSVLGGGEDGIEPVSPPEGMTEPGHSRSAVYPLLYRDGEQTEPSRMGSKSPGNTSQPPAFFSKLTESNSAMVKSKKQEINKKLNTHNRNEPEYNISQPGTEIFNMPAITGTGLMTYRSQAVQEHASTNMGLEAIIRKALMGKYDQWEESPPLSANAFNPLNASASLPAAMPITAADGRSDHTLTSPGGGGKAKVSGRPSSRKAKSPAPGLASGDRPPSVSSVHSEGDCNRRTPLTNRVWEDRPSSAGSTPFPYNPLIMRLQAGVMASPPPPGLPAGSGPLAGPHHAWDEEPKPLLCSQYETLSDSE
2510
MSGSTQPVAQTWRATEPRYPPHSLSYPVQIARTHTDVGLLEYQHHSRDYASHLSPGSIIQPQRRRPSLLSEFQPGNERSQELHLRPESHSYLPELGKSEMEFIESKRPRLELLPDPLLRPSPLLATGQPAGSEDLTKDRSLTGKLEPVSPPSPPHTDPELELVPPRLSKEELIQNMDRVDREITMVEQQISKLKKKQQQLEEEAAKPPEPEKPVSPPPIESKHRSLVQIIYDENRKKAEAAHRILEGLGPQVELPLYNQPSDTRQYHENIKINQAMRKKLILYFKRRNHARKQWEQKFCQRYDQLMEAWEKKVERIENNPRRRAKESKVREYYEKQFPEIRKQRELQERMQSRVGQRGSGLSMSAARSEHEVSEIIDGLSEQENLEKQMRQLAVIPPMLYDADQQRIKFINMNGLMADPMKVYKDRQVMNMWSEQEKETFREKFMQHPKNFGLIASFLERKTVAECVLYYYLTKKNENYKSLVRRSYRRRGKSQQQQQQQQQQQQQQQQQPMPRSSQEEKDEKEKEKEAEKEEEKPEVENDKEDLLKEKTDDTSGEDNDEKEAVASKGRKTANSQGRRKGRITRSMANEANSEEAITPQQSAELASMELNESSRWTEEEMETAKKGLLEHGRNWSAIARMVGSKTVSQCKNFYFNYKKRQNLDEILQQHKLKMEKERNARRKKKKAPAAASEEAAFPPVVEDEEMEASGVSGNEEEMVEEAEALHASGNEVPRGECSGPATVNNSSDTESIPSPHTEAAKDTGQNGPKPPATLGADGPPPGPPTPPPEDIPAPTEPTPASEATGAPTPPPAPPSPSAPPPVVPKEEKEEETAAAPPVEEGEEQKPPAAEELAVDTGKAEEPVKSECTEEAEEGPAKGKDAEAAEATAEGALKAEKKEGGSGRATTAKSSGAPQDSDSSATCSADEVDEAEGGDKNRLLSPRPSLLTPTGDPRANASPQKPLDLKQLKQRAAAIPPIQVTKVHEPPREDAAPTKPAPPAPPPPQNLQPESDAPQQPGSSPRGKSRSPAPPADKEAEKPVFFPAFAAEAQKLPGDPPCWTSGLPFPVPPREVIKASPHAPDPSAFSYAPPGHPLPLGLHDTARPVLPRPPTISNPPPLISSAKHPSVLERQIGAISQGMSVQLHVPYSEHAKAPVGPVTMGLPLPMDPKKLAPFSGVKQEQLSPRGQAGPPESLGVPTAQEASVLRGTALGSVPGGSITKGIPSTRVPSDSAITYRGSITHGTPADVLYKGTITRIIGEDSPSRLDRGREDSLPKGHVIYEGKKGHVLSYEGGMSVTQCSKEDGRSSSGPPHETAAPKRTYDMMEGRVGRAISSASIEGLMGRAIPPERHSPHHLKEQHHIRGSITQGIPRSYVEAQEDYLRREAKLLKREGTPPPPPPSRDLTEAYKTQALGPLKLKPAHEGLVATVKEAGRSIHEIPREELRHTPELPLAPRPLKEGSITQGTPLKYDTGASTTGSKKHDVRSLIGSPGRTFPPVHPLDVMADARALERACYEESLKSRPGTASSSGGSIARGAPVIVPELGKPRQSPLTYEDHGAPFAGHLPRGSPVTTREPTPRLQEGSLSSSKASQDRKLTSTPREIAKSPHSTVPEHHPHPISPYEHLLRGVSGVDLYRSHIPLAFDPTSIPRGIPLDAAAAYYLPRHLAPNPTYPHLYPPYLIRGYPDTAALENRQTIINDYITSQQMHHNAATAMAQRADMLRGLSPRESSLALNYAAGPRGIIDLSQVPHLPVLVPPTPGTPATAMDRLAYLPTAPQPFSSRHSSSPLSPGGPTHLTKPTTTSSSERERDRDRERDRDREREKSILTSTTTVEHAPIWRPGTEQSSGSSGSSGGGGGSSSRPASHSHAHQHSPISPRTQDALQQRPSVLHNTGMKGIITAVEPSTPTVLRSTSTSSPVRPAATFPPATHCPLGGTLDGVYPTLMEPVLLPKEAPRVARPERPRADTGHAFLAKPPARSGLEPASSPSKGSEPRPLVPPVSGHATIARTPAKNLAPHHASPDPPAPPASASDPHREKTQSKPFSIQELELRSLGYHGSSYSPEGVEPVSPVSSPSLTHDKGLPKHLEELDKSHLEGELRPKQPGPVKLGGEAAHLPHLRPLPESQPSSSPLLQTAPGVKGHQRVVTLAQHISEVITQDYTRHHPQQLSAPLPAPLYSFPGASCPVLDLRRPPSDLYLPPPDHGAPARGSPHSEGGKRSPEPNKTSVLGGGEDGIEPVSPPEGMTEPGHSRSAVYPLLYRDGEQTEPSRMGSKSPGNTSQPPAFFSKLTESNSAMVKSKKQEINKKLNTHNRNEPEYNISQPGTEIFNMPAITGTGLMTYRSQAVQEHASTNMGLEAIIRKALMGKYDQWEESPPLSANAFNPLNASASLPAAMPITAADGRSDHTLTSPGGGGKAKVSGRPSSRKAKSPAPGLASGDRPPSVSSVHSEGDCNRRTPLTNRVWEDRPSSAGSTPFPYNPLIMRLQAGVMASPPPPGLPAGSGPLAGPHHAWDEEPKPLLCSQYETLSDSE
2409

MTMDSGADNQQSGDAAVTEAESQQMTVQAQPQIATLAQVSMPAAHATSSAPTVTLVQLPNGQTVQVHGVIQAAQPSVIQSPQVQTVQSSCKDLKRLFSGTQISTIAESEDSQESVDSVTDSQKRREILSRRPSYRKILNDLSSDAPGVPRIEEEKSEEETSAPAITTVTVPTPIYQTSSGQYIAITQGGAIQLANNGTDGVQGLQTLTMTNAAATQPGTTILQYAQTTDGQQILVPSNQVVVQAASGDVQTYQIRTAPTSTIAPGVVMASSPALPTQPAEEAARKREVRLMKNREAARECRRKKKEYVKCLENRVAVLENQNKTLIEELKALKDLYCHKSD
118
MTMDSGADNQQSGDAAVTEAESQQMTVQAQPQIATLAQVSMPAAHATSSAPTVTLVQLPNGQTVQVHGVIQAAQPSVIQSPQVQTVQSSCKDLKRLFSGTQISTIAESEDSQESVDSVTDSQKRREILSRRPSYRKILNDLSSDAPGVPRIEEEKSEEETSAPAITTVTVPTPIYQTSSGQYIAITQGGAIQLANNGTDGVQGLQTLTMTNAAATQPGTTILQYAQTTDGQQILVPSNQVVVQAASGDVQTYQIRTAPTSTIAPGVVMASSPALPTQPAEEAARKREVRLMKNREAARECRRKKKEYVKCLENRVAVLENQNKTLIEELKALKDLYCHKSD
118
MTMDSGADNQQSGDAAVTEAESQQMTVQAQPQIATLAQVSMPAAHATSSAPTVTLVQLPNGQTVQVHGVIQAAQPSVIQSPQVQTVQSSCKDLKRLFSGTQISTIAESEDSQESVDSVTDSQKRREILSRRPSYRKILNDLSSDAPGVPRIEEEKSEEETSAPAITTVTVPTPIYQTSSGQYIAITQGGAIQLANNGTDGVQGLQTLTMTNAAATQPGTTILQYAQTTDGQQILVPSNQVVVQAASGDVQTYQIRTAPTSTIAPGVVMASSPALPTQPAEEAARKREVRLMKNREAARECRRKKKEYVKCLENRVAVLENQNKTLIEELKALKDLYCHKSD
118
MTMDSGADNQQSGDAAVTEAESQQMTVQAQPQIATLAQVSMPAAHATSSAPTVTLVQLPNGQTVQVHGVIQAAQPSVIQSPQVQTVQSSCKDLKRLFSGTQISTIAESEDSQESVDSVTDSQKRREILSRRPSYRKILNDLSSDAPGVPRIEEEKSEEETSAPAITTVTVPTPIYQTSSGQYIAITQGGAIQLANNGTDGVQGLQTLTMTNAAATQPGTTILQYAQTTDGQQILVPSNQVVVQAASGDVQTYQIRTAPTSTIAPGVVMASSPALPTQPAEEAARKREVRLMKNREAARECRRKKKEYVKCLENRVAVLENQNKTLIEELKALKDLYCHKSD
118
MTMDSGADNQQSGDAAVTEAESQQMTVQAQPQIATLAQVSMPAAHATSSAPTVTLVQLPNGQTVQVHGVIQAAQPSVIQSPQVQTVQSSCKDLKRLFSGTQISTIAESEDSQESVDSVTDSQKRREILSRRPSYRKILNDLSSDAPGVPRIEEEKSEEETSAPAITTVTVPTPIYQTSSGQYIAITQGGAIQLANNGTDGVQGLQTLTMTNAAATQPGTTILQYAQTTDGQQILVPSNQVVVQAASGDVQTYQIRTAPTSTIAPGVVMASSPALPTQPAEEAARKREVRLMKNREAARECRRKKKEYVKCLENRVAVLENQNKTLIEELKALKDLYCHKSD
118
MTMDSGADNQQSGDAAVTEAESQQMTVQAQPQIATLAQVSMPAAHATSSAPTVTLVQLPNGQTVQVHGVIQAAQPSVIQSPQVQTVQSSCKDLKRLFSGTQISTIAESEDSQESVDSVTDSQKRREILSRRPSYRKILNDLSSDAPGVPRIEEEKSEEETSAPAITTVTVPTPIYQTSSGQYIAITQGGAIQLANNGTDGVQGLQTLTMTNAAATQPGTTILQYAQTTDGQQILVPSNQVVVQAASGDVQTYQIRTAPTSTIAPGVVMASSPALPTQPAEEAARKREVRLMKNREAARECRRKKKEYVKCLENRVAVLENQNKTLIEELKALKDLYCHKSD
118
MTMDSGADNQQSGDAAVTEAESQQMTVQAQPQIATLAQVSMPAAHATSSAPTVTLVQLPNGQTVQVHGVIQAAQPSVIQSPQVQTVQSSCKDLKRLFSGTQISTIAESEDSQESVDSVTDSQKRREILSRRPSYRKILNDLSSDAPGVPRIEEEKSEEETSAPAITTVTVPTPIYQTSSGQYIAITQGGAIQLANNGTDGVQGLQTLTMTNAAATQPGTTILQYAQTTDGQQILVPSNQVVVQAASGDVQTYQIRTAPTSTIAPGVVMASSPALPTQPAEEAARKREVRLMKNREAARECRRKKKEYVKCLENRVAVLENQNKTLIEELKALKDLYCHKSD
118
MTMDSGADNQQSGDAAVTEAESQQMTVQAQPQIATLAQVSMPAAHATSSAPTVTLVQLPNGQTVQVHGVIQAAQPSVIQSPQVQTVQSSCKDLKRLFSGTQISTIAESEDSQESVDSVTDSQKRREILSRRPSYRKILNDLSSDAPGVPRIEEEKSEEETSAPAITTVTVPTPIYQTSSGQYIAITQGGAIQLANNGTDGVQGLQTLTMTNAAATQPGTTILQYAQTTDGQQILVPSNQVVVQAASGDVQTYQIRTAPTSTIAPGVVMASSPALPTQPAEEAARKREVRLMKNREAARECRRKKKEYVKCLENRVAVLENQNKTLIEELKALKDLYCHKSD
118
MTMDSGADNQQSGDAAVTEAESQQMTVQAQPQIATLAQVSMPAAHATSSAPTVTLVQLPNGQTVQVHGVIQAAQPSVIQSPQVQTVQSSCKDLKRLFSGTQISTIAESEDSQESVDSVTDSQKRREILSRRPSYRKILNDLSSDAPGVPRIEEEKSEEETSAPAITTVTVPTPIYQTSSGQYIAITQGGAIQLANNGTDGVQGLQTLTMTNAAATQPGTTILQYAQTTDGQQILVPSNQVVVQAASGDVQTYQIRTAPTSTIAPGVVMASSPALPTQPAEEAARKREVRLMKNREAARECRRKKKEYVKCLENRVAVLENQNKTLIEELKALKDLYCHKSD
256
MESEQLFHRGYYRNSYNSITSASSDEELLDGAGVIMDFQTSEDDNLLDGDTAVGTHYTMTNGGSINSSTHLLDLLDEPIPGVGTYDDFHTIDWVREKCKDRERHRRINSKKKESAWEMTKSLYDAWSGWLVVTLTGLASGALAGLIDIAADWMTDLKEGICLSALWYNHEQCCWGSNETTFEERDKCPQWKTWAELIIGQAEGPGSYIMNYIMYIFWALSFAFLAVSLVKVFAPYACGSGIPEIKTILSGFIIRGYLGKWTLMIKTITLVLAVASGLSLGKEGPLVHVACCCGNIFSYLFPKYSTNEAKKREVLSAASAAGVSVAFGAPIGGVLFSLEEVSYYFPLKTLWRSFFAALVAAFVLRSINPFGNSRLVLFYVEYHTPWYLFELFPFILLGVFGGLWGAFFIRANIAWCRRRKSTKFGKYPVLEVIIVAAITAVIAFPNPYTRLNTSELIKELFTDCGPLESSSLCDYRNDMNASKIVDDIPDRPAGIGVYSAIWQLCLALIFKIIMTVFTFGIKVPSGLFIPSMAIGAIAGRIVGIAVEQLAYYHHDWFIFKEWCEVGADCITPGLYAMVGAAACLGGVTRMTVSLVVIVFELTGGLEYIVPLMAAVMTSKWVGDAFGREGIYEAHIRLNGYPFLDAKEEFTHTTLAADVMRPRRNDPPLAVLTQDNMTVDDIENMINETSYNGFPVIMSKESQRLVGFALRRDLTIAIESARKKQEGIVGSSRVCFAQHTPSLPAESPRPLKLRSILDMSPFTVTDHTPMEIVVDIFRKLGLRQCLVTHNGRLLGIITKKDILRHMAQTANQDPASIMFN
50
MESHSRAGKSRKSAKFRSISRSLMLCNAKTSDDGSSPDEKYPDPFEISLAQGKEGIFHSSVQLADTSEAGPSSVPDLALASEAAQLQAAGNDRGKTCRRIFFMKESSTASSREKPGKLEAQSSNFLFPKACHQRARSNSTSVNPYCTREIDFPMTKKSAAPTDRQPYSLCSNRKSLSQQLDCPAGKAAGTSRPTRSLSTAQLVQPSGGLQASVISNIVLMKGQAKGLGFSIVGGKDSIYGPIGIYVKTIFAGGAAAADGRLQEGDEILELNGESMAGLTHQDALQKFKQAKKGLLTLTVRTRLTAPPSLCSHLSPPLCRSLSSSTCITKDSSSFALESPSAPISTAKPNYRIMVEVSLQKEAGVGLGIGLCSVPYFQCISGIFVHTLSPGSVAHLDGRLRCGDEIVEISDSPVHCLTLNEVYTILSHCDPGPVPIIVSRHPDPQVSEQQLKEAVAQAVENTKFGKERHQWSLEGVKRLESSWHGRPTLEKEREKNSAPPHRRAQKVMIRSSSDSSYMSGSPGGSPGSGSAEKPSSDVDISTHSPSLPLAREPVVLSIASSRLPQESPPLPESRDSHPPLRLKKSFEILVRKPMSSKPKPPPRKYFKSDSDPQKSLEERENSSCSSGHTPPTCGQEARELLPLLLPQEDTAGRSPSASAGCPGPGIGPQTKSSTEGEPGWRRASPVTQTSPIKHPLLKRQARMDYSFDTTAEDPWVRISDCIKNLFSPIMSENHGHMPLQPNASLNEEEGTQGHPDGTPPKLDTANGTPKVYKSADSSTVKKGPPVAPKPAWFRQSLKGLRNRASDPRGLPDPALSTQPAPASREHLGSHIRASSSSSSIRQRISSFETFGSSQLPDKGAQRLSLQPSSGEAAKPLGKHEEGRFSGLLGRGAAPTLVPQQPEQVLSSGSPAASEARDPGVSESPPPGRQPNQKTLPPGPDPLLRLLSTQAEESQGPVLKMPSQRARSFPLTRSQSCETKLLDEKTSKLYSISSQVSSAVMKSLLCLPSSISCAQTPCIPKEGASPTSSSNEDSAANGSAETSALDTGFSLNLSELREYTEGLTEAKEDDDGDHSSLQSGQSVISLLSSEELKKLIEEVKVLDEATLKQLDGIHVTILHKEEGAGLGFSLAGGADLENKVITVHRVFPNGLASQEGTIQKGNEVLSINGKSLKGTTHHDALAILRQAREPRQAVIVTRKLTPEAMPDLNSSTDSAASASAASDVSVESTAEATVCTVTLEKMSAGLGFSLEGGKGSLHGDKPLTINRIFKGAASEQSETVQPGDEILQLGGTAMQGLTRFEAWNIIKALPDGPVTIVIRRKSLQSKETTAAGDS
143
MESHSRAGKSRKSAKFRSISRSLMLCNAKTSDDGSSPDEKYPDPFEISLAQGKEGIFHSSVQLADTSEAGPSSVPDLALASEAAQLQAAGNDRGKTCRRIFFMKESSTASSREKPGKLEAQSSNFLFPKACHQRARSNSTSVNPYCTREIDFPMTKKSAAPTDRQPYSLCSNRKSLSQQLDCPAGKAAGTSRPTRSLSTAQLVQPSGGLQASVISNIVLMKGQAKGLGFSIVGGKDSIYGPIGIYVKTIFAGGAAAADGRLQEGDEILELNGESMAGLTHQDALQKFKQAKKGLLTLTVRTRLTAPPSLCSHLSPPLCRSLSSSTCITKDSSSFALESPSAPISTAKPNYRIMVEVSLQKEAGVGLGIGLCSVPYFQCISGIFVHTLSPGSVAHLDGRLRCGDEIVEISDSPVHCLTLNEVYTILSHCDPGPVPIIVSRHPDPQVSEQQLKEAVAQAVENTKFGKERHQWSLEGVKRLESSWHGRPTLEKEREKNSAPPHRRAQKVMIRSSSDSSYMSGSPGGSPGSGSAEKPSSDVDISTHSPSLPLAREPVVLSIASSRLPQESPPLPESRDSHPPLRLKKSFEILVRKPMSSKPKPPPRKYFKSDSDPQKSLEERENSSCSSGHTPPTCGQEARELLPLLLPQEDTAGRSPSASAGCPGPGIGPQTKSSTEGEPGWRRASPVTQTSPIKHPLLKRQARMDYSFDTTAEDPWVRISDCIKNLFSPIMSENHGHMPLQPNASLNEEEGTQGHPDGTPPKLDTANGTPKVYKSADSSTVKKGPPVAPKPAWFRQSLKGLRNRASDPRGLPDPALSTQPAPASREHLGSHIRASSSSSSIRQRISSFETFGSSQLPDKGAQRLSLQPSSGEAAKPLGKHEEGRFSGLLGRGAAPTLVPQQPEQVLSSGSPAASEARDPGVSESPPPGRQPNQKTLPPGPDPLLRLLSTQAEESQGPVLKMPSQRARSFPLTRSQSCETKLLDEKTSKLYSISSQVSSAVMKSLLCLPSSISCAQTPCIPKEGASPTSSSNEDSAANGSAETSALDTGFSLNLSELREYTEGLTEAKEDDDGDHSSLQSGQSVISLLSSEELKKLIEEVKVLDEATLKQLDGIHVTILHKEEGAGLGFSLAGGADLENKVITVHRVFPNGLASQEGTIQKGNEVLSINGKSLKGTTHHDALAILRQAREPRQAVIVTRKLTPEAMPDLNSSTDSAASASAASDVSVESTAEATVCTVTLEKMSAGLGFSLEGGKGSLHGDKPLTINRIFKGAASEQSETVQPGDEILQLGGTAMQGLTRFEAWNIIKALPDGPVTIVIRRKSLQSKETTAAGDS
143
MESHSRAGKSRKSAKFRSISRSLMLCNAKTSDDGSSPDEKYPDPFEISLAQGKEGIFHSSVQLADTSEAGPSSVPDLALASEAAQLQAAGNDRGKTCRRIFFMKESSTASSREKPGKLEAQSSNFLFPKACHQRARSNSTSVNPYCTREIDFPMTKKSAAPTDRQPYSLCSNRKSLSQQLDCPAGKAAGTSRPTRSLSTAQLVQPSGGLQASVISNIVLMKGQAKGLGFSIVGGKDSIYGPIGIYVKTIFAGGAAAADGRLQEGDEILELNGESMAGLTHQDALQKFKQAKKGLLTLTVRTRLTAPPSLCSHLSPPLCRSLSSSTCITKDSSSFALESPSAPISTAKPNYRIMVEVSLQKEAGVGLGIGLCSVPYFQCISGIFVHTLSPGSVAHLDGRLRCGDEIVEISDSPVHCLTLNEVYTILSHCDPGPVPIIVSRHPDPQVSEQQLKEAVAQAVENTKFGKERHQWSLEGVKRLESSWHGRPTLEKEREKNSAPPHRRAQKVMIRSSSDSSYMSGSPGGSPGSGSAEKPSSDVDISTHSPSLPLAREPVVLSIASSRLPQESPPLPESRDSHPPLRLKKSFEILVRKPMSSKPKPPPRKYFKSDSDPQKSLEERENSSCSSGHTPPTCGQEARELLPLLLPQEDTAGRSPSASAGCPGPGIGPQTKSSTEGEPGWRRASPVTQTSPIKHPLLKRQARMDYSFDTTAEDPWVRISDCIKNLFSPIMSENHGHMPLQPNASLNEEEGTQGHPDGTPPKLDTANGTPKVYKSADSSTVKKGPPVAPKPAWFRQSLKGLRNRASDPRGLPDPALSTQPAPASREHLGSHIRASSSSSSIRQRISSFETFGSSQLPDKGAQRLSLQPSSGEAAKPLGKHEEGRFSGLLGRGAAPTLVPQQPEQVLSSGSPAASEARDPGVSESPPPGRQPNQKTLPPGPDPLLRLLSTQAEESQGPVLKMPSQRARSFPLTRSQSCETKLLDEKTSKLYSISSQVSSAVMKSLLCLPSSISCAQTPCIPKEGASPTSSSNEDSAANGSAETSALDTGFSLNLSELREYTEGLTEAKEDDDGDHSSLQSGQSVISLLSSEELKKLIEEVKVLDEATLKQLDGIHVTILHKEEGAGLGFSLAGGADLENKVITVHRVFPNGLASQEGTIQKGNEVLSINGKSLKGTTHHDALAILRQAREPRQAVIVTRKLTPEAMPDLNSSTDSAASASAASDVSVESTAEATVCTVTLEKMSAGLGFSLEGGKGSLHGDKPLTINRIFKGAASEQSETVQPGDEILQLGGTAMQGLTRFEAWNIIKALPDGPVTIVIRRKSLQSKETTAAGDS
143
MESHSRAGKSRKSAKFRSISRSLMLCNAKTSDDGSSPDEKYPDPFEISLAQGKEGIFHSSVQLADTSEAGPSSVPDLALASEAAQLQAAGNDRGKTCRRIFFMKESSTASSREKPGKLEAQSSNFLFPKACHQRARSNSTSVNPYCTREIDFPMTKKSAAPTDRQPYSLCSNRKSLSQQLDCPAGKAAGTSRPTRSLSTAQLVQPSGGLQASVISNIVLMKGQAKGLGFSIVGGKDSIYGPIGIYVKTIFAGGAAAADGRLQEGDEILELNGESMAGLTHQDALQKFKQAKKGLLTLTVRTRLTAPPSLCSHLSPPLCRSLSSSTCITKDSSSFALESPSAPISTAKPNYRIMVEVSLQKEAGVGLGIGLCSVPYFQCISGIFVHTLSPGSVAHLDGRLRCGDEIVEISDSPVHCLTLNEVYTILSHCDPGPVPIIVSRHPDPQVSEQQLKEAVAQAVENTKFGKERHQWSLEGVKRLESSWHGRPTLEKEREKNSAPPHRRAQKVMIRSSSDSSYMSGSPGGSPGSGSAEKPSSDVDISTHSPSLPLAREPVVLSIASSRLPQESPPLPESRDSHPPLRLKKSFEILVRKPMSSKPKPPPRKYFKSDSDPQKSLEERENSSCSSGHTPPTCGQEARELLPLLLPQEDTAGRSPSASAGCPGPGIGPQTKSSTEGEPGWRRASPVTQTSPIKHPLLKRQARMDYSFDTTAEDPWVRISDCIKNLFSPIMSENHGHMPLQPNASLNEEEGTQGHPDGTPPKLDTANGTPKVYKSADSSTVKKGPPVAPKPAWFRQSLKGLRNRASDPRGLPDPALSTQPAPASREHLGSHIRASSSSSSIRQRISSFETFGSSQLPDKGAQRLSLQPSSGEAAKPLGKHEEGRFSGLLGRGAAPTLVPQQPEQVLSSGSPAASEARDPGVSESPPPGRQPNQKTLPPGPDPLLRLLSTQAEESQGPVLKMPSQRARSFPLTRSQSCETKLLDEKTSKLYSISSQVSSAVMKSLLCLPSSISCAQTPCIPKEGASPTSSSNEDSAANGSAETSALDTGFSLNLSELREYTEGLTEAKEDDDGDHSSLQSGQSVISLLSSEELKKLIEEVKVLDEATLKQLDGIHVTILHKEEGAGLGFSLAGGADLENKVITVHRVFPNGLASQEGTIQKGNEVLSINGKSLKGTTHHDALAILRQAREPRQAVIVTRKLTPEAMPDLNSSTDSAASASAASDVSVESTAEATVCTVTLEKMSAGLGFSLEGGKGSLHGDKPLTINRIFKGAASEQSETVQPGDEILQLGGTAMQGLTRFEAWNIIKALPDGPVTIVIRRKSLQSKETTAAGDS
143

IndexError: string index out of range

In [63]:
unmap_substrate = [sub for sub in unique_substrates if sub not in phosxl]

In [101]:
sum([str(sub) == 'nan' for sub in unique_substrates])

2

In [5]:
def get_uniprot_entry(acc):
    url = "https://rest.uniprot.org/uniprotkb/search?query="+acc+ "&&format=tsv&fields=id,sequence"
    try:
        urlData = requests.get(url).content
        rawData = pd.read_csv(io.StringIO(urlData.decode('utf-8')),sep = '\t').iloc[0,1]
    except:
        rawData = ""
    return rawData

In [102]:
# unmap_substrate
res_ls = []
for substrate in unmap_substrate:
    if str(substrate) == 'nan':
        res = ''
    else:
        print(substrate)
        res = get_uniprot_entry(substrate)
    res_ls.append(res)

P17870
P67939
A0A2Z4LIS9
P32850
Q3B891
Q2KIC2
A4K2W5
P06401-2
P18841
Q08E52
P35398-4
Q2QLG7
P24801
Q9QX70
P62978
ENSP00000267569
Q04865
O97952
F1M391
P14100
Q2HJ81
Q6GNV6
Q3T160
Q28589
Q5T7K2
Q8IXJ6-2
Q80ZH1
Q70T02
ABI33873
Q5RAX1
Q5RAG2
Q6QNF3
P50551
Q5EAE6
P0CH28
Q28923
Q6DBX4
Q6NVR1
P41984
Q810W5
ENSP00000248419
A2T767
P16220-1
Q17R91
P04629-2
A4K2S1
Q95168
Q6A548
Q9WVB0-2
Q96IK2
Q9MZD9
Q9GLX8
Q2QL90
Q7YSG7
Q5RDC8
Q28350
A0JNE3
P0CG66
P61142
P62161
Q5R7I1
Q5R4T2
A8E4N3
Q9GKX7
B2RXW8
Q76II0
Q9H4U5
Q5R7D8
A5A6K2
Q9PVX8
P69341
Q91XW0
Q2YDF1
Q8HZP6
A0MLS5
Q64623
Q4R383
O77656
P02541
Q2QLG6
Q3SZB8
Q91636
Q804H7
Q4R4X8
P79394
Q9QUS1
P60952
Q9UC54
P61585
E2RH47
P23355
Q9XT90
Q5RA03
Q864S8
Q8I009
Q2M3B4
Q8MIK0
Q5R943
Q15300
Q8MKI8
Q5TZA2-2
Q6GM86
Q6P7A6
Q6XBN7
Q91783
Q9H2W4
CG6975-PA
A9ULZ2
P81436
Q91431
Q99PW1
Q9XSZ5
D4ACL3
Q7TNI8
Q08499-5
Q7YS81
Q9Y2J6
Q2KJ93
P02718
Q9NH55
Q1JQA2
NP_001005762
A2VDV2
P56951
P10731
A0JNH1
Q5R4K9
Q5R8S0
A5D7P0
Q6FI05
O88944-2
A1YF08
Q9PUM6
Q4R562
P06396-2
C09G9.6.1
Q9UDC6
A7X8C7
Q148G7
P52654
P54252-2
P06186
Q9WTN3-4
Q9Y5N4
Q8CD28
Q8QGV2
Q29495
P17706-2
AAB24205
P53787
Q9UJB6
Q9UME3
P69808
P24643
Q92606
Q5NUL3-1
Q53AD2
Q17QZ4
P0CG54
P61143
O18927
Q2TBH7
Q7LDL9
Q06124-2
P79226
P13591-1
P48018
Q5CD18
Q4R4S7
Q95MM9
Q9TU19
Q4R1J6
Q8VGC3-2
P9WMF8
Q08DI6
Q5RC43
Q9WUR6
Q5RES4
P54288
Q9HCH8
Q01059
A0SXL6
Q3ZBW4
Q02955
P10665
P46529
P0CB89
A9UK05
AAA40678
ENSGALP00000036444
P61223
Q5R9H0
Q6QT55
P51450-2
O62747
Q95242
Q5XPT5
O02671
O62806
Q32PF2
D2HXI8
Q95330
XP_006230684
B8XX90
Q5RES1
A6H750
P13943
Q24312
P70304
Q6NUF4
Q5R410
P97832
Q4R4T5
Q9JJV8
O88839
F8W7Z5
Q3SYZ2
Q4R3X5
Q0MQI8
Q9UE50
ENSRNOP00000012056
Q9BDP6
P15304-2
P42231
P56513
P33724
Q5R1W8
Q5R8M1
A8X6H4
Q1LZG6
O89017
P28028-1
Q28GU6
Q96C05
P56729
Q00194
Q96DW4
Q5R444
Q9ULA0-2
Q8C8K9
A4K2M3
G3V8H4
Q29277
P50751
Q6GTU5
Q2KIA0
Q28708
P01099
Q52KS4
Q5RCV3
Q6J1J1
P25930
Q9HAH2
Q5E9P3
P08103-2
Q66RN5
Q6AYT2
Q02297-6
Q4R381
Q95216
Q8DR34
Q6RX08
Q5E995
Q5R1P3
P22328
ENSP00000357298
Q5R4K3
A2SW69
P05480-1
Q28619
Q5RBA5
P21263-2
O77507
Q5RCS7
Q96RI1-2
C50F4.11
O75914-2
A4FUD9
P18206-2
P51666
P62992
Q9MYX7
Q95209
C0HJG9
Q6TYA7
A5D9C6
Q6TYA8
P51448-2
P35566
O46550
Q9KKQ7
Q9MYZ9
Q38PU5
Q5R7C0
Q99M65
Q8AXF4
NP_001100737
HSBO22
Q9H3D4-2
Q0VCD2
P25188
Q6EWH2
A1A4I4
Q2IBF0
A6ZWC8
Q14135-4
A5A6M2
Q5RF31
Q5EAD3
Q00839-2
P30205
Q98TY9
P63048
Q6B3Y2
P26432
P79387
Q9NS23-2
P56424
Q8BKJ9
Q32LL2
A6QQQ9
Q7T2H4
Q4R4U2
Q91XQ2
G3V7D4-1
Q6DE87
B0I4X3
P25274
Q2KIG1
Q6GQG3
Q9XTA5
P23583
Q8R2Y9
Q2IBD6
P0DN41
P08592-2
P02584
O15519-2
Q91822
Q09YH8
G0YZM8
Q32L23
Q5R878
B5DEX4
Q08DJ8
Q5RBF2
P32233
P02522
Q9QZ65
Q8MKD5
P42929
Q6PIJ9
Q09YN7
Q96P43
Q63767-2
Q2KJ94
O46480
A9JTP3
P35567
Q8MJ44
Q2M1V0
Q9UDF2
Q9XSM3
Q8JGN5
Q5IS70
ENSRNOP00000048410
Q6S9E0
Q92123
P51958
CG1708-PA
Q863B6
O49686
G1N806
B5A923
Q6S9C0
P09851
Q04790
Q0MQB6
P34208
Q24150
Q28D37
Q92908-2
Q9UC36
P23443-2
Q6F3J0
Q9Z2Q8
Q16122
Q5R710
Q9UDL5
P35560-2
Q9NZ35
Q9GKR4
B8XIA5
Q5RCP8
P09610
O55076
Q95220
P30419-2
Q5R4L2
ENSP00000352232
Q9PU13
E1C2I2
Q92063
Q32LM0
P04695
Q8SPZ3
Q95115
Q5PXD3
Q8JHV9
O97799
Q9N179
CG6757-PA
P70099
P19234
P48968
P21692
P24033
Q6RBX8
P35613-2
Q5E984
Q96T22
Q9BT38
Q15858-3
NP_579829
Q2KIW5
O46471
E1BFR5
Q95KV1
Q5R8G6
Q08301
P34998-2
P15991
Q9GKX8
P14270-6
Q8WNU8
Q91615
Q6NZY6
Q17QG2
O62732
Q8HZU1
Q17R13
P02641
P0CG65
A1YES6
Q2IBD7
A7MB74
Q09427
Q0IHQ8
Q07DW0
P54745
P56423
Q5RFD3
P49884
P48799
P30311
NP_001076191
Q9BGX5
P23196
Q09821
Q0V8F0
Q27ID4
P34826
Q6GMY0
Q8T4F7-2
H2LBU8
Q4R7U4
Q8IZG2
F8W6Q8
C8BKD0
Q24K09
Q9Y899
A5A6M0
P33674
Q7YR42
Q9Z297
ENSRNOP00000013522
P58108
P35521
Q29537
Q7ZXK3
O00255-2
P23097
A4UTP7
P29353-2
NP_062220
Q8NFA2-3
ABR15760
P80031
A2Q0Z0
Q29000
Q9HBY8-1
D2HWM5
P56491
Q5R8P5
Q6DET9
CG5330-PA
Q5R4N9
Q08499-4
P28801
P31039
Q9R0T0
A6XKM2
Q0VBZ9
A7MB80
Q2QLH7
P9WJB4
Q92630-2
P42072
NP_001102772
Q2LC84-2
O95398-3
P61012
Q00756
Q92040
E9Q777
Q5R8R5
P50569
P31424-2
Q9NZD0
Q7JJU6
P06906
P20911
Q6RSS1
P05772
P43481
O19001
B9EKA3
P09445
B3SV56
Q4R7Y4
Q9Y5J2
Q5R997
Q95107
A7E320
P07313
P63050
A7YWI9
P61283
P43348
Q60HC2
ENSGALP00000016789
Q7SIA2
Q5PYI0
Q08DY8
P16258
Q5RBH3
Q9JHY7
Q5R4R8
B9V5F5
O18793
D6C652
Q28021
Q925J9-4
P57100
Q13301
A6ZYV5
XP_001480843
P49139
P49757-3
E1BUH4
NP_001178533
Q5PXS1
B6V8E6
B2GU58
Q2TA25
Q08E26
Q9GZX1
P15146-2
Q5RBA4
P30946
P98175-2
Q5RC51
Q05086-2
A0JNH9
P42532
O88529
P00511
P79100
E1C7U0
P63243
P33567
P51664
P58196
Q864U1
P21127-12
Q29040
Q5RA10
Q5RAH9
P83487
Q5ZLY8
P83268
A5PJU9
Q28024
Q29RT6
Q28269
Q9UPF5
Q66H84
P62799
Q9GKL7
O19002
Q8MIK9
Q5R1X2
Q91974
B1WAR9
Q08460-5
Q05152
Q96KS4
Q86XX3
P63052
Q9UQP9
AAC50053
ENSMUSP00000043430
Q007T2
Q9QXW2
Q91GT2
Q8MJ26
Q0IHT3
P02302
G5E9M7
P61926
Q5ZI08
Q07DY2
Q9QZJ5
Q6J6I9
Q9ESY2
Q64159
P43347
Q9JJ67
Q96K01
P79307
Q9GKK8
P56720-1
Q5JSS0
P10830
O19111
Q09YH9
Q3T0N5
Q8R331
P97924-6
Q95212
Q792T7
P68105
O89106
Q96T88-2
Q8TDY6
P34908
Q5XFN2
O57342
P49032
P68103
Q9TV98
Q9GK38
Q9FGM1
E1BPQ1
B5B2W9
P30957
P53781
Q8WN94
Q0VCE2
P78477
F1NA71
Q0PGG7
Q17QJ0
Q64704-2
O77627
Q5FWU0
Q32KM1
P18246
A7XW16
ENSP00000248996
P12798
P69826
P24406
Q6TJY3
P61635
P48734
Q5R7U1
Q6B856
Q60528
P9WHH1
Q5REW7
Q5T2R7
Q9GLW0
Q9GLE4
P02544
Q28996
P23437
P84246
G5E867
Q32LP2
P51792-2
P98149
O14708
P83509
Q9UIB0
Q5RCU0
A5PK26
Q29480
Q9GKL2
Q4R4K6
P07293
Q3T0C7
Q91572
A1A5H8
Q5R440
P58195
P12965
Q06413-3
Q86X82
P02751-1
Q5EAB2
P06213-2
Q9TTY8
A1YF19
P81623
O02718
P59692
Q0R4E4
Q95153
Q58DJ0
A6H7I5
Q95KU9
Q9BY57
P42013
O14686-3
P12023-2
P70032
Q9JLH3
ENSMUSP00000029545
Q4V7G1
Q99KG5-2
P79132
Q2KIA5
Q5CZI7
P79943
Q6NWP9
P17120
P79923
P84770
Q5R733
Q08050-2
P62629
P11716
Q03060-11
Q810D0
Q02399
Q29502
P51953
Q9WVH5
Q28265
Q05116
Q4R4X4
Q9Y220
P61072
Q9DF50
P27049
Q5RCH1
O02822
Q5R6Z9
P62157
Q9QYV0
A1YG22
Q6R8F2
Q9QXN1
Q96C78
Q9JHJ9
Q1W668
Q9H4X1-2
O18868
Q95KV0
Q9PTG8
P15381-4
Q5E9Y0
Q4A1L5
Q5BQN8
Q3SZY3
Q00366
A7MBD1
Q697L1
Q2QLB0
Q3T0G8
P49816-2
O09185
O02722
Q9BVA8
P22752
Q28647
P61291
B3SXQ8
Q3TF18
Q9BUB5-2
Q32NJ6
Q6DDV8
A7X8B3
Q5ZIU3
P07221
Q07192
P61258
Q96FC3
Q2HJ27
P11939
P54829-3
NP_059009
Q7YRL2
P18433-2
P67808
P29678
Q5R893
Q8CJ75
Q16615
Q9GLN5
O88479
Q9BZY2
E2RGF3
Q8HXW9
Q2IBF3
Q6DEB4
P0CG64
P41035
Q9UIH8
Q6P823
P28329-3
Q8CJD2
Q5RBS5
O12944
Q9ESN9-2
O70162
Q90933
O43852-15
P68271
Q60674
Q3LSL6
NP_001104263
Q6PI79
P12637
F1MJR8
P53805-2
Q9N272
Q5TCN4
O97930
Q6SLL5
Q3T0P5
Q3MUI1
Q5REY6
Q5BIN5
Q5QJC2
P04274
Q2IBC2
Q9TUH9
P37234
Q5R490
P61140
Q9UGF0
Q2IBC1
Q2QLB1
Q80XL1
Q3SX26
F1PEE8
Q5RBG3
Q9NRF5
P62796
P04394
F1PMR9
A6ZZR4
A5A6K9
Q792H5-2
P61146
Q6NUR9
P32154
Q28474
A4K2P5
Q2KI99
Q5E9Y2
P0CG67
A2T756
Q6B4V6
I3LMB3
P37803
Q62986
P41685
P70096
P79892
P53601
P03969
Q9P2W8
Q96H62
Q62132-2
Q9WUA5
Q2KJE0
Q5R5M7
Q8HYS5
P11799-2
Q91820
Q9NR80-3
Q08775-5
Q02375
P56950
Q58D94
Q9DC21
Q5D144
Q80WR0
Q8WTW5
Q90W58
P30277
Q5R8Z3
P0C0K5
P47859
P97317
P18911-2
A4IH24
CG10539-PA
P69893
Q95MG6
Q7YRZ8
Q9TUM3
P21359-2
Q5RE28
P80109
Q00589
Q4R362
Q99N77
A2VDZ3
Q8TDC3-2
F8WI90
P00949
P21146
Q04752
Q56JV3
Q5R7H4
Q59HH6
Q5ZIF8
Q5RDH5
C7GJ78
Q95YJ1
F1PAA9
P58400-1
Q28824
ENSP00000343690
Q9JI55
P49699
P29294
Q792H5-3
P83888
P69895
E3SCZ8
P37231-2
Q5RCC9
P52948-2
Q5R9C9
NP_776683
Q6R5A3
P61145
A0QNG3
Q80YE4-2
Q6P4Y6
Q4R5B3
Q4R712
ENSMUSP00000074684
Q8R4T2
P10936
Q2KI14
Q95NE7
Q8WML4
Q03414
P69816
Q4R4Q3
Q5E9L6
E2RAI2
P22723-2
Q861Q8
Q3B7M7
O94759-3
P36956-3
Q8QGQ6
Q2KJD0
Q7ZUY3
P48963
XP_008773743
Q8MKD1
P15381
Q5R616
Q4R4S6
Q09YN6
P54252-1
Q61258
A4K2Q5
Q5HZK9
Q2LGB3
Q8N3M1
BAA34185.2
Q2QLH8
P27124
Q7TMZ9
P56580
ENSP00000347528
Q2HJ49
Q3SZL0
P18688
Q9HDD2
P08955
O75030-2
Q28514
B6ZGS9
Q9TSZ6
Q5MYA0
Q9FEV9
Q8NG31-2
F1LW91
Q9MZ19
A0M8R5
P84088
A7X8B5
Q9NTR3
O02761
Q3SZ94
P00883
A8WJR8
ENSMUSP00000034815
Q09138
P09867
Q6TEQ7
Q15910-2
Q6YNX6
Q58DH8
Q08353
P51177
P48670
P47823
O09181
P04972
P02646
CG3981-PB
P00489
Q9XSI1
Q91604
A0M8S7
A0M8S6
P12928-2
P62158
F1N5V1
Q60487
O97775
P37882
Q6U1J6
O75030-10
P01117
P97318-2
Q9H2D6-5
Q49ZA3
Q0MQB7
Q24JY4
A5A6H4
P09038-2
Q4A1L4
P30309
P62988
Q5R465
Q99490-2
NP_001263640
Q108U8
P49919-2
P27699-2
Q28555
Q0IIL7
Q5IS69
P81728
A0JNB0
P14607
Q9NSP6
P02700
P18708
P27799
P67999-2
P61144
P58772
Q52KN7
P04412
Q5SWX4
Q5PU49
P32676
Q2HJ38
Q86X73
P09741
Q07E38
A0R2D3
Q5R829
Q9N0T5
A1YFZ3
P62803
Q865S3
Q3MUI2
Q5VXN8
NP_001099740
P33981-1
AAB24204
Q91618

Q8HXW3
P29350-3
Q63449
Q4R8C3
P56498
Q4R630
Q3LRT3
P37238-2
Q3T169
Q2EF73
P67938
Q4JF28
Q8TD99
P49841-2
Q60416
P19517
Q05B92
Q28566
P70114
E2RJI4
Q5IS80
ENSMUSP00000098874
D4GYE3
P02313
P41823
O43665-1
P13834
Q28685
Q98TW0
Q7Z5C3
P28053
Q6NTJ3
Q4R633
Q5R9I9
Q4R4R6
Q96PH1-4
P01131
Q8BMH6
Q7ZXH9
Q07E26
P31976
Q9TT90
Q9MYL0
Q9DGD3
B2CXA1
Q5R5A0
Q9MZ06
Q3ZBL9
P46633
P34815-2
P20460
Q60550
A1YG85
P11309-2
Q08DC7
P78348-1
D3YN49
Q6J6I8
XP_849482
Q7YR76
Q92126
P41110
Q8JH64
P62139
Q5R8T7
Q99MM3
E2RK09
P62991
O35800
Q13878
A4K2Y1
Q6PQZ2
Q5RBU9
Q08493-2
NP_001258431
Q5R4F3
P51662
A7X8B7
Q9XT09
Q28521
NP_001099736
O53380
Q920M9
P29353-3
Q5VT18
O46469
Q3MHP5
P26630
Q3ZBU7
Q9N261
P0CG55
P28025
Q60524
CG4005-PB
Q62985-2
Q5R902
Q08289-2
Q9MZL5
Q9DE07
Q9GJP9
C7GVI6
Q92021
P17290
Q2T9U2
Q28317
Q06124-1
B5KFD7
P37176
P17970
Q108U7
Q5R9Y6
Q6URC2
Q764M6
O02755
Q1WK23
Q60495
P62801
Q6PI20
P05786
Q5FBR4
O46606
P11845
Q07E25
Q50L39
O97600
A5A6L0
P10829
F1MRK3
P63058_OBS
A2T6Y4
Q75M87
F1SRY5
Q66WT7
Q5RD00
O73932
Q6BBL6
P02714
Q15711
P22756-4
AAC63511
Q7YRZ9
P0CG53
P49812
Q07DV9
Q2QLF3
P48798
Q8HZM6
Q28889
P32120-2
Q9DGE0
Q7TNL5
P13351
Q8R5I7
Q28DR4
Q60439
A6QNQ6
Q4F9K6
Q3UD40
Q5R923
Q9NQS9
Q28199
Q9MZA9
Q5RCZ5
P60483
NP_001103022
Q12809_VAR_014388
Q98T92
Q6I6F4
Q32KW2
Q2QLF2
Q9GKK5
P41541
Q91790
Q8N6W3
P13406
P58776
E9PVP1
Q6JBI6
O60504_VAR_055019
P25321
NP_001102797
O77737
Q4QRF4
Q9XT18
O15350-2
O77628
Q8VDJ2
Q569C1
O46680
B7ZR30
P05128
Q28642
Q9TT15
P68399
Q2HJ21
I6L9G5
Q8N850
Q96UT3
A4K2T0
F1LNZ2
P70118
O75030-9
Q9Y621
P05126
P55823
Q2KL21
NP_001093990
Q5REL2
Q28156
Q764M8
A0M8R6
Q5RA72
P0CY46
O70420
Q78E59
Q3MHM5
Q676U5-3
Q28ER3
A0QNG6
Q07343-2
Q0MQI9
Q9YHY6
O97790
Q4R407
Q28H51
P0C276
P24799
Q3B7M6
Q6R755
P67998
O02812
NP_001184222
P64898
Q17RH5
P55245
Q0QF17
Q5R8S3
Q0IIB6
P00518
P84233
P02554
Q0QF01
Q9NZS5
Q5RAK8
P46937-2
O70526
Q00552
Q5RAD2
Q8WP14
P10102
Q9TUX8
Q09YJ1
P02576
A5A6N3
Q767L7
Q08297
O02827
Q63980
O77506
ENSMUSP00000007980
P02638
Q80XU2
Q3I5G7
Q9BST9-2
Q9TTT5
Q91YB0
Q5R7A7
Q9H2S8
Q05688
Q8HZQ5
A7YY54
Q9GRU1
ENSP00000261937
Q08E02
Q5NUL3-2
P0A0E1
Q28997
Q2QLD3

In [104]:
len(res_ls) == len(unmap_substrate)

True

In [111]:
phospho_seq = pd.concat([phosphosite_xl.loc[:,["uniprot","sequence"]].drop_duplicates(), \
pd.DataFrame({"uniprot":unmap_substrate,"sequence":res_ls}).iloc[2:,:]],axis = 0)

In [112]:
interaction_data_mapped = pd.merge(interaction_data,phospho_seq,left_on = "substrate",right_on = "uniprot")

In [113]:
print("number of unique phosphosite accession mapped now")
mapped_substrates = list(set(interaction_data_mapped["substrate"].values))
print(len(mapped_substrates))

number of unique phosphosite accession mapped now
7661

In [115]:
interaction_data_mapped.columns = ["substrate","kinase","p_ind","p_aa","uniprot","substrate_seq"]
interaction_data_mapped = interaction_data_mapped.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq"]]

In [116]:
interaction_data_mapped.head()

,substrate,kinase,p_ind,p_aa,substrate_seq
0,P34901,Q05655,183,S,MAPVCLFAPLLLLLLGGFPVAPGESIRETEVIDPQDLLEGRYFSGA...
1,P34901,P17252,183,S,MAPVCLFAPLLLLLLGGFPVAPGESIRETEVIDPQDLLEGRYFSGA...
2,P34901,P17252,183,S,MAPVCLFAPLLLLLLGGFPVAPGESIRETEVIDPQDLLEGRYFSGA...
3,P34901,Q05655,183,S,MAPVCLFAPLLLLLLGGFPVAPGESIRETEVIDPQDLLEGRYFSGA...
4,Q9UQL6,Q05655,259,S,MNSPNESDGMSGREPSLEILPRTSLHSIPVTVEVKPVLPRAMPSSM...

## Fetch kinase sequence

In [117]:
kinase_xl = pd.read_pickle("${SPARK_ACQUISITION_ROOT}/kinase_ml/data/pretraining/kinase_xl.pkl")

In [148]:
interaction_data_mapped["p_ind"] = pd.to_numeric(interaction_data_mapped["p_ind"])
interaction_data_mapped = interaction_data_mapped.drop_duplicates()

In [149]:
res_df = pd.merge(interaction_data_mapped,kinase_xl,left_on = "kinase",right_on = "Entry")

In [127]:
kinase_xl.loc[kinase_xl["Entry"] == "Q05655",:]

,Entry,Entry name,Status,Protein names,Gene names,Organism,Sequence,Length,Cross-reference (Pfam),Cross-reference (RCSB-PDB),Cross-reference (AlphaFoldDB),Cross-reference (PROSITE),Domain [CC],Domain [FT],Protein families,subfamily
449,Q05655,KPCD_HUMAN,reviewed,Protein kinase C delta type (EC 2.7.11.13) (Ty...,PRKCD PKCD,Homo sapiens (Human),MAPFLRIAFNSYELGSLQAEDEANQPFCAVKMKEALSTERGKTLVQ...,676,PF00130;PF00069;PF00433;,NaN,Q05655;,PS51285;PS50004;PS00107;PS50011;PS00108;PS0047...,"DOMAIN: The C1 domain, containing the phorbol ...","DOMAIN 1..106; /note=""C2""; /evidence=""ECO:00...","Protein kinase superfamily, AGC Ser/Thr protei...",AGC Ser/Thr protein kinase family

In [156]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df["kinase"])))

number of mapped kinase out of 2331 kinases
565

In [200]:
dataraw = "${SPARK_ACQUISITION_ROOT_ALT}/protein_databases"
filename = "uniprot_kinase_prosite.tab"
filepath = os.path.join(dataraw,filename)
uniprot_kinase_prosite = pd.read_csv(filepath, \
                    sep = "\t")

In [201]:
res_df2 = pd.merge(interaction_data_mapped,uniprot_kinase_prosite,left_on = "kinase",right_on = "Entry")

In [202]:
res_df12 = pd.concat([res_df.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq","Sequence", "Organism","Domain [CC]","Domain [FT]","Protein families"]],\
res_df2.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq","Sequence", "Organism","Domain [CC]","Domain [FT]","Protein families"]]],axis = 0).drop_duplicates()

In [203]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df2["kinase"])))

number of mapped kinase out of 2331 kinases
2040

In [204]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df12["kinase"])))

number of mapped kinase out of 2331 kinases
2040

In [205]:
dataraw = "${SPARK_ACQUISITION_ROOT_ALT}/protein_databases"
filename = "uniprot_kinase_interpro.tab"
filepath = os.path.join(dataraw,filename)
uniprot_kinase_interpro = pd.read_csv(filepath, \
                    sep = "\t")
res_df3 = pd.merge(interaction_data_mapped,uniprot_kinase_interpro,left_on = "kinase",right_on = "Entry")
res_df123 = pd.concat([res_df3.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq","Sequence", "Organism","Domain [CC]","Domain [FT]","Protein families"]],\
res_df12.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq","Sequence", "Organism","Domain [CC]","Domain [FT]","Protein families"]]],axis = 0).drop_duplicates()

In [206]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df3["kinase"])))

number of mapped kinase out of 2331 kinases
2134

In [207]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df123["kinase"])))

number of mapped kinase out of 2331 kinases
2134

In [208]:
dataraw = "${SPARK_ACQUISITION_ROOT_ALT}/protein_databases"
filename = "uniprot_kinase_supfam.tab"
filepath = os.path.join(dataraw,filename)
uniprot_kinase_supfam = pd.read_csv(filepath, \
                    sep = "\t")
res_df4 = pd.merge(interaction_data_mapped,uniprot_kinase_supfam,left_on = "kinase",right_on = "Entry")
res_df124 = pd.concat([res_df4.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq","Sequence", "Organism","Domain [CC]","Domain [FT]","Protein families"]],\
res_df123.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq","Sequence", "Organism","Domain [CC]","Domain [FT]","Protein families"]]],axis = 0).drop_duplicates()

In [209]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df4["kinase"])))

number of mapped kinase out of 2331 kinases
2134

In [210]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df124["kinase"])))

number of mapped kinase out of 2331 kinases
2134

In [212]:
uniprot_kinase_interpro.head(1)

,Unnamed: 0,Entry,Entry name,Status,Protein names,Gene names,Organism,Sequence,Length,Cross-reference (Pfam),Cross-reference (RCSB-PDB),Cross-reference (AlphaFoldDB),Cross-reference (Interpro),Domain [CC],Domain [FT],Protein families
0,0,Q6PHZ2,KCC2D_MOUSE,reviewed,Calcium/calmodulin-dependent protein kinase ty...,Camk2d Kiaa4163,Mus musculus (Mouse),MASTTTCTRFTDEYQLFEELGKGAFSVVRRCMKIPTGQEYAAKIIN...,499,PF08332;PF00069;,NaN,Q6PHZ2;,IPR013543;IPR011009;IPR032710;IPR000719;IPR017...,DOMAIN: The CAMK2 protein kinases contain a un...,"DOMAIN 14..272; /note=""Protein kinase""; /evi...","Protein kinase superfamily, CAMK Ser/Thr prote..."

In [182]:
dataraw = "${SPARK_ACQUISITION_ROOT_ALT}/protein_databases"
filename = "uniprot_kinase_interpro_fam20c.tab"
filepath = os.path.join(dataraw,filename)
uniprot_kinase_interpro_fam20c = pd.read_csv(filepath, \
                    sep = "\t")
res_df5 = pd.merge(interaction_data_mapped,uniprot_kinase_interpro_fam20c,left_on = "kinase",right_on = "Entry")
res_df12345 = pd.concat([res_df5.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq","Sequence", "Organism","Domain [CC]","Domain [FT]","Protein families"]],\
res_df124.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq","Sequence", "Organism","Domain [CC]","Domain [FT]","Protein families"]]],axis = 0).drop_duplicates()

In [183]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df5["kinase"])))

number of mapped kinase out of 2331 kinases
5

In [184]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df12345["kinase"])))

number of mapped kinase out of 2331 kinases
2139

In [185]:
dataraw = "${SPARK_ACQUISITION_ROOT_ALT}/protein_databases"
filename = "uniprot_kinase_interpro_histadine.tab"
filepath = os.path.join(dataraw,filename)
uniprot_kinase_interpro_histadine = pd.read_csv(filepath, \
                    sep = "\t")
res_df6 = pd.merge(interaction_data_mapped,uniprot_kinase_interpro_histadine,left_on = "kinase",right_on = "Entry")
res_df123456 = pd.concat([res_df6.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq","Sequence"]],\
res_df12345.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq","Sequence"]]],axis = 0).drop_duplicates()

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3135: DtypeWarning: Columns (11,13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [186]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df6["kinase"])))

number of mapped kinase out of 2331 kinases
34

In [187]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df123456["kinase"])))

number of mapped kinase out of 2331 kinases
2173

In [194]:
unmapped_kinase = interaction_data_mapped["kinase"].drop_duplicates()[~interaction_data_mapped["kinase"].drop_duplicates().isin(res_df123456["kinase"])]

In [198]:
uniprot_kinase_interpro_histadine.loc[:,[]]

,Organism,Domain [CC],Domain [FT],Protein families
0,Staphylococcus aureus (strain MRSA252),NaN,"DOMAIN 61..114; /note=""HAMP""; /evidence=""ECO...",NaN
1,Bacillus subtilis (strain 168),NaN,"DOMAIN 189..405; /note=""Histidine kinase""; /...",NaN
2,Pseudomonas aeruginosa (strain ATCC 15692 / DS...,NaN,"DOMAIN 217..269; /note=""HAMP""; /evidence=""EC...",NaN
3,Aneurinibacillus migulanus (Bacillus migulanus),NaN,"DOMAIN 66..118; /note=""HAMP""; /evidence=""ECO...",NaN
4,Staphylococcus aureus (strain Newman),NaN,"DOMAIN 186..238; /note=""HAMP""; /evidence=""EC...",NaN
...,...,...,...,...
1244081,Rhodanobacter sp. C05,NaN,"DOMAIN 76..128; /note=""PAC""; /evidence=""ECO:...",NaN
1244082,Usitatibacter rugosus,NaN,"DOMAIN 167..385; /note=""Histidine kinase""; /...",NaN
1244083,Paenibacillus peoriae,NaN,"DOMAIN 227..448; /note=""Histidine kinase""; /...",NaN
1244084,Bacillus sp. FDAARGOS_527,NaN,"DOMAIN 223..269; /note=""HAMP""; /evidence=""EC...",NaN
1244085,Cavia porcellus (Guinea pig),NaN,"DOMAIN 238..362; /note=""Histidine kinase""; /...",PDK/BCKDK protein kinase family

## final mapping of kinase using interpro information

In [214]:
dataraw = "${SPARK_ACQUISITION_ROOT_ALT}/protein_databases"
filename = "uniprot_kinase_interpro.tab"
filepath = os.path.join(dataraw,filename)
uniprot_kinase_interpro = pd.read_csv(filepath, \
                    sep = "\t")
res_df1 = pd.merge(interaction_data_mapped,uniprot_kinase_interpro,left_on = "kinase",right_on = "Entry")
res_df1["kinase_flag"] = "pk"

filename = "uniprot_kinase_interpro_fam20c.tab"
filepath = os.path.join(dataraw,filename)
uniprot_kinase_interpro_fam20c = pd.read_csv(filepath, \
                    sep = "\t")
res_df2 = pd.merge(interaction_data_mapped,uniprot_kinase_interpro_fam20c,left_on = "kinase",right_on = "Entry")
res_df2["kinase_flag"] = "fam20c"

filename = "uniprot_kinase_interpro_histadine.tab"
filepath = os.path.join(dataraw,filename)
uniprot_kinase_interpro_histadine = pd.read_csv(filepath, \
                    sep = "\t")
res_df3 = pd.merge(interaction_data_mapped,uniprot_kinase_interpro_histadine,left_on = "kinase",right_on = "Entry")
res_df3["kinase_flag"] = "histadine"

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3135: DtypeWarning: Columns (11,13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [216]:
res_df = pd.concat([res_df1,res_df2,res_df3])

In [217]:
print("number of mapped kinase out of 2331 kinases ")
print(sum(interaction_data_mapped["kinase"].drop_duplicates().isin(res_df["kinase"])))

number of mapped kinase out of 2331 kinases
2173

In [219]:
res_df = res_df.loc[:,["substrate","kinase","p_ind","p_aa","substrate_seq","Sequence","Cross-reference (Pfam)","Cross-reference (Interpro)","Domain [CC]","Domain [FT]","Protein families","kinase_flag"]]

In [222]:
res_df.shape == res_df.drop_duplicates().shape

True

In [224]:
res_df.columns = ["substrate","kinase","p_ind","p_aa","substrate_seq","kinase_seq","kinase_pfam","kinase_interpro","domain_cc","domain_ft","protein_families","kinase_flag"]

In [262]:
def get_kinase_domain_ind(s):
    s = str(s)
    try:
        res = [doc.split(";")[0].split("..") for doc in s.split("DOMAIN ")[1:] if "Protein kinase" in doc]
    except:
        res = []
    if len(res) == 0:
        try:
            res = [doc.split(";")[0].split("..") for doc in s.split("DOMAIN ")[1:] if "Histidine kinase" in doc]
        except:
            res = []
    if len(res) == 0:
        try:
            res = [doc.split(";")[0].split("..") for doc in s.split("DOMAIN ")[1:] if "Fam20C" in doc]
        except:
            res = []
    return res

In [263]:
kinase_coord = res_df["domain_ft"].apply(lambda s: get_kinase_domain_ind(s))

In [266]:
res_df["kinase_coord"] = kinase_coord

In [281]:
res_df["kinase_coord"].apply(lambda s: len(s)==1).sum()

30752

In [279]:
res_df["kinase_coord"].apply(lambda s: len(s)<1).sum()

1696

In [277]:
res_df["kinase_coord"].apply(lambda s: len(s)>1).sum()

808

In [282]:
res_df = res_df.loc[res_df["kinase_coord"].apply(lambda s: len(s)==1),:]

In [283]:
res_df.shape

(30752, 13)

In [284]:
dataraw

'${SPARK_ACQUISITION_ROOT_ALT}/protein_databases'

In [285]:
res_df.to_pickle("${SPARK_ACQUISITION_ROOT}/kinase_ml/data/interactions/interaction_exp_cleaned_220915.pkl")

In [101]:
dat = pd.read_pickle("${SPARK_ACQUISITION_ROOT}/kinase_ml/data/interactions/interaction_exp_cleaned_220915.pkl")

In [102]:
res_ls = []
for substrate in dat['substrate']:
    if str(substrate) == 'nan':
        res = ''
    else:
        print(substrate)
        res = get_uniprot_entry(substrate)
    res_ls.append(res)

P34901
Q9UQL6
P18433-2
P18433-2
P61978
P61978
P35570
P35570
P35570
P53004
P53004
P53004
P53004
P15941
P35611
P13789
P13789
P13789
P13789
P14598
P14598
P14598
P14598
P14598
P14598
P14598
P14598
P14598
Q16206
O35303
O70468
P19429
P19429
P19429
P15407
P15407
O76090
Q9UBS0
Q9H257
O46469
P05107
P05107
Q05655
Q05655
Q05655
Q05655
Q05655
Q05655
Q05655
Q05655
P13796
Q9HBA0
Q9HBA0
Q9HBA0
P05787
P04406
P04406
Q02297-6
P51398
P51398
P51398
P51398
P51398
P42224
P37230
P37230
P37230
P62753
P62753
Q8WN94
Q8WN94
Q99808
Q14247
P98082
Q9Y2R2
Q15139
Q15139
Q15139
P29473
P15381
P15381
P15381
P15381
Q8K585
Q8K585
P08057
P08057
P08057
P08057
P08057
P08057
Q60795
Q08775
P17405
P17405
P68431
P28329-3
P28329-3
P13498
P04637
Q8TCU6
P78536
Q6AYD3
P12830
P35568
P35568
P35568
P35568
P21730
Q9NRY6
Q96A00
P11413-3
P11413-3
P53671
P10588
P70181
P40189
P23396
P23396
Q80X41
O14939
O95817
P29353-2
Q15717
Q15717
Q62318
P35222
P61073
P61073
P49840
Q96C90
P30273
Q61143
Q9BZK7
P40763
P49841
Q9WVE0
O00429
Q09472
Q01543
P08581
Q9UQ80
Q9UQ80
Q96D96
Q96D96
P04040
O15350-2
P12931
P52757
P30086
Q8IV61
Q00960
P10636-8
P10636-8
P10636-8
P10636-8
P06493
P06401
O15350
P48787
P00533
Q13501
P49815
P49815
P02545
P10415
P17302
O15162
Q7KZI7
P19634
Q00535
P09758
Q15080
Q15080
P48050
P48168
P31946
P58753
Q8NE86
Q16615
P31232
Q9UQ13
Q9UQ13
Q8TCJ0
P05230
Q96D96-4
Q96D96-4
O00165
Q91WK7
Q91WK7
Q91WK7
Q91WK7
O95544
O95544
P34901
P35570
P35570
P35570
P53004
P53004
P35611
P35611
P35611
P13789
P13789
P13789
P14598
P14598
P14598
P14598
P14598
P14598
P14598
P14598
P14598
O70468
O70468
P19429
P19429
P19429
P19429
P19429
P19429
O76090
Q9UBS0
P05107
P05107
P05107
P13796
P37230
P37230
P37230
Q9Y2R2
Q15139
Q15139
Q15139
P29473
P15381
P15381
P15381
P15381
P15381
P15381
P15381
Q8K585
Q8K585
P08057
P08057
P08057
P08057
P08057
P08057
P68431
P28329-3
P28329-3
P28329-3
P28329-3
P28329-3
P13498
P04637
P04637
P04637
P04637
P78536
P21730
P21730
P21730
P21730
P21730
P21730
Q96A00
P10588
P70181
O14939
O14939
Q15717
Q15717
Q15717
P49840
Q96C90
P49841
Q9WVE0
Q9WVE0
Q09472
P08581
Q9UQ80
Q9UQ80
P30086
P38936
P38936
P38936
Q01815
Q01815
Q63881
Q63881
P35367
P35367
P35367
P08050
P08050
P08050
P08050
P08050
P08050
P33535
P12957
P12957
P55042
P55042
P55042
P55042
P55042
P05556
P23977
P23977
P23977
Q02294
Q02294
P11831
P11831
O35433
O35433
O35433
O35433
O35433
O35433
P19490
P19490
P08670
P08670
P08670
P08670
P08670
Q01970
P18052
P18052
P23818
P47709
P47709
Q96PH1-4
Q96PH1-4
Q96PH1-4
P19493
P31645
P31645
P31645
P16070
Q13224
Q13224
P10522
P10522
P10522
P42261
P42261
P42261
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q9Z297
Q00613
O95786
O95786
P32004
P04004
P04004
P04004
P04004
P60983
P06127
P06127
P11387
P04775
P04775
P04775
P08833
P08833
P08833
P08833
Q60997
P31749
P31749
Q04206
Q62622
P13569
P13569
P13569
P13569
P13569
P13569
P13569
P27699
Q15672
P35579
O75376
P43629
P11473
P06401
O15350
P10275
Q9NS23-2
Q9NS23-2
P04049
P04049
Q13769
Q13769
P10276
Q13131
P29474
P50552
P00533
P04626
Q16875
Q99623
O14920
O14920
Q8TD43
Q8TD43
Q9BZL6
Q9BZL6
Q9BZL6
O60716
P04177
P24844
P24844
P24844
P19174
P52566
Q02156
Q02156
Q02156
Q01844
P35900
P15311
P01116-2
P35569
Q5JVS0
Q5JVS0
P31424
Q06486
Q06486
Q06486
Q06486
Q06486
Q06486
P35612
P35612
P35612
G0YZM8
G0YZM8
G0YZM8
Q86UR1
P08684
P08684
P08684
P08684
P08684
P08684
P08684
P08684
P08684
P08684
P08684
P08684
P08684
P08684
Q07954
Q07954
Q07954
Q07954
O00168
Q12809
P08183
P08183
P08183
Q9UKG1
O60941
O60941
O60941
P35400
P21731-2
P22449
P17812
P17812
Q8WTQ7
P07949
Q14432
Q14432
Q14432
Q14432
Q14432
Q14432
Q14432
Q14432
O08589
O08589
O08589
O15217
Q9EPK8
P00523
Q05209
Q05209
Q13522
Q13522
Q9XSM3
Q9XSM3
Q9UH77
Q8WZ42
Q8WZ42
P02687
P02687
P02687
P02687
P02687
P02687
P02687
P02687
Q63664
Q63664
Q63664
Q63664
P41181
P04083
P04083
P06685
Q9NQA5
Q9NQA5
P22002
P56513
P56513
P56513
P42260
P42260
P17676
P17676
P62755
P23693
P23693
P52565
P52565
Q00961
P06239
O60928
Q9WV60
P35521
P21731
P21731
P21731
P21731
P21731
P37802
P37802
P37802
P16144
P16144
P16144
P16144
Q8NER1
Q8NER1
P24155
Q9NPC2
P55087
P49685
Q92837
P15336
P15336
P15336
P10415
Q00657
P49407
P29966
P29966
P29966
P29966
Q969H0
Q969H0
Q9NRF2
Q9NRF2
Q8CI15
P17302
P17302
P25098
P12003
P12003
P30411
P13863
Q8N556
O75955
Q13002
P29350
P07355
P07355
P19156
P48048
P48048
P48048
P30999
P42866
P42866
P23528
P23528
P02786
P19491
P02584
Q9Y6K9
Q9Y6K9
Q7KZI7
P18031
P48678
Q04637
Q12959
O14745
O14745
O14745
O14745
Q06481
Q14524
P36897
P16144-2
P10721
P10721
P10721
P10721
Q15172
P29317
O14493
P49768
Q96KS0
Q96KS0
Q96KS0
Q99801
Q9BR76
P13726
P13726
O75469
Q28156
Q13507
Q13507
Q13976
Q61743
Q505F1
Q505F1
Q505F1
Q05193
O60674
O60674
Q92888
Q92879
Q92879
Q92879
Q92879
Q92879
Q92879
Q92879
Q92879
Q06124
Q06124
Q06124
Q06124
Q2NL51
P09211
P14416
P14416
P19103
P19103
Q9NRY4
Q9NRY4
Q9NRY4
P32300
P30680
Q9BPZ7
P56537
O75689
O75689
P46940
P23975
P23975
P17252
P17252
P17252
P60879
P33778
P19086
P19086
Q13418
Q13418
P06213
P06213
P06213
Q8TDQ1
Q15762
Q61146
Q5NUL3-2
Q5NUL3-2
Q5NUL3-2
P35351
P09758
P09758
Q61625
Q9BR39
P35439
P35439
P35439
P35439
O94992
Q15080
Q15080
Q5QD51
Q5QD51
P39087
P39087
P12624
P12624
P12624
P12624
P06836
P70441
P04256
P04256
P04256
P04256
P04256
P04256
P04256
P16527
P16527
P16527
P16527
Q91XY5
P50752
P50752
P50752
P50752
P50752
P08253
P08253
P08253
P08253
P08253
P22756
P22756
Q03343
Q03343
Q03343
Q03343
Q63089
Q63089
Q63089
Q63089
Q63089
Q63633
O70420
O70420
O70420
P16054
Q96RI1-2
Q96RI1-2
O95243
O95243
P02803
P36542
Q07869
Q07869
P60880
P60880
Q8NF50
Q8NF50
Q8NF50
Q15311
Q15311
Q15311
Q15311
Q99418
P16150
Q9EP80
P09631
P09631
P16671
Q9Y6H6
Q16658
P21359-2
Q29106
P60881
O94806
P00749
P00749
Q8N726
O35054
P01589
P01589
Q9Y624
Q13303
P29972
P29972
P01730
P01730
P21399
P21399
O88797
P36225
Q28204
Q28204
Q96PY5-3
P35398
P35398
Q05940
Q05940
Q9JIM1
Q9JIM1
Q9JIM1
Q9H1D0
Q9H1D0
Q08092
P26769
P26769
O15519-2
Q03721
Q03721
Q03721
Q03721
P02547
P02547
P02547
P02547
P11234
Q9BQE3
Q9BQE3
E2RGF3
E2RGF3
AAB24205
Q64666
O95471
P10688
P51907
P51907
P55204
P31424-2
Q03157
Q03157
P39429
O88943
Q14994
P35869
P35869
P48050
P53812
O15519
P49802
P35722
Q68ED2
Q92681
P81274
Q03173-4
P47196
A2ASS6
A2ASS6
Q96MS0
Q01959
Q01959
P61765
P61765
P48168
Q96T49
Q9JHZ9
Q8R1G6
P41180
P41180
Q8NFA2-3
Q8NFA2-3
P10599
O35240
O35240
AAB24204
P45379
P45379
P45379
P45379
P45379
Q00589
P10894
P27799
Q8N0W4
P08567
P08567
P58821
P62139
Q8VDU0
O60500
O60500
P09693
Q6ZQ88
P41091
O89050
O89050
Q12791
P43119
Q99PT1
Q01995
O18734
O94759-3
Q9C0K0
P10687
P12979
Q28708
Q9QYC0
P56581
P56581
P00184
Q01954
Q9HAN9
P07936
P22460
Q9WTQ2
Q14315
Q14315
P11171-4
P11171-4
P04272
P25100
P25100
P25100
P25100
P25100
P25100
Q5FWH6
Q5FWH6
Q66HL2
Q66HL2
Q66HL2
Q5NUL3-1
Q5NUL3-1
Q5NUL3-1
O00161
O00161
O00161
Q9WVE8
Q8VHX6
P09038
Q6UVK1
Q96RI1
Q96RI1
Q9H3Q1
Q9H3Q1
P48730
P48730
P48730
P48730
P48730
P48730
P48730
Q9Y271
Q9Y271
Q9Y271
Q92686
Q99JA4
Q99JA4
P35503
Q9UKF7
Q9UKF7
Q71U36
Q96QS3
Q62871
Q62871
P11309-2
Q14749
Q922E4
O75144
P78314
Q16760
Q16760
Q00169
Q9NXH3
ENSP00000248419
O94901
P51674
Q96AX2
P18206
P18206
B6ZGS9
B6ZGS9
Q9UQ13
Q9UQ13
P31146
Q9UNF0
Q01826
O95832
Q15858-3
Q86UX7
Q9UQL6
Q9UQL6
P13789
O70468
P15381
P15381
P15381
P15381
P28329-3
Q96A00
P40189
P35222
P35222
P35222
Q61143
P02548
P02548
P02548
Q01815
Q01815
P29995
P61012
P61012
Q3UMR5
Q3UMR5
P11799
P11799
Q63881
Q63881
P48616
P48616
P48616
P48616
P48616
P35367
P35367
P35367
P35367
P08050
P08050
P08050
P08050
P08050
P08050
P08050
P08050
P08050
P08050
P08050
P08050
P08050
P08050
P08050
Q15796
Q15796
Q15796
P15036
P15036
P15036
P23677
BAA34185.2
P33535
P33535
P33535
Q9Y618
Q9Y618
Q9Y618
Q9Y618
P11275
P11275
P11275
P11275
Q14654
Q14654
P28229
P28229
P28229
P28229
P28229
P28229
P28229
P28229
Q00566
Q9UQM7
Q9UQM7
Q9UQM7
Q4G163
P31016
P12957
P12957
P12957
P12957
P12957
P12957
P12957
P12957
P55042
Q9QW08
O88935
P13346
P13346
P13346
P05556
P05556
Q9JIR4
Q9JIR4
P07101-4
P07101-4
P07101-4
P28741
P28741
P18297
P18297
P18297
Q96PM5
Q96PM5
P15381-4
P15381-4
Q62696
Q62696
P23977
Q02294
Q02294
Q02294
O15273
O15273
P16949
O00631
P15304
Q8CGV2
Q7TN99
Q7TN99
Q7TN99
Q7TN99
Q7TN99
Q7TN99
Q7TN99
P23385
P14921
P14921
P14921
P14921
P07101
P07101
P35270
P43003
P43003
Q62812
P35372
Q9Y496
P63329
P46527
P11831
P11831
Q9Y4D2
Q9Y4D2
Q9BXL7
O35433
O35433
Q92736
Q92736
Q8CBW3
P19490

P19490
P08670
Q01970
P18052
P18052
O14713
P23818
P47709
Q96PH1-4
Q96PH1-4
Q96PH1-4
Q96PH1-4
Q96PH1-4
P19493
P31645
Q9QYP1
Q9QYP1
Q6SLE7
Q99K10
O08553
P15337
P15337
P07293
Q9QUH6
Q9CQD6
P21333
B0LPN4
B0LPN4
P16070
O43526-4
Q00960
Q14674
C6K2K4
P07101-3
P07101-3
P31000
Q06210
B2DD29
O14490-2
P29476
Q13224
P29172
P19020
P17599
P10522
P10522
Q66JT0
P42261
P09917
Q04760
P37840
P10636-8
P10636-8
Q9WV18
P08485
P61810
P55055
P62198
Q9Z297
P51790
P51790
P34152-3
Q00613
P26678
E9Q401
E9Q401
O43524
P00533
P00533
P00533
P00533
P00533
P04626
Q14457
Q14457
Q14457
Q9UQM7-2
Q01147
O95180
Q03555
Q03555
Q12879
P78352
P70313
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
Q14524
O75469
P47712
P49654
Q9NQC7
Q9NQC7
Q9NQC7
O95997
O95997
O95997
O95997
Q9BZB8
P34152
F6SEU4
F6SEU4
F6SEU4
F6SEU4
F6SEU4
F6SEU4
F6SEU4
F6SEU4
F6SEU4
P24588
P24588
F1PEE8
F1PEE8
P11798
Q9JJV9
P41134
Q99PW8
F1LM64
F1LM64
P29475
Q8BHY3
Q9UQD0
Q9UQD0
Q9UQD0
Q9UQD0
Q6DIC0
Q9NSA2
P35436
Q00005-2
Q00005-2
Q00005-2
Q9H254
Q9UQL6
Q9UQL6
P19429
P19429
P19429
P04406
Q14247
P29473
Q60795
P04637
P04637
P35568
O00429
Q09472
P11799
P15304
P46527
Q06210
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
P35638
O75925
Q9NYV6
P13569
P13569
P13569
P50516
P46937
P46937
O15350
O15360
Q9Y478
Q9Y478
Q9Y478
Q9Y478
Q9Y478
Q9Y478
Q9Y478
Q7Z3C6
Q8VBU5
Q8VBU5
Q8VBU5
Q9WVH4
Q7Z628
P07954
P48787
Q13131
Q13131
Q13131
Q13131
Q13131
Q13131
Q15036
Q9JLN9
Q06210-2
P29474
P29474
P50552
Q13085
Q9UQK1
Q9UQK1
P23458
P23458
P63244
O95278
P49816-2
P49816-2
Q64337
Q9H0B6
Q9H0B6
P52292
O00418
O70405
O70405
O70405
O70405
O60825
O43524
O43524
O43524
O43524
O43524
O43524
O43524
P08151
Q9BZL4
Q6TCH7
P00533
Q925J9
Q925J9
Q925J9
Q92538
Q8N122
Q8N122
Q13621
Q13362
Q13362
P41235
P49674
P04626
Q14694
Q9BUB5-2
P28028
P13405
Q14457
Q14457
Q14457
Q14457
Q8VIP2
O75385
O75385
Q9BU19
P15387
P15387
Q05469
Q8BJ56
P53996
P70673
Q8CHY6
P36956-3
Q86TI0
Q86TI0
Q9H3M7
Q07866
O88871
Q16875
Q9P2M7
Q9P2M7
P97784
Q8IXJ6
P14859
Q13363
P46414
P15056
Q9Z0U4
Q12778
Q12778
P43405
Q9NR19
P49816
P62894
O00763
P49117
Q13501
P27546
Q08460-4
P09874
O55043
P55011
P55011
O60260
P49815
Q12888
Q96PU5
Q07955
Q13950
Q9H2X6
Q9H2X6
Q9H2X6
P08559
P08559
Q15910
P19338
Q13586
Q13586
Q14C86
Q14524
Q16236
Q16236
Q16236
Q13309
Q03393
Q8ND76
P05091
P22460
P22460
O95239
P38532
Q9Z0Z3
P56558
Q8IY63
Q60949
Q60949
Q60949
Q60949
Q60949
Q60949
Q60949
Q8NE86
Q5SWU9
Q9UQ84
Q16576
O88487
Q4JK59
O95210
Q9NRC8
Q6N021
P00390
Q8C7E7
P26358-2
Q9NZQ7
Q9NZQ7
O14929
Q6PAR5
O15503
P54310
P14270-6
O88831
O88831
O88831
O88831
O88831
O88831
O88831
O88831
O88831
P11908
P60891
Q8CI51
Q9WVS6
Q9Y297
Q8BKJ9
P28028-1
Q922J3
Q9UJF2-2
P27768
Q9UQL6
Q9UQL6
Q09472
P16949
Q62812
P15337
P0DP23
P16220
P16220
Q04206
Q3LRT3
P14866
Q6JHU9
P45481
Q99623
Q9UQM7-2
P05783
Q92793
Q16566
Q16566
Q16566
P56524
P56524
P56524
P0DP24
P0DP25
Q9UNW9
Q9UNW9
Q9UNW9
Q9Y6J0
P16615
Q9UQL6
Q9UQL6
P30260
Q13393
P05549
Q13085
O00418
O43524
O43524
O43524
O43524
O43524
O43524
P08151
P08151
P08151
Q9BZL4
P15387
P15387
Q86TI0
P02340
P02340
P09874
P28562
O70343
O70343
P11103
Q92819
P70460
Q9UQB8
Q13177
O14920
O14920
Q8BYJ6
Q8BRK8
Q9BXM7
Q9BXM7
Q9BXM7
Q12888
Q9H2X6
Q9H2X6
Q9H2X6
P08559
P08559
O88487
Q9H902
P15919
Q9NSK0
Q9BRK0
Q8R0I0
Q9GZY8
Q8N2F6
O88597
Q922J3
Q9UQL6
Q9UQL6
O35303
O00429
Q09472
P46527
P46527
P18846
P16220
P16220
Q13085
Q05469
P46414
P46414
Q3LRT3
Q9UQM7-2
P04177
P04177
O08679
O08679
O08679
P12928
P12928
P12928-2
P12928-2
P17074
O55043
Q8C2B3
Q8C2B3
Q8C2B3
P11716
Q2LC84
Q2LC84
Q9NP62
Q9NP62
Q9NP62
Q9NP62
Q9NP62
O43432
Q9R1U5
P24844
P39019
Q9CZX8
Q9UKV0
Q9UKV0
P05783
Q9Y570
Q16566
Q14012
Q7KZI7
Q7KZI7
Q7KZI7
Q7KZI7
P57059
Q14155
P49757
P49757
P17600
O14994
Q9Y5J2
Q92777
Q8N3M1
Q9UQL6
P35611
P14598
P14598
P14598
P14598
O35303
O70468
O70468
O70468
O70468
P19429
P19429
P19429
P19429
P13796
Q9HBA0
P51398
P51398
P51398
P51398
P37230
P37230
Q15139
P15381
P15381
P15381
P08057
P08057
P08057
P08057
P04637
Q8TCU6
Q96A00
P35222
P35222
P35222
P49840
P30273
Q61143
Q61143
P49841
Q9WVE0
Q9WVE0
O00429
P12931
P12931
Q61337
Q61337
Q61337
P02548
P02548
P02548
Q01815
P61012
P11799
P11799
P11799
P11799
Q63881
P48616
P35367
P08050
P08050
P08050
P08050
BAA34185.2
P55042
Q9QW08
P07101-4
P28741
P23977
Q02294
P16949
P16949
P15304
Q7TN99
Q7TN99
Q7TN99
Q7TN99
Q7TN99
Q7TN99
Q7TN99
P07101
P11831
Q92736
Q92736
P19490
P08670
P08670
P08670
Q01970
P23818
P47709
P47709
P19493
P15337
P15337
P07293
P21333
B0LPN4
B0LPN4
P16070
O43526-4
O43526-4
Q14674
C6K2K4
P07101-3
Q06210
Q06210
Q13224
Q66JT0
P42261
P09917
P09917
P09917
P09917
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
P26678
E9Q401
E9Q401
Q01082
P03372
P03372
Q62627
P04004
P60983
P60983
Q8C863
Q8C863
P16220
P16220
P50895
P07900
Q04206
Q04206
Q04206
P08551
P13569
P13569
P13569
P13569
P13569
P13569
P13569
P13569
P13569
O95477
O95477
Q923E4
P41208
P13834
Q28147
Q28147
Q16543
D3ZFT1
D3ZFT1
P08238
O75376
O95863
P36955
P36381
P36381
Q6J4I0
O15392
Q13563
Q04207
P11473
P05549
P27986
O14965
P50516
O43521
Q13526
Q13526
Q9NS23-2
P04049
P04049
P04049
P06241
P10276
P10276
Q01094
Q01094
Q01094
Q15208
Q15208
Q9Y478
Q8VBU5
P48787
P48787
Q06210-2
Q06210-2
P29474
P29474
P29474
P29474
P50552
P50552
P50552
Q13085
Q13085
O60825
P08151
P08151
P08151
P08151
Q8N122
P04626
Q05469
Q05469
P36956-3
O88871
Q16875
Q13363
Q12778
Q12778
Q08460-4
P09874
P09874
P09874
O70343
O70343
O70343
P70460
Q9Y6Q9
O75581
P04177
P04177
P17074
P17074
O55043
O55043
Q9NP62
Q9NP62
Q9R1U5
P39019
P19174
P05132
P10636
P10636
P10636
P10636
Q9Y6R1
Q8IW41
Q92934
Q92934
Q92934
P04792
P04792
P04792
P63104
Q07352
Q07352
P54748
P07101-2
P15311
P35236
P01116-2
P26038
Q15052
Q06486
Q16181
O75151
O75151
O75151
O75151
P84243
P84243
Q14738
Q14738
Q14738
P06400
P19838
P39880
P39880
P39880
Q16665
Q16665
Q16665
Q16665
Q16665
Q16665
Q16665
Q16665
Q16665
P18266
P61224
P61224
Q00536
Q00536
Q00536
Q00536
O70507
O70507
O70507
O70507
O70507
O70507
O70507
O70507
O70507
O70507
O70507
O70507
O70507
O70507
O70507
O70507
O70507
O88335
P11137
P11137
P11137
P29294
P29294
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
Q9ES52
O76054
P33076
P33076
P33076
Q86V87
P0DMV8
Q5S007
Q5S007
Q5S007
Q5S007
Q6P069
P54227
P54227
Q96PU5
Q96PU5
Q96PU5
O35626
P97756
P97756
P97756
P97756
P97756
G0YZM8
G0YZM8
G0YZM8
Q93034
Q05086-2
P04213
P02714
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P27732
P10071
P10071
P10071
P10071
P10071
P10071
Q06124-2
Q06124-2
Q8K4Z3
P78348-1
Q6ZWR6
Q6ZWR6
Q6ZWR6
P55211
P55211
P55211
P24390
Q86UR1
Q86UR1
Q14896
Q14896
Q14896
Q14896
P43694
Q9ULJ8
Q9NX63
P20152
P08684
P08684
P08684
P08684
P08684
Q9NYF0
Q9NYF0
Q8IYT8
Q07954
P27448
Q9NZV8
P31323
Q9WVL4
Q6XVN8
P50571
P50571
P61586
P34998-2
Q13972
P43275
Q8VGC3
Q8VGC3
Q0PCR6
Q6R891
O00168
O00168
Q9QUG9
Q9QUG9
Q9QUG9
Q9QUG9
Q6J4K2
P24385
P24385
P24385
P21146
Q9NRD9
Q9NRD9
Q9Y2K6
P70170
P70170
P70170
O35274
O35274
O35274
P07550
P07550
P07550
P07550
Q9P289
Q12809
Q12809
Q12809
Q12809
P27815
P00511
P00517
P00517
P00517
P00517
P00517
P00517
P00517
P00517
P00517
P00517
P08183
P08183
P08183
Q9BY41
O97600
O97600
Q5EG47
Q5EG47
Q5EG47
Q5EG47
Q5EG47
O14813
P14136
P14136
P14136
P14136
P50549
P50549
P50549
P10637
P10637
O54851
O54851
O54851
O54851
P70114
P70114
P70114
Q01860
Q01860
Q9H2S1
Q9H2S1
Q9H2S1
Q9H2S1
Q9H2S1
Q9UKG1
Q0R4E4
P17661
P17661
P17661
Q9JJ67
Q9JJ67
Q9Y259
Q9Y259
Q62915
Q62915
O60941
O60941
P35400
P48544
P48544
Q08499-2
Q08499-2
P48729
P48729
P47859
P11497-2
Q7Z2W7
Q7Z2W7
P13668
Q9WTP9
P21731-2
P21731-2
P11881
P11881
Q6VV64
Q8IWQ3
P22449
P22449
P00439
Q9NXR1
Q9NXR1
Q08499-7
P50402
Q13370
Q13370
Q13370
P0DJI6
P11497
P17812
Q90623
Q90623
Q90623
Q90623
O95644
O95644
O95644
Q8WTQ7
Q8WTQ7
P49655
Q9NS28
P63251
P63251
P63251
Q10758
Q10758
Q10758
Q10758
Q10758
Q10758
Q10758
Q10758
Q10758
Q9GZX7
Q9GZX7
P07949
Q07343
P19544
P19544
Q9UJY1
Q14432
Q14432
Q14432
Q8R071
O75762
O75762
O75762
O75762
P52190
O14921
P97826
P97826
P97826

P97826
O08589
O08589
Q10728
Q10728
O15217
P10636-2
P10636-2
P10636-2
Q9EPK8
P00523
P47736
P47736
Q05209
Q05209
Q08495
Q62101
Q62101
P17612
P17612
P17612
P17612
P17612
P17612
P17612
P17612
P17612
P17612
Q13522
Q13522
Q13522
Q63943
Q63943
P15146-3
P15146-3
P15146-3
O95180
P54296
Q9XSM3
Q920N7
P22091
Q9Y233-2
Q5S006
Q9UD71
Q00756
O15554
Q14847
Q3UVX5
P17655
P17655
P35560-2
P35560-2
P35560-2
Q95N27
Q99259
P20942
P20942
Q07955
Q8CGN5
Q8CGN5
Q02952
Q02952
Q02952
Q02952
O43164
O43164
P18828
O00482
O94811
O94811
O94811
Q91Y55
Q96T88
Q00059
Q00059
Q00059
Q00059
P30306
P30306
P30306
Q99LM3
Q7TNL5
Q7TNL5
Q7TNL5
Q7TNL5
Q9UH77
Q9Y4C1
P04176
Q60875
Q60875
Q8WZ42
Q8WZ42
Q8WZ42
Q01728
Q92917
Q92917
O60479
P07953
Q08499-6
Q99NE5-7
Q71RJ2
P26955
P81122
P81122
P02687
P02687
P02687
P02687
P02687
P02687
P02687
P02687
Q09470
Q9GZU1
Q9GZU1
Q62600
Q62600
Q62600
Q63664
Q63664
P01103
Q92063
P62195
Q7TQN4
P53805-2
P29994
P29994
P41181
P04083
Q8N5S9
Q8N5S9
O94763
Q08493-2
O08773
O08773
NP_001076191
O75688
P54253
P06685
P27708
P27708
P27708
P97490
P20265
O00231
Q9UII2
P01892
P01892
Q9NQA5
P62834
P05023
Q9HCR9
Q9HCR9
P52188
P22002
Q9Y6D6
P56513
P56513
Q8CFN5
P42260
Q92597
Q92597
P17676
P08955
P35240
P35240
P12270
P97610
Q13576
P32067
P30835
Q8IVT5
P01099
P01099
P62755
P17542
P0C643
P0C643
Q9H3Z4
P23693
P23693
Q99N78
P48436
P48436
P56720
P56720
P52565
P54645
P02522
Q29495
Q29495
O15551
P19517
Q9UH99
Q9UH99
Q9UH99
Q8TAE6
Q00961
Q9Z329
P41240
P06239
Q9Y6E0
Q8IWU9
Q9NP97
P24529
P26599
P00176
NP_579829
Q01130
Q01130
Q01130
Q01130
Q7M2N1
Q14344
P51448-2
P13612
P21818
P21818
O00141
Q12802
Q12802
P80109
O60928
P08588
P10412
P55273
Q96P20
P09483
P09483
P09483
P54830
Q9WV60
P27699-2
P05093
Q04887
Q04887
Q7LDG7
P70271
P41777
Q68EM7
Q14103
P35521
O43665
O43665
Q712U5
P35560
P35560
P35560
P15924
P21731
P21731
P21731
Q9H492
Q13535
P37802
Q9H0K1
Q60670
P21980
P21980
P28818
Q9Z2Z9
Q9NP71
P98161
O43181
Q15746
P16144
HSBO22
O95295
Q8NER1
Q9WU70
P09810
Q15149
P55064
Q60817
Q9R0Z9
Q9R0Z9
Q8WVI7
Q99996
Q99996
P09066
P18265
Q15054
Q9JJ40
Q9WTY4
P22459
E9PZQ0
Q9HC16
P16066
P24155
P34080
O14558
Q02375
P19793
Q15835
Q9NPC2
P30518
P48549
P23771
P13255
P23441
P63252
Q9QYW1
Q16790
Q16531
O76074
Q13185
Q9UMX1
Q16891
P55087
P32245
F1LQH2
P49685
O14649
P49698
P51787
P36956
P02718
P41161
Q92837
Q9EQY0
P51557
Q03555
P17302
P17302
P17302
P17302
P07737
P07737
Q13936
Q13936
Q14289
Q7KZI7
P70313
Q13586
Q9UNZ2
P05067
Q9R1E0
Q9R1E0
P56524
P56524
P56524
Q14524
Q14524
Q14524
Q14524
Q96RR4
Q96RR4
Q96RR4
P56720-1
Q61937
Q61937
Q61937
Q61937
P50750
Q9Y210
Q96D31
Q684P5
P54288
P56545
Q9Y6X9
O94992
P60880
P60880
P60880
P60880
A2ASS6
A2ASS6
A2ASS6
Q96T49
Q96T49
P19438
P19438
Q8CFH6
P48736
Q9Y283
Q7Z589
O43768
Q9Y2K2
Q9Y2K2
Q9Y2K2
P54310
P12023
Q6PIY7
Q811T9
Q9NRI5
Q9NRI5
P25799
P25799
Q9H2G2
P56211
P26433
P26433
P61223
P61223
Q9WVR8
Q9UL62
Q9UL62
P17752
P17752
XP_008773743
XP_008773743
XP_008773743
XP_008773743
Q9QXU8
Q9DBL9
Q16637
Q16637
Q16637
Q16637
Q16637
Q9Z0Y9
Q9Z0Y9
Q9Z0Y9
Q9Z0Y9
Q14185
O88667
O88667
O88667
Q86X55
Q9JM04
Q5T2W1
Q8BG32
Q61083
NP_062220
NP_062220
P70604
Q06124-1
Q06124-1
Q12983
P21981
Q7M6Y2
O60658
Q99497
Q9JLU4
Q9NR82
P17105
P04439
P04439
O94875
O43665-1
Q96D21
P49748
Q969F2
O43511
Q09427
Q08460-2
P07384
P07384
P07384
P07384
P07384
Q9P0L9
Q9P0L9
Q9P0L9
Q8IYM1
Q13200
O95140
P49675
P49675
P35438
Q9UHL0
O75665
O75665
Q2Q1W2
Q02080-2
Q676U5-3
Q9UH17
Q63563
Q63563
Q676U5-2
Q1PSW8
Q62668
Q62668
NP_001263640
Q92890
Q0VGL1
Q15642
Q9UQL6
P68431
P10636-8
P10636-8
P10636-8
P10636-8
P30622
P00533
Q9UKV0
P39428
P26645
P26645
P26645
O15553
O15553
Q16512
Q9UQL6
Q9UQL6
O70468
P19429
P19429
P19429
Q14247
Q14247
Q15139
Q15139
Q15139
Q15139
P15381
Q96A00
P35222
P35222
O00429
O15273
O15273
P05412
P05412
P16220
P16220
P16220
P31749
P31749
P48426
O95863
P05549
P05549
P27986
P48787
P48787
P50552
P50552
P00533
P00533
Q8BRK8
P48025
Q92934
Q92934
Q92934
P04792
Q14896
Q12809
Q5EG47
P23693
P23693
Q8NER1
O14558
Q9NRA0
Q9NRA0
O60331
P02686
Q92918
P63010
P63010
Q13936
P23528
Q7KZI7
O95251
O95251
Q9UBF8
O96013
O96013
Q8WUI4
Q8WUI4
Q8WUI4
Q9Y5P4
Q8WYL5
Q8WYL5
Q8WYL5
Q96QB1
O60602
Q15276
O75628
P26450
Q99683
Q66T02
Q66T02
P16258
P18901
Q9UBF8-2
Q9Y3E5
Q9Y3E5
Q9BST9-2
Q9EQG6
P53367
Q13671
Q13671
Q80SW1
P53367-2
P16144-2
P02686-5
Q8R4B8
P22059
O00206
Q9GZY8
Q9GZY8
Q9GZY8
P34056
P16220-1
Q9GZX1
Q9GZX1
Q9WTQ1
Q9WTQ1
P35670
P35670
P35670
P35670
Q9Z1Y3
Q9Z1Y3
Q9Z1Y3
A6ND36
Q9H2S8
Q9UQL6
P21333
P30307
Q01094
O14920
O14920
Q13546
Q13546
Q13546
Q60855
P22626
Q8IVT5
P00338
Q9H2X6
Q14C86
Q14C86
P56524
Q8WUI4
P49005
Q6IN33
Q6IN33
P68363
P26045
P52564
P52564
P23588
P07437
Q15750
Q15750
Q15750
Q15750
P38159
O43318
O43318
O43318
O43318
P54646
P14625
P14625
P14625
P62820
P68104
P61006
Q99959
Q6P589
Q9NTR3
Q9NTR3
Q5SQI0
Q9UQL6
P10636-8
P10636-8
P10636-8
Q8TEW0
Q8TEW0
Q9UQB8
P10636
Q9BXM7
Q92974
Q92974
Q92974
P10637
Q6VV64
Q6VV64
Q6VV64
Q92974-2
Q92974-2
P78352
Q7KZI7
P56524
Q8WUI4
P05198
Q99689
Q9NQT8
Q9NQT8
Q7L804
Q3U182
Q3U182
Q3U182
Q9H4P4
P46939
Q6WKZ4-3
Q53ET0
Q53ET0
Q9Z340
Q9Z340
Q9UQL6
P35611
O35303
O35303
P04637
P04637
P04637
P04637
O14939
Q15717
P35222
P35222
P40763
O00429
P12931
P30086
P14618
Q02294
P08670
O43526-4
O43526-4
P29476
P17599
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P61810
P61810
P41236
P49418
P49418
P49418
P01106
Q02078
P67999
P67999
Q14194
Q14194
Q9ERR1
Q9ERR1
Q9ERR1
Q9ULW0
P10275
P10275
Q05397
Q05397
Q8VBU5
P29474
P15387
P15387
P15387
P15387
Q8IXJ6
Q12778
P09874
P09874
P09874
Q16555
P04150
P04150
P04150
O60260
Q02750
Q3V6T2
P07814
P07814
P35612
P35612
P35612
P02545
P06400
P06400
P06400
Q16665
Q00536
Q5S007
P13668
P13668
Q9NXR1
Q9UD71
O94811
O94811
O94811
P24529
P28818
Q07820
P49023-2
P37238
P37238
P37238
Q03555
O60331
O60331
P56817
Q9Y371
Q80YE4-2
O35927
O35927
P21575
P35968
P49023
P49023
Q14721
Q14721
Q14721
Q14721
O75122
P62136
P15927
P15927
P15927
P05067
Q9R1E0
Q96C19
Q06413
P26358
Q8NEB9
Q8NEB9
Q96QB1
Q96QB1
Q96QB1
Q96QB1
P42858
P42858
P42858
O94916
Q8BH43
P49768
O89038
Q15853
Q15853
P47942
Q14195
Q16236
Q16236
Q16236
O15516
O15516
O43464
P23443-2
P23443-2
P23443-2
O35426
Q9UM11
Q9UM11
Q9UM11
P62483
P62483
Q9Y210
Q9NZ72
Q9NZ72
P37231
P07196
Q05193
Q14814
P28352
P23242
P23242
Q15078
Q15078
P14416
P97318-2
P97318-2
P28740-1
P28740-1
Q8IWU2
P47989
Q9JJM9
Q9JJM9
P97427
Q5FWU0
Q13794
Q63932
Q63932
Q16643
P19103
P19103
O70589
O70589
Q9JK48
Q5BJU7
Q5BJU7
Q5BJU7
NP_001184222
NP_001184222
A2CG49
Q3U7R1
Q99490-2
Q99490-2
Q8JZP2
P21769
Q61235
Q60829
Q8BR65
Q96KR7
Q04735
Q8AYS8
P51111
P51111
Q70AM4
Q8CJH2
Q8CJH2
Q80Y83
Q8C0T5
Q99KH8
Q9UKV5
O54898
Q9ERT9
Q9ERT9
Q62950
P04156
O35412
Q13315
O15169
Q9Y490
P33533
Q99719-2
P70392
Q704Y3
Q3UHL1
Q00535
P05067-4
P16527
Q13303
Q15833
O43602
O43602
O43602
O43602
Q16643-3
Q16643-3
Q9NZD0
Q9NZD0
Q9NZD0
Q8N850
O00499
P27695
O75553
Q9BSJ8
O14827
O43166
P50406
B2RXW8
Q9QYB1
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q69Z98
Q8IV63
P08908
Q13136
Q8IWR1
P97836
Q9BT38
Q9UDC6
Q86X73
Q91YB0
Q91YB0
Q8NEL9
Q8NEL9
Q9UQL6
Q14247
Q13563
Q01105-2
P50552
P50552
P50552
Q9BZL6
P04792
Q7KZI7
P17181
O96013
Q8WUI4
Q8WYL5
Q8WYL5
Q9UBF8-2
Q13671
P53367-2
P16144-2
Q99828
Q9GZY8
Q96K01
Q9UQL6
P05787
P68431
P68431
P68431
P68431
P68431
P04637
P04637
P04637
P04637
P04637
P14618
P11799
P11799
P08670
P08670
P35580
P25490
P25963
P25963
P25963
O14950
P08238
P08238
O15392
O15392
Q14980
Q14980
Q14980
Q14980
Q13761
Q13761
Q91636
Q91636
Q91636
Q9BQG0
Q8TEW0
P53350
O14777
O14777
O14777
O14777
O14777
O14777
Q9UPY8
Q8IX03
Q9BXS6
P49450
Q9NS23-2
Q9NQS7
Q9NQS7
Q9NQS7
Q9NQS7
Q9NQS7
Q9NQS7
Q9NQS7
Q9NQS7
Q9NQS7
Q9NQS7
Q02241
Q02241
Q92538
P68433
P68433
P46013
P46013
Q12888
Q5UIP0
Q96GD4
Q96GD4
Q96GD4
Q96PK6
Q96PK6
Q9Y520
Q9H0H5
Q9H0H5
Q9H0H5
P84243
P84243
P84243
P84243
P06400
Q8WWI1
Q8WWI1
P14136
P14136
P14136
P17661
P17661
P17661
Q15149
Q07820
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q9WU62
Q9WU62
Q09666
Q99661
Q99661
Q99661
Q99661
Q99661
O00571
P06748
Q9Y2I6
Q9Y2I6
Q9Y2I6
Q8WWK9
Q8WWK9
P82970
P82970
Q9UJ70
Q8TF76
Q8TF76
Q8TF76
Q8TF76
P78527
Q00839
Q00839
P38159
Q9H211
Q9H211
Q9H211
Q9H211
Q61937
Q3KR16
Q3KR16
Q3KR16
Q3KR16
Q3KR16
Q3KR16

Q3KR16
Q9UBB4
Q9Y266
Q13315
Q9NQG5
O95235
P33778
P33778
Q53HL2
Q53HL2
Q53HL2
Q53HL2
Q53HL2
P98179
Q8NEM2
Q99879
Q99879
Q99879
Q99879
Q93079
Q93079
Q93079
Q93079
P58876
P58876
P58876
P58876
P23527
P23527
P23527
P23527
Q6DN03
Q6DN03
Q6DN03
Q6DN03
Q17R91
Q17R91
Q17R91
Q17R91
P35659
P62807
P62807
P62807
P62807
Q9H410
Q9H410
O95239
O95239
Q53SF7
Q53SF7
Q8NEY8
P05204
P05204
Q08J23
P18615
Q02241-2
Q9H6F5
Q16778
Q16778
Q16778
Q16778
P46778
Q9H788
Q8NG31
Q8NG31
Q69YH5
Q69YH5
Q69YH5
Q96CF2
Q96CF2
Q96CF2
O60814
O60814
O60814
O60814
Q99877
Q99877
Q99877
Q99877
Q8WYJ6
Q8WYJ6
Q8WYJ6
Q8WYJ6
Q8WYJ6
Q8WYJ6
P46783
Q9Y2R4
P06899
P06899
P06899
P06899
Q6DRA6
Q6DRA6
Q6DRA6
Q6DRA6
Q5T5U3
Q5T5U3
P45973
Q5QNW6
Q5QNW6
Q5QNW6
Q5QNW6
Q8IVT2
Q9P227
Q6NZI2
Q9Y5B9
P62917
Q9BW61
Q9NP77
Q9NP77
Q9NP77
O00566
Q9NQZ2
O15523
Q8TE77
Q96E39
Q6LED0
O76021
Q71DI3
Q71DI3
Q9NZD0
Q9NZD0
Q9NZD0
O95229
O95229
O95229
Q9CSU0
Q96K21
Q8TD99
Q8TD99
Q8TD99
Q6NWP9
Q6NWP9
Q16695
Q9P2W8
Q8N850
Q96KS4
Q96KS4
Q96KS4
Q9NYP9
Q92995
P20263
P29594
Q9UQL6
Q14247
Q15139
Q15139
Q9Y2X7
O94806
Q9GZY8
Q9UQL6
Q9UQL6
P46527
P46527
O43432
P24844
Q9Y570
Q9UQL6
Q9UQL6
Q09472
P16220
Q13131
Q92793
Q16566
Q16566
Q16566
Q8TDC3-2
Q9Z0W5
Q8IU85
Q14012
P56524
P56524
Q9UQL6
Q9UQL6
P35568
Q9Y618
Q9Y618
P36956
P36956
P36956
P56524
P56524
P57059
Q3U182
Q3U182
Q3U182
Q9WTN3-4
Q91X84
Q91X84
Q91X84
Q91X84
P97943
Q53ET0
Q6UUV9
Q8N6W3
Q9JIP4
Q9UQL6
P35570
P35568
P27986
P27986
Q9H0K1
Q9H0K1
Q9H0K1
Q3U182
Q91X84
Q91X84
Q91X84
Q91X84
Q53ET0
Q15078
Q9BV73
Q9BV73
Q6UUV9
Q8N6W3
Q6UUV7
Q9UQL6
Q14247
P35222
Q05397
Q05397
Q05397
Q05397
Q14457
P07949
O43561-2
Q66H76
P63000
Q9H5V8
P26010
P26010
Q60598
Q60598
Q99961
P56945
P56945
Q9Y2X7
O35346
P49023
P49023
P49024
Q9H9S0
Q9H9S0
P12814
P23634-6
Q14451
Q14451
O75962
O00401
Q9Y220
Q9Y220
O75508
O75508
P18433-2
P61978
P61978
P61978
P61978
P61978
P61978
P61978
P15941
Q9UBS0
Q05655
Q05655
P04406
P42224
Q14247
Q14247
Q14247
Q14247
Q14247
Q15139
Q15139
Q15139
Q15139
P29473
P04637
P04637
P12830
P12830
P12830
P12830
O14939
P35222
P35222
P35222
P40763
P40763
P40763
P49841
P12931
P12931
P12931
P12931
P52757
P08050
P08050
P14921
P46527
P46527
P46527
P31645
P31645
P17599
P37840
P10636-8
P34152-3
P34152-3
P34152-3
P34152-3
P34152-3
P60484
P60484
P60484
P60484
P60484
P60484
P60484
P51636
P51636
Q16625
Q16625
P32004
P03372
P25963
P62161
P62161
Q00987
Q00987
O15259
P07900
P35579
O15379
O15379
O15379
P08238
Q13283
P06493
P67999
P27986
O14965
O15350
P10275
P04049
P04049
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q13769
Q07912
P11802
Q7Z3C6
Q7Z3C6
P63244
P63244
P63244
P00533
P00533
P00533
P00533
P00533
P00533
P00533
P00533
P00533
P41235
P41235
P41235
P04626
P15387
P15387
P15387
Q8IXJ6
Q13177
O14920
O14920
O14641
O14641
O14641
O14641
O14641
Q02248
Q9BZL6
Q969T9
Q969T9
Q86WV6
P31995
P31995
P16885
P16885
P12318
P12318
P52566
P52566
P42229
P22681
P22681
F8W6Q8
Q01844
Q96J92
Q96J92
Q96J92
Q9UKV8
Q9UKV8
Q9UKV8
P15311
P15311
Q3V6T2
Q3V6T2
P30304
P30304
P12956
P02545
Q92974
P55211
Q86UR1
Q07954
Q07954
P61586
P61586
P21146
P21146
P21146
Q12809
Q12809
P50402
P50402
P50402
P07949
Q9EPK8
Q9EPK8
Q14847
P26955
P04083
P01892
P05023
P05023
P22002
P52565
P52565
P98161
Q15746
Q15746
Q8NER1
Q9R0Z9
Q9R0Z9
P37238
P49407
P78347-2
P78347-2
Q14790
P63000
P35228
P35228
O60331
P10828
P10301
P53355
P53355
P00338
Q14790-4
Q9JI11
Q9Z1Y4
P17302
P17302
P17302
Q13813
Q13813
P35916
P35916
P35916
P35916
P35916
P35916
P01112
P01112
P01112
Q9Y2W1
Q9Y2W1
Q9Y2W1
Q9Y2W1
P06396
P06396
P06396
P06396
P06396
Q9H5V8
Q9H5V8
Q9H5V8
P25098
P25098
P25098
P12003
P12003
P29353-3
P29353-3
P29353-3
Q12879
Q12879
Q12879
Q12879
Q12879
Q12879
P52732
P52732
P52732
P29477
P30411
P30411
P19022
P19022
P19022
P19022
P19022
P13863
Q03135
P35790
P35790
P29353
P29353
P29353
Q13480
Q13480
Q13480
Q13480
Q13480
O43823
O43823
O43823
O43823
O43823
O43823
O43823
O43823
O43823
O43823
O43823
P32248
P97318
P97318
P97318
Q92945
Q92945
Q92945
P26010
P26010
P23246
P23246
P78347
P78347
Q8R173
Q8R173
Q93052
Q93052
Q93052
P09215
P09215
P09215
P09215
P09215
P09215
O15492
O15492
Q9Y371
Q9UPT8
Q9UPT8
Q9UPT8
Q9NWQ8
Q16832
Q16832
Q16832
Q16832
Q8N556
Q8N556
Q8N556
Q8N556
Q8N556
Q13322
Q13435
Q13435
F1M7Y5
F1M7Y5
F1M7Y5
Q9NYF8
Q9NYF8
Q9NYF8
Q9NYF8
Q9NYF8
Q9NYF8
O15530
O15530
O15530
Q15654
Q9Y613
P16662
P30205
O75955
O75955
Q62165
P11413
P11413
P11413
Q15691
P33151
P33151
P33151
Q92556
Q92556
P48167
Q13002
P05480
P29350
P29350
P51812
P51812
P51812
P51812
P51812
P51812
P51812
Q8CHT1
P07355
P15529-4
O00560
O00560
Q9ULV8
O15455
Q92734
Q92734
Q80YE4-2
Q80YE4-2
O43490
O43490
Q8IZL8
Q9BXP5
Q9BXP5
Q9BXP5
Q9BXP5
Q96TC7
Q90933
O35927
O35927
O35927
P19367
Q9UGK3
Q9UGK3
Q9UGK3
Q96P31
Q96P31
Q96P31
Q96P31
P09327
P09327
P09327
P09327
P09327
P49025
P49025
P21575
P21575
O70161
Q9Z2S9
O15162
O15162
Q07832
Q07832
P01889
Q9Y3Q4
P51792-2
P19156
P19156
P48048
P31431
P31431
P01111
Q9NZQ3
Q9NZQ3
P10686
P10686
Q60598
Q60598
Q60598
Q68CZ2
Q68CZ2
Q68CZ2
Q9UKT4
Q9NV92
Q9NV92
Q9NV92
Q9NV92
Q62417-5
Q62417-5
P10398
P10398
P98175-2
P98175-2
P98175-2
P22723
P22723
Q15642-3
Q02153
P60953-1
Q99961
P49789
Q8IXH7-4
Q15417
P30999
P30999
P30999
Q62419
Q63604
Q63604
Q16595
Q9Z1K9
Q8R5G7
Q8R5G7
P56945
P56945
P07737
Q96AC1
Q96AE4
Q96AE4
Q96AE4
O95297
O95297
Q96KB5
Q96KB5
Q9NPY3
Q9NPY3
P05106
P05106
Q9H7P9
O15056
P42866
P51692
P51692
Q13905
P63010
P51809
Q12913
Q12913
O88703
Q96KG7
Q61824
P19404
P52789
Q13936
Q60631
P23743
P26040
O08747
P36544
P36544
Q9UKW4
Q92529-2
Q92529-2
Q92529-2
Q92529-2
Q92529-2
Q92529-2
Q9R186
Q9R186
P23528
P37173
Q9H2X6
P53801
P31040
O14746
P97465
Q9Y2X7
Q9Y2X7
Q9Y2X7
O43597
P67775
P57737
P57737
P57737
P57737
Q14289
Q14289
Q14289
Q14289
O35346
P30556
Q91YM2
O89032
O89032
Q9QUI0
P02786
P19491
P19491
P19491
P34741
Q92558
O42254
P22001
P22001
P22001
P22001
A1X283
Q8CGX0
Q99439
Q969H4
Q969H4
Q969H4
P16591
Q00610
Q9NZC7
P55284
Q05586
P02584
P35637
P70336
Q60610
Q7L0Q8
P35968
D3YYY8
P29066
P51813
P00519-2
P14923
Q8WWM7
Q91049
Q91049
Q13017
P49023
P49023
P04695
Q6UN15
P08559
P08727
Q14721
P63101
Q9UN19
P27870
P11511
Q9WUD9
Q792H5-3
Q9UK17
P78352
Q6TEQ7
Q9NR80-3
P50281
O43613
P12235
Q9Y6K9
P43403
P06733
P50570
O43663
Q9UHR4
Q9UHR4
Q9UHR4
Q9UHR4
Q9UHR4
Q9UHR4
P08069
P08069
P08069
P17813
P17813
P00519
P10721
Q9EPK5
Q16236
P20138
Q13444
Q13444
P01100
P01100
O14744
Q9NRY4
Q9NRY4
P46940
Q99704
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
Q99504
P31994
Q9H1D0
P19438
Q13009
P01350
P09769
P20936
Q14118
P23634
P60953
O15357
O15357
P30443
P41743
P41743
P41743
P41743
P41743
P41743
O08599
Q5MYA0
Q5MYA0
Q6NZY6
Q8TDY6
P22682
P22682
P53396
P53396
P53396
P53396
O15524
P34152
P34152
P34152
P34152
P34152
Q16615
D3ZMK9
P0DP29
P0DP29
Q8IVP5
P13688
P13688
Q9P219
Q9P219
P04439
Q96RI1
P18206
Q14258
P46937-3
P46937-3
P46937-3
P12023-2
P12023-2
O75116
O43184
A6NMY6
O43281
P11488
P16035
P16035
P16035
O14874
P46934-4
P46934-4
P46934-4
P46934-4
P46934-4
O75604
O75604
Q9Y446
Q13642-1
Q13642-1
Q9Y4D1
Q9BXK1
Q7TNI8
Q99MB1
P13597
Q96RD7
Q96RD7
P01116
P01116
P49279
Q9NPF5
P18827
O14976
O14976
Q9BZG1
Q9BX66-4
Q9BX66-4
P06396-2
P06396-2
P06396-2
P06396-2
P06396-2
P18206-2
P18206-2
Q12929
Q12929
Q12929
Q12929
P62192
Q9H310
P05480-1
Q14693
Q14693
Q14693
Q3TB82
Q3TB82
Q9Y448
Q14155-1
P61978
P61978
P53004
P14598
P14598
P05787
P42224
Q14247
Q14247
Q08775
P04637
P04637
P78536
P35568
P23396
O95817
O95817
O95817
P40763
P49841
O00429
Q09472
Q09472
P14618
P38936
P38936
P11799
Q63881
Q63881
Q63881
Q15796
Q15796
Q15796
Q15796
Q15796
P07101-4
P23977
P16949
P16949
P07101
P46527
P31645
P07101-3
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
Q00613
O75582
O75582
O75582
P03372
P03372
P03372
P05412
P05412
Q9Y6W5
Q9Y6W5
Q9Y6W5
Q14005
P32121
P32121
P11388
P11388
P11388
P11388
P11388
P10242
Q9NYV6
P01106
Q15672
P56270
Q15596
P04198
Q13541
Q9UBN7
Q9UBN7
P06401
O75676
O75676
P49795
Q04637-8
O43521
Q8IX03
Q8IX03
P10275
P10275
P04049
P04049
P04049
P24941
P33242
P13631
O43524
O43524
O43524
O43524
P00533
Q8N122
Q8N122
Q8N122
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P04626
P15056
P15056
P15056
P28562
P28562
O75581

O75581
O60716
O60716
O60716
P42227
P42229
Q01844
P04150
P42225
Q92934
Q02750
Q02750
Q969V6
P07101-2
P49815
Q15648
Q15648
P49790
P49790
P49790
P49790
P49790
P49790
P49790
P49790
P49790
P49790
Q92974
P33076
P33076
P54227
P55211
Q86UR1
P61586
P61586
P21146
Q01860
Q08499-2
O95644
Q9UJY1
Q9UJY1
Q9UJY1
Q05209
Q3UVX5
Q3UVX5
P17655
Q08499-6
P27708
P17676
P08955
P17542
P06239
P24529
Q15746
Q15746
Q15746
P16144
Q9R0Z9
P19793
P36956
Q07820
Q07820
P49715
P23928
Q16828
Q16828
Q16828
Q16828
Q9DBB1
Q9DBB1
P17679
P17679
Q16690
Q16690
Q16690
P15336
P15336
P49023-2
P49023-2
P49023-2
Q63531
Q63531
Q63531
P37285
Q9BUB5
P28033
P28033
P28033
Q05682
Q05682
P70302
P70302
P70302
Q9NYA1
Q9H8Y8
Q9H8Y8
Q8WX93
Q8WX93
Q9EPI6
O70337
P50616
P50616
P50616
P10415
P10415
P10415
Q60793
P37238
Q9NQ66
Q13950
Q13950
Q13950
Q13950
Q13950
Q13950
Q13950
Q13950
Q13950
P04972
O75030-9
Q13614
Q9Z1S8
Q9Z1S8
Q9Z1S8
Q9Z1S8
Q9Z1S8
Q6U1J6
Q80YV2
Q80YV2
P41212
P41212
P19419
P19419
P62813
P12980
P08047
P08047
P08047
O43561-2
Q15788
Q15788
Q63622
Q96RK0
Q96RK0
Q92793
Q01196-8
Q01196-8
Q01196-8
Q01196-8
Q01196-8
P54283
P54283
Q8R4Z9
Q00657
P47930
P47930
Q96FF9
Q96FF9
Q62120
O88498
Q66H76
P17861
P17861
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
P35658
P35658
O70162
O70162
O70162
Q92974-2
Q92974-2
Q08775-5
Q08775-5
P20339
Q98T92
O08529
P29590-4
P29590-4
P29590-4
P29590-4
P29590-4
P29590-4
Q8VDS3
Q9NRA0
Q9NRA0
Q03060
Q03060
Q9UIG0
Q08509
Q08509
C9JLW8
C9JLW8
Q9Z0F8
P49407
P27361
P27361
P78347-2
P78347-2
P10417
Q14790
Q9BR01
Q9ULC4
P97287
Q8N9N5
Q8N9N5
P09951
P09951
P09951
P52909
A6X8Z5
A6X8Z5
P51557
Q16559
Q03555
P63000
Q04211
P26431
P26431
Q15046
O60244
P29966
P16951
Q9UHB6
Q9UHB6
Q9UHB6
Q96Q27
Q96Q27
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q9UKX7
Q9UKX7
P98083
Q05152
Q05152
P27577
Q08369
Q08369
Q02447
P11362
P14784
P42702
P62070
Q05682-4
Q62947
Q9CQJ7
Q5ZMW5
P46152
P70531
Q62132-2
Q969H0
P35228
P33981
P12841
O60331
P27824
P27824
Q12931
Q00175
Q92908
O88447
Q86UC2
Q9UQC2
P10828
P10301
O35254
Q92797
Q61183
Q9NRF2
Q8CI15
P53355
Q16254
Q16254
P41182
P41182
P31395
Q13164
Q12772
Q12772
Q62227
Q61097
P43364
Q9PU52
Q14934
P02686
Q9UPT5
Q16584
Q16584
Q99814
Q13322
Q13322
Q13322
Q9Y613
Q9NZQ3
Q15750
Q13485
NP_776683
P23927
P28324
P28324
P01100
P01100
P01100
P01100
P01100
O60504-2
Q9ULV5
Q15303
Q15303
P56192
P56192
P21802
O14994
Q9QYY0
ENSP00000352232
P14270-6
P49615
Q62151
Q1W668
Q1W668
Q969R2
Q969R2
Q969R2
Q969R2
Q14761
P08235
P08235
P08235
P08235
P08235
P08235
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q53GS7
Q53GS7
Q53GS7
Q53GS7
Q53GS7
Q8K1M6
Q9UQ13
P78543
Q13127
Q13127
Q15366
Q15366
Q15366
Q15366
NP_059009
NP_059009
NP_059009
NP_059009
Q8K3Y3
Q8BTI8
Q4W5Z4
Q9H9Z2
Q8BFV3
Q8BFV3
Q8BFV3
Q8BFV3
Q9ERG0
Q9ERG0
Q9ERG0
Q13115
Q13115
O15027
O15525
P29067
Q8NET8
Q6UUV7
Q15007
Q15007
Q15007
Q3TWL2
Q3TWL2
Q8BGD7
Q8BGD7
Q8BGD7
Q8BGD7
Q8BGD7
Q8BGD7
Q2M1V0
P11531
P15408
P15408
Q9H0F6
P49366
Q62739
Q62739
Q62739
Q62739
Q9NZI5
Q9Y5A9
Q9Y5A9
Q64018
Q86U44
Q86U44
Q86U44
P23415
P61978
P35611
P35611
O35303
P05787
Q14247
Q8K585
Q8K585
P04637
P23396
O95817
O95817
O95817
O95817
Q15717
P40763
O00429
Q09472
Q09472
P14618
Q61337
P38936
P12957
P12957
P12957
P12957
P12957
P16949
P16949
P46527
P08670
P08670
P21333
P21333
P21333
P21333
P21333
Q14674
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P52927
P52927
P30260
P30260
P30260
P30260
P30260
P30260
P30260
P30260
P30260
P30260
P30260
P30260
P30260
Q04724
Q04724
Q04724
Q14005
P11387
P11387
Q96EB6
Q96EB6
P11388
P11388
P11388
P11388
P11388
P67870
P16220
P16220
P16220
P16220
P54274
P54274
P31749
P31749
P49736
P49736
P49736
P38398
P38398
P38398
P38398
Q13509
Q60864
Q60864
P29692
P49418
P49418
P49418
Q96RL1
Q99638
Q99638
Q99638
Q99638
Q99638
Q9BPX3
Q9BPX3
Q9BPX3
P30305
P30305
P30305
P29590
Q14493
Q13541
Q13541
P46060
O15392
P30307
P30307
P30307
P30307
P30307
P30307
P30291
P30291
P68400
P68400
P68400
P68400
P67999
P67999
P67999
P67999
P18858
Q14980
Q14980
Q14980
Q14980
Q14203
P46937
P46937
P46937
P46937
P46937
P46937
P46937
Q8NHV4
Q8NHV4
Q8NHV4
Q15398
Q15398
Q15398
Q15398
Q15398
Q15398
Q15398
Q15398
Q15398
O15350
Q9ULW0
Q9ULW0
Q8IX03
Q8IX03
P10275
P10275
P10275
Q9BXS6
Q9BXS6
P49450
Q9NQS7
O95835
O95835
P24928
P24928
Q01094
Q01094
P11416
P11416
P52292
P52292
O00418
O70405
O70405
O70405
O70405
O70405
O70405
O70405
O70405
O70405
P00533
Q8N122
Q8N122
Q8IXJ6
Q12778
Q13501
Q13501
Q9Y6Q9
Q9Y6Q9
P04179
Q92934
Q02750
Q02750
O14974
P05783
Q07817
P54132
P54132
O14757
O14757
P30304
P30304
P30304
P46013
P46013
Q12888
Q12888
Q9UQ35
Q9UQ35
Q9BW19
Q9BW19
Q9BW19
Q86WB0
P39748
P49792
P49792
P49792
P49792
P49792
P02545
P02545
P02545
P02545
O15151
Q9UPP1
Q9UPP1
Q92974
P27816
P27816
P27816
P27816
P27816
Q9UK53-2
P06400
P06400
P06400
P06400
P06400
Q32P44
P39880
P39880
Q16665
P55211
P20152
P17661
P17661
P17661
P13668
P13668
P11881
P11881
Q9NXR1
Q9NXR1
Q9NXR1
Q9NXR1
Q9NXR1
Q9NXR1
Q10728
Q10728
Q10728
P47736
Q02952
Q02952
O94811
O94811
O94811
O94811
Q96T88
P12270
Q12802
P10412
P55273
P41777
P41777
Q13535
Q15149
P36956
Q07820
Q07820
Q8WX93
Q8WX93
P10415
P10415
P10415
Q13950
Q13950
P08047
P08047
P08047
P08047
Q15788
Q01196-8
Q01196-8
Q01196-8
Q01196-8
Q01196-8
Q01196-8
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q96FF9
Q8IZP0
Q03060
Q03060
Q03060
Q03060
Q14790
Q9ULC4
Q03555
Q9UKX7
P33981
O60331
P27824
O35254
O35254
O35254
O35254
P00338
P17302
P17302
P52732
O15530
Q96KB5
O14746
P67775
Q15910
Q15910
P50613
P50613
Q9H8V3
Q9H8V3
Q9H8V3
Q9H8V3
Q9H8V3
Q9H8V3
O75143
O75143
O75143
O75143
Q99728
Q99728
Q99728
Q99728
P19338
P19338
P19338
G5E9M7
G5E9M7
G5E9M7
G5E9M7
P13084
P13084
Q9NTG7
Q9NTG7
Q06830
Q9HCH0
Q9HCH0
Q9HCH0
Q9HCH0
Q9HCH0
Q9HCH0
Q9HCH0
Q9HCH0
Q9HCH0
Q9HCH0
Q9HCH0
Q9HCH0
Q9HCH0
Q9HCH0
P18031
Q96R06
Q96R06
Q9NTI5
O75122
O75122
O75122
O75122
O75122
Q14978
Q14978
Q13586
P11171-2
P11171-2
Q14643
Q14643
Q9Y6I3
Q9Y6I3
Q14202
Q01986
Q01986
P30309
P30309
P30309
P30309
P30309
P10085
P10085
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
O88643
P23443
P23443
P23443
P23443
Q8IZD2
Q02880
Q7Z3J3
Q9GZM8
Q9GZM8
Q9GZM8
P17096
P17096
P17096
Q16659
Q16659
Q16659
Q16659
Q9WU62
Q9WU62
P11157
P48678
P48678
Q13428
Q13428
Q13428
Q01581
Q9NZT2
Q90828
P50570
P50570
Q61188
Q61188
A6NKT7
P62136
P61980
Q38SD2
O43148
P52948-2
P52948-2
P52948-2
P52948-2
P52948-2
P25206
P25206
P25206
Q9BYG3
P63279
Q09666
Q96IF1
Q96IF1
Q13042
Q13042
Q13042
O94782
P04183
Q92574
Q92574
Q92574
O15446
P48679
P48679
Q99661
Q92993
Q92993
Q5FBB7
Q01167
Q01167
Q9NZJ0
P49915
P33316-2
Q5TB30
O00443
O60701
P43307
P20700
P20700
Q8IWB6
Q8IWB6
Q8IWB6
P98170
Q04637
P48200
Q9GZV5
Q9GZV5
Q9GZV5
Q9GZV5
Q9GZV5
O60566
O60566
O60566
P53564
P49459
Q08050
Q08050
Q08050
Q08050
O94762
Q08050-2
P18754
P18754
P18754
Q14807
Q14807
P15927
P15927
P15927
P0C1Z6
O43683
O43683
O00571
O00571
P26368
P11654
Q14CS0
Q14CS0
Q14739
Q14739
Q9UNZ2
Q8IX90
Q8IX90
Q8IX90
Q8IX90
Q8IX90
Q8IX90
O15287
O60610
Q12959
Q12959
F2Z3T9
Q9UPU5
Q9UPU5
Q9UPU5
Q9UJX5
Q53EZ4
Q53EZ4
Q14C86
P06748
P06748
P06748
P06748
P06748
Q9Y2I6
Q9Y2I6
P22392
Q14157
O75154
P15531
P15531
Q5BJF6-3
Q9UQR0
Q9UQR0
Q9UQR0
Q9UQR0
P33316
Q91XB0
Q91XB0
Q16513
O00562
O00562
Q9Y2V2
P30305-2
P30305-2
P24898
P24898
P24898
P14635
P14635
O00311
O14773
P0C1X8
Q05982
Q05982
P31350
P31350
O70199
Q9UHD8-2
Q8WWK9
Q9Y5N6
Q9EPJ0
D4A5A6
D4A5A6
Q9JK25
O95251
O95251
Q3UV55
P70399
Q8TAP9
Q8TAP9
Q8TAP9
P82970
P11598
F1RR02
Q9UBF8
Q96JH7
Q96JH7
Q99666
Q9H4X1
P17325
P17325
P17325
Q6PGQ7
Q6PGQ7
Q6PGQ7
Q6PGQ7
Q9H467
F1LW91
P31001
P31001
P31001
Q9UJX2
Q9UJX2
Q9UJX2
Q9UJX2
Q9UJX2
Q2M2I8
P49916
P49916
P49916
P99024
O14715
Q9NQR1
P35251
P35251
P48432
P05067
P17706-2
Q9Y3Z3
O00267
Q9UJ70
Q9R1E0
O14745
O14745
P54578
P23769
Q96C19
O14980
Q9JK11-2
P42166
Q14244
P19804
P19804
Q9NZH5
Q96T23
O43521-2
Q13188
Q96C36
Q06413
O43663
O43663
P33993
P33993
NP_001178533
P22234
P46061
P46061
Q6Y7W6
Q2NKX8
NP_001099740
P13051
Q9Y5T5
P26358
P27361-3
O00399
Q9Y4H2
Q8TF76
P62138
P17096-2
P17096-2
O60285
P61020
Q9H1E3
O75152
P20338
Q8NFH8
P30101
Q8NEB9
P35565
Q06481
Q96Q89
O35280
O35280
Q4FZY0
Q16512
Q16512
Q16512
Q16512
P07437
P62820
P24864
O60346
O60346
O60346
O60346
O60346
O60346
O60346
O60346
O60346
O60346
O60346
O60346
O60346
P20393
P13639
Q9H211
Q9H211
Q9H211
P12272
Q99708
Q99708
Q6P1N0
Q13415
Q13415
Q13415

P38919
P51587
Q9H9S0
Q9H9S0
O95235
O95235
O95235
O95235
O95235
O95235
O95235
Q53HL2
Q9H410
O95239
Q69YH5
Q8IVT2
Q8IVT2
Q8IVT2
Q8IVT2
Q8IVT2
Q8IVT2
Q8IVT2
Q8IVT2
Q8IVT2
Q8IVT2
Q8TD19
Q8NCD3
Q8NCD3
Q8NCD3
Q8C6L5
Q13009
P11171
P11171
P15172
P15172
P15172
Q07666
O95997
P22314
P22314
P52926
P52926
Q08379
Q08379
O14994
ENSP00000347528
P60891
Q14CB8
Q14CB8
Q96GX5
Q96GX5
Q9NZD0
Q9P2W8
Q8N850
Q8N884
Q15021
Q15021
Q5TBA9
Q99549
Q99549
Q99549
Q99549
Q15291
Q15291
Q9H4B7
Q13885
Q9BVA1
P04350
P68371
Q9BUF5
A6NNZ2
Q3ZCM7
Q04725
Q04725
Q13049
Q13049
Q13049
O95139
O95139
O95139
Q14135-4
Q14135-4
Q14135-4
Q14135-4
Q8WUF5
Q8WUF5
Q1W668
Q1W668
Q1W668
Q1W668
Q9UI09
Q9UI09
Q9UNH5
Q9UNH5
Q9UNH5
Q9UGP4
Q9UGP4
Q9UGP4
Q9UGP4
Q3UNW5
P42898
O88942
Q93008
O00512
O75306
P42695
Q969R2
Q969R2
Q969R2
Q969R2
P49821
Q9UGL1
Q9UGL1
O94761
O94761
P56181
Q96QE3
Q811T9
Q9NRI5
Q9BTA9
Q9BTA9
Q9BTA9
Q9BTA9
O94901-9
O94901-9
Q9NZI6
Q99K48
P78344
Q96PY5
Q14106
O75170
Q5VXN8
Q5VXN8
Q86X82
F8W7Z5
Q8WTW5
Q8WTW5
Q8WTW5
Q8WTW5
Q96T22
Q15233
Q15233
Q15233
Q15233
Q03060-11
Q03060-11
Q9Y5J2
Q9HAH2
Q9HAH2
Q8NEL9
Q8NEL9
Q8NEL9
Q8WUX9
Q8WUX9
Q03188
P61371
Q9JJN0
Q642G4
Q92963
Q01105
O75381
P29692-2
P61978
P61978
Q14247
P04637
P04637
Q15717
P40763
O00429
Q9UQ80
Q99JB6
Q99JB6
P38936
Q15796
Q15796
Q15796
P16949
P16949
P46527
P10636-8
P10636-8
P10636-8
P03372
P03372
P03372
P03372
P03372
Q15003
Q14676
Q14676
Q14676
Q9NYV6
P31749
P31749
P49736
P49736
P49736
P49736
P49736
P49736
P49736
P38398
P38398
P38398
P01106
Q99638
P29590
Q03112
P46060
O43395
P30307
P06401
P06401
P06401
P06401
P06401
P06401
P18858
P18858
P18858
P18858
P10244
P10244
P10244
P10244
P10244
P10244
Q14194
Q14980
O15350
Q9ULW0
P10275
P49450
P24941
Q9BZL4
Q8IXJ6
Q12778
Q12778
P25054
Q13118
Q969V6
P29351
Q7Z2Z1
Q7Z2Z1
P54132
O14757
O14757
P30304
P46013
Q9UKM9
Q9UEY8
Q15648
Q15648
Q16204
P25205
P12956
P39748
Q9UPP1
P06400
P06400
P06400
P06400
P06400
P06400
P06400
P06400
P06400
P06400
P06400
Q00536
Q9NXR1
Q05209
P15146-3
Q96T88
P17676
P10412
P10412
P55273
Q14103
O95295
P23771
Q07820
Q07820
Q07820
Q07820
Q07820
P15336
Q05682
Q9H8Y8
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q15788
Q01196-8
Q01196-8
Q01196-8
Q01196-8
Q03555
P29966
P29966
P33981
P33981
P33981
P23804
O43303
O43303
O43303
O43303
O43303
O43303
O43303
O43303
Q9Y2W1
P25098
Q9NYF8
Q8IZL8
Q8IZL8
P21272
P21272
Q12800
Q12800
Q12800
Q12800
Q8TDN4
P38432
Q15910
Q15910
P50613
P50613
Q99728
Q99728
Q99728
Q99728
P19338
P19338
Q14202
P30309
P10085
P17096
P50570
Q61188
P62136
P25206
P04183
Q01167
Q01167
Q9NZJ0
Q04637
P48200
P49459
Q08050-2
P15927
P15927
P15927
O00571
Q12959
Q12959
P06748
P06748
P06748
P06748
Q9UQR0
Q9UQR0
Q9UQR0
Q9UQR0
O00311
P31350
P31350
O95251
P82970
P49916
P49916
P49916
P48432
P48432
P17706-2
Q9Y3Z3
O00267
O00267
O00267
Q9R1E0
Q9JK11-2
P33993
P33993
P22234
P46061
P46061
Q6Y7W6
Q6Y7W6
P13051
P13051
P13051
P13051
P26358
Q9H1E3
O75152
P15923
P15923
P15923
P15923
Q14191
Q14191
Q9UGP5
Q9UGP5
Q9UGP5
Q9UGP5
P06536
P06536
Q9H3D4
Q03468
Q9NS91
Q9EQW6
Q96KS0
Q9BZS1
P24864
P24864
P24864
O43623
O43623
Q99626
Q02363
O75533
O75533
O75533
O75533
O75533
O75533
O75533
P42677
Q13309
O75469
O75469
O75469
O75469
O75469
O75469
Q08999
Q08999
Q08999
Q08999
Q08999
Q08999
Q08999
Q08999
Q08999
Q08999
Q08999
Q08999
Q08999
P62324
P13639
P13639
Q9H211
Q9H211
O75179
O75179
O75179
Q5JTZ9
P78317
P78317
Q13352
Q13352
Q9WU82
Q9WU82
Q9WU82
Q9WU82
Q8WYH8
Q99607
Q99607
Q15554
Q9NSV4
P28324
P28324
P12268
P12272
Q99741
Q99741
Q99741
P55196
P10644
Q61937
Q15813
Q53GL7
Q53ET0
P31943
Q99708
Q99708
Q9NYB0
A1KXE4
Q13330
Q96E09
Q6P1N0
Q53H80
Q53H80
P54198
P48972
P48972
P48972
Q9Y2K7
Q14207
Q14207
Q14207
Q14207
Q14207
P30050
Q9UM11
Q9UM11
Q9UM11
Q9UM11
O60504_VAR_055019
Q9H425
P15146-2
Q9NP87
P33991
P33991
P33991
Q9BXR0
Q9H2G4
Q9H2G4
O60271
Q05516
Q05516
P29374
P29374
P29374
P29374
P29374
Q5TZA2-2
Q9ULX3
Q9NRH3
Q6XBN7
Q86T82
Q86XL3
Q9H3P2
Q9UKY1
P08621
P49717
P49717
P49717
Q8WXE1
Q8WXE1
Q13416
Q13416
Q96II8
Q02535
P50750
Q9Y676
Q13415
Q13415
Q13415
Q8IXM2
P28749
P28749
P28749
P28749
P28749
P28749
P28749
P28749
P28749
P28749
P28749
Q92547
Q92785
Q0VD86
Q0VD86
Q0VD86
P23772
Q02539
P52948
P62913
Q9C0C2
P38919
Q9Y253
Q9C0C9
P23258
O14686
Q13242
P48634
P20248
Q71UM5
O15014
O14497
Q96T88-2
Q9H910
Q7KZ85
P15146
Q12948
Q6UB35
Q15047
O60934
Q6PKG0
Q6PKG0
Q6PKG0
Q8NBZ0
Q9UPN3
Q03252
Q9UIF9
Q8WUM0
Q2NL82
P62483
P62483
P22674
Q9P2B4
O75616
P55795
Q9P270
Q9H6K1
Q9C0D5
P51649
Q8IXJ6-2
Q5JTV8
Q8TAP6
P84022
P84022
P84022
P84022
P84022
Q9H3D4-2
P51587
P51587
Q9R207
Q13303
Q12906
Q92698
Q92698
P17480
P33981-1
Q96GX5
Q16656
Q16656
Q9NZD0
Q9NZD0
O35144
Q9NY74
Q9NY74
O94761
O94761
Q14106
Q8WTW5
Q8WTW5
Q8NG08
O00499
Q8VEH2
Q9GKR4
Q9GKR4
Q9GKR4
Q9HCH8
P48431
P48431
O43463
P23921
P61978
P35611
P35611
P35611
P35611
P14598
P05787
Q14247
Q14247
P29473
P29473
P29473
P29473
P04637
P04637
P78536
P35568
P35568
P23396
P40763
P49841
O00429
Q09472
Q09472
Q09472
Q09472
Q09472
Q09472
Q09472
Q09472
P14618
P38936
P38936
P38936
P11799
Q63881
Q63881
Q63881
Q15796
Q15796
Q15796
Q15796
Q14654
Q14654
P31016
P31016
Q9JIR4
Q9JIR4
P16949
P16949
P14921
P07101
P46527
P46527
P46527
Q96PH1-4
P31645
Q14674
P07101-3
P09917
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
Q00613
Q00613
Q13153
O75582
O75582
O75582
P32004
P32004
P03372
P03372
P03372
P05412
P05412
Q9Y6W5
Q9Y6W5
Q14005
Q14005
P32121
P32121
P11388
P11388
P11388
P11388
P11388
O46606
Q04206
Q62622
Q62622
Q62622
Q62622
Q62622
P28482
P28482
P01106
P01106
P22736
Q15672
Q15596
P29590
P29590
P29590
P29590
O95863
O95863
P04198
Q13541
Q13541
Q13541
Q13541
Q9UBN7
P68400
P68400
P67999
P67999
P67999
P67999
P06401
O75676
O75676
P49795
Q04637-8
O43521
Q8IX03
Q8IX03
P10275
P04049
P04049
P04049
P04049
P04049
P24941
P24928
P33242
Q15797
Q15797
Q15797
Q15797
Q13285
O43524
O43524
O43524
O43524
P00533
Q8N122
Q8N122
Q8N122
P04626
P36956-3
P36956-3
Q9H3M7
P15056
P15056
P09874
P09874
P28562
P28562
P28562
P28562
O75581
O75581
O60716
O60716
O60716
P04177
P04177
P42229
Q8CBD1
Q8CBD1
Q8IW41
Q01844
Q92934
Q02750
Q02750
Q02750
P18654
P18654
P18654
Q969V6
P22893
P49137
P49137
P49137
P49137
P49137
P07101-2
P49815
P35236
P35236
Q3V6T2
Q3V6T2
Q15648
Q15648
P49790
P49790
P49790
P49790
P49790
P49790
P49790
P49790
P49790
P49790
P35612
P35612
P35612
Q92974
Q16665
Q16665
P29294
P29294
P33076
P33076
P54227
P55211
Q86UR1
Q01860
Q01860
Q01860
Q08499-2
P11881
P11881
Q07343
Q05209
Q08495
Q08495
Q3UVX5
P17655
O94811
O94811
Q00059
Q71RJ2
P02687
P02687
Q08493-2
P27708
P17676
P08955
P06239
P06239
P24529
P37802
Q15746
P19793
P36956
Q07820
P49715
P23928
Q16828
Q16828
Q9DBB1
Q9DBB1
Q16690
Q16690
Q16690
P15336
P15336
P49023-2
P49023-2
P49023-2
Q63531
Q63531
Q63531
P37285
Q9BUB5
P28033
P70302
P70302
P70302
Q9NYA1
Q9H8Y8
Q9H8Y8
Q8WX93
Q8WX93
O70337
P50616
P50616
P50616
P10415
P10415
P10415
Q60793
P37238
P37238
Q9NQ66
O75030-9
Q13614
Q6U1J6
Q80YV2
Q80YV2
P19419
P19419
P19419
P19419
P19419
P19419
P19419
P19419
P19419
P12980
P08047
P08047
P08047
Q15788
Q15788
Q15788
Q63622
Q96RK0
Q96RK0
Q92793
Q01196-8
Q01196-8
Q01196-8
Q01196-8
Q01196-8
P54283
P54283
Q00657
P47930
P47930
Q96FF9
Q96FF9
Q62120
O88498
Q66H76
P17861
P17861
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
P35658
P35658
Q08775-5
P29590-4
P29590-4
P29590-4
P29590-4
P29590-4
P29590-4
Q8VDS3
Q9NRA0
Q9NRA0
C9JLW8
C9JLW8
P49407
P78347-2
P78347-2
P10417
Q14790
Q9ULC4
P97287
Q8N9N5
Q8N9N5
P09951
P09951
P52909
Q03555
Q04211
P26431
P26431
O60244
P29966
P16951
Q96Q27
Q96Q27
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q9UKX7
Q9UKX7
Q05152
Q05152
P27577
Q08369
Q02447
P11362
P14784
P42702
P62070
Q05682-4
Q62947
Q9CQJ7
Q5ZMW5
P46152
P70531
Q62132-2
Q969H0
P33981
P12841
P12841
O60331
Q12931
Q00175
Q92908
O88447
Q86UC2
Q9UQC2
P10828
O35254
Q61183
Q9NRF2
P53355
P53355
P41182
P41182
Q13164
Q12772
Q12772
Q62227
Q61097
Q14934
P02686
Q9UPT5
Q99814
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
Q13322
Q13322
Q13322
Q9Y613
P51812
P51812
Q60749
Q60749
Q60749
Q13586
Q13586
Q13586
P23443
P23443
P23443
Q9GZM8
Q9GZM8
Q53EZ4
Q53EZ4
O00562
O00562
P14635
P14635
P17325
Q96I25
Q96I25
P52945
P52945
Q15750
P19525
P05198
O00213
O00213
O00213
O00213
P19332
O43623
O43623
Q64350
Q9Y463

P19634
P19634
P19634
P19634
P19634
P19634
P19634
Q8C050
Q8C050
Q8NHW3
Q8NHW3
Q15554
Q53ET0
P50548
P50548
P50548
P50548
Q61743
Q61743
Q15418
O35740
Q9D0A0
Q9D0A0
Q02224
Q02224
Q02224
Q02224
P30041
Q9BY84
P41969
P41969
P41969
P41969
P41969
P41969
P41969
P41969
Q07889
Q07889
Q07889
Q07889
Q07889
Q96EP5
Q96EP5
O95600
P84022
P84022
P84022
P84022
Q9NZ72
P15066
P15066
P15066
P15923-2
P15923-2
P15923-2
Q96RS0
Q13625
Q505F1
Q5JQC9
Q63155
Q63155
Q63155
P01100
P01100
P01100
P01100
P01100
P19878
Q91YD3
Q91YD3
Q15700
Q08499-4
B2RWS6
B2RWS6
B2RWS6
P25118
P25118
P25118
P25118
P25118
P25118
P25118
P37231
P35398-4
Q08499-5
O08537
O08537
Q5T447
P07196
Q60867
Q60867
Q60867
Q60867
Q9BTL3
Q96LC9
Q96LC9
P00558
Q7TQF7
Q04982
Q9Z0V2
Q9Z0V2
Q9Z0V2
P47712
P63086
Q7L5N1
Q14686
O35244
Q07343-2
P46695
P46695
P46695
O60504-2
P11308
P11308
P11308
P11308
Q9ULV5
Q9H9S0
Q9H9S0
P35398
P15976
P15976
P15976
P15976
P21802
Q07666
P17480
P17480
P43354
P43354
ENSP00000352232
Q62151
Q13878
Q14761
Q9Y6K1
P08235
P08235
P08235
P08235
P08235
P08235
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q53GS7
Q53GS7
Q53GS7
Q53GS7
Q53GS7
Q8K1M6
Q9UQ13
P26651
P78543
P43146
P43146
P43146
P13056
O60504
Q9NVD7
Q9NVD7
Q13127
Q13127
P13591-1
Q15366
Q15366
Q15366
Q15366
NP_059009
NP_059009
NP_059009
NP_059009
Q8K3Y3
Q99967
Q99967
Q99967
Q6S5L8
Q8BTI8
Q4W5Z4
Q9H9Z2
P25962
B0I4X3
O94953
O94953
O94953
O94953
O94953
O75030-10
Q925J9-4
Q925J9-4
Q92606
Q92606
Q92606
Q6UUV7
Q15007
Q15007
Q15007
Q8BGD7
Q8BGD7
Q8BGD7
Q8BGD7
Q8BGD7
Q8BGD7
P15408
P15408
Q9H0F6
P49366
Q62739
Q62739
Q62739
Q62739
Q9Y5A9
Q9Y5A9
Q64018
Q86U44
Q86U44
Q86U44
P23415
Q9NRZ9
A9UK05
P61978
P61978
P05787
P05787
P04637
P04637
P35568
P35568
P35222
P35222
P35222
P40763
Q61337
P38936
P38936
P38936
P31016
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
P05412
P05412
P05412
P05412
Q8C863
Q8C863
Q8C863
Q96EB6
Q96EB6
Q96EB6
P06837
P06837
P01106
P01106
P22736
Q15672
P30307
O43379
P46937
P46937
P46937
P46937
P46937
Q13526
P10275
P10276
P10276
P10276
P11802
Q9WVH4
O43524
Q8N122
Q8N122
Q8N122
P36956-3
P36956-3
Q13363
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q02248
Q02248
Q14653
P42226
Q01844
P04150
P42225
Q05639
Q05639
Q6JBY9
Q6JBY9
Q6JBY9
P63104
Q07817
Q07817
Q07817
Q13043
P54227
P54227
P13668
O95644
P81122
P21818
P21818
Q96P20
P19793
P19793
P19793
P19793
P36956
Q07820
Q07820
Q07820
P15336
P15336
P15336
P15336
P10415
P10415
P10415
Q13950
P19419
P08047
P08047
O43561-2
O88498
O88498
P10417
P29966
P16951
P16951
P98083
Q14934
Q14934
P49023
P30305-2
P30305-2
O43521-2
O43521-2
O43521-2
Q06481
Q93045
Q96I25
Q96I25
P06536
Q15750
O88809
Q9H3D4
P17275
P17275
P08592
Q8WYK2
Q9H211
Q9H211
Q9H211
Q9H211
Q9H211
Q9H211
Q9H211
Q9H211
Q99607
P28324
P28324
P28324
P28324
P28324
P28324
P15146
P15146
P15146
Q9NZ72
P37231
Q96LC9
P14618-2
Q14451
P05067-4
Q04666
P55957
Q9UQF2
Q9UQF2
P98177
P98177
P98177
P98177
O54918
O54918
O54918
O54918
Q96J02
Q96J02
Q96J02
Q9NRA8
Q9NRA8
Q9NRA8
Q9NRA8
Q9NRA8
Q9NRA8
P28667
P28667
P28667
Q60700
Q60700
Q6JBI6
Q6JBI6
Q6JBI6
Q6JBI6
Q6JBI6
P54259
P54259
P31947
O09112
O09112
O09112
Q9ESN9
Q9ESN9
Q9ESN9
Q60591
Q60591
Q60591
Q60591
Q60591
Q60591
P54846
P17535
P85298
Q149T7
Q149T7
Q149T7
Q9NR28
Q9NR28
P05627
Q8WYQ5
Q96FI4
Q96FI4
Q96FI4
Q12904
Q8N6T7
Q7KZF4
P54841
P31946
Q9NPI6
Q9H2B2
Q16621
Q16621
Q6NUR9
Q1W668
Q1W668
Q9UGP4
Q9UGP4
Q9UGP4
Q9UGP4
Q969R2
Q969R2
Q969R2
Q969R2
P10070
Q53GS7
Q53GS7
Q53GS7
Q53GS7
Q53GS7
Q14749
B5B2W9
B5B2W9
P46937-3
P46937-3
P46937-3
Q6SZW1
Q8K4K7
P50232
P20263
P61978
P61978
P53004
P14598
P14598
P05787
P42224
Q14247
Q14247
Q08775
P04637
P04637
P78536
P35568
P23396
O95817
O95817
P49841
O00429
P38936
P38936
P11799
Q63881
Q63881
Q63881
Q15796
Q15796
Q15796
Q15796
Q15796
P07101-4
P23977
P07101
P46527
P31645
P07101-3
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
O75582
O75582
O75582
P41236
P03372
P03372
P03372
Q9Y6W5
Q9Y6W5
Q9Y6W5
Q14005
Q14005
P32121
P32121
P11388
P11388
P11388
P11388
P11388
P10242
Q9NYV6
Q15672
P56270
Q15596
Q9UBN7
Q9UBN7
P06401
O75676
O75676
P49795
Q04637-8
O43521
Q8IX03
Q8IX03
P10275
P10275
P04049
P04049
P04049
P24941
P24928
P13631
O43524
O43524
O43524
O43524
P00533
Q8N122
Q8N122
Q8N122
P04626
P15056
P15056
P28562
O75581
O75581
P42229
Q01844
P04150
Q92934
Q02750
Q02750
Q969V6
P07101-2
P49815
Q15648
P49790
P49790
P49790
P49790
P49790
P49790
P49790
P49790
P49790
P49790
P33076
P33076
P55211
Q86UR1
P61586
P61586
P21146
Q01860
Q08499-2
O95644
Q9UJY1
Q9UJY1
Q9UJY1
Q05209
P17655
P27708
P17676
P17542
P06239
P06239
Q15746
P16144
P19793
P36956
Q07820
Q07820
P49715
P23928
Q16828
Q16828
Q16828
Q16828
Q9DBB1
Q9DBB1
P17679
Q16690
Q16690
Q16690
P15336
P49023-2
P49023-2
P49023-2
Q63531
Q63531
Q63531
P37285
Q9BUB5
P28033
P28033
Q05682
Q05682
P70302
P70302
P70302
Q9NYA1
Q9H8Y8
Q9H8Y8
Q8WX93
Q8WX93
O70337
P50616
P50616
P50616
P10415
P10415
P10415
Q60793
P37238
Q9NQ66
Q13950
Q13950
Q13950
Q13950
Q13950
Q13950
Q13950
Q13950
Q13950
P04972
O75030-9
Q13614
Q9Z1S8
Q9Z1S8
Q9Z1S8
Q9Z1S8
Q9Z1S8
Q6U1J6
Q80YV2
Q80YV2
P41212
P41212
P19419
P19419
P62813
P12980
P08047
P08047
P08047
O43561-2
Q15788
Q15788
Q63622
Q96RK0
Q96RK0
Q92793
Q01196-8
Q01196-8
Q01196-8
Q01196-8
Q01196-8
P54283
P54283
Q8R4Z9
Q00657
P47930
P47930
Q96FF9
Q96FF9
Q62120
O88498
Q66H76
P17861
P17861
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
Q8IZP0
P35658
P35658
O70162
O70162
O70162
Q92974-2
Q92974-2
Q08775-5
Q08775-5
P20339
O08529
P29590-4
P29590-4
P29590-4
P29590-4
P29590-4
P29590-4
Q8VDS3
Q9NRA0
Q9NRA0
Q03060
Q9UIG0
Q08509
Q08509
C9JLW8
C9JLW8
P49407
P27361
P27361
P78347-2
P78347-2
Q14790
Q9BR01
P97287
Q8N9N5
Q8N9N5
A6X8Z5
A6X8Z5
Q16559
Q03555
P63000
Q04211
P26431
P26431
Q15046
O60244
P29966
Q9UHB6
Q9UHB6
Q9UHB6
Q96Q27
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q9UKX7
Q9UKX7
Q05152
Q05152
P27577
Q08369
Q02447
P11362
P14784
P42702
P62070
Q05682-4
Q62947
Q9CQJ7
Q5ZMW5
P46152
P70531
Q969H0
P35228
P33981
O60331
P27824
P27824
Q12931
Q92908
O88447
Q86UC2
Q9UQC2
P10828
P10301
Q92797
Q61183
Q9NRF2
Q8CI15
P53355
Q16254
Q16254
P41182
P41182
P31395
Q13164
Q12772
Q12772
Q62227
Q61097
P43364
Q9PU52
Q14934
P02686
Q9UPT5
Q16584
Q16584
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
Q13322
Q13322
Q13322
P51812
Q13485
P01100
P01100
P01100
P01100
P15976
P15976
P15976
P15976
P17480
P17480
Q01892
O14994
ENSP00000352232
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q8IZQ8
P78543
B0I4X3
O75030-10
Q92606
Q92606
Q92606
Q8NET8
P61978
P61978
P38936
P38936
P01106
P01106
P01106
P54227
P54227
O95644
Q8VDS3
P97287
P97287
P98083
P05067
O43521-2
Q06481
P06536
P05067-4
P55957
Q9UQF2
Q9UQF2
O54918
P54259
P54259
P28738
Q61768
Q16600
Q16600
Q969R2
Q969R2
Q969R2
Q969R2
Q9BT38
P05067-3
P61978
P68431
P68431
P04637
P04637
P04637
P53671
P53671
P53671
P49841
P08670
Q9UNN5
Q9UNN5
P03372
P03372
P25490
P49810
P25963
P25963
P25963
P25963
Q96EB6
P49736
P38398
P41208
P40337
P30305
Q13563
Q12798
O75496
Q14194
Q14194
O43379
O43379
O43379
O43379
Q6NUF4
Q6NUF4
Q6NUF4
O14965
O14965
O14965
O14965
O14965
O14965
O14965
O14965
O14965
O14965
O14965
O14965
O14965
O14965
O14965
P50516
O15143
Q14980
Q14980
Q14980
Q14980
Q14980
Q14980
Q14980
Q14980
Q14980
Q14980
Q96EZ8
Q96EZ8
Q14203
Q13761
Q13761
P46937
P12755
P12755
Q91636
Q91636
Q9BQG0
Q8WV24
Q9HC77
P70166
P70166
Q8TEW0
Q8NHV4
Q9ERR1
P53350
Q15398
Q15398
Q15398
Q15398
Q13158
Q9NRM7
Q9NRM7
O15350
O95983
O95983
Q49MG5
Q49MG5
O43521
O43521
O43521
Q14511
O14777
O14777
O14777
Q9ULW0
Q9ULW0
Q9UPY8
Q13526
Q8IX03
P10275
P10275
Q96CG3
O15360
Q9BXS6
Q9JJ11
P49450
Q9NS23-2
Q9NS23-2
P11233
Q9Y6A5
Q99623
P53667
P53667
P05783
Q92974
P48729
O00560
O00560
Q96R06
Q9GZM8
P06748
Q99708
Q99708
Q02224
Q9UJX3
O95239
Q9NZD0
Q9BZB8
P00352
P00352
P00352
Q9Y657
Q9Y657
P07195
Q9BT25
Q9BT25
Q14863
Q9NWT8
P57073
Q16600
Q9BY57
P30305-3
Q96CX2
Q96CX2
Q6RSS1
Q3B891
Q93073
P35570
P35570
P35570
P35570
P14598
P14598
P14598
Q9H257
Q9H257
P42224
Q99808
P15381
P04637
P04637
P04637
P04637
P04637
P04637
P04637
P12830
P12830
P12830
Q9Y618
Q9Y618
P12957
P12957
P55042
P55042
P55042
P55042
P55042
P46527
P11831
P11831
P11831
P11831
P15337
P15337
P15337
P15337
P15337
P15337
P07293
Q00960
P37840
Q00613
O95786
O95786
O95786
Q13153
P52927
P52927
P52927
P52927
Q9CVD2
P35638
P35638
P35638
P35638
P08473
P60484
P60484
P60484
P60484
P60484
O75582
O75582
O75582
O75582
O75582
P41236
P41236
P41236
P26361
P26361

P26361
P51636
P51636
Q01082
Q01082
P26432
P26432
Q28862
Q28862
Q28862
Q28862
Q28862
Q28862
Q28862
Q28862
Q28862
Q28862
Q28862
Q28862
O54943
O54943
O54943
Q9UNN5
Q9UNN5
P35580
P35580
P35580
P35580
P35580
P30260
Q16625
Q16625
Q16625
Q13148
Q13148
Q13148
P32004
P32004
P18887
P18887
P18887
P18887
P18887
P18887
P18887
P18887
P18887
P18887
P18887
P18887
P18887
P18887
P18887
P83916
Q15555
P03372
P03372
P03372
P42892-3
P42892-3
P42892-3
Q62627
Q62627
P97461
P97461
P04004
P04004
F1LSG0
F1LSG0
Q15287
P35221
P25490
P42768
P42768
O60936
P25686
P25686
P25686
Q8N5B7
Q8N5B7
Q8N5B7
Q8N5B7
P55010
P55010
P55010
P55010
Q18PE0
Q18PE0
Q18PE0
Q18PE0
Q18PE0
Q18PE0
Q18PE0
P09803
P09803
P09803
P09803
P09803
Q96PX8
P05114
P05114
P05114
P05114
P05114
Q6VY07
Q03267
Q03267
Q03267
Q03267
Q03267
Q03267
Q03267
Q13393
Q13393
P49959
P49959
P49959
P49959
P49959
P45984
P45984
P05412
P05412
P05412
P18846
P18846
P18846
P18846
P18846
Q96FW1
Q9UKD2
Q9UKD2
Q9UKD2
Q04724
Q04724
P35226
Q9Y6W5
Q9Y6W5
Q9Y6W5
Q9Y6W5
Q9Y6W5
O00170
Q01827
Q01827
O14958
O14958
Q15003
P09629
P09629
P09629
P09629
P60983
P08195
P08195
P08195
P08195
P08195
Q06787
Q9HA82
Q9HA82
Q9HA82
Q9HA82
Q14676
Q14676
Q14676
Q14676
Q14676
Q14676
Q14676
Q14676
Q14676
Q14676
Q14676
Q14676
P06127
P06127
P06127
P02649
Q13371
Q13371
Q13371
Q13371
Q13371
Q6ZMG9
Q6ZMG9
Q6ZMG9
Q6ZMG9
P33724
Q61985
P0DP23
P0DP23
P0DP23
P0DP23
Q08945
Q08945
Q08945
Q03014
Q03014
Q8C863
P42582
Q14005
Q9UER7
Q9UER7
P47239
Q14940
Q14940
Q14940
Q14940
Q14940
P49810
P49810
P49810
P49810
P47863
P47863
P47863
O15266
Q9UHH9
Q9UHH9
P37238-2
P37238-2
P25963
P25963
P25963
P25963
P25963
P25963
P25963
XP_849482
XP_849482
P32121
P11387
P11387
Q96SB4
Q96SB4
Q96SB4
Q96SB4
Q62717
Q62717
Q62717
Q62717
O75925
O75925
O75925
Q9UKX2
P04775
P04775
P04775
Q96EB6
Q96EB6
P21673
P21673
P11388
P11388
P11388
P11388
P08833
P08833
P08833
P07221
P17936
P17936
P17936
Q9UQE7
P05455
P10242
P10242
Q13323
Q13323
P67870
P67870
P16220
P16220
P16220
P16220
Q9Y5B0
Q9Y5B0
Q9Y5B0
Q9Y5B0
Q9Y5B0
Q9Y4R8
Q9Y4R8
Q9Y4R8
P06837
P06837
P06837
P06837
P06837
Q01717
Q01717
Q01717
Q9NYV6
Q9NYV6
P13383
P13383
P13383
O46606
O46606
O46606
P54252-2
P54252-2
P54252-2
P62161
Q61699
Q96IZ0
Q00987
Q00987
Q08705
Q08705
Q08705
Q08705
Q62773
Q9Y365
Q60997
P02316
P02316
O08608
P54274
O15259
O15259
O15259
Q61006
Q61006
O14950
P31749
P12821
P49736
P49736
P49736
P49736
P49736
P49736
P49736
P49427
P49427
P49427
P49427
P49427
P50895
P41541
Q8NE71
Q8NE71
Q8BMD2
Q8BMD2
Q8BMD2
Q8BMD2
P30203
P30203
P30203
P07900
P07900
P07900
P07900
O75822
P38398
P51946
Q13509
Q04206
O95905
O95905
O95905
O88828
P39687
P39687
P47823
P47823
P46531
P46531
Q8TAE8
P32851
P11717
P11717
P19447
Q92915
Q92915
Q16666
Q15084
Q15084
P00736
Q9UJU2
Q9UJU2
Q60864
P30622
Q62048
P20042
P20042
P08551
P16546
Q712K3
Q62622
P29692
P49418
P49418
P33527
P13569
P13569
P13569
P13569
O95477
O95477
O95477
P09958
P09958
Q923E4
Q923E4
Q923E4
Q923E4
P41208
P41208
O43852-15
P28482
P28482
P02638
P01106
P01106
P01106
P01106
P01106
P22736
Q9UBF6
P27699
P27699
Q96RL1
Q96RL1
Q6PAJ1
P49716
P10646
P13834
Q15672
Q15672
P35579
P35579
Q16623
Q99638
Q99638
Q96HZ4
Q9ULV4
Q92688
P18422
P18422
Q28147
Q28147
P53787
P40337
P40337
P40337
P48426
P10243
Q06265
Q06265
Q92784-2
P56270
Q02078
P84088
Q9BPX3
Q9BPX3
Q06609
O88572
P23760
P14317
P14317
Q15653
Q15653
P24668
Q13829
Q13829
Q640N2
Q02067
Q9UJY5
P52946
P52946
Q13426
O15379
Q16543
Q15019
P30305
P30305
Q9UMD9
Q9UMD9
P13839
P13839
P13839
P13839
O60341
O60341
D3ZFT1
D3ZFT1
D3ZFT1
P61244
P61244
P08238
P08238
P08238
P61265
Q15596
Q15596
Q15596
Q15596
P29590
P29590
P29590
P29590
P09023
P34826
P34826
Q92769
Q14493
O75376
P42575
P35922
O95863
P13349
P13349
Q62881
P36955
P36955
Q9HCU9
Q03112
Q03112
P04198
P04198
P24610
Q63737
Q63737
Q63737
Q9Y237
Q96KQ7
Q13541
P46060
P09057
P27540
P00257
P36381
P04818
P04975
P04975
Q6J4I0
Q6J4I0
Q6J4I0
O43395
O76061
O60671
O60671
P63058_OBS
P63058_OBS
P43629
P43629
P02671
P02671
P61982
O15392
P06744
Q68FX6
P12763
P12763
P12763
Q9UBN7
Q63692
Q01534
Q13563
P30307
Q13547
Q13547
P32120-2
Q13283
Q15185
Q15185
P09651
P52907
P07910
Q93009
O43156
Q0IIL7
Q01105-2
Q04207
P11473
P30291
Q9WTL8
Q12798
P01131
P68400
P06493
P53539
P67999
Q91YI4
Q61644
P06401
O14737
P12259
O75676
P18858
P10244
P05549
P49795
Q13133
Q04637-8
P27986
O75496
Q92538
Q92538
Q13501
O15055
O15055
Q9NY61
Q9NY61
Q9NY61
Q9NY61
Q9BXW9
Q9BXW9
Q9BXW9
Q9BXW9
Q9BXW9
Q9BXW9
Q9UPP1
P0DMV8
P28033
P21272
P0C0S8
P17096
P17096
Q13428
P06748
P17096-2
P17096-2
P16104
P42858
P42858
P11274
P54252
P54252
O00327
P31751
Q61937
P00558
P08575
P08575
P08575
P08575
P27348
O75943
P40692
Q14839
Q14839
Q14839
Q9JIM1
Q8N6T7
P18848
Q9BSI4
O08816
O08816
P41002
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
P78344
P0DP29
P0DP29
P0DP29
Q8N5P1
Q14449
Q14449
Q14449
Q14449
Q14761
P58771
P06795
P06795
P06795
Q8IVP5
Q61850
O88508
O88508
Q9Y6K1
Q9Y6K1
P00374
P00374
Q6NXS1
Q6NXS1
Q6NXS1
Q8TF40
Q8TF40
Q8TF40
Q8TF40
Q8TF40
Q9UGP8
Q9UGP8
Q9UGP8
Q13530
Q13530
Q9C0B1
O43242
O43889
P30793
Q01831
Q01831
Q96G74
Q9BYF1
Q8VCD5
P15884
P15884
P15884
Q62936
P08235
P08235
NP_001093990
NP_001093990
NP_001093990
NP_001093990
NP_001093990
P20810
Q9BRS2
Q96NY9
Q92796-2
P54252-1
P49321-2
Q80ZG1
Q80ZG1
Q80ZG1
Q80ZG1
Q80ZG1
F1PMR9
F1PMR9
P83917
Q9JKX4
Q8NEL9
P02751-1
P35570
P15941
Q60795
Q60795
P04637
P35222
P35222
P35222
P35222
P35222
P40763
P40763
P49841
O00429
O00429
O00429
P12931
P12931
P12931
P12931
P14618
P38936
P38936
P11799
P31016
O15273
O15273
P14921
P14921
P11831
P31645
P15337
P37840
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
Q9CVD2
P60484
P60484
P41236
P26432
P03372
P03372
P03372
P03372
P09803
P05412
P05412
P05412
O75925
O75925
P11388
P16220
P16220
P50895
P07900
P07900
Q04206
P01106
P01106
P49716
P49716
P13834
P13834
P13834
P13834
P40337
P52946
P52946
O60341
P08238
O95863
O95863
O95863
O95863
O95863
O95863
O95863
P04198
P24610
Q13541
Q13541
Q13541
Q13541
P30291
Q9ERR1
Q9NS23-2
Q9NS23-2
Q9NS23-2
Q01094
Q01094
Q15797
Q15208
Q15208
Q13131
Q13131
Q13131
Q9H0B6
O70405
O70405
Q8N122
Q8N122
Q8N122
Q8N122
Q8N122
P49816
P49816
P49816
P49816
O75581
Q9D0L1
Q9D0L1
P25054
P25054
Q02248
Q02248
Q02248
O08679
Q9NP62
Q9R1U5
Q16555
Q16555
Q16555
Q14653
Q14653
Q14653
P10636
P10636
P10636
P10636
P10636
P10636
P13807
P13807
P13807
P13807
Q02156
P30281
P04150
Q07817
P54132
P30304
O15294
O15294
P35612
P35612
P19838
P19838
Q16665
Q16665
Q16665
P33076
P0DMV8
Q14896
Q14896
P24385
P17661
P17661
P17812
P47736
P15146-3
P15146-3
Q95N27
P17676
P17676
P17676
P48436
Q14103
P15924
P15924
Q15746
P19793
P19793
P19793
Q9UMX1
P36956
P36956
P36956
Q92837
Q07820
Q07820
Q07820
P28033
P28033
O75030-9
O75030-9
O75030-9
O75030-9
P08047
P08047
A6X8Z5
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q92908
Q16584
Q16584
Q6U7Q0
P01112
P01112
P01112
P23246
Q9NYF8
Q15691
Q15691
O35927
P21575
P30999
P30999
Q9Y6K9
Q9Y6K9
Q9Y6K9
Q9Y6K9
P21272
P21272
E9PAV3
Q7KZI7
Q15910
Q15910
Q6R327
Q6R327
Q96R06
Q96R06
Q96R06
Q96R06
O75122
O75122
O75122
O75122
O75122
Q9BYG3
Q9BYG3
Q92993
Q92993
P98170
Q08050-2
Q6PGQ7
Q6PGQ7
P05067
P13051
P13051
P56524
P56524
P08069
P22415
P22415
Q13485
Q13485
Q13485
P57059
Q9P0L2
O00213
P17275
P17275
Q00653
Q00653
Q00653
P58012
P49768
P49768
P49768
P28661
Q9QZW9
Q9QZW9
Q8K3Y6
Q8K3Y6
Q8K3Y6
Q8K3Y6
Q8K3Y6
Q8K3Y6
Q8K3Y6
Q8K3Y6
O95271
O95271
O95271
O95271
P12036
P70447
P70447
Q9NRR4
Q9NRR4
Q9EQW6
Q07812
Q3TFD2
Q3TFD2
Q96KS0
Q96KS0
Q9UKA4
Q9UKA4
O89038
O89038
O89038
P28334
Q9BZS1
Q9BZS1
O43602-2
P22670
P22670
Q15853
Q15853
P24864
P24864
P24864
Q96F46
P52947
P52947
O60346
O60346
O60346
O60346
O43623
O43623
O43623
O43623
P40124
Q60943
P20393
P20393
Q9UKT5
Q62952
Q62952
Q62952
P06401-2
P06401-2
P06876
Q9NRD5
Q9NRD5
O75952
O75952
Q9HB09
P14873
P56720-1
P47942
P47942
P47942
Q64350
P08592
Q99626
Q14195
Q14195
Q14195
P54252
Q9Y6H5
Q9H0Z9
Q01201
P06537
P06537
P30279
P23204
P16884
Q16236
Q16236
P12524
P12524
P16401
Q14494
O00327
O00327
Q13887
O15516
P53805
Q00944
P14719
Q8BUV3
O15033-2
P52630
P52630
P52630
P10914
P10914
Q8NHW3
Q8NHW3
Q8NHW3
Q8NHW3
Q9UPN3
Q9UPN3
Q9UPN3
Q9UPN3
Q9UPN3
Q9UPN3
Q9UPN3
Q9UPN3
Q9UPN3
Q9UPN3
Q9NZ72
P11308
O15169
P56537
P56537
P56537
P56537
P35869
P35869

P35869
P35869
P35869
P35869
P35869
P35869
P35869
Q60591
Q60591
Q60591
P30405
P21796
P21796
O75030
O95997
O95997
Q13765
ENSP00000343690
ENSP00000343690
ENSP00000343690
Q9NZQ7
Q9NZQ7
P19544-7
P19544-7
P19544-7
Q5CZI7
Q969R2
Q969R2
Q969R2
Q969R2
Q16615
Q14449
Q14449
Q14449
Q14449
Q14449
Q14449
Q49AN0
B3SXQ8
B3SXQ8
B3SXQ8
P15314
P15314
P54840
P54840
P54840
P54840
Q14596
Q5XFN2
Q5XFN2
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q14995
Q7Z2W4
Q7Z2W4
Q7Z2W4
Q7Z2W4
Q99684
Q99684
Q9JIY0
Q8CF90
Q8CF90
Q8CF90
Q8CF90
Q8CF90
Q9Y2X9
Q53GS7
Q53GS7
Q53GS7
Q53GS7
Q53GS7
Q01518
Q01518
Q921Y0
P70661
P70661
Q8BGW1
Q8BGW1
O88420
Q9NW38
Q9BPU6
Q9BXF6
Q9BXF6
Q5SW75
Q5SW75
Q62176
O75030-2
Q6FI05
P49841-2
Q7M6Y2
Q7M6Y2
Q06831
Q06831
Q14249
Q14249
P24071
Q9UKT6
P17947
P17947
Q9UKC9
Q9Y4K3
Q6IA17
P35570
P35570
P35570
P35570
P35570
P35570
P53004
P53004
P35611
P35611
P14598
P14598
P14598
Q9UBS0
P29473
P15381
P15381
P15381
P15381
P08057
P08057
P28329-3
P28329-3
P35568
P35568
Q96A00
P35222
P49841
P49841
Q9WVE0
Q01705
P08670
P08670
P08670
P10636-8
P10636-8
P10636-8
P10636-8
P60484
P60484
P60484
P35580
P35580
P35580
Q16625
Q16625
Q16625
Q16625
Q04206
O95863
P46937
P46937
Q8IX03
Q8IX03
O14920
O14920
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q13118
Q13118
Q5JVS0
Q5JVS0
P35612
P55211
P27448
P06685
Q8NER1
P08047
P08047
P08047
P08047
P08047
P08047
Q7KZI7
Q6STE5
Q9NPB6
P29317
Q15831
Q15831
Q9P0L2
Q07812
Q16236
Q9WTK7
Q05513
Q9Y243
P47712
P61587
Q9Z340
Q9WVS8
Q16612
Q95168
Q96RI1-2
P31946
Q8VHC5
O43175
O43175
O43175
Q15831-2
O43315
O43315
Q02956
Q02956
Q02956
Q8N2W9
Q15466
P97629
P97629
P55040
P26285
O88792
Q12933
P61809
Q9QZS3
Q15109
Q9GZQ8
Q96RI1
P09429
P09429
P09429
P49757-3
P49757-3
P49757-3
Q99M65
Q9UJZ1
P78563
P78563
P07340
F1M707
P35570
P35570
P35570
P35570
P35570
P35570
P35570
P35570
P15127
P15127
P15127
P15127
P15127
P22681
P22681
P22681
P16573
P16573
Q9Z200
Q4QQV2
Q4QQV2
O55173
O55173
O55173
Q2IBC5
Q2IBC5
P07150
P35570
P35570
P35570
P35570
P35570
P35570
P35570
P35570
P35570
P15304
P15337
Q14940
Q14940
Q14940
Q14940
Q14940
Q14940
Q14940
Q14940
Q9WVH4
Q9WVH4
Q9WVH4
Q9WVH4
Q9WVH4
O70405
O70405
O70405
O70405
Q8VIP2
P97784
P97784
P02340
O70343
O70343
P70460
P70460
Q02248
P35569
P22449
P11497
P11497
P11497
Q62600
Q62600
P56720
P54645
P54645
P49698
P70531
O88447
O88447
P70313
P70313
P55016
Q3U182
Q9Z2V6
Q9Z2V6
B2RWS6
P10361
P51639
P80386
P80386
P80386
Q60949
Q60949
Q5SWU9
P54310
P10853
P55014
Q91XJ1
Q91XJ1
Q91XJ1
Q3LRZ1
Q32Q86
Q32Q86
Q91XQ2
O35552
A2RRU1
Q00715
O88763
O88763
Q9QYK2
Q9QYK2
O08796
Q6PF93
Q6PF93
O88597
O88597
O88597
Q9Z1E4
Q8VCB3
Q64475
Q6ZWY9
Q64478
Q8CGP1
P10854
Q8CGP2
Q64525
Q64524
Q9D2U9
Q8K4Q0
Q8K4Q0
Q9WTN3
P15304-2
E9Q4Z2
Q9WUA5
Q99MZ3
P35570
P23396
P15337
O43524
O43524
P49816
P49816
P18266
Q62600
P35240
P35240
P62755
P62755
P54645
P18265
G3V7R4
G3V7R4
G3V7R4
P48679
P32182
O35147
Q3MKQ2
E9PST5
D3ZBQ1
D3ZBQ1
P61016
P16638
Q91ZN7
Q9Z330
P0CE43
Q5TKR9
P42346
P0C5E3
Q63085
P20417
O54748
O54748
P17431
P17431
P17431
P62961
Q9UMS4
P11345
P53563
Q09137
D3ZH75
P35570
P52631
P35570
P35570
Q60795
O08553
Q8C863
Q02248
P31995
P12318
P10637
P22723
P30999
P09793
P09793
P97427
Q80W68
Q80W68
Q80W68
Q80W68
Q3UND0
Q01097
Q01097
Q01097
Q01097
Q01097
Q01097
Q01097
O55042
P28867
P28867
P05532
P05532
P97813
P97813
P97813
P97813
Q91XM9
Q9QVP9
Q3U1F9
P49615
P39688
Q07763
Q07763
Q9QZS7
Q3UUV5
Q3UUV5
Q9QUM4
Q9QUM4
Q9QUM4
Q9QUQ5
Q9QUQ5
P42682
P22646
P22646
Q9JHI8
Q8BM65
Q8BM65
Q923Z0
Q923Z0
Q923Z0
Q923U0
Q923U0
Q923U0
Q923U0
P28776
B2CXA1
P70315
Q5QNS5
Q8R5A3
Q8R5A3
P35570
Q5F3W0
P62909
Q63369
Q63369
O00161
Q6TMG5
Q6TMG5
Q6TMG5
Q9QY17
Q63746
Q63746
O70377
O70377
P35570
Q60795
P08050
P18052
P18052
P23818
P23818
Q62048
P27699
P04049
P04049
P48787
P48787
P48787
P48787
P48787
P00533
P45481
P14602
P14602
Q8BYI6
G0YZM8
G0YZM8
G0YZM8
P20152
P20152
P20152
P20152
P20152
P20152
P20152
P20152
P20152
P20152
P20152
Q9UKG1
Q62101
Q60670
P28033
P28033
P16951
P16951
P16951
P02786
P19491
P31750
P48678
P48678
P48678
P48678
P48678
P48678
Q9WTK7
Q61743
Q505F1
Q505F1
Q9ERT9
P60879
Q99N57
P70441
P50752
P50752
P50752
P50752
Q68ED2
P56581
P56581
P63073
Q64314
Q64314
Q64314
Q64314
Q64314
P23819
P05532
P05532
P15383
P20444
P20444
O70439
P19785
P15409
P15409
P63080
P63080
Q8VHY0
Q6NZJ6
Q60641
Q60641
Q9Z239
Q91V14-2
E0CZ16
P53810
Q9DAS9
Q61029
Q28024
P53811
P53811
Q61553
P61979
Q64205
P30561
P55088
P26817
P68404
Q9ET78
P28700
Q8C3Q5
Q8C3Q5
Q91Z79
P35570
P35611
P35611
P14598
P14598
P35367
P08050
P08050
P08050
P33535
P11275
Q02294
Q02294
Q02294
P23385
O35433
O35433
P18052
P18052
Q13224
Q13224
P10636-8
P10636-8
P10636-8
P10636-8
P06127
P06127
P13569
P13569
P13569
P13569
P13569
P13569
P04049
P04049
P04626
P15127
P15127
P50753
P50753
P50753
P50753
P35612
P35612
O00168
O00168
P63251
Q9UJY1
Q9UJY1
O08589
O08589
P10636-2
P10636-2
Q7TNL5
P06685
P06685
P23693
P23693
P23693
P23693
Q00657
P29966
P29966
P25098
P07355
P21575
P22723
P22723
P19491
P19491
P19491
P19491
P21272
P21272
F1RR02
F1RR02
F1RR02
P49768
P08592
P05554
P02253
Q61743
Q05193
P19103
P26932
Q6PW52
P06213-2
P16573
P35439
P35439
P35439
Q15080
Q91XY5
Q03343
O70420
O70420
O70420
P60881
P60881
P00749
P00749
Q03721
Q03721
Q03721
Q03721
P31424-2
P47196
P61765
P61765
P58821
P43119
P12979
P07936
Q9WTQ2
P26285
P34900
P34900
P04272
P06766
P06766
P30009
P30009
P30009
P51639
P23634
Q63028
P70496
P70496
P70496
P10636-6
P10636-6
P10636-6
P10636-6
P10636-5
P10636-5
P10636-5
P10636-5
P02542
P02542
P02542
P02542
Q00959
P14925
P21707
P41035
O00161
O00161
O00161
O00161
Q61411
P19335
P19335
P19335
Q99JE6
Q92686
P78314
P78314
Q16760
Q16760
Q00169
Q00169
Q9NXH3
P53810
Q9DAS9
Q00969
Q00969
Q00969
Q62735
Q62735
P09429
Q3UIW5
P70496-2
P70496-2
P70496-2
O15539
O15539
P22756-4
P22756-4
Q8VH46
P30678
P13444
B5DEX4
Q99N77
Q9JIS4
Q9JIS4
P39086-2
P39086-2
P15431
O70377
O70377
O70377
Q812E9
Q812E9
P16446
P16446
P22723-2
P31044
Q62847
P32301
P32301
Q62666
P20395
P20395
Q14469
Q14469
P05696
P30679
P20272
P48548
P25122
O54968
Q01814
Q63099
Q63099
XP_006230684
XP_006230684
XP_006230684
D3ZNZ9
P35570
Q6AYD3
Q6AYD3
P08050
P23693
P23693
P23693
P25098
P09215
P09215
O15162
P63101
P62909
P62909
P68510
Q99JE6
Q9DAS9
P00564
P58195
Q9WTQ1
Q9WTQ1
Q923V7
P20411
Q9CQV8
Q6Q760
P35570
O35433
O08679
P15127
P06685
P06685
P09217
P47196
P97629
P97629
Q01714
Q01714
Q01714
Q01714
O08678
Q62735
Q63484
Q9QY78
Q9QY78
Q8VHF0
D4AE59
Q4FZT0
P35570
P35568
P35568
P35568
P35568
P35568
Q61337
P23818
P27699
P35922
Q9JLN9
Q9JLN9
P35569
P35569
P35569
P35569
P35569
Q9WV60
P23804
Q9WTK7
P54103
Q61823
P62754
P62754
O08796
P19785
Q6QI06
Q3TLD5
Q8CGC7
Q64364
P80314
P35570
P35570
P35570
P35570
P35570
P35570
P62753
P62753
P18266
P62755
P62755
P62755
P62755
P18265
P56720-1
P56720-1
P56720-1
O35147
P26285
P26285
P42346
P42346
Q9JID1
P35570
P31016
P35569
P13668
P13668
P21818
P21818
P52909
P17325
P17325
P06536
A4GTP4
O43602-2
O43602-2
O43602-2
P15146
P15146
P15146
O35147
P84245
F1MAL5
Q01714
Q01714
P49950
P49950
P49950
P50232
P54258
Q78E65
Q9R237
Q9R237
Q9EPH2
Q9EPH2
Q9EPH2
Q6AYT2
Q05343
Q05343
Q05343
Q05343
Q2EJA0
Q2EJA0
Q2EJA0
F1M787
NP_001258431
P35570
P35570
P35570
P49816
P35569
P35569
P35569
Q10728
Q10728
Q10728
Q64122
P48675
P48675
P48675
P47819
P47819
P53670
P53669
O88764
P62963
P35570
P31000
P31000
Q10728
Q10728
P51792-2
P47942
Q64122
Q64122
P60879
O35763
P31977
Q08290
Q08290
Q08290
Q08290
Q08290
Q63028
Q63028
Q62868
P35570
P35568
P35569
Q3U182
Q91X84
P61809
P35570
P08050
Q02294
Q02294
O35433
O35433
P19490
P19490
P19490
P19490
P31000
P31000
P31000
P31000
P31000
P31000
P31000
P47863
P04775
P04775
P04775
P04775
P04177
P15127
P31424
P31424
P11497
O08589
O08589
O08589
P06685
P06685
P22002
P42260
P42260
P19491
P19491
P21272
Q62968
P19103
P35351
P35439
P35439
P35439
P35439
P22756
P22756
Q03343
Q03343
Q03343
P60881
P60881
P26769
P26769
Q64666
O35240
O35240
P10687
P07936
Q6LED0
Q6LED0
P56741
P06766
P06766
P07727
P08033
P15383
P15823
P15823
P19836
P19836
P30009
P30009
P30009
Q63270
Q63270
P84245
P84245
Q63028
Q63028
P70496
P70496
P70496
Q9JJH5
P11345
P11345
Q9ESI7
Q9ESI7
Q9ESI7
Q9ESI7
Q9ESI7
P97924-6
P97924-6
P97924-6
O08565
O08565
O88420
Q9QY17
P07150
P15389
Q5XIS9
O70377
O70377
P16446
P16446
Q62847
O54968
Q8VIJ4
P49950
Q9EPH2
Q9EPH2
Q9EPH2
P63074
Q07936
Q04940
Q63633-2
P61169
P61169
P61169
P61169
P61169
O35260

D4ACL3
D4ACL3
P25095
P25095
P25095
P11505
P11506
Q64568
Q64542
Q64159
P26051
Q91ZN1
Q91ZN1
P25114
P25114
P85845
Q9R1K8
A1L1K8
A1L1K8
Q3KRD8
Q02955
O70617
P06907
P06907
P06907
Q06496
Q9QUS1
P97887
P04774
P08104
P15390
O08562
P81728
Q10836
Q9ESQ5
Q9ESQ5
P35570
Q157S1
Q3LRZ1
P53004
P53004
P53004
P35568
P35568
P35568
P35568
P35568
P35568
P35568
P35568
P60484
P60484
P25963
P62161
P62161
P27986
P27986
P27986
P22681
P22681
P81122
P81122
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
O15530
O15530
O15530
P29350
P67775
Q13017
P18031
P18031
Q9Y4H2
Q9Y4H2
Q9Y4H2
Q9Y4H2
Q9Y4H2
Q9Y4H2
P42232
P06213-2
P06213-2
P06213-2
P06213-2
P06213-2
P06213-2
P06213-2
Q99704
Q99704
Q00194
Q00194
P04274
P04274
P04274
P04274
P04274
Q92569
P06213
P06213
P06213
P06213
P06213
P06213
P06213
P06213
P06213
P06213
Q60770
P16573
P35232
O35718
P62158
P0DP29
P0DP29
P13688
P13688
Q9P219
Q13480-2
Q13480-2
Q13480-2
Q13480-2
Q13480-2
Q13480-2
Q13480-2
Q13480-2
P29350-3
P15941
P15941
P12931
P27986
P09619
P09619
P09619
P09619
P09619
P09619
P09619
P09619
P09619
P09619
P09619
P09619
P09619
P09619
P16234
P16234
P16234
P16234
Q05397
Q05397
P42684
P42684
P42684
P42684
P42684
P42684
P42684
P42684
Q13769
P06241
Q07912
P19174
P15311
P15311
Q06124-2
Q16828
Q16828
P41212
P41212
Q9NRF2
P00519-2
P00519-2
Q06124
Q06124
Q06124
Q06124
P20936
ENSP00000352232
Q16615
Q16615
P29350-3
P15941
O14939
P29353-2
P29353-2
P29353-2
P35222
P35222
P14618
P62161
P62161
O95477
Q9UBN7
Q13547
Q05397
Q05397
P00533
P00533
P00533
P00533
P00533
P00533
P00533
Q14457
Q14457
Q14457
Q13501
P24844
P24844
Q86WV6
P19174
P19174
P19174
Q9UKV8
P15311
P15311
Q3V6T2
Q3V6T2
P21146
P21146
P21146
Q12809
P04083
O60331
P29353-3
P29353-3
P29353-3
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
P09215
P09215
O15492
O15492
O15455
O70161
P10686
P10686
P51692
P51692
P51692
P51692
Q92529-2
Q92529-2
Q92529-2
Q92529-2
Q92529-2
Q92529-2
P67775
Q91YM2
Q9UK17
P18031
Q38SD2
P78527
Q8IVM0
Q8IVM0
Q8IVM0
P42566
P62993
P09211
P09211
P09211
Q13315
Q9P0J1
P48050
P11171-4
P07948
P52735
P52735
P52735
Q8NFJ5
Q8NFJ5
Q8NFJ5
Q8NFJ5
P42567
Q63768
P08487
P08487
P08487
P08487
P12004
O00767
O00767
O00767
P61926
Q96TA1
Q91V17
Q8TDY4
Q14164
Q14164
Q92952
P50904
P37231-2
P62158
P61925
P11171
P20936
P19105
O14964
Q5VXN8
Q16615
P0DP29
P0DP29
P13688
O75121
O00291
P40818
P40818
Q01813
Q9P219
P48431
Q03181
Q13480-2
Q13480-2
Q13480-2
Q13480-2
Q13480-2
Q13480-2
Q13480-2
Q13480-2
Q9GZX1
Q9GZX1
Q9GZX1
Q9GZX1
Q9GZX1
Q9GZX1
Q6PIJ9
Q6PIJ9
Q6PIJ9
P63096
P63096
P63096
Q7Z699
P57780
P57780
Q15645
Q15645
P15941
Q14247
Q15139
Q15139
Q15139
P35222
P35222
P35222
O00429
O00429
O00429
P08581
P08581
P04040
P04040
P31016
P46527
P46527
P46527
Q8CBW3
Q8CBW3
P37840
P37840
P10636-8
P03372
P03372
P25490
P42768
P05412
Q9Y6W5
P25963
P11387
Q00987
Q00987
Q00987
P01106
P01106
Q99638
Q06609
Q06609
Q92769
P27986
O75496
Q14980
P46937
P53350
P53350
P53350
O15350
P09619
P09619
P09619
P42684
P29474
P63244
P00533
P00533
P00533
Q9Y6Q9
Q9BZL6
Q9BZL6
Q14653
P19174
P19174
P52566
P52566
P22681
Q06187
Q6NUN9
O60260
P17844
P39689
Q9UJM3
Q9UJM3
Q13043
O15151
O15151
P06400
P55211
P55211
P50402
Q14847
P04083
P17676
Q13535
Q13535
Q15746
Q15746
Q15746
Q15746
Q15746
Q15746
Q15746
Q15746
Q15746
Q16531
Q16531
Q62120
Q62120
Q8IZP0
P01112
Q03135
P97318
P97318
P09215
P29350
P29350
O15162
O15162
Q62417-5
Q62417-5
Q62417-5
P56945
Q9H7P9
Q13905
Q9H2X6
P00519-2
P49023
P49023
P08559
P43403
P47811
P47811
P10085
P10085
Q92993
Q92993
Q13188
P00519
P00519
P00519
Q13671
O00213
Q95107
Q95107
Q9UL17
Q9UL17
Q9UL17
P55317
P55317
P11274
P11274
P11274
P36895
P36895
P36895
P36895
Q04750
Q6P1J9
Q6P1J9
Q6P1J9
P24270
P24270
Q9C0H9-5
Q9C0H9-5
Q13573
Q13573
Q13573
Q6ZUJ8
Q6ZUJ8
Q6ZUJ8
Q6ZUJ8
Q6ZUJ8
Q04929
Q9H3D4
Q9H3D4
Q9H3D4
P46108
P46108
P46108
Q14498
Q14498
P16333
Q921Q7
Q64010
P43351
Q9Y6N7
Q9Y6N7
Q9Y6N7
P46109
P23727
P17275
P17275
P17275
NP_001005762
O14818
O14818
P17931
P17931
P17931
P35235
P35235
P35235
P35235
P35235
Q03468
Q9EPK5
P15391
O15269
Q9Y6H1
O94916
P07203
P07203
Q15118
O95433
Q8BH43
Q92731
D3ZGB1
P15498
P15498
P56962
P37231
P37231
Q00535
O43586
Q9NRQ2
Q9NRQ2
Q9R1Z8
O43602
Q70E73
Q70E73
Q70E73
Q9BX66
Q9BX66
Q9BX66
Q05086
O94875-2
O94875-2
O94875-2
O94875-2
O94875-2
Q7Z434
Q7Z434
Q7Z434
Q9UPY6
Q9UPY6
Q9UPY6
Q9UPY6
Q9UPN9
Q9UPN9
Q9UPN9
O60234
P12532
Q5MYA0
Q5MYA0
Q5MYA0
Q5MYA0
Q5MYA0
Q5MYA0
Q5MYA0
Q5MYA0
Q5MYA0
Q6NZY6
Q8TDY6
Q5T2R7
Q62245
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q9BX66-4
Q9BX66-4
Q9BX66-4
P14151
Q8IZP0-4
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q8N8Z6
Q96PH1
Q96PH1
Q14192
Q14192
Q14192
Q14192
Q9ULZ3
Q96BN8
P15941
P29353-2
P35222
P35222
P12931
P12931
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P10275
P06241
P00523
P06239
O60331
P05480
O43353
P13639
P13639
P49654
P07947
P08575
P08631
P07948
P09769
Q96DW4
Q16615
P05480-1
P15941
Q14247
Q14247
Q14247
Q14247
Q14247
P35222
P40763
P52757
P37840
P10636-8
P42768
P06127
P06127
Q14194
P42684
P42684
P42684
P42684
P42684
P42684
P42684
P06241
P06241
P06241
P06241
P06241
P06241
P06241
P04626
Q02248
O60716
Q16555
Q62418
Q62418
P16885
P16885
P16885
P12318
P12318
P12318
P22681
P22681
P22681
P11911
P10636
P35612
P84243
P11137
P17612
Q9R0Z9
Q9R0Z9
P49023-2
Q12879
Q12879
Q12879
Q12879
Q12879
Q12879
Q12879
Q03135
Q9NWQ8
Q13322
O75955
P51812
P51812
P51812
P51812
P51812
P51812
P51812
Q80YE4-2
Q80YE4-2
O43490
O43490
P22723
P22723
P30999
P30999
P30999
Q12913
Q12913
Q14289
O35346
P35637
P14923
P14923
P78352
Q9Y6K9
Q16539
O43294
Q14643
P05067
O43663
Q14524
Q14524
P00519
P00519
P00519
P00519
P00519
P00519
P00519
P00519
P00519
P54646
P11274
Q62952
P47942
Q16236
P20963
P20963
Q9WTK7
Q9WTK7
Q9WTK7
Q9WTK7
Q9WTK7
P16284
P16284
Q13291
Q13291
Q13291
Q96LC7
Q63155
Q63155
Q06124
Q06124
P97318-2
P97318-2
P97318-2
P97318-2
Q99490-2
Q99490-2
Q00535
Q08290
Q08290
ABR15760
ABR15760
Q96J02
P30419
O15117
O15117
O15117
O15117
O15117
O15117
O15117
O15117
O15117
Q01628
Q9QX11
O14559
P07766
P07766
Q86WV1
Q86WV1
Q86WV1
Q86WV1
Q86WV1
Q6X936
Q6X936
P11137-3
P11137-3
P37397
F1M0Z1
O75886
O75886
O75886
Q80W68
Q80W68
Q80W68
Q80W68
Q3UND0
Q8TDQ1
Q8TDQ1
Q8TDQ1
Q9R044
Q9R044
Q9R044
Q9R044
Q9R044
Q9R044
Q9R044
Q9R044
ABI33873
ABI33873
ABI33873
ABI33873
P35354
Q14254
P31994
Q9NPH5
O14522-1
O14522-1
Q9NQC3
Q15762
Q9NZA1
Q01097
A8K4G0
O60500
P42681
P11912
P40259
P40259
Q9BZW8
Q9BZW8
Q96J84
Q96J84
Q9UBN4
Q9UBN4
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q96PD2
Q9CQW9
Q9CQW9
O75051
O75051
Q9UIW2
Q9UIW2
P52209
P15530
Q15858
Q15858
O54865
Q495A1
Q9UIB0
Q9UIB0
Q9H4U5
P30419-2
Q6RBX8
P11137-2
Q9QZS7
Q9QZS7
P35613-2
P35613-2
A1Y2K0
A1Y2K0
A1Y2K0
A1Y2K0
P35611
Q14247
P68431
P68431
P04637
P04637
P04637
P04637
P04637
P04637
P12931
P12931
P12931
P10636-8
Q14676
P67870
Q04206
Q96RL1
Q06609
P30305
P30305
O43395
P30307
P06493
P18858
Q9BQG0
P53350
P53350
Q9NRM7
Q9NRM7
O15350
Q9NS23-2
Q9NS23-2
Q9NS23-2
P52292
P43405
Q02750
Q13263
Q6PD62
P11047
Q9NUU7
P22626
P84098
P84098
P67809
Q7Z2Z1
Q7Z2Z1
Q7Z2Z1
Q7Z2Z1
Q9NRL2
P54132
P54132
P54132
P54132
P68433
P68433
P68433
O00716
O14757
O14757
O14757
O14757
O14757
Q14669
Q9UKI8
Q9UKI8
P49761
P07814
Q53H47
Q06486
Q06486
Q06486
Q06486
P85299
O75461
O75461
Q12789
P39689
P39689
Q5T8P6
P49919
P16989
Q27J81
P30304
P30304
P30304
P30304
P30304
P30304
P46013
Q14186
Q9UJM3
Q9UJM3
Q9BXW9
Q9UKM9
Q12888
Q14966
Q99590
Q9UQ35
Q9UQ35
Q9UQ35
Q9UQ35
Q9UQ35
Q9P2D1
Q13439
Q9UEY8
Q9BW19
Q16181
P43243
P43243
P43243
P33992
Q96T58
Q5UIP0
Q96GD4
Q9NXE8
Q96PK6
Q96PK6
Q96PK6
Q13907
Q9H8G2
Q9Y520
O75151
Q16143
P52272
Q15648
Q16204
Q16204
Q9Y2T7
O95785
Q86WB0
P49790
P49790
O35618
Q9NWH9
Q9NWH9
O15294
Q8NG66
Q04837
P25205
O95707
P35612
Q8IY67-2
Q6UB98-2
Q9H8N7
P12956
Q13257
Q13257
Q13043
O75592
O75592
Q9BRD0
O60343
O60343
P36507
Q9GZR7
Q9BTD8
P39748
Q99848
P49792
Q9HC62
Q08AD1
Q9Y3Y2
Q5JSZ5
P02545
O15151
O15151
O95625
O95625
Q9UPP1
Q9H0H5
Q9UMR2
Q86UE8
Q86UE8
Q92974
Q9Y570
P84243
P27816
Q9UK53-2
Q00341
Q86WR7
Q14004
Q6T4R5
Q5JTH9
Q9HAW4
Q14738
P55039
O43660
P15822
Q53F19
Q9HB96
Q9HB96
Q96QD9
P05432
Q9BY77
P26373
P52294
Q8N4C8

P06400
P19838
Q9BXB4
Q96ST3
Q13470
Q32P44
Q9Y4F5
Q8WWI1
Q96E09
P33991
P51587
P08631
Q9Y294
Q9UQ84
Q6NWP9
Q9H040
Q9H040
Q9H040
P25799
P25799
P25799
P25799
Q58FA4
Q6S7F2
P35611
P35611
P68431
P68431
P53671
P02548
P02548
P08670
P60484
P60484
P60484
P60484
P60484
Q96IZ0
O14950
O14950
Q05397
P50552
P49816
P24844
P24844
Q16555
P04150
P04150
O14974
O14974
O14974
P53667
P35241
P15311
P26038
P20152
P14136
P14136
P14136
P17661
P17661
P17661
P17661
P17661
Q90623
Q90623
Q90623
O94811
O94811
O94811
P41181
P48436
O14649
O14649
P29966
Q9Y613
Q9Y613
Q9Y613
P07737
P19634
O14744
Q14160
Q14160
P26932
P26932
P26932
P26932
P26932
Q9Z207
Q9Z207
P61587
P61587
P61587
P61587
Q9DBR7
Q9DBR7
Q9NRY4
Q9NRY4
Q9NRY4
Q9NRY4
Q9NRY4
Q8N264
Q8N264
Q8N264
Q8N264
Q8N264
Q8N264
Q9Z340
Q64122
Q64122
Q9DAW9
Q9DAW9
P26041
Q5E9E2
Q5E9E2
O60237
O43293
O43293
Q6ZPF3
Q9UPT6
Q9UPT6
Q9UPT6
P19105
P19105
Q14CB8
Q96KS4
Q96KS4
Q96KS4
P12023-2
P35611
P35611
P35611
P35611
P35611
O70468
O70468
O70468
P29473
P08057
P08057
Q61337
Q61337
Q61337
P07101-4
P16949
P07101
O35433
O35433
O35433
O35433
O35433
O35433
O35433
Q92736
P07293
P07293
P21333
C6K2K4
P07101-3
P31000
P10636-8
P04775
P04775
P04775
P13569
P13569
P41208
Q6J4I0
Q6J4I0
P09651
Q12798
P04049
P48787
P48787
P50552
P50552
P14859
P11716
P07101-2
P35612
P35612
P97756
P50571
Q8VGC3
Q8VGC3
Q8VGC3
P00511
P00511
P50549
Q10728
Q10728
Q10728
Q10728
Q9Y233-2
P20942
Q99LM3
P07953
P06685
P20265
P35240
P62755
P62755
P62755
P02522
Q8IWU9
Q8IWU9
P55273
P41777
P41777
P41777
Q60670
HSBO22
HSBO22
O76074
P15336
P04972
P29966
Q9MZ06
F1RR02
F1RR02
F1RR02
F1RR02
P35565
P49768
P02253
P00515
P09211
Q64122
Q64122
P51177
P35439
P60881
P18666
P18666
P26285
P26285
P08033
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
O88831
P48675
P02542
P02542
P02542
P07516
Q01955
Q01955
Q9Z1P2
P07150
P19632
Q99MM3
Q99MM3
Q9EPF2
Q9EPF2
Q9EPF2
P34058
P25961
P25961
P25961
P10860
P63259
NP_001102797
P27791
P62962
P62962
P62962
P62962
P05545
P36953
Q91XW0
Q91XW0
O96001
O96001
Q66H98
Q66H98
P42930
P42930
P42930
P42930
Q68FR6
Q7M0E3
Q61411
C0JPT7
C0JPT7
C0JPT7
C0JPT7
C0JPT7
C0JPT7
P13224
A0A0G2JUA5
A0A0G2JUA5
A0A0G2JUA5
P02646
P02646
P02646
P02646
P85125
P85125
P85125
P85125
E9PTU4
Q99068
P63269
P63269
Q80ZA3
Q80ZA3
P36202
P36202
P06624
P17475
D3ZFU9
D3ZFU9
P34908
P34908
Q63081
Q63081
F1M8X9
P68510
P68136
P68136
D3ZVR9
B5DEN5
B5DEN5
B5DEN5
P17289
Q5EBC0
I6L9G5
D3ZAN3
Q9QX79
P0DN86
Q9BSF0
P19357
P07153
P07153
P21571
P31360
P31360
O88767
O88767
P05065
D3ZG43
Q9QXQ0
P13635
Q66H94
Q810D0
P07335
D3ZHA0
Q5XI07
Q62703
P60711
P35611
P35611
P13789
P13789
P13789
P13789
O46469
P29473
P08057
P08057
P08057
P08057
P08057
P08050
Q13131
P24844
P24844
P24844
P24844
P35612
P35612
HSBO22
HSBO22
P04972
P29966
P07355
P23727
P02253
P46193
P46193
P06213
P02699
P02699
P02699
P02699
P02699
P06836
P21399
P21399
P61765
P61765
P09693
P09693
P63073
P04272
P08033
Q63270
Q63028
Q63028
Q3THE2
P18841
P18841
O02755
O02755
P43249
P43249
Q05764
Q05764
P09038
P43481
P43481
Q3SZL0
Q3SZL0
P14732
P14732
Q01059
P14568
P35611
P35611
P14598
P98082
Q96A00
P53671
Q96C90
P08670
P08670
P48787
P48787
P48787
Q9BZL4
P24844
P24844
Q16555
O14974
O14974
P35241
P15311
P26038
Q90623
O95644
Q10728
P56817
Q15417
P68104
P47942
P19634
P28740-1
Q9DBR7
Q9DAW9
Q9DAW9
Q90635
Q64287
Q64287
Q92673
P60879
Q99962
P05067-4
P10916
Q8N850
Q8N850
O88942
P51911
P51911
P51911
P51911
P51911
Q15306
Q15306
O75116
O75116
O75116
O75116
Q9UJB6
Q9UJB6
P13789
P13789
P13789
P13789
O70468
P19429
P19429
Q9UBS0
P05787
P05787
Q15139
Q15139
P15381
P15381
P15381
P08057
P08057
P08057
P08057
P28329-3
P28329-3
P78536
Q96A00
P40763
Q9WVE0
P08581
P08050
P08050
P08050
P08050
P08050
P08050
P05556
P05556
Q02294
Q02294
Q02294
Q02294
Q02294
P10636-8
P10636-8
P10636-8
P10636-8
Q16625
Q16625
P16220
P16220
P43629
P00533
O14920
Q9BZL6
Q9BZL6
Q9BZL6
O60716
Q02156
Q02156
Q02156
Q02156
Q92934
Q92934
Q92934
P05783
P35569
Q96GD4
P27732
P56513
P56513
P56513
Q8NER1
Q8NER1
O14649
P15336
P20339
P11362
P17302
P42866
P98170
O14493
O14493
Q9BR76
Q62968
Q9H9S0
Q9H9S0
Q9H9S0
Q9H9S0
Q9H9S0
Q9HAW7
O75689
O75689
Q86XR7
O54701
O54701
O54701
Q14145
Q14145
P04899
P04899
P04899
P39447
P46940
P05091
P05091
P05091
P18708
P18708
P23975
P62491
E2RAI2
Q6PW52
Q16612
Q95168
Q8NE86
Q5FWH6
Q5FWH6
Q6GMY0
Q6GMY0
P11679
P11679
P11679
O94925-3
P48751
P18507
Q5JXC2
P13789
P14598
P14598
P05787
P42224
P04637
P04637
P04637
P78536
Q15717
Q15717
P40763
P49841
P49841
P49841
P38936
P38936
P38936
P31645
O43526-4
O43526-4
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
Q00613
Q00613
P35638
P35638
O75582
O75582
O75582
P03372
P03372
P03372
Q15672
Q02078
Q02078
Q02078
Q02078
Q02078
Q02078
Q02078
Q02078
Q02078
Q02078
Q02078
P30305
P30305
O95863
P30307
O75676
O75676
O75676
O75676
O75676
P10275
P07954
O00418
O70405
O70405
O43524
O43524
O43524
O43524
O43524
P00533
P00533
P00533
P41235
Q9BUB5-2
Q9BUB5-2
P15387
P15387
P36956-3
P36956-3
Q9H3M7
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q8IW41
Q02156
Q01844
P04150
P04150
P04150
P42225
Q6P9Z1
Q0VBL6-2
Q0VBL6-2
Q0VBL6-2
Q0VBL6-2
Q0VBL6-2
Q0VBL6-2
Q0VBL6-2
Q0VBL6-2
Q0VBL6-2
Q0VBL6-2
P04792
P53667
Q969V6
Q969V6
Q9UKV8
P49137
P49137
P49137
P49137
Q8K4J6
Q8K4J6
Q8K4J6
P17844
P17844
Q07817
P35236
P35236
P68433
O15151
P27816
P27816
P06400
P06400
P06400
P06400
P06400
Q86UR1
Q86UR1
P13668
O95644
Q63943
Q63943
Q71RJ2
P20265
P20265
P20265
P48436
P55273
Q9WV60
Q15746
Q15746
P36956
P36956
P15336
P15336
P15336
Q9BUB5
Q9BUB5
P10415
P10415
P41212
P41212
P19419
P19419
O88498
Q66H76
O70162
O70162
O70162
Q08775-5
Q9UIG0
Q14790
Q04211
Q15046
Q15046
P16951
P16951
P98083
P11362
Q14934
Q14934
P56817
P17302
P17302
P29353
P29353
Q92945
P49023
Q14721
Q14721
Q15910
P43403
P47811
P47811
Q16539
Q16539
P17181
Q92993
P23769
Q06413
Q06413
O43255
Q96I25
Q96I25
P22415
P52945
P52945
Q15750
Q15750
Q15750
Q15750
Q15750
Q15750
Q15750
P19525
P05198
P17275
Q9NRR4
Q9NRR4
Q9NRR4
Q9NRR4
Q9NRR4
P06876
Q99626
P30279
O43464
Q13155
P19634
P19634
P19634
P19634
NP_776683
Q99J83
Q61026
Q99958
Q60876
Q60876
Q60876
Q8WYK2
P78356
Q06986
Q06986
P21462
Q9UBK2
Q9UBK2
Q9UBK2
Q8VI67
Q8VI67
P05554
Q8C050
Q8C050
P70396
P70396
P21397
P49919-2
Q9UK80
Q9JHG6
Q9JHG6
Q9JHG6
Q9JHG6
Q9JHG6
Q9JHG6
Q9JHG6
Q9JHG6
Q9JHG6
Q9JHG6
Q9NQU5
Q06413-3
Q06413-3
Q06413-3
P42574
P06702
Q8NHW3
Q8NHW3
Q8K120
Q8K120
Q9BR76
P42566
O60381
P42677
O35426
O35426
Q92993-2
Q08874-8
E1BUH4
E1BUH4
Q9WTU3
Q62968
Q62968
Q15075
P13726
P13726
P23927
Q06330
Q9H1K0
P02511
Q9JLS3-2
O15198
O43257
Q13309
P18850
Q9H211
Q9H211
Q9H211
Q9H211
Q9H211
P28324
P28324
Q12948
Q12948
Q9H3D4-2
Q9H3D4-2
Q9H3D4-2
Q9H3D4-2
O00257
O43684
P23975
Q07666
Q07666
ENSP00000267569
P49138
Q6RSS1
Q6RSS1
Q8VCD5
Q9UDL5
B5B2W9
B5B2W9
P78543
P51448
O54992
P56178
P56178
Q16644
Q16644
Q16644
Q60707
Q60707
Q60707
Q9C026-5
Q9C026-5
Q14765
P13473
P13473
Q8TE85
Q96L92
P61371
Q91ZE9
Q91ZE9
Q91ZE9
P14598
P14598
P05787
P62753
P29473
P29473
P68431
P35568
P23396
O14939
P35222
P49840
P49841
O00429
Q09472
P14618
P14618
P14618
Q61337
Q61337
P38936
P38936
P08050
P08050
P46527
P46527
P46527
P46527
Q9BXL7
Q9BXL7
Q9BXL7
P08670
P15337
P21333
P10636-8
P10636-8
Q00613
Q00613
Q13153
P26432
Q9UNN5
P03372
P03372
Q62627
P35226
P05455
P16220
Q00987
Q00987
Q00987
P54274
P54274
P31749
P31749
P38398
P38398
P22736
Q15672
Q15672
Q15672
P56270
O75376
P09651
P30291
P68400
P46937
P12755
O43521
P10275
P10275
P10275
P10275
Q96CG3
O15360
P04049
Q05397
Q05397
P24941
P10276
P13631
Q9WVH4
Q13131
Q13131
P29474
P29474
P29474
O70405
O60825
O60825
O43524
O43524
P00533
Q14457
Q14457
Q86TI0
Q86TI0
Q86TI0
Q86TI0
Q16875
P46414
P15056
P15056
Q12778
Q12778
Q12778
Q12778
Q12778
P49816
P49816
P49816
P49816
P45481
Q99623
Q99623
O70343
Q02248
P19174
Q06187
Q06187
P51617
P04150
Q92934
P04792
P63104
Q07352
Q07352
Q07352
P49815
P49815
P49815
P15311
Q3V6T2
P29351
P67809
O14757
Q06486
P39689
P39689
Q96GD4
Q13043
Q13043
Q13043
O60343
O60343
O60343
O60343
O60343
O60343
O60343
O60343
P02545
P02545
O15151
P26373
P0DMV8
P55211
P31323
Q8VGC3
P07550
Q13370
Q62600
P29994
P54253
P54253
P35240
P35240
P35240
P35240
P32067
P17542
P54645
Q00961
Q96P20
Q9WV60
P18265
Q13185
Q13185
P17679
Q8WX93
Q13950
Q13950
Q13950
Q13950
P08047
P08047
P08047
Q92793
P63000
P26431
Q969H0
O60331
Q9UQC2
Q16584
Q16584

Q6U7Q0
Q6U7Q0
Q6U7Q0
Q6U7Q0
P23804
G3V7R4
P35465
P17302
Q92945
Q13322
P51812
O35927
P05106
P52789
O14746
O14746
P08727
Q8TDN4
Q8TDN4
Q15910
Q7YSG7
Q15633
Q6R327
P19338
P19338
P18031
P48678
P62136
Q09666
P48679
P48679
P98170
P06748
Q9Y2V2
P48432
O14745
P54578
P23769
Q13188
Q13188
P26358
O60285
Q9H4A3
Q9H9Q4
P55072
P55072
P55072
O35099
Q8WYL5
Q96QB1
Q96QB1
Q96QB1
Q99683
P29317
Q9UN36
Q9UN36
Q9Y2I7
Q9Y2I7
P45985
P42858
P42858
P37089
Q15118
O43464
P19634
P19634
P19634
Q13309
Q9Y261
P42345
P42345
P42345
P20749
Q92547
P84022
B2RWS6
B2RWS6
O08537
Q7L5N1
Q04912
Q92879
Q99490-2
Q99490-2
Q63744
Q9H6Z4
Q05195
P78371
Q53EL6
Q53EL6
Q9UBP6
Q8BGD9
Q64092
P19484
Q96B36
Q9BRS8
Q9BPZ7
P55316
O15111
P33778
Q06806
P35232
P98177
P98177
P98177
P98177
O96028
Q5XUX0
Q96J02
Q99418
O15519
O95999
O95999
Q16778
P06899
P06899
Q5QNW6
Q5QNW6
Q9NR28
Q8N6T7
P60335
G1N806
G1N806
Q9Y3M2
Q14315
Q14315
Q96F86
Q7Z6J0
Q7Z6J0
Q7Z6J0
Q9R210
Q12906
Q96S44
Q9Y5S9
P26285
P26285
Q9Z1T6-1
Q9Z1T6-1
Q3MKQ2
Q86V81
Q86V81
P29375
P29375
P29375
P29375
P29375
P62509
P22829
E9PST5
E9PST5
P97303
Q9Z200
Q9Z120
O75030
D3ZBQ1
D3ZBQ1
P49918
P49918
Q9BVI0
Q9BVI0
P49760
P49760
Q9BRQ0
O08967
O08967
Q60987
Q9WVH3
Q9WVH3
Q9Y283
Q9Y283
Q9Y283
Q92794
Q9UKV3
Q9Y3C5
Q15027
P15331
Q13107
P63138
Q8BG60
P53365
Q8K382
Q8K382
Q9NPC1
Q9NPC1
Q9Z0X4
Q9Z0X4
Q9Z0X4
P41279
Q16763
P60905
P29401
P29401
P15806-2
Q9BWT1
Q15942
Q9H4X1-2
Q8IYJ3
P55937
P55937
Q86VP3
P21453
O08528
Q9NWV8
Q9Z2B5
Q8NCD3
Q95YJ1
P78362
Q01098
P15976
Q99502
Q9BZQ8
P67778
Q12809_VAR_014388
Q96HP0
Q80U87
Q7Z589
Q921I6
Q15121
Q8C6L5
P53804
P61016
P09601
Q13009
Q7Z5H3
Q9UIK4
Q13045
Q60949
Q60949
Q60949
Q60949
Q60949
Q60949
Q60949
O00548
Q14678
Q2PPJ7
Q2PPJ7
Q2PPJ7
P53396
P53396
P53396
A0A2Z4LIS9
P35558
P84103
P84103
P84103
P84103
P84103
O14686-3
O08785
P41002
P41002
Q5TA89
Q5TA89
Q5UE93
Q69ZI1
P61247
P61247
P61247
Q96KG9
Q9CZU6
P62424
P45880
Q06203
Q9UGI0
Q9UGI0
P19544-7
Q96BF3
Q14CB8
Q96ST2
Q96ST2
Q9UPY5
Q96GX5
Q6PIY7
Q6PIY7
Q9P0N9
P53602
Q9Y4P1
Q71DI3
Q71DI3
P62908
Q6NUR9
Q9Y2J6
Q9Y534
P97677
Q9JID1
P86411
P62909
Q9R0I6
Q99497
P78563
P18911-2
P41241
O75140
P55265
P99999
P36776
P36776
P15559
P15559
Q64315
Q64315
Q9P2H5
P35227
Q8N9L9
Q9P0V3
Q86VY4
Q8WTX7
P14598
P14598
P14598
P14598
P14598
P14598
P14598
P14598
P14598
P14598
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96FA3
P51617
P51617
P51617
Q9NWZ3
Q9NWZ3
Q9NWZ3
Q9NWZ3
Q9NWZ3
Q9NWZ3
Q9NWZ3
Q9NWZ3
Q9NWZ3
Q9NWZ3
Q9NWZ3
Q9NWZ3
P14598
P14598
P14598
P14598
P14598
P14598
P14598
P14598
Q9UBS0
P05107
P05107
P98082
P15381
P15381
P15381
P15381
Q8K585
Q8K585
P68431
P28329-3
P28329-3
P28329-3
P28329-3
P28329-3
P35568
P35568
P21730
P49840
P30273
P49841
Q9WVE0
Q9WVE0
Q02294
Q02294
Q02294
Q02294
Q02294
P16949
P16949
Q62812
Q9BXL7
Q9BXL7
Q9BXL7
Q01970
Q96PH1-4
Q96PH1-4
P10636-8
P10636-8
P10636-8
P10636-8
Q16625
P11388
P31749
P31749
P35579
P43629
O15350
Q13131
Q06187
Q5F3W0
Q8CIS0
Q8CIS0
Q8CIS0
P35569
P31424
P27732
Q7Z2W7
Q7Z2W7
P22449
Q9UH77
P81122
P81122
P04083
P06685
P06685
P23693
P23693
Q9WV60
Q8NER1
P15336
P15336
P15336
P15336
P15336
Q9WTU6
P29353
P29353
P29353
P07355
P42866
P35637
P20700
P20700
P29317
Q96D31
Q96D31
Q06124
Q06124
Q06124
Q06124
Q2NL51
P62491
Q07869
Q07869
P60881
Q9H1D0
Q9H1D0
O15519-2
Q03721
Q03721
Q03721
Q03721
O15519
P28799
P05771-2
Q5ZID9
Q62921
Q62921
Q62921
Q62921
Q62921
Q62921
Q9R210
Q9R210
Q9R210
Q9R210
P35548
P35548
P48736
Q9P2D0
Q9P2D0
P11171-4
P14679
P14679
Q12906
P11167
P11166
Q9UE50
Q9UE50
P00564
Q5T7P8
Q5T7P8
Q5T7P8
Q9UBU3
O95832
Q6ZN17
P14598
P14598
Q00613
P15056
P15056
Q14653
Q9UKV8
P35240
Q9WV60
Q7Z589
Q7Z589
O15119
Q96ST2
Q96ST2
P70671
P70434
P70434
P78563
P55265
P99999
O35303
Q8K585
Q8K585
Q8K585
P12928-2
P13668
P13668
Q10728
P00523
P00523
P00523
P21818
P70531
G3V7R4
P13084
P13084
P13084
P13084
P24898
P24898
P24898
P08592
P33568
P33568
P33568
P69897
O35147
P10361
P35439
P62909
P53563
Q9JHY7
P48675
P48675
P48675
Q63802
P30427
O35923
Q62736
Q62736
Q62736
Q62736
Q62736
Q62736
Q9JHX4
P30277
P51952
P19139
P19139
P19139
P19139
B1WC58
P28023
P39052
P97691
Q62839
Q810T5
Q810T5
O08984
O08984
G3V8T1
G3V8T1
G3V8T1
Q78PB6
Q78PB6
Q78PB6
Q63503
O35987
Q5I6B8
Q5U2N3
Q6NYB7
P05714
Q63528
Q9Z2P4
P85108
Q3KRE8
Q4QRB4
Q6P9T8
Q07141
P63281
Q7TPK1
Q8CF97
Q9JK11
Q792T7
Q00959
O35303
Q01815
Q9JIR4
P15304
P15304
P15304
P15304
P19490
P47709
P19493
P15337
B0LPN4
B0LPN4
P17599
P10636-8
P10636-8
P04775
P04775
P04775
P04775
P04775
O15392
Q13563
P04177
P18266
P97756
P97756
O00168
Q5EG47
P13668
P13668
P11497
P11497
O08589
Q10728
Q9Y233-2
P20942
P04176
Q71RJ2
Q7TQN4
P06685
P22002
P42260
P42260
P54645
P21818
P21818
Q12802
P18265
P24155
P34080
P34080
P34080
P34080
P23441
Q9QYW1
Q9QYW1
Q9QYW1
Q9QYW1
P09951
P46152
P70531
P70531
P35465
P21272
P21272
Q9JK25
P23727
Q14494
P12839
P12839
P12839
P12839
P12839
P12839
P19103
O35147
O35147
O35147
P60881
Q9JHZ9
Q6LED0
P22829
P22829
P60905
P61016
P51639
P01237
O88831
Q63085
P28023
P41035
P19632
P26433
P26433
Q9JM04
NP_062220
Q9JLU4
P19112
P19112
Q5RJK5
Q9UI08
Q925N3
P11101
P11101
P19335
P19335
P19335
P31421
P31421
Q9GZQ8
Q9GZQ8
Q63648
P04800
P19527
P19527
P19527
P19527
P19527
P12336
P12336
P12336
P12336
O70441
P31422
P52191
P15389
P15389
Q14573
Q14573
Q14573
P54829-3
P54829-3
Q05941
P97541
P14100
P14100
Q99JE6
P10037
P10037
P00518
P14646
Q62747
Q63537
P09610
P15385
P35234
O35867
P41740
Q62668
P01161
O35303
P15337
P15337
P29476
P29476
P17599
O08679
O08679
O08679
O08679
P17074
Q2LC84
Q2LC84
Q9R1U5
P24844
P05783
P97756
P97756
P09951
P49757
P51639
O70441
Q63537
ENSRNOP00000048410
ENSRNOP00000048410
Q3MUI2
Q63450
F1LNZ2
F1LNZ2
Q2LC84-2
Q3MUI1
A1L1I3
O35303
O35433
P23693
P23693
Q9EQG6
Q9WTQ1
Q9Z1Y3
Q9Z1Y3
Q9Z1Y3
P97680
B5DFN2
O35303
P13834
P48787
P48787
P41235
Q16875
P46414
P46414
P46414
P55011
P35569
O15151
P11497
P11497
P11497
Q62600
Q62600
P23693
P54645
P54645
P54645
Q3U182
P80386
P80386
P80386
P80386
P80386
P80386
Q8CI51
Q5XIT8
O08623
Q9JJH5
O70468
O70468
O70468
O70468
O70468
O70468
O70468
O70468
P35222
Q61337
P37840
P09803
P09803
P09803
Q03267
Q03267
Q03267
Q03267
Q61985
Q61699
Q60864
Q923E4
O88572
Q02067
P35922
P24610
P24610
Q9UBN7
Q9WTL8
P02340
P01103
P01103
Q8CFN5
Q60598
P21272
P53564
P53564
P53564
P06876
P06876
Q8C3Q9
P12813
P70444
Q9Z1E3
P38532
O08586
P00860
Q91ZP3
Q91ZP3
Q9CXW3
P06800
P06800
P06800
P06800
P06800
P06800
P06800
P06800
P63058
P63058
P63058
P46099
Q9WTL8-4
P49443
P49443
Q61686
Q61686
Q61686
Q61686
Q61686
P70288
P17433
O70480
P97445
P97445
O70468
O70468
O70468
O70468
O70468
O70468
O70468
O70468
P70181
Q61143
Q61337
Q61337
Q61337
P11799
P11799
P16949
P23818
P23818
Q99K10
O08553
P21333
Q66JT0
P09917
E9Q401
P16220
P16220
Q04206
Q923E4
P27699
Q6J4I0
Q04207
P04049
P04049
P04049
P11416
P48787
P48787
Q05469
Q05469
Q05469
Q05469
O70343
Q9R1U5
P05132
P05132
P05132
P14602
P14602
G0YZM8
G0YZM8
G0YZM8
P20152
P20152
P20152
P20152
P20152
P20152
P50571
P61586
Q0PCR6
Q0PCR6
Q6R891
Q5EG47
O54851
O54851
O54851
O54851
P11881
P11881
Q6VV64
O95644
O95644
Q63943
Q63943
Q00756
Q8CGN5
Q8CGN5
P30306
P30306
Q7TNL5
Q7TNL5
Q7TNL5
P26955
Q8CFN5
P10412
Q96P20
P54830
Q9WV60
Q60670
Q99996
P09066
Q9HC16
O14558
P49698
Q9EQY0
P46152
Q62132-2
Q9JK25
P56524
P56524
P26645
P26645
P26645
P26645
O35099
O35099
Q8R4B8
O88809
Q9WTK7
Q61743
Q9Z0V2
Q9Z0V2
Q60829
Q9ERT9
Q6ZPF3
Q6ZPF3
Q6ZPF3
P60879
Q99N57
P16573
O54918
Q01097
Q01097
P70441
Q9JIM1
Q9JIM1
Q9JIM1
Q9JIM1
Q9JIM1
Q8CFH6
P32927
P56741
P56741
P01101
P00536
P00536
P00536
P00536
P00536
P00536
P54310
P54310
P54310
Q8VBU8
O88445
P27671
P27671
P27671
Q9DBL9
Q5EBG6
Q8VHX6
P49582
Q9JKS4
Q9JKS4
P97769
P19783
Q8CGA3
Q04899
Q04899
Q04899
Q8C6M1
P15105
P15105
Q6P4S6
Q6P4S6
Q6P4S6
Q8BVZ1
Q99MR9
Q5NCY0
Q7TNL7
ENSMUSP00000074684
P43884
P43884
P43884
Q9QXZ9
Q9QXZ9
Q9QXZ9
Q3USB7
Q3USB7
P51180
P70218
Q9EPR4
Q9EPR4
O54724
O54724
O54724
O54724
O08852
O88602
Q62261
Q07279
Q91V27
P61014
P61014
Q9DCB4
P60192
Q61792
Q15111
Q812A2
P30051
Q8BXA7
Q8BXA7
P08553
P17290
Q9Z266
Q9CRB9
Q06507
P46662
P46662
P70188
Q8BW96-2
Q3UYC0
Q8C3Q5
Q8C3Q5
Q8C3Q5
Q8C3Q5
Q8C3Q5
Q8C3Q5
Q8C3Q5
P26048
O35085
Q8C4Q6
O70468
O70468
O70468
O70468
O70468
O70468
O70468
O70468
O70468
O70468
O70468
O70468
Q01815
Q01815
Q3UMR5
Q00566
P13346
P13346
Q62812
Q9Y4D2
Q9Y4D2
P18052
P18052
P23818
P23818
P15337
P15337
Q9WV18
E9Q401
Q62048
P08551
P27699
P70166
Q9WVH4
P54227
P20152
P50571
P50571
Q00756

P20942
P20942
P20942
P20942
P20942
P22723
P22723
P22723
Q01959
Q01959
Q01959
Q01959
Q01959
P12979
Q99104
P38532
P34152
P61014
P61014
Q8K1M6
P11798
P11798
P11798
Q9JJV9
Q99PW8
Q9Z2Y3
Q8VHH7
O88935-1
P11507
P09055
P09055
Q9QWW1
Q64704-2
Q00560
Q8BHY3
O70468
E9Q401
E9Q401
Q9Z2V6
P61014
O70468
Q04760
E9Q401
E9Q401
Q9Z2V6
P61014
P61014
Q9CPU0
Q64704
O70468
P48787
P48787
Q8C2B3
Q8C2B3
Q8C2B3
Q62101
Q62101
Q62101
Q62101
P23693
P23693
Q8WUI4
Q8WUI4
Q8WUI4
Q80SW1
Q921Q7
Q9Z2V6
Q9Z2V6
Q704Y3
Q01279
Q01279
Q8BZ03
P70218
O70468
O70468
P48787
P48787
P48787
P48787
P42227
Q8CBD1
Q8CBD1
Q62101
Q62101
Q969H0
Q969H0
P09215
P22723
P26645
P26645
P26645
Q704Y3
Q704Y3
P16054
P39429
P47196
P47196
P46460
P09055
P09055
Q9WTQ1
Q9WTQ1
P11679
P11679
P19429
P19429
P19429
P19429
P10275
P10275
Q15208
O43524
O43524
O43524
O43524
O43524
Q14457
Q12778
Q12778
Q12778
Q12778
Q14653
Q14653
P04150
P04150
P04150
P04150
Q96GD4
Q13043
Q13043
Q13043
G3V7R4
Q9JI11
Q06830
Q06830
Q06830
P00519
P16104
Q7L9L4
Q7L9L4
P33778
P33778
Q99879
Q93079
P58876
P23527
Q6DN03
P62807
Q16778
O60814
Q99877
P06899
Q6DRA6
Q5QNW6
P17301
Q61233
Q99880
Q8N257
P57053
P46938
Q64373
Q9GZQ8
Q9CQV6
NP_001100737
Q8IZJ1
F1M2K4
P19429
P12957
P12957
P19490
P04049
P04049
Q01986
Q16659
Q29122
P31152
O75914-2
O75914-2
O75914-2
P19429
O14950
O14950
P24844
P24844
Q06413
P50411
P19105
P19105
P15407
P15407
P15407
P15381
P15381
P15381
P15381
P68431
P35568
P10588
P70181
Q9WVE0
Q8IV61
Q9BXL7
Q9BXL7
Q9BXL7
P10636-8
P10636-8
P10636-8
P10636-8
Q9UHD2
Q92934
Q92934
O14974
P35241
Q5F3W0
P15311
Q9Z2A0
Q9Z2A0
Q04759
P35236
P35236
Q8CIS0
Q8CIS0
Q8CIS0
Q3V6T2
O95267
P29351
P06332
P01116-2
P26038
P35569
O43516
Q9Y4G8
Q13191
Q5JVS0
Q5JVS0
Q9UEW8
Q9UEW8
Q9UEW8
Q9UEW8
P32942
P31424
Q15052
Q15052
O15530
O15530
O15530
O15530
P43403
P43403
P43403
P43403
O94992
P16150
Q969F2
Q9UBS0
Q14247
Q9WVE0
Q9WVE0
Q09472
P19490
P08670
P08670
P08670
P10636-8
P10636-8
P10636-8
P10636-8
Q8TEW0
P08151
P08151
P51617
Q13118
Q13118
Q92934
Q92934
Q92934
P15311
P27448
P08047
Q969H0
Q969H0
P26040
Q7KZI7
Q4VCS5
Q4VCS5
Q4VCS5
Q15910
Q15910
Q15910
Q6STE5
P50613
Q62406
P78545
Q9NPB6
Q9H8V3
Q16236
P49757
P49757
P49757
P17480
Q13464
Q13464
Q13464
Q13464
Q13464
Q14184
O15498
Q9UBS0
P98082
P15381
P15381
P15381
P15381
Q8K585
Q8K585
P28329-3
P28329-3
P28329-3
P28329-3
P28329-3
P04637
P21730
P49840
P49841
Q9WVE0
P08050
O88935
O88935
Q01970
P19493
P10636-8
P10636-8
P10636-8
P10636-8
P06127
P06127
P07900
P07900
P07900
P43629
P10276
P31424
P22449
Q9H3Z4
Q9H3Z4
P17302
P25098
P42866
P50281
Q13507
Q03721
Q03721
Q03721
Q03721
P48168
Q9JHZ9
P28667
P28667
Q14155
Q14155
Q7Z2E3
Q91XS8
P08138
Q61553
P48058
O95544
O95544
Q9UBS0
Q04207
Q64337
P45481
Q8BYJ6
Q02248
P35569
Q62101
Q62101
P26645
P26645
P26645
Q9WTK7
Q704Y3
Q9Z340
P39429
Q8VHC5
Q02956
O88792
Q9QZS3
O88351
O88351
O89090
O89090
O89090
O89090
Q5SXA9
Q5SXA9
Q9QUR7
Q8VHJ5
Q05512
Q60641
Q9WUA6
Q03141
Q99JB2
P98078
P05107
P29353-2
P29353-2
P29353-2
P52757
P60484
P60484
P03372
P42768
P06127
P06127
P25963
Q13283
P27986
Q9UHD2
Q9UHD2
P48025
P48025
P48025
P19174
P19174
P16885
P16885
P16885
P16885
P16885
P42229
P22681
P22681
P22681
Q13094
Q13094
Q13094
P15311
Q04759
P06239
P06239
P14784
P14784
P14784
P14784
P14784
Q61097
Q13813
P30205
P29350
P29350
P23743
P67775
Q14289
Q14289
Q9UN19
P27870
P27870
P27870
P12235
P43403
P43403
P43403
P43403
P43403
P43403
P43403
P43403
P43403
Q8N1K5
Q8N1K5
Q8N1K5
Q8N1K5
Q8N1K5
Q8N1K5
Q16539
O09039
Q08881
Q06830
P23727
P23727
P15498
P15498
P15498
Q9BZS1
P24161
P24161
P24161
P24161
P24161
P24161
Q9NP31
Q9NP31
Q9NP31
Q9NP31
Q9H204
P20963
Q9BWW4
Q9BWW4
P20138
P20138
Q8IVM0
Q8IVM0
Q8IVM0
Q9WTK7
Q9WTK7
Q9WTK7
P16284
P52630
P31041
P31041
Q13291
Q13444
Q13444
Q811D0
P24666
P24666
P16086
Q96LC7
Q96LC7
Q96LC7
O14543
O14543
P08575
P52735
P52735
P52735
P10747
Q9UQQ2
Q91GT2
Q96DW4
P13688
P13688
Q495A1
Q96C78
Q96C78
Q8IWV1
Q8IWV1
Q8IWV1
Q8IWV1
Q9H400
Q7Z6A9
Q7Z6A9
Q7Z6A9
Q7Z6A9
P05107
P05107
Q15139
Q15139
P49840
P49841
Q9WVE0
Q16625
Q16625
Q9BZL6
Q9BZL6
Q9BZL6
P31424
Q9WV60
P15336
Q06124
Q06124
Q06124
Q06124
P24723
P24723
Q2NL51
P09211
P09211
Q05655
Q13153
P31749
P31749
O14920
P05132
P10636
P10636
P10636
P10636
P10636
P10636
P10636
P10636
P10636
P10636
P10636
P10636
P10636
Q02156
Q02750
P18654
P18654
P18654
Q04759
P36507
P17612
O00141
O00141
Q63531
O60331
Q99814
P09215
O15530
O15530
O15530
O15530
O15530
O15530
P51812
P05106
P05106
P08559
P08559
P08559
P31750
P23443
P23443
P23443
P23443
Q16513
Q16512
Q16512
O35099
O35099
Q99683
Q99683
Q9HBY8
Q06226
P31751
Q05513
P18652
Q9Z1M4
P09217
Q96BR1
Q9Y243
P23443-2
Q9D2E1
Q05516
Q05516
Q05516
Q05516
Q05516
Q05516
Q15418
P00558
P24723
P17252
Q15349
P17600
P41743
P05771
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
P05129
Q5TCN4
P13861
Q9HBY8-1
Q05655
P40763
P08581
P10275
Q02248
Q16555
Q16555
P15311
P15311
P15311
Q13480
Q60598
Q60598
Q60598
P16591
P16591
P14923
P16284
P16284
P46459
Q08481
O13016
Q9NQS9
Q9NQS9
P13796
Q00987
Q86YD1
Q86YD1
P13796
P49840
P49841
Q00987
Q9WV60
Q96J02
Q96J02
Q13045
Q13045
Q9H4U5
Q9H4U5
P51659
Q9HBA0
P46527
P60484
P25490
P25490
P25490
P42768
P14317
P14317
P14317
P68400
P42684
P42684
P42684
P42684
P42684
P42684
P42684
P11802
P43405
P43405
P43405
P43405
P43405
O14920
O14920
Q13568
Q13568
P48025
P02730
P02730
P02730
P02730
P31995
Q62418
Q62418
P16885
P12318
P12318
P12318
Q9GZY6
Q9GZY6
Q9GZY6
Q9GZY6
Q9GZY6
P42229
P22681
P11911
Q06187
Q06187
Q8N6F7
Q8N6F7
Q8N6F7
Q8N6F7
Q8N6F7
Q13263
Q13263
Q13263
P29351
P11137
Q14847
Q14790
Q14790
O43823
O43823
O43823
O43823
O43823
O43823
O43823
O43823
O43823
O43823
O43823
O15492
O15492
Q9NWQ8
Q9NWQ8
P30205
P29350
P29350
Q96TC7
Q14289
Q14289
Q9UN19
Q9Y6K9
P42680
P33993
P00519
P00519
P00519
P00519
P00519
P00519
P00519
P00519
P00519
P11274
P15391
P15391
Q13291
O54918
O54918
P30419
P30419
P35354
P31994
P07948
P07948
P32927
P32927
P32927
P32927
P28867
P28867
P28867
Q9Y6Y9
Q9Y6Y9
P23819
Q8BZI0
Q8BZI0
P35991
Q99N69
Q9H792
Q12972
Q12972
P19235
P11912
P40259
P40259
P53396
P53396
P53396
P53396
P53396
P53396
O15524
Q9UIB8
P15530
P30419-2
P30419-2
P30419-2
P21854
P21854
Q7Z7G1
Q7Z7G1
O75022
O75022
O60711
Q9Y6L6
Q9HBA0
P16220
P16220
Q9WVH4
Q01147
Q01147
O88335
Q96PU5
Q96PU5
Q96PU5
P23804
P29477
P29477
Q9R1E0
Q9R1E0
Q9R1E0
Q9QX74-7
Q8CFI0
Q8CFI0
Q61084
P63085
P47809
Q9QXJ1
Q60680
Q60680
Q9QYG0
Q9QYG0
Q9QYG0
Q8VBV4
P14142
Q62433
Q62433
Q62433
Q62433
Q62433
G3X939
P05787
P49841
Q00613
Q13148
Q13148
P28482
P28482
P06401
P04049
P17542
P37238
P27361
P27361
P27361
P27361
P10085
P63086
P63086
P21708
P21708
P63085
P63085
Q99N57
Q63844
Q63844
P29067
Q8BGD7
Q8BGD7
Q8BGD7
Q8BGD7
Q8BGD7
Q8BGD7
Q6ZN28
Q6ZN28
Q6ZN28
P05787
P28482
P28482
P27361
P27361
P05787
P04637
Q61143
Q61143
Q61143
Q61143
P08050
P08050
P08050
Q9ERR1
Q9ERR1
P33242
Q9WVH4
Q925J9
Q925J9
P28028
P97784
P49117
P49117
P49117
P02340
P02340
P02340
P04177
Q8CBD1
Q8CBD1
P42225
P22893
Q3V6T2
Q3V6T2
P35569
P68433
Q16665
Q16665
P54227
P54227
Q6R891
Q6R891
P11881
P11881
P22091
Q60875
P81122
P24529
P54830
P54830
P17679
P28033
Q05682
O70337
Q60793
P37238
Q80YV2
Q80YV2
P19419
Q00657
Q00657
P47930
P47930
P47930
P47930
P47930
Q08509
Q08509
P10417
P97287
Q04211
P16951
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
P98083
P27577
P27577
Q08369
P12841
Q00175
Q00175
P10301
Q61183
Q61097
Q61097
Q61097
O70161
Q60749
Q60749
Q60749
P23443
P48678
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
P26645
Q80YE7
O88809
O88809
O88809
O88809
P14873
Q8C050
Q8C050
Q9JHG6
Q8K120
Q61743
Q61743
P41969
P41969
P41969
P41969
P41969
P41969
P41969
P41969
P41969
Q505F1
Q91YD3
Q91YD3
P25118
P25118
P25118
P25118
O08537
O08537
Q60867
Q60867
Q60867
Q60867
Q9Z0V2
Q8C3Q9
P23242
P23242
P23242
Q9Z340
Q9DAW9
P63085
Q0VGT2
Q99N57
Q99N57
Q99N57
Q99N57
Q99N57
Q99N57
O54918
O54918
O54918
O54918
Q9ESN9
Q9ESN9
Q9ESN9
P05627
P31938
P31938
P22829
P29678
P01101
P01101
P01101
P01101
P19836
O08599
O08599
Q9R1Z8
Q9R1Z8
P43354
P43354
P43354
P43354
Q01279
Q9R194
Q9R194
P97471
P47713
P15037
P49138
P35639
P20444
O88487
F2Z3U3
F2Z3U3
P62908
P62908
P84244
O89090
O89090
Q8K4R9
Q60953
Q60953
Q60953
Q60953
Q8BUN5
Q8BUN5
Q8BUN5
P34152
O55201
P11679
P41164
P41164
P41164
P41164
Q08874
P41183
P70211
P70211
P70211
P28563
P28563
Q9Z2B9
Q9Z2B9
B2RQC6
Q9CX84
P51448
Q3UFY4
Q9DA80
P18760
P70459
Q99P72
Q8R1Q8

Q80YD1
Q8R080
Q6PDH0
Q6PDH0
Q8BP71
Q68FE6
Q6ZQ58
Q6ZQ58
E9Q616
E9Q616
E9Q616
E9Q616
E9Q616
E9Q616
E9Q616
Q80WR0
Q9QY06
Q80U35
Q9CWK8
P70333
Q61818
Q61169
Q9EP71
Q7TT28
Q9WTQ5
Q06219
Q06219
Q06219
Q06219
Q811L6
Q9QYR6
Q9QYR6
Q9QZL0
F6ZDS4
F6ZDS4
F6ZDS4
Q80U49
Q80U49
Q8R4Z4
Q9EQQ9
Q91W92
Q8K2J7
D3YXK2
Q9WTU0
Q8CG79
Q70E20
P10493
P59041
Q9DBR1
Q9D032
Q62219
Q91VX2
Q3URZ6
Q80XK6
Q9EST3
Q6A065
Q80X50
Q7TSC1
Q7TSC1
Q7TSC1
Q9R1L5
P58468
A6H8H2
P58871
P58871
Q7TPV4
O54819
P09450
Q8K0F1
P18653
Q8BUR4
O70475
Q3UGS4
E9PVP1
Q0VGY8
O88286
Q6Y7W8
Q60592
Q9WU42
O35737
Q8CJ00
O55098
Q99K01
Q8CJF7
Q640N1
Q8JZX9
Q9WVB0-2
A2APB8
E9Q9R9
Q80YR5
Q8BFV3
Q8BFV3
P20263
O08709
Q9JLH3
Q9JLH3
Q9JLH3
Q1HL35
Q1HL35
Q1HL35
Q99JX3
P05787
P05787
P23396
P14921
Q02078
P06401
O43521
Q01860
P17676
Q07820
Q9NRA0
Q9NRA0
P30041
P84022
P84022
P84022
P47712
Q14686
Q9UPT6
Q9UPT6
Q9UPT6
O75030
O14994
Q16526
O43602
O43602
O43602
O43602
Q49AN0
Q49AN0
Q13115
Q13115
Q12929
P49116
P49116
P49116
P54829
P54829
P05787
P28329-3
Q96A00
Q15796
P55042
P05556
P05556
P16949
P07101
P07101
P07101
P35270
Q92736
P08670
P08670
Q01970
O14713
P21333
P07101-3
Q06210
O14490-2
O14490-2
P42261
P42261
Q04760
P10636-8
P10636-8
Q00613
P26678
Q16625
P32004
Q96EB6
Q96EB6
P16220
P16220
P16220
Q13131
P00533
P00533
P00533
P00533
P00533
Q9Z0U4
P10636
P05783
P18266
Q9NZV8
Q9NZV8
P14136
P14136
P14136
P17676
Q8IWU9
P18265
Q9HC16
Q13936
Q12959
O95999
Q15121
Q13555
P17600
P17600
Q9Y281
Q8NE86
Q8NE86
O76070
Q8N850
Q5CZI7
Q9H6L5
Q13554
Q13554
Q9Y5N4
Q6GMY0
P48058
Q15906
Q15906
Q15906
O60266
P24046
P09417
Q13255
P16615
P63027
Q7Z406
Q13698
Q13562
P04406
P68431
P68431
P68431
P35222
Q00613
P03372
P35226
P16220
P00533
Q12778
Q99623
Q99623
P15311
O43516
O43516
Q9H0H5
Q13370
P35240
Q9Z1S8
Q9Z1S8
O60331
Q92945
P98170
Q9Y4H2
Q9Y4H2
Q9Y4H2
Q9Y4H2
Q99683
Q9Y2I7
Q15118
O43464
B2RWS6
B2RWS6
O15111
Q09167
Q64314
Q8CFH6
P60335
G1N806
G1N806
Q9Y3M2
O35491
Q92908-2
Q14315
Q96F86
Q9JHJ0
Q9GZV1
Q86YS7
Q7Z6J0
Q7Z6J0
Q7Z6J0
Q99104
P30405
P97474
P49760
O08528
P53804
P53396
Q99697
Q04656
Q04656
Q04656
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
Q13835
P78477
P78563
P55265
P99999
Q00266
Q00266
P42224
P35222
P60484
P51812
P51812
P22607
P22607
P22607
P22607
P22607
P22607
Q9UPZ9
Q9UPZ9
Q6N021
P42224
P35568
P23396
P25963
P25963
Q04206
Q04206
Q04206
Q04206
Q04206
Q04206
Q04206
P01106
P01106
Q04207
Q04207
Q04207
O15350
O43524
Q16875
O14920
O14920
Q96CV9
Q14653
Q14653
Q14653
Q14653
Q14653
Q9UHD2
Q13568
Q13546
Q13546
Q9Y4G8
P19838
P19838
P19838
P19838
Q9BXH1
Q9BXH1
Q9BXH1
Q9Y6K9
Q9Y6K9
Q9Y6K9
Q9Y6K9
Q9Y6K9
Q92574
Q92574
P26450
P42858
P42858
P42858
Q9H3D4
Q9H3D4
Q01201
Q8N3F0
P20749
Q04864
Q04864
Q04864
P01100
P28740-1
P42771
Q99704
Q99704
Q99704
Q99704
Q9NQC7
Q9NQC7
Q9NQC7
Q9NQC7
Q9NQC7
Q9NQC7
Q9NQC7
O88522
O88522
P19438
Q5D1E7
Q5D1E7
O09044
O09044
O95999
O95999
O95999
O95999
O95999
Q14164
Q7Z434
Q96BF3
Q92905
Q92905
P42859
P41227
P21580
Q6P2E9
Q6P2E9
Q6P2E9
Q6P2E9
Q9H765
P97503
P97503
P97503
O00161
P63017
Q60769
P42224
P42224
P49840
O95786
Q9UNN5
P03372
P25963
P25963
P31749
P31749
Q04206
Q04206
Q04207
P46937
O43524
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q14653
Q14653
Q14653
Q14653
Q8N7N6
Q8N7N6
Q8N7N6
Q8N7N6
Q92985
Q92985
Q92985
Q92985
P42225
P42225
P42225
O95644
O95644
O95644
O95644
Q96AC1
P98170
O00571
P42858
P52630
P10914
P10914
P10914
Q80TQ2
O14519
Q12933
Q14164
Q9H765
Q96AQ6
P42224
P12979
P12979
P12979
Q8BHY3
P42224
Q14247
P29353-2
P29353-2
P29353-2
P37840
P37840
P37840
P10636-8
P13569
P14317
P14317
P43405
P43405
P43405
P43405
P48025
P48025
P48025
P02730
P02730
P02730
P02730
P31995
P31995
Q62418
Q62418
P19174
P19174
Q8WV28
Q8WV28
Q8WV28
Q8WV28
Q8WV28
P16885
P12318
P12318
P12318
Q13422
Q13422
Q9GZY6
Q9GZY6
Q9GZY6
Q64725
Q64725
P52566
P42229
P22681
P22681
P22681
P05132
Q8CBD1
Q8CBD1
Q8CBD1
P11911
Q9EPB4
P51452
P51452
Q06187
Q8N6F7
Q8N6F7
Q8N6F7
Q8N6F7
Q8N6F7
P10636
F8W6Q8
Q13094
Q13094
O14986
P06239
Q92918
P29353
P29353
P29353
P56945
P56945
P05106
Q14289
Q6ZUJ8
Q6ZUJ8
Q6ZUJ8
Q8TB45
P17252
O43914
O43914
P05771
P78314
P78314
P78314
P05129
Q8IWV1
Q8IWV1
Q8IWV1
Q8IWV1
Q9UH65
P32119
Q9H310
P42224
P68431
P51946
P51946
P46531
P46531
P46531
Q01094
Q15797
Q15797
Q15797
Q15797
P42227
P42225
P84022
P84022
P84022
P42230
D3Z194
P62753
P62753
P62753
P62753
P35568
P35568
P35568
P35568
P35568
P35568
P49841
P23818
P10636-8
P10636-8
P10636-8
P03372
P49959
Q06787
P35922
O00418
P08151
O70343
O70343
P35569
P07814
Q9BY77
Q9BY77
O94763
P27708
Q9WV60
O60331
O60331
P23804
Q15633
Q6R327
P23443
P23588
Q9UN36
Q9UN36
Q9H3D4
P42345
P42345
Q8TB45
Q8TB45
Q8TB45
Q05195
P78371
Q53EL6
Q53EL6
Q8BGD9
Q9BYV9
Q92519
Q16873
Q09161
Q09161
Q09161
P33778
O35147
P54103
P78362
Q16637
Q9GZT9
Q9NSP6
Q9NSP6
P62753
P62753
P04637
P04637
P04637
Q13224
Q00613
O95786
O95786
O95786
O95786
O95786
O95786
O95786
O14950
P32851
Q16623
Q13526
Q14457
P24844
Q96FA3
P25205
P53355
P53355
P53355
Q96RR4
P40429
Q80YE7
P09493
O43293
O43293
O43293
O43293
O43293
O43293
Q01097
Q96IK2
P62753
P62753
P13834
P52946
P52945
P68104
Q96RG2
Q96RG2
Q96RG2
P61964
Q14247
Q14247
Q14247
P68431
P35222
P35222
Q9UQ80
Q61337
Q61337
P16949
P16949
P08670
P21333
P21333
P21333
Q13153
Q13153
Q13153
Q13153
Q13153
P03372
O95863
O14965
O14965
O15143
Q13761
P53350
P04049
P04049
Q13363
P15056
O55043
P24844
Q92934
Q92934
Q92934
Q92934
Q92934
Q02750
P53667
Q96T58
Q96T58
Q92974
Q92974
P84243
Q10728
P35240
P52565
P52565
P52565
Q96P20
Q96P20
Q96P20
Q15746
P49023-2
Q92974-2
Q9Y2X7
Q9Y2X7
P49023
P78545
Q16659
Q99661
Q99661
P46108
P58012
O43623
Q13352
P28740-1
P28740-1
P28740-1
P28740-1
P42230
P36871
P51114
P19086
Q13418
Q13418
Q13233
A0MZ67
A0MZ67
Q99426
Q99426
P18669
P18669
Q9Y6X9
Q06806
P05625
P05625
Q9Z206
Q9Z206
Q9Z206
Q15365
Q15365
Q99N57
P63167
Q9Z2F5
Q91XC0
Q99MC0
Q70Z35
P31152
ENSP00000248996
ENSP00000357298
Q8BTM8
A0MZ66
O70250
Q8IYU2
Q9H1Y0
Q5VY93
P50395
P50395
Q14247
P40763
Q99K10
P16144
P11362
P11362
P11362
P11362
P11362
P11362
P11362
P11362
P11362
P11362
P11362
P00338
P00338
Q8R173
P51812
P56945
P56945
P56945
P56945
P56945
P08559
Q15118
Q15118
Q15118
Q9UBW7
Q9UBW7
Q9UBW7
Q9UBW7
Q9UBW7
Q9UBW7
Q9UBW7
Q9Y2J4
P52480
Q9P0J1
Q9P0J1
P24752
O60506
Q8WU20
Q8WU20
Q8WU20
Q8WU20
Q8WU20
Q8WU20
Q9CZA6
Q9CZA6
Q9UDF2
Q9UDF2
Q9UDF2
Q9UDF2
Q9UDF2
Q9UDF2
Q9UDF2
O75874
Q14247
Q14247
Q14247
P12931
P37840
O15259
O15259
Q05397
P29474
O43561-2
Q14289
Q9CPX6
O43294
Q7YSG7
Q9QWY8
Q9QWY8
P70313
Q13586
Q02535
Q02535
Q02535
Q02535
Q9QVP9
P98082
Q61337
P16949
P55055
Q16625
O95180
Q13555
Q13555
P15173
P15173
P15173
Q5SWX4
Q15139
Q15139
P31016
Q62696
Q62696
Q62696
P16949
P16949
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
Q00613
Q00613
O00418
O00418
Q13501
Q13501
P30281
Q6JBY9
P13668
Q62101
Q62101
Q62101
Q62101
Q62101
Q62101
Q92993
Q92993-2
O57342
O57342
O57342
P61371
P29473
Q28021
P04272
A7E3S4
A7E3S4
Q8WML4
P09851
O77628
O77628
Q17R13
Q6R8F2
Q6R8F2
Q6R8F2
Q66WT7
Q66WT7
Q2KJ93
O18738
F1N5S9
P04394
P31039
Q3SX26
P29473
P48616
Q2T9S0
Q3MHM5
Q3ZBU7
Q6B856
Q2KJD0
Q3T169
E1BPQ1
P67939
Q6J1J1
O62654
O62654
O62654
Q1LZG6
P68399
P68399
P68399
P68399
Q148G7
Q2KIA5
A6H7I5
Q9N179
E1BFR5
A5D7P0
A5D7P0
A5D7P0
A5D7P0
A5D7P0
Q3B7M6
Q3T160
Q3T160
Q08E02
Q3SZC4
Q3SZY3
Q2TBH7
Q3T0C7
Q3T0C7
Q2HJ81
A7E320
P29473
P67939
P67939
Q3T160
Q3T160
O02755
Q3SYU2
P49884
P49884
Q58DH8
Q2HJ27
Q17QZ4
F1N5V1
P29473
P48616
P17599
P17599
Q13522
P62136
P67939
P67939
P23196
Q28199
Q28199
Q0VCX4
Q0VCX4
A2VDZ3
P07516
Q32LM0
P29473
P17599
P00517
P00515
Q01314
Q08E52
A7MB74
Q95KV0
P04409
P05126
P05128
Q6TJY3
A1A4I4
P15381
P08057
P08057
Q96A00
Q61143
Q61337
P35367
P35367
P16949
P11831
P31645
E9Q401
Q13153
P50552
P50552
P50552
Q05469
P70460
P70460
P11716
P04792
P04792
P04792
P04792
Q15052
P18266
P61224
P29294
P43694
P61586
P00511
P00511
Q0R4E4
P35400
P21731-2
P21731-2
Q90623
Q90623
Q9NS28
Q10728
Q10728
Q14847
Q8WZ42
Q8WZ42
Q8WZ42
Q8WZ42
Q8WZ42
P29994
P29994
P04083
P32067
P21731
HSBO22
O76074
P78347-2
P78347-2
P78347
P78347
Q9Y613
P10644
Q9WVC5
P35520
P35520
Q9Y210
Q9Y210
Q96D31
P02253
Q13507-3
Q684P5
P54288
NP_001104263
P41220
P41220
Q28156
Q8CJD2
Q28265
Q13507
Q13976
Q03393
Q76M96
Q76M96
A2ASS6
Q9Z0X4
O43768
Q15637
Q75M87
Q75M87
Q9UBN4
P56211

O96001
O96001
XP_008773743
XP_008773743
Q9Y6F6
Q9HCX4
O35245
O35245
P48995
P48995
P52943
P36201
Q13976-2
Q13976-2
Q80XI6
Q80XI6
P19686
P15381
P15381
P15381
P02316
P02316
P13569
P13569
P50552
P50552
P29294
P29294
HSBO22
HSBO22
O14558
O76074
P19491
P02253
P54288
NP_001104263
P51177
Q5QD51
Q9EPF2
O96001
O96001
P85125
P85125
P85125
P85125
P36202
P36202
P17475
D3ZFU9
Q810D0
A7MB80
A7MB80
P61585
Q2TA49
Q2TA49
Q2TA49
Q9Y6F6
Q9Y6F6
P00516
P00516
P00516
P00516
P00516
P00516
P00516
P00516
P00514
O88989
Q4V7C7
P02313
Q9WU34
Q9JMB0
Q7TMZ9
Q8K585
Q8K585
Q8K585
P15337
Q9WU82
Q9WU82
Q9EQH5
Q63046
Q63046
Q63046
D4A8X0
D4A8X0
D4A8X0
P08057
P08057
P08057
E1BPQ1
Q2M2T1
Q32L48
P62808
P08057
P08057
P08057
P08057
P61635
P05786
P05786
P08057
A7E3S4
A7E3S4
Q60795
Q60795
Q60795
Q60795
Q60795
Q60795
P49841
P01108
O08553
O08553
Q8BMD2
Q9WTL8
Q9WTL8
O70405
O70405
Q02248
Q02248
Q02248
Q02248
Q02248
Q02248
Q02248
P39689
P19838
P19838
P10637
P10637
P10637
P10637
P10637
P10637
Q9WV60
Q60670
Q60817
P28033
P28033
P28033
P97287
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
P23804
P23804
Q3UV55
Q3UV55
P70447
P70447
Q3TFD2
Q3TFD2
P40124
P06876
P14873
P14873
P14719
Q8BUV3
Q9JHG6
Q9JHG6
Q9Z0V2
P25322
P25322
P30282
O35625
O35625
P16054
P05627
P05627
P05627
Q9R194
Q9R194
Q60751
O08785
O08586
P25799
Q02496
Q62188
Q9Z1E4
Q8VCB3
Q8VCB3
Q8VCB3
Q8VCB3
Q3TTA7
Q3TTA7
Q9JIY0
Q8BGW1
Q8BGW1
Q61221
Q61221
Q61221
Q8VHJ5
Q05512
P70670
Q60674
Q8CGY8
Q8CGY8
Q7TME2
Q3UPF5
Q9WTI7-3
P40338
Q9DBD5
Q9WVG6
O35516
O35516
O35516
O35516
Q7M6Y2
Q7M6Y2
Q8BKJ9
Q8BKJ9
Q06831
Q06831
Q60795
P02340
P42227
P14602
P14602
P35569
Q62101
Q62101
P63101
P26645
P26645
P26645
P23242
P31946
P28867
P28867
Q8VI36
P10853
Q9JJ00
P62908
Q02496
P61979
P50580
P29352
P63318
P97324
P98083-2
Q91Y86
Q3UP24
P97369
Q08775
Q61337
P08670
P27699
P27699
P27699
P27699
P27699
P27699
Q9ERR1
Q9ERR1
P46414
Q12778
P02340
P54227
P54227
P20152
P11881
P11881
P05480
O70161
P21272
P10085
P10085
O88643
Q9WU62
Q9WU62
P48678
Q61188
P25206
P25206
Q3UV55
P31001
P31001
P31001
P99024
P48432
Q9R1E0
Q61937
Q61937
Q61937
Q61937
P49717
P49717
P49717
P49717
P49717
P53566
P53566
Q9ERT9
Q9DBR7
Q9ERD7
Q62193
P00520
P00520
P22314
Q9QY81
O14994
P08775
P08775
P02544
O70201
Q922U2
Q922U2
P47810
P02542
P02542
P02542
P17095
P17095
Q64373
P97929
O08901
O89110
P24860
Q03147
Q8K2Z4
Q8K2Z4
Q60737
Q60737
Q60737
Q60737
O08788
Q9WUB4
Q3TLR7
P39054
Q07139
Q07139
O08796
O08696
E9Q8I9
Q8C0P0
Q8CHK4
Q80WE4
Q5SXA9
Q5SXA9
Q3U9G9
Q9D279
Q9D279
Q9D279
Q9D279
Q9D279
P48967
P48967
Q3TYA6
Q3TYA6
Q3TYA6
Q6GQX2
Q6GQX2
Q6GQX2
Q6GQX2
Q6GQX2
Q6GQX2
P33215
E9Q7G0
E9Q7G0
E9Q7G0
Q80TJ7
Q80TJ7
O35954
Q9QXS1
Q60953
Q99K43
P62821
P56371
Q8BX09
Q8BX09
P97440
A2AQ07
Q7TMM9
Q9CWF2
Q9D6F9
P68372
Q922F4
Q62440
Q62440
Q62440
Q9WVB2
Q9WVB2
Q62441
P63280
Q8VDF2
P67869
P62137
P30427
P11440
P17095-1
Q9DC21
P05480-1
P13297
P26039
P68431
P25963
P25963
P25963
O15392
Q9NQS7
Q9NQS7
Q9NQS7
P84243
P84243
O75410
Q9WU62
Q9WU62
Q71DI3
Q71DI3
Q6NWP9
Q6NWP9
Q16695
O88445
Q8IZG2
P68431
P68431
P68431
P68431
P04637
P05412
P05412
P02340
P02340
P15336
P15336
P15336
P38432
P0C0S8
O75531
O75531
O75531
Q99986
Q99986
Q99986
O75469
Q9NZD0
P68431
Q99638
Q99638
Q96PY6
Q96PY6
Q96PY6
P68431
P35568
P61073
O00429
Q61337
Q61337
Q61337
P38936
P38936
P01108
Q01705
P46527
P46527
Q00987
Q00987
Q04206
P01106
P52907
P52907
Q13761
Q13761
Q13761
Q13761
P10275
P10275
P29474
O43524
O43524
Q92934
P30304
Q16665
Q01860
Q01860
O95644
O95644
O95644
O95644
O95644
O95644
O95644
O95644
O95644
O95644
O95644
Q92597
Q99814
P51692
Q9Y4H2
Q99683
Q9BZS1
Q99801
Q99801
Q99801
Q99801
Q99801
O60381
O60381
Q13309
Q13309
Q13309
Q96T88-2
P70658
Q96B36
P27448-3
P27448-3
P27448-3
Q9UNQ0
Q13200
Q8TA86
Q8TA86
Q9HC52
O75140
P47756
P47756
P47756
P68431
P05412
P05412
O75385
O75385
O75385
Q06830
P81274
Q96S44
P68431
P68431
P84243
Q71DI3
Q6NWP9
Q16695
Q6NXT2
P68431
O96017
P46379
Q9NYL2
Q9NYL2
Q9NYL2
Q9UGF0
Q9HDD2
Q9HDD2
P68431
P04637
Q96A00
Q96A00
P40763
P38936
Q00987
Q00987
O14950
O14950
Q14457
P24844
P24844
O14974
Q14669
Q90623
Q90623
Q90623
P40429
Q64122
Q64122
O43293
O43293
O43293
O43293
O43293
O43293
P10916
Q9CQ19
Q9CQ19
Q9UNH5
Q8WWI1-3
P68431
Q9TUB2
Q9TUB2
Q9TUB2
Q9GLN5
P02540
P02540
P02540
P02543
Q9N0X0
P68431
P35568
P35568
P35568
P35568
P35568
P35568
P35568
P03372
P07550
P07550
O15530
O15530
P07355
P08069
P08069
P08069
P08069
P08069
P08069
P08069
P08069
P08069
P78324
P78324
P12004
P12004
P12004
Q03431
P68431
BAA34185.2
BAA34185.2
BAA34185.2
P02316
P04176
Q8N5S9
Q8N5S9
F1RR02
F1RR02
F1RR02
F1RR02
Q13049
P19112
P19112
P19112
P09038
P36887
P36887
P52179
P68431
Q15717
P35222
P35222
P35222
P35222
Q9Y618
Q9Y618
Q9Y618
P03372
P25963
P25963
Q04206
P01106
P01106
Q04207
O14965
O43524
P46414
Q9Y6Q9
Q13546
Q13546
P19838
P19838
P19838
P24385
Q92793
Q92793
Q9BXH1
P26450
Q00653
Q00653
Q00653
Q00653
Q00653
Q00653
Q00653
Q01201
P51450-2
Q9BUZ4
Q9Y261
Q9Y261
Q676U5
O88907
Q8N3F0
P42345
P42345
Q86VP1-2
Q86VP1-2
Q60974
Q60974
P20749
Q04864
Q04864
Q04864
Q9C0C7
Q92905
Q92905
Q86VP1
Q86VP1
Q99558
Q99558
Q99558
Q9CXV9
P63017
P04637
P04637
P04637
P04637
P04637
P03372
P49736
P49736
P49736
P49736
P49736
P49736
P49736
P49736
P49736
P49736
P49736
P19447
P35922
P06493
P10275
P21127
P21127
P21127
P24941
P24941
P24941
P24941
Q00534
Q9JKV2
P24928
P24928
P24928
P24928
P10276
Q9H0D6
Q01094
Q01094
P11416
P11416
P33242
P11802
Q15797
Q9BYE7
P13631
P13631
Q9NYV4
Q13285
P29474
P29474
P14859
Q15648
P06400
P06400
P06400
Q01860
Q14847
P50613
P50613
O00267
O00267
O00267
O00267
P50750
Q9UPZ9
P08775
Q9NZD0
Q9UQ88
Q9UQ88
Q9NZS5
Q9NZS5
Q8N543
P04637
P40189
P48616
P48616
P48616
P48616
P07101-4
P07101-4
P07101
P07101
P07101
P11831
P11831
P08670
P08670
P08670
P08670
P15337
P07101-3
P07101-3
P07101-3
P09917
Q00613
O75925
P16220
P16220
Q00987
Q00987
P31749
P30305
P30305
P30305
P30305
P30307
P53350
P53350
O00418
Q14457
Q16875
Q0VBL6-2
P18654
P18654
Q13151
P14602
P14602
P04792
P04792
P04792
P53667
Q96J92
Q6JBY9
Q6JBY9
Q9CQT2
Q969V6
Q969V6
P63104
P22893
P22893
Q9UKV8
O95816
P05783
P05783
P49137
Q8K4J6
Q8K4J6
Q07352
Q07352
Q07352
Q9NQC3-2
Q9UPN4
Q9UPN4
Q9D312
O15511
Q14134
Q14134
O95453
P54748
P17844
P07101-2
P07101-2
Q92904
Q13546
Q8BYI6
Q13263
P19973
P19973
P33241
P33241
Q9NY61
Q07817
P49815
Q01147
Q01147
P35900
Q60855
Q60855
P27815
Q01860
Q01860
Q3UVX5
Q08499-6
P17302
P17302
P17302
P51812
P18615
P18615
P18615
P14270-6
Q92905
Q1W668
Q1W668
Q8N5C8
P26651
P26651
Q9Y580
Q9Y580
P34931
Q09014
Q2M3B4
Q2M3B4
Q9UC36
Q9UC36
Q9UC36
P04637
P04637
P04637
P12830
P12830
P35222
P10636-8
P10636-8
P10636-8
P10636-8
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
P49810
P49810
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
Q00987
P35922
P43629
P43629
P30291
Q14511
Q14511
P46937-2
P02340
P02340
P02340
P02340
P02340
O15055
O15055
O15055
Q9Y6Q9
O14641
O14641
O75581
P25054
P25054
P25054
P25054
Q02248
Q9BZL6
Q16665
Q96T88
P02687
Q60838
Q60838
Q60838
Q60838
Q60838
Q6U7Q0
P48985
P48985
P48985
P48985
P48985
P48985
P48985
P48985
P48985
P27707
P27707
P27707
P27707
Q99814
Q99814
P56817
P23804
P23804
P23804
G3V7R4
G3V7R4
O43312
Q9MZ06
P51532
P51532
Q02880-2
P53041
Q9BRK4
Q9BRK4
Q9BRK4
Q9BRK4
P04637
P35222
P07101
O14713
P03372
P07954
P53667
Q92974
Q92974
P49023-2
Q92974-2
O96013
P18084
P18084
P62826
Q157S1
Q93045
O43623
O43623
Q01196
O00401
O00401
P28698
P04637
P04637
P04637
P04637
P04637
P04637
Q15717
Q15717
Q15717
P14618
P10636-8
P18887
P18887
P18887
P38398
P40337
P29590
P30307
Q9NRM7
Q9NRM7
Q9NRM7
Q9NRM7
Q9NQS7
P21127
Q01094
Q14457
Q14457
Q13263
Q9NY61
Q9NY61
Q9NY61
P54132
O00716
P30304
P30304
P30304
P30304
Q96GD4
O15151
O15151
P06400
P02687
P02687
P02687
P02687
P02687
P02687
P33981
Q08050
Q08050-2
O43255
O43255
O43255
O43255
O96017
O96017
O96017
O96017
O96017
O96017
O96017
O96017
O96017
O96017
O96017
O96017
O96017
O96017
Q9UHR4
P61289
P29590-3
P16403
P16403
P16403
P16403
P16403
P23560
O60673
Q15554
P51587
Q9UGF0
Q9UGF0
Q9UGF0
Q9NZD0
Q9BZY2
O60664
Q99541
P04637
P10636-8
P10636-8
P06493
P35569
P83268
P83268
Q9Z1X4
Q9Z1X4
P19525
P19525
P19525
P19525
P19525
P19525
P19525
P19525
P19525
P19525
P19525
P19525
P19525
P05198
P05198
P68101
Q15172
Q12906
Q12906
Q9H3R0
P04637
P04637
P38936
Q13153
P60484

P60484
P60484
Q96EB6
Q96EB6
Q96EB6
P46937-2
Q13131
Q13131
Q9R1U5
P27448
P27448
P27448
Q5EG47
Q8IWQ3
P54645
Q9H0K1
Q8TDC3-2
Q7KZI7
O60285
P54646
J3KPC8
P25274
Q7RTN6
Q7RTN6
Q13485
Q9H093
Q15831
Q15831
Q15831
Q15831
Q15831
Q15831
P57059
Q14680
Q8TDC3
Q8TDC3
Q96L34
Q9P0L2
Q9NRH2
O14744
O14744
O14744
Q9Y2K2
Q9Y2K2
Q6UUV9
P04637
P37840
Q9UBN7
O75581
P26038
Q16143
P07550
P07550
P07550
P07550
P07550
P07550
P07550
P07550
P49407
P42866
P34947
P34947
P34947
P50502
O60353
P56485
P56485
Q9NZD0
P04637
P04637
O00429
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P31749
Q13501
P35241
P15311
P26038
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S007
Q5S006
O95295
P20339
P09951
P09951
P05067
P61020
P61020
Q99683
Q99683
Q8BH43
Q8BH43
Q2T9S0
P62280
P62280
P62280
Q3MHM5
P46459
P62841
Q3ZBU7
Q6B856
Q2KJD0
Q96CW1
P61026
Q6IQ22
Q15286
P20336
P20337
Q96E17
O95716
Q86YS6
P51148
O14966
O14966
P61006
Q92930
O75061
Q63481
Q9P2J5
P55258
P61027
P35283
Q9NPG1
Q91YQ1
P04637
P37840
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q96EB6
P49418
P49418
P49418
P49418
Q923E4
P13834
P24928
P24928
P08151
Q12778
Q13114
Q13114
Q13114
P55211
P24385
O95644
O95644
O95644
O95644
O43597
Q64350
P53805
P53805
O75533
O75533
Q9JHG6
Q9JHG6
Q7TQF7
Q8C3Q9
NP_001103022
NP_001103022
NP_001103022
Q13627
Q13627
Q96S94
Q96S94
Q96S94
Q52LA3
P41136
P30282
O76039
Q05193
Q14814
Q00959
Q49AN0
Q13247
Q60803
P04637
P07101
P07101-3
P07101-3
P07101-3
O00418
O43524
O43524
O43524
O43524
P04792
P04792
Q92599
Q92599
O60229
P25685
P25685
P25685
Q15382
Q9NZD0
Q9UC36
Q9UC36
P04637
P04637
P04637
Q96PM5
Q96PM5
Q96EB6
Q00987
Q15596
Q15596
Q15596
Q15596
P10275
P10275
P24928
P24928
P24928
P24928
P24928
P24928
Q9H0D6
Q15797
Q15797
Q15797
Q15797
P06400
P06400
P06400
P02687
P02687
P10412
P49459
Q6PGQ7
O00267
O00267
O00267
O00267
O00267
O00267
O00267
O00267
O00267
O00267
P50750
P50750
P50750
P50750
P50750
P50750
P50750
P50750
Q02539
P84022
P84022
P84022
P37231
Q8N543
P04637
P35222
P35222
Q09472
P46527
P18846
Q04724
Q04724
Q04724
Q96EB6
Q96EB6
P16220
P16220
P46531
P52946
P52946
P52946
O15379
P29590
P29590
P29590
Q13363
P02340
P02340
P17676
P17676
Q9H2X6
Q9H2X6
Q9H2X6
Q9H2X6
Q9H2X6
Q9H2X6
Q9H2X6
Q9H2X6
Q9H2X6
Q9H2X6
P17096
P17096
P17096
P17096-2
P17096-2
O43255
O43255
O43255
O43255
P52945
Q9H3D4
Q99607
P63015
P63015
P63015
Q9P1Z0
Q9P1Z0
Q9P1Z0
Q01196
Q01196
Q01196
P57682
P57682
P57682
P57682
P57682
P57682
P57682
P57682
P57682
P56545
O15297
O15297
O00257
O00257
Q9QZR5
Q9NZD0
Q9BZY2
Q9BZY2
P51608
P51608
Q9UBP0
Q16122
Q16122
Q16122
P04637
P04637
P04637
P12830
P35222
P08050
P08050
P08050
P28229
P28229
P28229
P28229
P28229
Q9BXL7
P37840
P37840
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
Q13148
P18846
P18846
P18846
P18846
P18846
Q01827
Q01827
P16220
P16220
P16220
P16220
P16220
P16220
P16220
P16220
P07900
P07900
Q04206
P32851
P01106
P01106
P27699
P27699
P27699
P27699
P13834
P13834
P40337
O60341
P08238
P35922
Q6J4I0
P07910
P07910
P07910
Q13158
Q12778
Q12778
Q13501
P02340
P02340
P02340
P02340
P02340
P02340
P02340
O75581
O75581
O75581
O75581
P25054
P25054
P25054
P25054
P02730
P02730
O60260
O60260
P63104
Q9UKV8
Q9UKV8
Q9UKV8
Q9UKV8
Q9UKV8
Q9Y4G8
Q9Y4G8
P67809
P30304
P30304
O15151
P0DMV8
Q92063
P56817
P17302
P17302
P17302
P17181
Q80SW1
Q80SW1
Q80SW1
P17931
P17931
O94916
O60346
O60346
O60346
O60346
Q64350
Q9WU82
P11308
P11308
P11308
P11308
P11308
P11308
Q9JKD8
Q8TB45
Q8TB45
Q8TB45
Q8TB45
Q8TB45
Q9Y2W7
O00257
Q9P2Y5
P55316
P27348
P16053
P16053
P16053
P16053
Q12968
Q12968
Q12968
Q12968
Q12968
Q6IE81
Q6IE81
Q9NRF8
A4GTP0
A4GTP0
P70444
Q00535
P62745
Q9H6E5
P56537
P56537
P42892
P42892
P98177
P98177
P35398
P78362
Q13009
Q9UGI0
Q9UGI0
Q969R2
Q969R2
Q969R2
Q969R2
Q9UDY8
O60716-3
O60716-3
O14503
Q8R4A3
P04637
P40763
P10636-8
Q00613
Q00613
Q00613
Q00613
Q00613
P05412
P46531
P01106
P13834
O95863
Q13541
Q13541
Q14194
Q9ERR1
Q16555
Q9UHD2
P10636
P30304
P30304
P30304
P30304
P30304
P30304
P30304
P30304
P84243
O14746
Q9Y2V2
Q9Y2V2
Q9Y2V2
O43255
O43255
O43255
O43255
O43255
O43602-2
Q64350
Q14195
Q0VGT2
Q0VGT2
O75449
O75449
O75449
P43686
ENSP00000343690
O43602
Q13144
P10070
P10070
B3SXQ8
Q92630-2
Q92630-2
Q92630-2
Q92630-2
Q92630-2
Q92630-2
Q92630-2
Q92630-2
Q92630-2
P04637
P04637
P40763
P38936
P38936
P38936
P31645
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P05412
P05412
Q9NYV6
P01106
P01106
P30307
P46937
P46937
P46937
P46937
P46937
Q13526
P11802
Q02248
Q02248
Q8IW41
Q07817
Q07817
Q07817
P54227
P54227
P19793
P19793
P19793
P19793
P36956
P15336
P15336
P15336
P50616
P50616
P50616
P10415
P10415
P10415
P10415
Q8VDS3
Q9UIG0
P29966
P16951
P16951
P98083
O35254
Q14934
Q14934
O43521-2
Q06481
P52945
P52945
P06536
Q15750
P49768
P49768
O43602-2
O43602-2
O43602-2
Q91Y80
Q8WYK2
Q9BQQ3
Q12968
Q12968
P05067-4
Q04666
P55957
Q9UQF2
Q9UQF2
P98177
P98177
O54918
P05627
ENSP00000267569
Q9UGP4
Q9UGP4
Q9UGP4
Q9UGP4
B5B2W9
B5B2W9
P46937-3
P46937-3
P46937-3
P46937-3
P46937-3
P20263
O60239
O95140
P81067
P81067
P04637
P37840
P60484
P60484
Q16625
P05412
P05412
P11388
P08551
P08238
P30307
P30307
Q07817
P30304
P30304
P30304
Q16143
Q16665
Q16665
P15336
P15336
Q14790
Q99986
P06748
P14635
O96017
O96017
P62258
O43852
O43852
O43852
O43852
O43852
O55042
Q9UGF0
Q9UGF0
Q9NZD0
Q9UQP9
P04637
P15337
P42768
P25963
P25963
P16885
P16885
P16885
P16885
Q13422
Q13422
Q06187
Q06187
P78347-2
P78347-2
P78347-2
P78347
P78347
P78347
P51813
P51813
Q08881
P42680
P42230
P24135
P24135
P24135
P24135
P58753
P58753
P58753
Q9UJV9
Q9UJV9
Q75M87
Q75M87
Q75M87
P04637
P04637
P38936
P10636-8
P10636-8
O95835
O14974
O14974
O14974
P39689
P39689
P55212
Q9NZD0
Q9NZD0
P04637
Q9NZD0
P04637
P04637
P07900
Q9Y6R1
P54132
P54132
P54132
P27816
P27816
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
O60566
O60566
O60566
O60566
Q9Y5T5
Q9Y5T5
Q9Y5T5
O96017
P00519
Q9Y6D9
Q9Y6D9
Q9Y6D9
Q9Y6D9
Q9Y6D9
Q9Y6D9
Q9Y6D9
Q9Y6D9
Q6IBW4
Q53HL2
Q53HL2
Q53HL2
Q53HL2
Q53HL2
P38646
P38646
Q96PE2
Q96PE2
Q96PE2
Q96E14
P33981-1
P33981-1
P04637
Q9NZD0
P04637
P08050
P08050
P04177
Q3V6T2
Q3V6T2
P68433
Q16665
Q16665
P54227
P54227
P24529
Q60793
Q80YV2
Q80YV2
P19419
Q00657
P47930
P47930
P10417
P16951
P27577
P27577
P12841
P23443
Q91YD3
Q91YD3
O08537
O08537
Q9Z0V2
P23242
P23242
Q9DAW9
P63085
P31938
P41164
P41164
P41164
P41164
P18760
P70459
P04637
P35222
P31016
P31016
Q62696
Q62696
Q62696
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
Q00613
Q00613
P07900
P30281
Q6JBY9
P36956
P36956
P15336
Q92993
Q12959
Q12959
Q12959
P26045
O43464
Q91Y80
P53778
Q92993-2
P15172
P15172
Q13424
Q13424
O60239
Q04323
P37198
P37198
P04637
P54274
O14777
O15360
Q5FBB7
Q5FBB7
P06748
P06748
P13639
Q9H2D6-5
Q9BV73
Q9BV73
Q9BV73
P51955
P51955
P51955
P51955
P51955
P51955
P51955
P51955
P51955
Q8N137
Q8N137
Q8N137
Q8N137
P36873
P36873
Q92997
Q92997
Q92997
Q92997
Q9NZQ7
Q9NZQ7
Q5T7B8
Q5T7B8
Q96CN5
Q99501
Q9BVA8
Q9BVA8
P04637
P53350
P02340
P02340
P02340
P38432
O75531
O75531
O75531
Q9UHP3
Q9UHP3
Q9UHP3
Q9NZD0
Q96EV8
Q96EV8
P04637
P04637
P37840
P35221
P35221
P35221
P11388
P46937
P46937
Q12778
Q12778
Q9Y6Q9
O75581
O75581
O75581
P10636
P10636
P10636
P10636
P63104
Q16665
P27707
P27707
P27707
P17302
P17302
P17302
P05067
P84022
O15169
O15169
O15169
O15169
Q9Y2W7
P56537
P56537
Q9NZW4
P01375
P04637
P38936
P38936
P21333
P21333
P38398
Q13761
Q9NS23-2
Q12778
P04179
P49815
P49815
P30304
O15151
P06400
P06400
P06400
P06400
P06400
P06400
P06400
P06400
P06400
P06400
P06400
P06400
P43694
P81122
P81122
Q13950
Q08369
P48985
Q8IZL8
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
P26358
P26358
P15923
P15923
P15923
P15923
P55072
P55072
Q96KS0
Q08999
Q08999

Q08999
P28749
P28749
P28749
P28749
P28749
P84022
P84022
P84022
P84022
P84022
P53566
Q14814
Q14814
Q9BQA1
Q9BQA1
Q9BQA1
P33568
Q92879
P28659
P19484
P19484
P19484
P19484
P17480
Q14106
Q9GKR4
Q9GKR4
Q9GKR4
Q92830
Q92830
O43791
P19532
Q8NFG4
Q8NFG4
Q8NFG4
P04637
Q15717
P14618
P38936
P46527
P46527
P21333
P21333
Q16875
Q16875
P49815
P49815
P06400
P06400
P06400
P06400
P06400
P06400
P06400
P06400
Q01196-8
Q01196-8
Q01196-8
Q01196-8
Q01196-8
Q01196-8
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
Q08050
P06748
Q96KS0
Q08999
Q08999
Q08999
Q92879
P14618-2
P19484
P19484
P19484
P19484
Q8WTW5
P19532
P04637
P35367
Q15796
P33535
P35372
P37840
Q14940
Q14940
Q14940
Q14940
Q14940
Q01717
Q01717
Q01717
Q01717
Q13509
Q13509
Q13509
P09619
P35241
P15311
P26038
Q16143
P07550
P07550
P07550
P07550
P07550
P07550
P07550
P21731-2
P21731-2
P32245
P32245
P42866
P42866
P42866
P42866
Q16539
P08069
P21462
P21462
P21462
P21462
P21462
P21462
P21462
P21462
P41143
P41143
P41143
P69897
P69897
P32300
P08172
P08172
P08172
P08172
P08172
P08172
P08172
P08172
P08172
P08172
P08172
P08172
P08172
P08172
P08172
P08172
P08172
Q9ERD7
P30680
P30680
P30680
P30680
P30680
P30680
P02401
P02401
Q95MG6
Q95MG6
O95398-3
P09497
Q9Y2W7
Q96A54
Q96A54
Q96A54
P70658
P70658
P26043
P51681
P51681
P51681
P51681
P41146
P41146
P41146
P41146
P25101
P25101
P25101
P25101
P25101
P25101
Q9Y5X5
Q9Y5X5
Q9Y5X5
Q9Y5X5
P25100
P25100
P25100
P25100
P25100
P25100
P35346
P18762
P18762
O60353
P56485
P56485
O76070
P05387
P05387
P18545
O14708
O14708
O14708
O14708
P12830
P35222
Q13148
Q13148
Q13148
Q13148
Q13148
P35922
O95863
O95863
Q13541
Q13541
P49674
P49674
P49674
P49674
P49674
P49674
P49674
P49674
P49674
P02340
P02340
P02340
P02340
P02340
O15055
O15055
O15055
O15055
Q90Z72
Q8TD43
Q9Y6Q9
O14641
O14641
O75581
O75581
O75581
Q9D0L1
Q9D0L1
Q13114
Q13114
Q13114
O35973
P25054
P25054
P51141
P51141
Q02248
Q02248
Q9BZL6
O60716
O00571
O00571
O00571
O00571
O75943
Q92997
Q92997
Q92997
Q92997
Q92997
Q92997
Q92997
Q92997
Q92997
O60353
O60716-3
O15534
O15534
O15534
P35568
Q5RKG9
P14618
Q99JB6
Q99JB6
Q61337
Q61337
Q61337
P38936
P38936
P01108
Q01705
Q00613
P01106
P01106
Q13131
Q16875
P51692
P52789
P09467
Q13200
Q9ESY2
Q9QXD6
P35568
Q61337
Q61337
Q61337
Q01705
P01106
Q92934
P51692
Q13200
P35568
P35222
P35222
P08670
P08670
P08670
P08670
P08670
P08670
Q14674
Q14674
P37840
Q00613
Q00613
P60484
P60484
P60484
P30260
P30260
P30260
P30260
P30260
P30260
P30260
P25490
P49959
P49959
Q14676
Q14676
Q14676
P11388
P11388
P11388
Q00987
P54274
Q8BMD2
P38398
P46531
P46531
P30622
P30622
P30622
P08551
P01106
Q06609
P30305
P30305
P30305
P30305
P30305
P30305
P30305
P30305
P30305
P30305
P30305
P30305
P30305
O60341
O15392
O15392
P30307
P30307
P30291
O43379
Q14980
Q14980
Q14980
Q14980
Q14980
Q14203
P46937
Q8NHV4
Q8NHV4
Q8NHV4
Q8NHV4
Q13158
O15350
Q49MG5
Q13526
Q15208
Q15208
Q15208
O14920
O14920
O14920
O14641
Q02248
Q96CV9
O60260
Q02750
Q02750
Q07817
Q12888
Q16143
P36507
P36507
Q9H0H5
Q9H0H5
Q9H0H5
Q9H0H5
Q9H0H5
Q9H0H5
Q9HAW4
P0DMV8
P0DMV8
P20152
P20152
P47736
P28818
P28818
P28818
P28818
P28818
P28818
Q96FF9
Q96FF9
Q14790
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P33981
P23804
Q15468
Q15468
Q9UKT4
Q9UKT4
P18031
P18031
O75122
O75122
O75122
O75122
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q9H1A4
Q8IZD2
Q38SD2
Q13042
Q92574
Q92574
Q99661
Q99661
Q99661
Q99661
Q8IWB6
O60566
O60566
O60566
O60566
Q08050
Q08050
Q08050-2
Q9UJX5
Q53EZ4
P06748
Q9Y2I6
Q9Y2I6
Q9Y2I6
Q9Y2I6
P14635
P14635
P14635
P14635
O95251
Q6PGQ7
Q6PGQ7
Q9UJX2
Q9UJX2
Q9UJX2
Q96T23
Q13188
Q13188
Q13188
O43663
O43663
Q2NKX8
Q9Y5T5
Q9Y5T5
Q9Y5T5
O60285
O60285
P62826
O96017
O96017
O96017
O96017
O96017
P78527
Q00839
P54646
O95271
O95271
O95271
O95271
O95271
Q99741
Q53GL7
Q99708
Q99708
Q99708
Q13416
O60563
Q96BK5
Q96BK5
Q96BK5
Q96BK5
Q96BK5
O95613
O95613
O95613
O95613
P63028
P63028
Q7L2Z9
Q7L2Z9
Q7L2Z9
Q7L2Z9
Q7L2Z9
Q7L2Z9
Q7L2Z9
Q7L2Z9
Q7L2Z9
Q9Y6D9
Q9Y6D9
Q9Y6D9
Q15022
Q15022
Q15022
Q9BVS4
Q9BVS4
Q9BVS4
O00139
Q9CXH7
Q9CXH7
Q9UJX3
Q9UJX3
Q9UJX3
Q9UJX3
Q9UJX3
Q9UJX3
Q28021
Q28021
Q28021
Q28021
Q9NYZ3
Q9NYZ3
Q9UBW7
Q9UBW7
Q9UBW7
O35625
Q8N4N8
Q8N4N8
Q8N4N8
Q8N4N8
Q3KR16
Q9H2D6-5
Q9NS56
Q9BQQ3
P51587
P51587
P51587
P51587
P51587
Q9UBB4
Q9UBB4
Q15435
Q15435
Q15435
Q15435
Q15435
Q6IBW4
Q71F23
Q71F23
Q9Y266
Q9Y266
AAC50053
Q9Y2T1
Q8TEP8-3
Q99640
Q99640
O35161
O35161
O35161
Q92994
Q92994
E9Q5G3
E9Q5G3
O95425
Q9Y2Z0
Q9Y265
P30626
Q2M2Z5
Q7TSG3
Q7TSG3
Q9CX34
Q58A65-2
O95235
Q12834
Q8IVT2
Q8IVT2
Q8IVT2
Q8IVT2
Q8IVT2
Q8IVT2
Q8TD19
P13693
P13693
Q8TDY6
P42898
P42695
O94901-9
O75170
O75170
Q8WTW5
Q62871
Q13127
Q76N32
AAC63511
AAC63511
AAC63511
AAC63511
AAC63511
AAC63511
AAC63511
Q8NG31-2
O43474
O60216
O60216
Q9H6R7
Q9H6R7
Q17RH5
Q17RH5
Q17RH5
Q17RH5
Q17RH5
Q8TCG1
Q8TEP8
P47806
Q59HH6
Q59HH6
Q59HH6
Q9NZ35
Q96FC3
Q9QUH6-3
Q9QUH6-3
Q9QUH6-3
Q9QUH6-3
Q9QUH6-3
Q9QUH6-3
Q9QUH6-3
E9Q8Q6
Q9NSG2
Q9NSG2
Q15013
P35568
Q61337
Q9Z2A0
Q9Z2A0
Q04759
Q8CIS0
Q8CIS0
Q8CIS0
P06332
P35569
P26043
Q9QYG0
P46099
Q3TTA7
Q9Z1W9
P15702
Q02111
P70365
P70365
Q8VBU2
P35568
P35568
P49841
P08581
P08581
P08581
P08581
P08581
P08581
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
P09874
P61586
P29353
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
Q13480
Q96KB5
Q04912
Q04912
Q04912
Q04912
P46940
P06213
Q96BD6
P35568
P11881
P81122
P81122
Q61937
P63028
P63028
O35161
O35161
O35161
P38532
P38532
ENSMUSP00000034815
ENSMUSP00000034815
Q9JJP2
Q9WVM1
Q9WVM1
Q9WVM1
Q9WVM1
P47810
P24860
O08788
O08696
O08696
Q9D279
Q9D279
Q9D279
P33215
P33215
P33215
E9Q7G0
E9Q7G0
E9Q7G0
Q99K43
Q9QZL0
Q80Z37
Q9Z1S0
Q9Z1S0
Q9Z1S0
Q8C4M7
Q8BT07
P97329
Q8C0N1
Q8C0N1
Q3UXL4
Q9ESG9
Q9ESG9
Q99KW3
Q7M6U3
Q8K389
Q96A00
Q96C90
O14950
O14950
P31749
Q90623
Q90623
Q90623
Q8TAE6
P45592
E9PAV3
P31750
Q13418
Q13765
P53671
O14950
P24844
P53667
Q5VT25
Q5VT25
Q5VT25
Q5VT25
Q86XX3
Q86XX3
Q86XX3
P53671
Q9BZL4
P24844
O14974
O43255
O43255
Q9Y5S2
Q80X41
P60484
P60484
P02340
P30304
P30304
P16951
P05627
Q9Z265
Q9Z265
O08586
O08586
Q64373
P48967
P48967
P48964
P48964
Q61221
Q61221
P11499
P29353-2
P29353-2
P29353-2
P02730
P51452
P51452
Q13094
Q13094
Q13094
Q15759
O43561-2
O43561-2
O43561-2
O43561-2
O43561-2
Q9UQC2
P29353
P29353
P29353
P10686
P10686
P43403
P43403
P43403
P43403
P43403
P43403
P43403
P43403
Q9UJU6
Q9UJU6
P47811
Q8N1K5
Q8N1K5
Q8N1K5
Q8N1K5
Q8N1K5
Q8N1K5
Q16539
O09039
Q9WUI1
P16410
P16410
Q9UQQ2
P29353-2
P35222
P40763
Q9NRF2
Q92529-2
Q92529-2
Q92529-2
Q92529-2
Q92529-2
Q92529-2
P04629-2
P04629-2
P04629-2
P04629-2
P04629-2
P04629-2
P04629
P04629
P04629
P04629
P04629
Q7Z5C3
Q7Z5C3
Q7Z5C3
Q7Z5C3
Q7Z5C3
P29353-2
P34152-3
P46937
Q9WV60
Q60598
Q60598
Q14155
Q61140
Q91YD9
P34152
P34152
Q03145
Q7TPR4
Q03160
Q03160
P34152-2
P35222
P06493
P04626
P04626
P04626
P04626
P04626
P04626
P04626
P04626
Q9BXH1
Q9BXH1
Q9BXH1
O43157
O43157
Q96N67
P00338
P35222
P35222
P35222
P35222
P40763
P31749
P31749
P49023-2
P49023-2
Q9UGK3
P56945
P56945
P51692
Q13017
P49023
P49023
Q13882
Q13882
Q13882
Q13882
Q13882
Q13882
Q13882
Q60749
Q60749
Q60749
Q96P48
Q9NRY4
Q07666
Q07666
Q07666
P35222
P35222
P35222
Q00613
P18887
P18887
P18887
P18887
P18887
Q96SB4
Q96SB4
Q9UQE7
P67870
P67870
P51946
Q16543
P35922
P04818
Q63692
O15350
Q99801
Q99801
P35222
P35222
P35222
P49840
P40763
P40763
P38936
O08553
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
P05412
P05412
P31749
P01106
Q13563
Q13131
Q9Y6Q9
Q9Y6Q9
O75581
O75581
O75581
O75581
Q16555
Q14653
Q14653
Q14653
P13807
Q07817
P17661
P17661
P17812
P81122
Q92597
Q92597
Q92597
Q07820
P28033
P28033
P28033
O75030-9
A6X8Z5
P70531
Q16584
Q16584
Q6R327
Q9BYG3
Q9BYG3
P13051
P13051
O15084
P22415
P22415
P06536
P70447
P70447
P24864
Q96F46
Q60943
P47942
P47942
P47942
P47942
P52630
P52630
P52630
Q8NHW3
Q8NHW3
Q8NHW3
Q8NHW3
P20749
P20749
Q9NZ72
P25322
P12839
P12839
P12839
P12839
P53566
P53566
Q9JKD8
P00515
P00515
Q2TBE6
Q2TBE6
Q07869
Q9NZQ7
Q9NZQ7
Q1W668
Q1W668
Q1W668
Q1W668
Q969R2
Q969R2
Q969R2
Q969R2
Q14449
Q14449
Q14449
Q14449
Q14449
P54840
P54840
P54840
P54840
Q9H5N1
Q14596
Q5XFN2
Q5XFN2
Q9Y4H4
D3ZZZ9
Q9CXL6
P35222
Q15208
Q15208
Q15208
Q15208
Q14653
P45985
P45985
Q9ERK0
Q09014
P35222
P60484
Q8CHT1
P62993
P21802
Q9UIH8
Q9UIH8
Q9UIH8
Q9UIH8
Q9UIH8
Q9UIH8
P35222
Q5RKG9
Q13158
P41181
P14625

P17931
Q12968
Q12968
Q12968
Q12968
Q12968
Q12968
P02666
P02810
P02810
P35222
Q02248
Q02248
P42227
Q08509
Q08509
Q08509
Q91YM2
Q60749
Q60749
Q60749
Q8VI36
Q8VI36
Q8R0L1
P61073
P61073
P61073
P61073
Q16625
O75581
P07550
P07550
P30411
P30411
O14745
P43250
P43250
Q15722
Q28619
P08069
P18762
P18762
P61073
P61073
O88572
P70658
P70658
P70658
P70658
P33534
P33534
P33534
P33534
P32299
P32299
Q61143
Q61337
P70460
P70460
P50571
O14558
Q9QUI0
Q9WVC5
Q9ESZ8
Q9ESZ8
Q8BUN5
Q8BUN5
Q61792
Q9Z2E4
Q9Z2E4
Q08460-5
Q08460-5
Q08460-5
P0C605-2
P0C605-2
P0C605-2
P0C605
P0C605
Q8CJC8
Q8CJC8
Q8CG03
Q61143
Q61143
Q61143
Q61143
Q9ERR1
P33242
Q9WVH4
Q925J9
Q925J9
P02340
P04177
P42225
P18654
P35569
P54227
P54227
P22091
Q3UVX5
Q60875
P02687
P24529
P17679
P28033
Q60793
P19419
Q9Z0F8
P10417
P51557
Q04211
P16951
Q8VIM5
Q8VIM5
Q8VIM5
Q8VIM5
P98083
P12841
Q00175
Q61097
P31750
P23443
P23443
P23443
Q9R1E0
Q8C050
Q8C050
Q9JHG6
Q8K120
P41969
P41969
P41969
P41969
P41969
O08537
O08537
Q9Z0V2
P23242
P23242
Q9ERT9
Q9DAW9
O54918
O54918
O54918
O54918
P05627
P05627
P31938
P31938
P29678
P01101
P01101
P01101
P01101
Q8VI36
Q8VI36
P19836
O08599
O08599
O14994
P47713
P15037
P49138
P49138
P20444
P84244
O89090
O89090
P34152
P70671
P41164
P41164
P41164
P41164
Q8BTI8
P28563
P28563
Q9Z2B9
Q9Z2B9
Q9CX84
P18760
Q61169
P09450
P18653
Q8CJ00
Q640N1
P35564
P70236
P70236
Q3UH06
Q3UH06
P08046
Q9CT10
P40763
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96FA3
P51617
P51617
Q9HAT8
P40763
P40763
P67999
P0DMV8
O00141
O00141
P52732
Q05586
P50613
P23443
P23443
P23443
P52948-2
P52948-2
Q08999
O95235
O95235
O95235
O95235
O95235
Q08345
Q96AP0
Q96AP0
Q13200
P35613-2
Q9HC35
P40763
P31749
P31749
P42229
P51692
Q12866
Q12866
Q12866
Q8NB16
P40763
P12931
P31749
P31749
P06241
P42229
P06239
Q92556
Q92556
P51692
P07947
P08631
P07948
Q96JJ3
Q8NB16
P30530
P30530
P30530
P30530
P30530
P30530
P40763
P50552
P42227
Q86WB0
Q86WB0
Q86WB0
P23246
Q9C0H9-5
P62993
Q06124
Q06124
Q06124
Q06124
Q9UM73
Q9UM73
Q9UM73
Q9UM73
P31939
Q9H9T3
P40763
Q02248
P42227
Q60598
Q60598
Q60598
Q08481
Q08481
Q08481
P70451
P40763
Q15796
P03372
P03372
P03372
P03372
Q9UJU2
Q9UJU2
Q9UJU2
Q9UJU2
Q9UJU2
Q02078
P46937
Q8N122
Q12778
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
Q9Y6Q9
P42227
Q13485
Q13485
Q15047
Q9NQB0
Q9NQB0
P84022
Q9UBE8
P40763
Q15300
P49841
P09651
P09651
O00418
P04792
P04792
P05783
Q15633
Q6R327
P49841
P49841
P49841
P46527
P46527
P15337
P10636-8
P26432
P25963
P16220
P16220
Q00987
P28482
Q9WVH4
O43524
O43524
O43524
Q9BUB5-2
P15056
P15056
Q12778
Q12778
Q12778
Q12778
O14920
P10636
Q96J92
Q96J92
Q96J92
P49815
P49815
P49815
P49815
P49815
P49815
O60343
O60343
O60343
O60343
O60343
O60343
O60343
O60343
Q96PU5
Q96PU5
Q96PU5
Q9EPK8
Q92597
Q92597
Q92597
Q92597
Q92597
Q92597
Q92597
O00141
Q969H0
P48048
Q6R327
Q9Y2V2
Q9H4A3
O00213
Q9QX74-7
Q9UN36
Q9UN36
Q9UN36
Q9UN36
P46933
Q92542
O35921
A4GTP4
A4GTP4
D3ZHH8
Q8CFI0
Q8CFI0
Q8CFI0
P14672
Q80UE6
Q80UE6
P50398
Q61084
Q61084
Q9Y2I7
P45985
P19332
P42858
P42858
P37089
O15111
O15111
P48764
Q99759
Q99759
O14686-3
Q9Y534
Q13878
Q5CZI7
Q13301
Q9H2W4
P49841
Q9WV60
Q09472
Q09472
P14618
P16949
P16949
Q00613
Q00613
P05412
P05412
Q13541
P33242
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P41235
P15056
P28562
O60716
O60716
O60716
P42225
Q15648
Q92974
P54227
P08955
P24529
Q9R0Z9
P17679
P15336
P28033
Q9EPI6
Q98T92
Q9Z0F8
P10417
Q9ULC4
P09951
P09951
P09951
P52909
P51557
P16951
P98083
Q08369
Q62132-2
P12841
Q00175
O35254
Q99814
Q9Y613
Q15750
NP_776683
P23927
P28324
P28324
P01100
O60504-2
Q9ULV5
Q15303
Q15303
P56192
P56192
P21802
Q9QYY0
P14270-6
P49615
Q62151
Q1W668
Q1W668
Q969R2
Q969R2
Q969R2
Q969R2
Q14761
Q53GS7
Q53GS7
Q53GS7
Q53GS7
Q53GS7
Q13127
Q13127
Q15366
Q15366
Q15366
Q15366
NP_059009
NP_059009
NP_059009
NP_059009
Q8K3Y3
Q8BTI8
Q4W5Z4
Q9H9Z2
Q8BFV3
Q8BFV3
Q8BFV3
Q8BFV3
Q9ERG0
Q9ERG0
Q9ERG0
Q13115
Q13115
O15027
O15525
P29067
Q09472
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q00613
Q00613
Q00613
P30305
Q01094
Q01094
O00418
P00533
P00533
Q8N122
Q8N122
P41235
P04179
P04179
Q15759
Q15759
Q6AZ28
Q6AZ28
Q8IW41
P17544
P13807
P13807
P13807
P13807
Q02156
Q01844
P30281
P04150
P04150
P42225
Q6P9Z1
P36956
P36956
P15336
P15336
Q92993
O60381
Q92993-2
O43257
Q96L92
P08581
Q13153
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q05397
Q07912
Q07912
P11362
P11362
P56945
P51813
P51813
P51813
Q16611
Q96T51
Q96T51
P08581
Q01970
Q01970
P26432
P26432
P26432
P09619
P29474
P29474
P29474
P00533
P04626
P04792
P97826
P97826
P97826
Q14847
P35521
P35521
P35521
P29350
P29350
P29350
O88703
Q03393
P41984
P51177
P32929
Q9UL51
Q3UR85
P08581
P08581
P08581
P08581
Q04912
Q04912
Q04912
Q04912
P08034
P08581
P08581
P04040
P04040
P05556
P10636-8
P10636-8
P10636-8
P09619
P09619
P09619
P42684
P42684
Q14653
P17676
P01112
O15304
Q9GZV5
Q13671
P24270
P24270
Q04929
P46108
Q921Q7
O14818
P17931
P17931
P35235
P35235
P35235
P35235
P07203
P07203
Q9NRY4
Q9JIA3
Q6NZY6
Q6NZY6
Q6NZY6
Q6NZY6
Q6NZY6
P12931
P16234
P16234
P16234
P16234
P16234
P16234
P16234
P16234
P16234
P16234
Q9P219
P12931
P18052
P34152-3
P34152-3
P34152-3
P34152-3
P34152-3
P09803
P09803
P09803
P25963
P00533
P00533
P46414
P46414
Q02248
Q02248
Q9UHD2
P42227
P11911
P11911
P15311
Q9Z2A0
Q9Z2A0
Q9Z2A0
P26038
P07949
P26955
Q9Z1S8
Q9Z1S8
P98083
Q9Z1Y4
P97318
P97318
P97318
Q8R173
Q8R173
Q62165
P05480
P05480
Q8CHT1
O70161
Q60598
Q60598
Q60598
Q60598
Q60598
P30999
P30999
P30999
P30999
P30999
P30999
P30999
P30999
P42866
Q61824
P37173
P55284
P70336
P31750
P31750
Q9QWY8
Q61188
P10721
Q08481
Q62077
Q99N57
Q99N57
Q01097
P28867
P28867
P28867
P28867
P01101
P01101
Q8VI36
Q8VI36
P49817
Q9WVC3
Q64355
Q61140
Q61140
Q61140
Q61140
Q61140
Q61140
Q61140
Q61140
Q61140
Q61140
Q61140
Q61140
Q61140
Q61140
Q61140
O08599
Q9QVP9
Q9QVP9
Q9QVP9
Q9QVP9
Q01279
Q60751
Q60751
Q60751
Q60751
Q60751
Q60751
P15116
P15116
P32507
P22682
Q6PDN3
Q9JJP2
Q61258
P34152
P34152
P34152
P34152
P34152
Q03717
Q02496
Q05695
P31809
P31809
Q8K2B3
P15530
P15530
Q8R0L1
Q06649
Q06649
Q06649
P12023-2
Q7TNI8
Q99MB1
O54967
P07356
P97504
Q80XL1
P60766
Q62371
Q62371
Q62371
Q62371
P14234
O89106
Q9DB70
Q62074
Q62074
Q62074
Q9D6J6
Q91ZP6
Q91ZP6
Q91ZP6
Q91ZP6
Q91WD2
Q91WD2
P35917
P35917
P35917
P35917
P35917
P35700
Q9R226
P63250
Q8R1S4
Q8R1S4
Q9ES28
Q9D832
Q3SZ94
Q3SZ94
P52795
P52795
O08579
O08579
Q9QXV8
Q9Z2I4
P62192
P12931
P08050
P08050
Q00960
Q00960
P15387
P22002
P22002
P35560
Q9Z0F8
P09951
P12841
P12841
P17302
P09215
P09215
F1M7Y5
F1M7Y5
F1M7Y5
P21575
P21575
Q9Z1K9
Q9R186
Q9R186
O35346
O35346
P19491
P04695
Q9WUD9
Q792H5-3
Q920L2
P16086
Q6PW52
Q6PW52
P16573
P16573
Q01279
Q3U1F9
P11345
P11345
P39052
P39052
Q6P6U0
P52631
Q63767
Q63767
Q66HL2
Q66HL2
P70600
P70600
Q9JM80
O55173
O55173
O55173
Q2IBC5
Q2IBC5
Q9QX70
Q62868
Q5U2X5
Q07936
Q9R0T4
Q9R0T4
Q9R0T4
G3V8H4
Q8CFN2
Q5BJS4
P19234
Q91ZT1
Q91ZT1
Q91ZT1
Q91ZT1
Q91ZT1
Q9Z272
Q9Z272
O88944-2
O88944-2
B2RUJ5
B2RUJ5
B2RUJ5
Q6P7A6
P60570
P41350
Q792H5-2
P12931
P32004
P10301
P34900
P34900
P52799
P11627
O94989
Q8N103
P30086
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P03372
P25963
P31749
P31749
Q04206
Q01094
Q9JLN9
Q8N122
Q13501
Q13501
O14920
O14920
Q96FA3
Q96FA3
Q96FA3
Q96FA3
Q96CV9
Q96CV9
Q96CV9
Q8TEV9
Q8TEV9
Q14653
Q14653
Q14653
Q14653
Q14653
Q14653
Q14653
Q14653
Q14653
Q8N7N6
Q8N7N6
Q8N7N6
Q92985
Q92985
Q92985
Q92985
Q9BRV8
Q9BRV8
Q9BRV8
Q9BRV8
Q9BRV8
Q9BRV8
P42226
Q9UHD2
Q13568
Q13568
P42227
P15127
Q86WV6
Q86WV6
Q8K3K8
Q14669
P31750
P31750
P23443
P23443
P98170
O00571
O00571
O00571
O00571
O00571
O00571
O00571
O00571
O00571
O00571
O00571
P42858
P42858
P56962
P52630
P42345
Q5D1E7
Q5D1E7
P11908
P60891
Q7Z434
Q9H765
Q96AQ6
Q8K4Q0
Q8IUC6
Q9WUL6
Q9WUL6
Q9WUL6
Q9WUL6
Q9WUL6
Q9WUL6
Q9WUL6
Q9WUL6
Q9WUL6
Q9WUL6
Q9WUL6
Q9WUL6
Q9WUL6
P60520
P60520
Q9BXW4
Q9BXW4
Q7LDL9
Q8WWI1-3
O95865
O95865
O95865
O95865
Q9BRZ2
Q99JB6
Q99JB6
P01108
P46527
P13405
P46414
Q12778
Q12778
P02340
P02340
P06400
P54227
P17676
P28033
Q00175
Q00175
O35254
P23804
P10085
Q61188
P48432
P48432
P46061
Q9WU82
Q9WU82
Q9WU82
Q9WU82
Q61937
P48972
P48972
P48972
P48972
P48972
P48972
P48972
P48972
P48972
P48972
P48972
P48972
P48972
P49717
P49717
P49717
P84022
P84022
P84022
Q62193
P25976
P25976
Q61502

Q9WUU9
Q16656
Q16656
P97929
Q03147
Q03147
Q3TLR7
Q60953
Q8VEH2
Q8VEH2
Q9ESJ1
P58252
F8VPZ5
P19785
P19785
P39749
Q8BMA5
Q8BMA5
Q8BMA5
Q8BMA5
Q8BMA5
Q8BUN5
Q8BUN5
Q8BUN5
Q64163
Q64163
Q8C0R0
Q61337
P01106
P04049
P04049
P04049
P04049
P04049
Q13118
Q92934
Q92934
Q92934
AAA40678
AAA40678
AAA40678
AAA40678
Q02750
Q02750
P50753
Q05639
O14974
P36507
P45379
Q61337
Q61337
P48787
P48787
Q01147
P28033
Q9WTK7
Q61337
Q61337
Q61337
Q8C863
Q8C863
Q8C863
Q923E4
Q923E4
P02340
P42227
Q9EPB4
P42225
Q05639
Q05639
P35569
P15336
P37238
P10417
P10417
P10417
P97287
P16951
P16951
Q14934
Q14934
P23443
O88809
P17275
P17275
O00327
O00327
O00327
Q8K120
Q8K120
P41969
P15066
O54918
O54918
O54918
O54918
P28667
P28667
P28667
P54846
P05627
P05627
P05627
P05627
P27661
P41971
P41971
ENSMUSP00000043430
P46938
P46938
P46938
P84244
O89090
O89090
Q07279
Q8K4Q0
Q8K4Q0
Q8K4Q0
P20263
O35126
Q8R4E9
Q8R4E9
Q9WVI9
Q9WVI9
P40749
Q8R418
P28700
P28700
P28700
P28700
Q99KG5-2
P97875
P55821
P55821
Q498M6
P81067
P81067
D3ZUM2
Q61337
Q61337
Q61337
P22736
O43521
P11416
Q9WVH4
Q9JLN9
O70405
O43524
P46414
P46414
Q8BYJ6
Q8BYJ6
Q8BYJ6
Q8BYJ6
Q8BYJ6
Q8BYJ6
Q02248
Q01147
Q01147
P29351
P35569
P35569
P35569
P35569
P39689
O60343
O60343
Q5EG47
P30306
Q9WV60
P17679
P23804
Q9JI11
O88703
P31750
P70313
O88643
Q61188
P48679
Q9R1E0
Q9R1E0
Q9R1E0
O35280
O35099
P20749
Q2NL51
Q96B36
Q60760
Q0VGT2
P47809
Q99N57
Q60700
Q60700
Q8CFH6
O35491
O35491
Q9R210
P62509
P97303
Q9Z120
Q9WVH3
Q9WVH3
Q9WVH3
P15331
P15806-2
Q9Z2B5
P67778
Q60949
Q60949
Q60949
Q60949
Q60949
Q60949
Q9Z1T6
Q9Z1T6
Q9Z1T6
Q9CZU6
P62908
Q9JIX8
Q91V92
Q5SNZ0
Q60680
Q8BZ21
Q9QYG0
Q9QYG0
Q9QYG0
Q641K5
Q9ET54
Q61409
P35821
Q9QYK7
O54781
Q9JI10
Q9JI10
P23950
P23950
P23950
Q61037
Q61037
P62960
Q61483
Q61823
Q61823
A3KGS3
A3KGS3
Q60989
Q8CEG0
P84244
F1MAL5
O70439
P62754
O55187
O55187
Q8BMH6
Q8BMH6
Q8BMH6
Q8BMH6
Q8BMH6
Q8BMH6
O88712
P61014
Q80XI6
Q9WVH5
Q9WVH5
B9EKA3
Q07813
P41241
O89017
Q61337
Q00960
Q62627
Q62627
P0DP23
P0DP23
P0DP23
P0DP23
P07221
P05455
Q96IZ0
P32851
P18422
P18422
Q62881
Q63692
P67999
P02340
P11497
O95644
P17096
P17096
P17325
P17325
Q64350
Q64350
P07936
P07936
P07936
P07936
P07936
P07936
P35659
P35659
P35659
P35659
P35659
P35659
P35659
Q4QRB4
P0DP29
P0DP29
P0DP29
P15884
P15884
P15884
NP_001093990
NP_001093990
P00860
Q07205
Q07205
Q07205
Q9H2G2
Q9H2G2
Q01714
P01252
P01252
P01252
P14925
P14925
P18146
P18146
P18146
P18146
P18146
P67999-2
P32198
P32198
Q05695
P21707
P12637
P12637
P12637
P52164
P52164
P41035
P41035
P31232
P02641
Q80ZG1
Q80ZG1
Q61337
Q04207
Q04207
Q9WVH4
Q60855
Q60855
P35569
O35426
O35426
O88522
O88522
O88522
O88522
O88522
O88522
O88522
O88522
O09044
O09044
Q9Z1E3
Q9Z1E3
Q9R0T8
O88351
O88351
O88351
O88351
O88351
O88351
O88351
O88351
P62908
P25799
P25799
Q9WUN2
P56477
P56477
Q9QY36
Q9WVE8
Q07174
Q61337
Q61337
P08670
P08670
P08670
P08670
P08670
O15143
O88643
P42230
Q99N57
Q99N57
Q9CQ19
Q91VC7
P63168
P19785
Q8BTM8
Q6P5G0
Q61532
Q9D0F9
Q8K2Q9
Q9D1E6
Q9D1E6
Q61337
P01108
P01108
P01108
P00520
P00520
Q99N57
Q99N57
P05627
P05627
P05627
P05627
P05627
O08605
O08605
Q6P5G0
Q61532
Q61337
Q61337
Q60875
Q60875
P37238
Q3THE2
Q8BTW9
Q61337
Q99N57
Q61337
Q61337
P46414
P39689
O35099
P97762
P97762
Q61982
Q61337
P01108
P39689
Q61982
Q61337
Q61337
Q61337
Q61337
Q61337
Q61337
Q61337
Q61982
Q61337
Q02750
Q02750
Q9DBR7
Q99N57
P50752
Q61337
Q61337
Q61337
Q63932
Q63932
P31938
P31938
P38936
P13834
Q96KQ7
P84243
P24385
Q9Z2V6
Q02363
Q9Y463
Q9Y463
Q9Y463
P20823
O75533
Q99801
Q99801
Q52LA3
P38936
Q9UER7
Q9UER7
P45983
P45983
O15530
O15530
Q15691
Q15691
Q15691
Q16539
Q16539
Q99683
Q99683
Q99683
Q99683
P52564
P45985
P46734
Q9Y3F4
Q9Y3F4
Q969S3
Q969S3
Q5VWQ8
Q8IUQ4
Q8IUQ4
Q8IUQ4
Q8IUQ4
P38936
O95863
P46937
P46937
P46937
P46937
P46937
Q9NRM7
Q9NQS7
Q8NHZ8
P46937-2
P46937-2
P46937-2
P46937-2
P46937-2
Q02241
Q02241
Q8N122
P00519-2
Q4VCS5
Q9GZV5
Q9GZV5
Q9EPK5
Q9Y2J4
P61981
P11908
P60891
P46938
P46938
Q8VHG2
O60828
P38936
Q15796
P02340
Q9Z2A0
P30306
P30306
O15530
O35099
Q13485
P84022
P10599
O15105
Q9Z1Z2
P38936
O70405
P02340
P42227
P04150
P42225
Q6P9Z1
P30306
P30306
Q8CFN5
Q8CFN5
P15336
P15336
P28033
Q04211
P16951
P16951
P31750
P31750
P47811
P47811
Q92993
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
Q9R1E0
P06876
Q99J83
Q06986
Q06986
Q8VI67
Q8VI67
Q8C050
Q8C050
P70396
P70396
Q8K120
Q8K120
O35426
O35426
Q92993-2
Q08874-8
P23927
P23772
Q9Z0V2
P16054
Q60591
P42228
P49138
P49138
P49138
P35639
P35639
P84244
O88420
P11679
P11679
Q8N5C8
Q8N5C8
P53668
Q9Z2B9
Q9Z2B9
Q68FE6
E9Q616
E9Q616
E9Q616
P70333
O35737
O54992
Q8R331
Q3UMW7
Q3UMW7
Q3UMW7
Q91X58
Q91X58
Q91X58
Q9WVS6
Q8R205
P18911-2
P18911-2
O55022
Q9Z1Q5
Q9CQF4
Q9CQF4
Q8C1D8
Q8C1D8
O08709
Q99460
Q9ERU9
P15375
P15375
P16460
P56402
P15806
P20029
P01108
Q9ERR1
P42227
Q06986
Q06986
Q06986
Q06986
Q0VGT2
Q0VGT2
Q62188
Q8CHW4
Q9Z1E4
Q9WV86
O70372
P02548
P10636-8
P00257
Q6J4I0
Q6J4I0
P11473
P00515
P00515
P07516
P07516
P07516
P0DP29
P0DP29
P0DP29
P0DP29
P48018
Q01815
Q02294
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
Q14194
Q14194
Q9ERR1
Q9ERR1
Q9ERR1
Q9ERR1
Q9ERR1
P46414
P46414
P02340
P02340
Q02248
P42227
P54227
P20152
Q6R891
P10637
P10637
P10637
Q8CFN5
P24529
P10417
P35465
P97318
Q80YE4-2
O35927
O35927
O70161
Q63604
P26040
O88643
O88809
O88809
O88809
O88809
O88809
O88809
O88809
O35625
P28352
P23242
P23242
Q15078
Q15078
P14416
P97318-2
P97318-2
P97318-2
P97318-2
P97318-2
P97318-2
P97318-2
P97318-2
P97318-2
P19103
O70589
O70589
Q9JK48
Q3U7R1
Q61235
Q60829
Q8BR65
Q04735
Q8C0T5
Q99KH8
Q9ERT9
P70392
Q3UHL1
Q01097
P61809
P61809
P31938
Q8VI36
P15209
O08599
P53349
P12023
O08785
O08785
P34152
P42859
P42859
Q03717
Q03717
Q9WV30
Q6PF93
Q9WUD1
Q8VDV3
Q8VDV3
F6SEU4
F6SEU4
F6SEU4
F6SEU4
F6SEU4
Q8R527
Q99NH3
Q99NH3
P97318-3
P49653
Q13319
Q13319
Q13319
XP_001480843
O89053
P27671
Q61171
Q6P5H2
P97317
P29995
Q14654
P63329
Q92736
Q92736
P26678
P26678
E9Q401
Q16625
Q8WZ42
Q8WZ42
Q8WZ42
Q8WZ42
Q8WZ42
P51787
P51787
Q9UK17
Q08289-2
P56524
P13688-8
P13688-8
Q14524
Q14524
O15084
P61014
Q08289
Q13557
Q13557
P55327
P61012
P61012
P61012
O77506
O77506
P61012
Q3UMR5
Q3UMR5
O88935
O88935
Q66JT0
Q62048
Q923E4
Q923E4
Q01147
Q01147
P20152
P20152
P24529
P28033
Q60867
Q62432
Q9Z2D6
P61014
Q8VHH7
Q9WV31
Q02789
O35671
Q91YE8
Q9Z0F7
P11799
P11799
P11799
P11799
P11799
P11799
P11799
P48787
P48787
P48787
P24844
Q64122
Q64122
Q9CQ19
Q9CQ19
P19105
P19105
P48616
Q5E9F8
Q5E9F8
P84227
P84227
P68432
P68432
P67939
P67939
P67939
Q6J1J1
O62654
O62654
O62654
Q28115
Q28115
Q28115
A5PJU9
A5PJU9
A5PJU9
P48616
P48616
Q28021
Q5E9E2
Q5E9E2
O02675
Q2HJ38
Q2HJ38
Q2HJ38
Q2HJ38
Q2HJ38
P31976
Q2HJ49
Q32LP2
P08050
P14921
P01106
Q02078
Q02078
Q02078
P29590
P29590
Q63943
O00141
Q13164
Q13164
Q13164
Q13164
Q13164
Q13164
Q13164
Q13164
Q13164
Q14934
Q14934
Q12959
Q06413
Q06413
Q06413-3
Q8K120
Q8K120
P01100
P01100
Q14814
P70595
P70595
Q13163
Q13163
Q13163
Q13163
B5B2W9
B5B2W9
Q5TCN4
P08050
P08050
P08050
P15304
Q62622
P01106
P04177
P13668
P13668
P15146-3
P06685
P08955
P21818
P21818
Q9EPI6
P08047
P08047
P09951
P09951
P09951
P52909
Q03555
P42702
Q62132-2
P12841
P12841
P12841
P12841
O35254
P24898
P17325
F1LW91
P35565
A4GTP4
P15146-2
P15146
P15146
P15146
Q15418
P84022
P21708
Q01196
Q01196
P0CE43
P0CE43
Q62736
Q01714
Q01714
Q62985
Q8R5I7
Q8R5I7
Q8R5I7
Q8R5I7
Q5FVC2
P27049
Q64623
Q64623
O70521
P37091
Q9WUD2
Q9WUD2
Q9WUD2
Q9WUD2
P37090
G3V7D4-1
P25977
P25977
Q64346
A0A0G2K2P5
NP_001099736
P49950
D3Z937
G3V727
P36506
P08050
P08050
P08050
P15304
Q62622
Q62622
Q62622
Q62622
Q62622
P01106
P70673
P70673
P04177
P04177
P55211
O35274
O35274
P13668
P13668
P21818
P21818
P08047
P08047
O88498
P09951
P09951
P09951
P52909
P42702
P46152
Q62132-2
P12841
P12841
P12841
P12841
O35254
P35465
P21272
Q01986
Q01986
Q01986
P06536
P06536
A4GTP4
A4GTP4
A4GTP4
A4GTP4
A4GTP4
A4GTP4
A4GTP4
A4GTP4
A4GTP4
P20749
Q15418
P84022
Q63155
Q63155
Q63155
P63086
P63086
P63086
O35244
P63085
Q01196
Q01196
P14270-6
Q32Q86
P0CE43
P0CE43
P62909
P11345
P11345
P11345
P11345
P11345
Q78PB6
Q78PB6
Q5I6B8
Q63449
Q63449
P84025
P84025
P84025
Q9ESI7
Q9ESI7
Q9ESI7
Q9ESI7
Q01714
Q01714
Q923I8
Q923I8
Q62985
Q9Z1P3
Q8R5I7
Q8R5I7
Q8R5I7
Q8R5I7
P35234
P35234
O88368
Q5FVC2
P27049
Q64623
Q64623
Q91V33
Q8VIJ4
O70521
P47973
Q8CJ75
P37091
Q9WUD2
Q9WUD2
Q9WUD2
Q9WUD2
P37090
G3V7D4-1
Q63053
Q63053
Q63053
P25977
P25977
Q64346
P56745
O88275
Q62767
Q62767
F1M3L7
F1M3L7

Q62986
Q62986
P41156
Q9R064
P55094
P55094
P55094
P50393
P08050
Q06226
Q2MJT0
Q2MJT0
Q2MJT0
A0A096MJY4
P08050
P08050
P08050
P08050
Q03114
Q5XIS9
P08050
P11388
P08050
P08050
O35433
O35433
P05783
Q10758
Q10758
P23693
P23693
Q62968
P52631
Q99JE6
Q9DAS9
P25122
P11679
P11679
P08050
P19493
P35439
P25122
P49620
P49620
P08050
P08050
P08050
P08050
Q66H76
Q66H76
Q9WUD9
O43294
Q1AAU6
P70600
Q62689
Q62689
Q99PD6
Q15796
Q15796
Q15796
Q15797
Q15797
Q15797
Q15796
Q15796
Q15796
Q96FW1
P17813
P17813
P68104
P84022
P84022
P84022
Q03167
Q9H3D4-2
Q9H3D4-2
Q15796
Q15796
Q15796
Q15796
P17599
P17599
P17599
P05412
P05412
P05412
P05412
P05412
P01106
P01106
P01106
P04049
P04049
Q13177
Q13177
Q13177
Q13177
P24844
P29294
P29294
P35240
Q05682
Q05682
P49023
P49023
Q16659
Q04637
P00519
P00519
Q70Z35
P62805
P62805
Q5XI73
Q5XI73
P55210
P55210
P55210
O08605
O08605
P31152
P01236
Q99523
Q8IYU2
Q53QZ3
Q53QZ3
Q53QZ3
Q53QZ3
Q15796
Q13153
Q13621
Q13621
Q13621
Q13621
Q13621
P55011
P55011
P55011
P55011
P55011
P55017
P55017
P55017
P55017
P35465
P84022
P15036
P15036
P33535
P33535
P11275
P11275
P11275
P11275
P11275
P11275
P31016
O88935
P07101-4
P07101-4
Q62696
Q62696
P23385
P07101
P07101
Q8CBW3
P19490
P19490
P15337
P15337
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
B0LPN4
B0LPN4
Q00960
P07101-3
P07101-3
P29476
P17599
P17599
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P62198
P00533
P00533
P00533
P00533
P00533
P04626
P04177
P04177
P07101-2
P07101-2
P20152
P20152
P50571
P50571
Q8VGC3
O35274
O35274
P13668
P10636-2
P10636-2
P22002
P17676
Q8IWU9
Q9HC16
P09951
P09951
P22723
P22723
P22723
P19332
P08592
P47712
Q62897
Q28204
P12979
P49757
P10636-6
P10636-6
P10636-6
P10636-6
P10636-5
P10636-5
P10636-5
P10636-5
P63044
P0C279
P97836
P97836
P97836
P21707
Q9JLU4
Q9JLU4
Q9JLU4
Q9JLU4
Q925N3
Q8K1M6
Q3MUI2
P08413
P08413
P08413
P35213
P35213
P97924
P13234
P13234
P13234
P13234
P97838
P55926
P55926
Q63273
Q63273
Q63273
P70587
P70587
P97837
P63080
Q64289
Q9WV48
A1L1I3
P11275
P11275
P11275
Q00566
P18297
P18297
P18297
Q62696
Q62696
P15337
P15337
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
P04177
P18266
O35274
O35274
O35274
P54645
P18265
P09951
P09951
P97836
P97836
P97836
Q9JLU4
Q9JLU4
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P08413
P97838
P70587
P70587
P70587
P97837
Q64289
Q9WV48
Q62623
Q14654
Q14654
P16949
P16949
O75582
P29590
P29590
P29590
P29590
O75676
O75676
P04049
P04049
P04049
P04049
P04049
P28562
P28562
P19419
P19419
P19419
P19419
P19419
P19419
P19419
P19419
O60331
Q86UC2
Q13322
P01100
P01100
P01100
P01100
P46695
P46695
P35398
Q07666
Q8IZQ8
Q8IZQ8
Q8IZQ8
Q8IZQ8
P26651
P78543
P43146
P43146
P43146
P13056
O60504
P31016
P15337
P01106
O08679
Q9R1U5
Q9R1U5
Q66H76
Q03555
P21272
P21272
P21272
P21272
P17325
P17325
P17325
Q6IN33
Q8K3Y6
Q8K3Y6
Q8K3Y6
Q8K3Y6
P14873
P14873
P47942
P47942
Q64350
P16884
Q9WU82
Q9WU82
Q9WU82
Q9WU82
Q9WU82
Q9WU82
P56558
P56558
A2RRU1
Q63503
Q63503
Q9WVS9
Q9ESI7
Q923I8
Q05764
Q05764
P17625
P17625
P17625
P17625
Q9Z1P3
O70239
O70239
Q9EPW1
Q9EPW1
O35800
O35800
O35800
P24062
Q8R5I7
Q8R5I7
Q8R5I7
Q8R5I7
Q8R5I7
Q8R5I7
Q8R5I7
Q8R5I7
Q63369
Q63504
O08678
P12957
P12957
P12957
P12957
P12957
O14950
O14950
P24844
P24844
O14974
P10916
P18666
P12957
P12957
P12957
P12957
P12957
P12957
P12957
P31395
P02542
P02542
P02542
E1C2I2
P11799-2
P12957
P12957
Q60598
Q60598
Q60598
Q01986
Q99N57
Q99N57
P31938
Q64331
Q63648
Q6P5G0
Q61532
P97477
P59241
Q99J21
P46662
O88935
P05132
P18654
P18654
P18654
P18654
Q9Z2A0
Q9Z2A0
Q9Z2A0
P10637
P10637
P10637
P10637
Q9NRA0
Q9NRA0
P31750
O88643
Q05513
Q8BSK8
P16054
Q02956
P20444
O88351
P68404
P63318
Q02111
Q9WUA6
P18653
Q9WVC6
P23298
Q60823
P12367
Q9WUT3
P70268
Q8BWW9
Q9QZS5
Q9ERE3
O88935
O88935
O08553
P23242
P28652
P61979
P31044
P63318
P63318
P28741
Q62696
Q62696
Q62696
Q62696
Q62696
Q62696
Q12959
Q12959
Q12959
Q91Y80
Q91Y80
Q13424
Q13424
O88420
Q499N6
Q62696
Q62696
Q62696
Q62696
Q62696
Q62696
Q62101
Q62101
Q62101
Q12959
Q12959
Q12959
O08796
O15273
O70548
P16949
P46527
Q9Y6Q9
Q9Y6Q9
P02686
Q15637
Q15637
Q9BSJ6
P17600
P19021
P16949
P46414
P97467
P04370
Q8BFY7
P15304
P04775
Q92915
P13834
P13834
P13834
P13834
P40337
P18266
P15314
P15304
P04775
Q92915
P13834
P13834
P13834
P13834
P40337
P18266
P10830
P81436
P81436
P15314
P14921
P46527
P46527
P46527
P09917
P09917
P09917
Q16543
Q16543
Q05397
Q05397
P11802
P04626
Q969T9
Q969T9
Q16555
P22681
P22681
P22681
Q9R0Z9
Q9R0Z9
P07355
Q16236
P07947
O60500
O15524
P07101
P09917
Q00613
P30305
O00418
P04792
P04792
P04792
O95816
P49137
P33241
P49815
Q9Y496
Q9JKV2
Q8N122
P46379
Q9UPZ9
P46527
O43663
P46459
P10644
Q8ND76
P46460
P46527
P46414
P22681
P22681
Q05086-2
Q62101
Q62120
Q62120
O15162
O15162
Q60598
P97465
P10085
P10085
O88809
O88809
P36895
P36895
P36895
P36895
Q921Q7
Q64010
Q8BH43
Q9JKD8
Q9JKD8
Q9JKD8
Q8C3Q9
Q4JIM5
P00520
P00520
P05067-4
Q8WYQ5
P28867
P49817
Q61140
Q9QXJ1
P05622
P05622
P05622
Q4VAA2
Q70E73
Q70E73
Q70E73
Q70E73
Q8BK64
Q9JJ00
P58196
P58196
O35704
P12023
Q9EQ32
Q9EQ32
Q9EQ32
Q9EQ32
Q9EQ32
P22682
Q8BZ03
Q8BZ03
Q6PDN3
Q6PDN3
Q6PDN3
Q6PDN3
Q6PDN3
Q6PDN3
Q9JJP2
Q8BFP9
P97814
Q9Z2U0
P68040
Q08297
P43352
Q62417
Q62417
Q62417
Q9D0I4
O08759
Q8VHI6
Q8VHI6
Q8VHI6
Q8VHI6
P46938
Q07E38
P49615
Q03173-3
P20192
G5E867
P43404
Q61258
F2Z3U3
Q9WVI9
Q3TF18
P46527
P46414
P48025
P48025
P48025
P48025
P31995
P12318
P42229
P29351
P29351
Q9EPK8
Q60598
P14753
P14753
Q99N57
P67778
P67778
P28867
P28867
P28867
P28867
P28867
P35991
Q99N69
Q9QVP9
Q9QVP9
P25911
P25911
Q3U1F9
Q3U1F9
Q3U1F9
Q9JM80
Q9JM80
Q9JM80
P24604
Q9EQR5
Q9EQR5
P21855
P21855
Q9QZE2
Q9QZE2
P97484
P97484
Q3UU41
Q18PI6
O70469
O70469
O70469
P20491
P20491
P63330
Q8VDZ4
P11831
P26678
Q9BXL7
Q9BXL7
Q13094
Q16584
Q9QUN3
Q92918
Q02779
Q5TCX8
O89100
Q13200
Q60787
O35433
P29476
P61810
P61810
Q6J4I0
P15387
P15387
P15387
P15387
P04177
P12928-2
P27732
O35274
P15146-3
P21818
Q66H76
P09951
Q03555
P21575
P21575
O35346
Q9WUD9
Q01986
P62138
D3ZGB1
O89038
P08592
Q9WU82
Q9UM11
Q9UM11
Q9UM11
P15146-2
P15146
Q9JJM9
Q9JJM9
Q5FWU0
P19103
Q8JZP2
Q04735
P51111
P51111
Q70AM4
Q8CJH2
O35412
P05067-4
P10361
O70420
O70420
P61765
P61765
Q2MJT0
Q62910-5
Q63686
Q5I6B8
P43138
Q9WVS9
Q9WVS9
Q9ESI7
Q9ESI7
Q9ESI7
Q9ESI7
Q9Z1X1
A0A096MJY4
Q99JE4
Q6AYE2
Q62799
Q62799
Q00959
P21263-2
P21263-2
Q62910
P06494
F1MAB8
P49187
Q07266
P40645
P08592-2
P97924-6
Q66HL2
Q66HL2
P84092
P19490
P18266
Q99JE6
Q99JE6
Q9JKA9
Q64595
Q64595
Q64595
P19490
P17599
P17599
P17599
P04049
P23693
Q01986
Q64331
P11345
P11345
P27704
Q62829
Q62829
Q62829
P08670
P08670
P29678
P29678
P00536
P00536
O14713
Q00987
Q00987
P10275
Q13363
Q13363
P53667
P56545
Q9BY11
P23818
O88703
Q9Y6F6
Q9Y6F6
Q61410
Q61410
Q61410
Q61410
Q61410
Q61410
Q61410
Q61410
P23818
P23818
Q8BYI6
G0YZM8
G0YZM8
G0YZM8
Q9UKG1
O70439
Q9Z239
Q91V14-2
E0CZ16
P31645
O14974
O14974
P55087
Q03393
P81274
P81274
P81274
Q15637
Q5VSY0
P42262
P21817
Q99K10
P11362
P11362
P11362
P11362
P11362
P11362
Q8R173
P22607
Q8BFP9
Q8BFP9
Q8BFP9
Q8K371
Q8C180
Q8C180
Q8C180
Q8C180
Q8C180
Q8C180
Q99K10
Q92529-2
Q92529-2
Q92529-2
Q92529-2
Q92529-2
Q92529-2
P22001
P22001
P22001
P22001
Q16620
Q16620
Q16620
Q16620
Q16620
Q13009
Q99K10
O08553
P24844
P35569
P35569
P20152
P20152
P26040
P23528
P70336
Q9DBR7
Q9DBR7
Q9DAW9
Q9DAW9
P26041
P26043
Q64287
Q64287
Q9QYC0
Q9QYC0
Q9QYC0
Q9CQ19
Q9CQ19
Q3THE2
Q08091
Q08091
Q08091
Q08091
Q08091
O88307
Q3UMT1
P15337
P62755
P62755
G3V7R4
Q09167
P16638
Q63085
P17431
Q9R0W1
P15337
P15337
P15146-3
Q66H76
Q62952
P47942
P47942
Q64350
P15146-2
P15146
P15146
P15146
Q07869
A2RRU1
P16638
P16638
P11845
P17625
P17625
P17625
P17625
Q9Z1P3
P15337
Q01147
Q01147
Q8K1M6
Q00560
P0DP26
P0DP27
P0DP28
Q6NZM9
Q6NZM9
Q6NZM9
Q8R081
P15337
P29476
P62161
Q3LRT3
P21818
P49757
P0DP29
Q3MUI2
P13234
P13234
P13234
P13234
P13234
P0DP30
P0DP31
Q99P99
Q99P99
F1LQ48
P19754
P19754
A1L1I3
P15337
P35560
G3V7R4
G3V7R4
G3V7R4
P46933
A4GTP4
A4GTP4
P63086
P47809
ENSRNOP00000013522
ENSRNOP00000013522
P19357
P26433
Q6JE36
Q6JE36
NP_001102772
NP_001102772
NP_001102772
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
Q9QUH6
P28818
P28818
P28818
P28818
P28818
P28818
P13084
O35412
O35412
P37377
P34058
F1M386
F1M386
F1M386
F1M386
F1M386
B0LPN4
B0LPN4
Q8VGC3
P54283
P09951
Q14524
Q14524
Q62897
P61016
Q8VGC3-2
P15791
Q00960

P32851
P62755
Q64122
Q91XJ1
O88764
O88764
O88764
O88764
O88764
P04692
Q00960
P31000
Q64122
P10361
P10361
P10361
Q6LED0
P84245
Q9JHY7
Q6AXW0
Q569C1
P48675
P48675
P48675
P47819
P47819
Q62909
Q5EB96
Q5EB96
Q5EB96
B2DD29
O08679
Q9R1U5
P54645
Q09137
O08678
Q8VHF0
D3ZML2
Q63553
Q7TNZ6
P29476
P29172
P29172
P29172
P29172
P29172
P29172
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636
P10636
P10636
P10636
P10636
P10636
P10636
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
P17599
P17599
Q28204
P27925
P17599
P17599
P17599
Q10728
P21818
P09951
P09951
P35465
P35465
P35465
P35465
P35465
Q01986
Q64122
O35147
A0MZ67
A0MZ67
Q62925
P11345
P11345
Q63648
Q9WTQ1
Q8IYU2
P53669
P27704
P38652
P17599
P02687
P14925
P02688
P17599
P27925
Q2KIA5
Q08DA8
Q66JT0
Q62048
Q923E4
Q01147
P20152
P20152
Q9Z2D6
P28652
P09917
P09917
P09917
P14317
P14317
P68400
Q05397
Q05397
Q05397
Q9UHD2
Q9UHD2
Q9Y6K9
Q920L2
Q920L2
Q9ER34
Q9ER34
Q9ER34
O43353
Q16236
P09769
P09917
P09917
P09917
P42768
O15350
P42684
P42684
P42684
P42684
P42684
P42684
P42684
Q9UHD2
Q9UHD2
P42229
Q92556
Q92556
Q92556
Q92556
Q92556
P51692
Q13905
P00519-2
P00519-2
P00519
P00519
P00519
P00519
P00519
P00519
P00519
P00519
P00519
P11274
Q13444
Q13444
Q4JIM5
P08631
P08631
P08631
P00520
Q8TDY6
Q5T7K2
Q5T7K2
Q96C78
Q96C78
P37840
P08238
Q9HC77
Q9HC77
P53350
O15350
Q9Y4G8
Q9Y4G8
Q9Y4G8
Q9Y4G8
Q16143
Q13972
Q13972
Q13972
Q13972
Q9Z0F8
Q969H0
Q969H0
Q969H0
P06748
P62258
O43852
O43852
O43852
Q8WTW5
O43166
O43166
Q96PV0
Q96PV0
Q96PV0
Q96PV0
Q96PV0
Q96PV0
Q96PV0
P37840
Q61937
Q8C0T5
Q8C0T5
O55042
F6SEU4
F6SEU4
F6SEU4
F6SEU4
F6SEU4
F6SEU4
F6SEU4
P27671
P27671
P27671
P27671
Q569L8
Q569L8
P11499
Q8CHG7
Q8CHG7
Q8CHG7
Q8CHG7
Q8CHG7
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636
P27816
P27816
Q13470
P11137
Q8WUI4
Q155Q3-2
Q99689
Q155Q3
O88809
O43602
O43602
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
Q5CZI7
P10636-8
P10636-8
P10636-8
P10636-8
P10636-2
P10636-2
P10636-6
P10636-6
P10636-6
P10636-6
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-5
P10636-8
P10636-8
Q923E4
P13834
P42227
Q9WV60
P49768
Q8C3Q9
O08599
Q9R194
Q3TWW8
Q61214
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
P10636-8
F1LSG0
F1LSG0
F1LSG0
P84243
P21575
P21575
P21575
P84245
O08816
O08816
O08816
Q923I8
Q63470
Q63470
Q63470
Q63470
Q63470
P10636-8
P10636-8
P10636-8
P10636-8
P19332
P15146
Q9ESI7
Q9ESI7
Q5M7W5
P10636-8
P10636-8
P10636-8
P10636-8
O08679
O08679
O08679
P19332
Q3LRZ1
Q3LRZ1
P10636-8
P13834
P02641
P02641
P02641
P00518
P18688
P18688
P18688
P00489
P10636-8
P10636-8
O00139
Q7L0J3
Q7L0J3
Q7L0J3
Q7L0J3
Q7L0J3
Q7L0J3
Q9Y592
Q13153
P46531
P46531
P46531
O00303
O00303
Q13153
P30291
Q13131
P10636
P10636
P49815
Q00536
P52565
Q5CZI7
Q13153
Q13153
Q13526
Q13131
P08151
P08151
Q16584
Q16584
P45985
P45985
P46734
P46734
P28740-1
P47809
P47809
Q13153
Q13131
Q8BRK8
Q5EG47
Q5EG47
P54645
P54645
P54645
Q60670
O88643
Q9WTK7
Q9WTK7
Q641K5
Q09137
Q09137
Q09137
Q69Z98
Q8VHJ5
Q05512
Q03141
Q8CIP4
Q8VDU5
Q3UUJ4
Q5RJI5
P60484
P38398
P01101
O75582
Q02078
P30305
P30305
P30307
O43255
P78543
P56178
P56178
Q16644
Q16644
Q16644
P41236
O75581
P37802
P37802
Q8ND76
Q8ND76
Q8ND76
Q8ND76
Q8ND76
Q8ND76
Q8ND76
Q8ND76
P41236
P30307
P10636
Q92974
Q13470
Q06413
Q8WUI4
Q99689
Q3U182
P27448-3
P27448-3
P27448-3
P27448-3
Q6VAB6
P26432
O54943
P35569
P35569
P42866
P42866
P42866
P42866
P32300
P33534
P33534
P18762
P18762
P09174
P56726
P56726
P56726
P56726
P56726
P56726
P56726
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
O54943
Q02248
Q02248
P23804
P23804
P23804
Q8BZ03
Q91ZD4
Q91ZD4
Q91ZD4
P13864
O54943
O35973
O35973
O35973
O35973
O35973
O35973
Q60829
Q8BZ03
Q91ZP3
Q91ZP3
P13864
Q16625
P03372
P03372
P03372
P05412
P05412
P18846
P46531
P46531
P46531
Q03112
P06400
P06400
Q14934
Q5TKA1
P21272
Q12800
Q8TDN4
P03372
Q66K74
P03372
Q08345
Q08345
Q62627
Q62627
Q10728
Q64122
P18666
P18666
P84245
P52631
F1LSG0
F1LSG0
P42768
P31749
P10275
P10275
P10275
Q07912
Q9Y4C1
Q9NZC7
P62805
O00401
O00401
Q9NRF5
O08816
O08816
P42768
Q6PAJ1
P00520
P28867
P28867
P08103
P08103
Q9JJP2
O88839
O88839
Q8BPU7
Q8BPU7
Q8BPU7
Q8BPU7
Q8BPU7
P08103-2
P08103-2
Q03267
Q03267
Q06187
P42230
P35991
P35991
P35991
P35991
Q9ESZ8
Q9ESZ8
Q9ESZ8
Q8CIH5
Q8CIH5
Q8CIH5
Q63953
Q03267
Q03267
P48025
P48025
P48025
P48025
P48025
P48025
P48025
P48025
P48025
P48025
Q9EPB4
Q9QUN3
Q9QUN3
Q9QUN3
Q9QUN3
Q9QUN3
Q62077
Q62077
P35991
P68369
P20444
ENSMUSP00000098874
ENSMUSP00000098874
ENSMUSP00000098874
Q9EQ32
Q9EQ32
Q9EQ32
P22682
P49710
P49710
P70218
P68404
P63318
Q06649
Q06649
Q06649
Q6A028
Q9D2Z1
Q9D2Z1
Q3UD40
Q3UD40
Q3UD40
P45984
P45984
P45984
Q13158
Q9WTU6
Q9WTU6
P53779-2
P45983
P45983
P45983-2
P53779
O15264
O15264
Q15711
P45984
Q15759
Q15759
P19793
Q9WTU6
Q9WTU6
P53779-2
P45983
P45983
P45983-2
P53779
Q16539
Q16539
P45985
P45985
P53778
P45983-3
P45983-3
P45983-3
P45983-3
P45983-3
O15264
O15264
Q15711
P45984
P31749
P28482
P27986
Q05397
Q05397
Q05397
Q05397
P19174
Q15759
P07949
P07949
P07949
P07949
P07949
P07949
P07949
P07949
P07949
P07949
P07949
P07949
P27361
P45983
O15530
Q16539
Q99704
P18848
P18848
P18848
P18848
Q8N4X5
P05412
P05412
P25963
P25963
Q8TD08
Q8TD08
Q8TD08
Q8TD08
Q8TD08
Q8TD08
Q8TD08
Q8TD08
Q96FW1
P17813
P17813
P68104
P84022
P84022
P84022
Q03167
Q9H3D4-2
Q9H3D4-2
P06127
P06127
P11473
P04177
P15127
P15336
P15336
P68363
P11167
P30009
P30009
Q99JE6
Q9DAS9
P15431
P31044
P25122
Q9WV87
P68403
P68403
P68403
P68403
P68403
P68403
P68403
P33724
Q6QNF3
Q6QNF3
Q6QNF3
Q8C863
Q8C863
Q9WV60
Q9JJ28
Q9UER7
Q8BRK8
Q13546
Q13263
Q5EG47
Q8NB16
Q8NB16
Q8NB16
Q9QZL0
Q9QZL0
Q9D2Y4
Q9D2Y4
Q9D2Y4
Q9Y572
Q9Y572
Q9Y572
P09622
Q9UER7
Q13158
P47863
Q10728
Q10728
P29994
P29994
P19491
Q9WU34
Q5XIG5
D4A4T0
P25963
P25963
O14920
O14920
Q01147
Q01147
Q01147
Q01147
P61160
P61160
P61160
P11413
P11413
P11413
P11413
Q00653
Q00653
O35763
O15111
O15111
P31977
Q96SB4
Q96SB4
Q96SB4
Q96SB4
Q07955
Q07955
Q07955
Q07955
Q07955
Q07955
Q07955
Q07955
Q07955
Q07955
Q07955
Q07955
G1N806
G1N806
G1N806
G1N806
Q9BWF3
Q9Y5S9
Q9Y5S9
Q96EB6
P16220
Q923E4
Q9Y6Q9
P84243
Q96B36
Q96EB6
Q96EB6
P31749
Q13131
P54645
Q16566
Q9Z0W5
Q8IU85
Q14012
Q96RR4
P54646
O88831
P11388
P11388
P49736
P49736
P49736
P49736
P49736
P49736
P49736
P49736
P49736
P49736
P49736
Q96GD4
Q9HAW4
Q9HAW4
Q9HAW4
Q9HAW4
Q9HAW4
Q9HAW4
Q9HAW4
Q9HAW4
Q9HAW4
P19338
P19338
P06748
P06748
O00311
O00311
O00311
O00311
O00311
O00311
O00311
P55081
Q9UBU7
Q9UBU7
Q9UBU7
O75475
Q9NS91
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
Q8TEA8
P11388
P11388
P11388
P11388
P11388
P24928
P24928
Q13177
Q13177
P16220
P16220
Q13541
P06493
P53350
P53350
Q14653
Q14653
Q14653
Q14653
Q14653
Q02750
Q02750
P35241
P15311
P26038
O14757
P36507
P36507
Q04637
P06748
P00519
P52564
P46734
Q15418
P33778
P51432
Q07174
Q07174
P16220
P16220
P11499
Q5BJF6
P16220
P16220
Q923E4
Q922Y0
Q00987
P02340
P18654
P14602
P14602
Q9CQT2
P22893
P22893
P22893
P22893
P22893
P22893
P22893
P22893
P22893
P22893
P22893
P22893
P22893
P22893
Q9D312
P19973
Q60855
Q60855
P28033
P35639
P35639
ENSMUSP00000007980
P38532
P23950
P23950
P23950
P34931
P05784
P53668
Q8VDG3
Q9CX86
Q571K4
Q9JJZ4
Q8CD28
P54274
P52732
P23443
Q15058
Q15058
Q15058
Q15058
Q15058
Q61006
O14950
O14950
P24844
P24844
Q64122
Q64122
P10070
O14950
O14950
Q6LED0
O14950
Q80YE7
Q01097
Q9CQ19
Q3THE2
Q3THE2
O54784
O54784
O54784
O54784
O54784
P62754
P62754
O88597
Q9QUR7
O35526
P31749
Q8NB16
P31749
Q8IW41
P31152
P07900
P07900
P08238
O43432
P07900
P06493
P24941
P24941
P11308
P39951
P07900
Q62622
Q62622
P13834
P08238
P08238
P00515
P00515
P0DP29
P0DP29
P0DP29
P0DP29
Q07205
Q07205
Q07205
P27124
Q9GJP9
Q9GJP9
Q04206
O75581
P25054
P25054
P25054
P25054
P07948
P47823
P13834
P46531
Q13158
Q8NHW3
Q8NHW3
O14733
O14733
P31938
P30622
P00533
Q62622
Q62622
P17325
P47942
Q64350
P09416
Q9ESI7
P52631
Q8R4T2
Q8R4T2
Q8R4T2
Q8R4T2
Q6E0V2
Q673L6
P13569
P62136
P62139
P11216
Q923E4
P10417
P10417
P10417
Q8K120
Q8K120
P41969
P15066
P46938
P46938
P46938
O89090
O89090
Q07279
Q8K4Q0
Q8K4Q0
Q8K4Q0

P20263
O35126
Q8R4E9
Q8R4E9
Q9WVI9
Q9WVI9
P40749
P28482
P28482
P27361
P27361
Q9QX70
Q6PAJ1
Q08481
Q08481
P49710
P49710
P16879
P13834
P13834
P13834
P13834
P68105
Q28147
Q28147
P40337
P40337
P40337
P40337
P40337
P40337
P40337
O14777
Q9EPK5
P21796
Q92698
P48163
Q06609
P61586
P61586
Q14847
Q62120
Q62120
P00519
P00519
P00519
P11274
P11274
P11274
P11274
P43351
P46109
Q9Y6H1
P62993
Q4VAA2
O88572
Q8BGU5
Q8BGU5
Q8BGU5
Q8BGU5
Q8BGU5
Q8BGU5
O88572
Q9UBN7
P02340
Q60598
P12813
P00860
Q91ZP3
Q91ZP3
Q9CXW3
O88572
P42866
P33534
P33534
P33534
P33534
Q99L47
Q91ZZ3
Q8VEB1
Q8VEB1
P14317
P14317
P11274
P11274
P11274
P11274
P11274
P47942
P46459
P07332
P07332
Q08481
Q9UIB8
Q6GTU5
P14317
P68400
Q920L2
Q920L2
Q9ER34
Q9ER34
Q9ER34
Q6P6U0
Q6P6U0
P52631
P14317
P68400
Q64725
Q64725
O35346
O35346
P11598
P11598
P11598
Q07014
Q07014
P70600
P70600
Q9JM80
Q9JM80
C0HJX2
C0HJX2
C0HJX3
C0HJX3
P81718
P52946
Q02248
Q02248
P42227
Q01147
P63015
P63015
P63015
Q9QZR5
P17095
P17095
Q60953
Q60953
Q60953
P17095-1
P81269
P51608
P56546
Q03347
Q03347
Q03347
Q5F293
Q5F293
Q5F293
Q9Z2D6
P52946
P62754
P62754
Q9Z1E4
P10126
Q16543
P46937
Q7Z3C6
Q7Z3C6
Q13131
Q13131
Q64337
Q64337
O70405
O70405
Q8N122
Q8N122
Q8N122
Q8N122
Q8N122
Q14457
Q14457
Q14457
Q14457
Q14457
Q13501
Q8TEV9
Q8TEV9
Q8TEV9
Q8TEV9
Q86WV6
O60260
Q13546
Q13546
Q13546
Q13546
Q13546
Q13546
Q13546
Q13546
Q13546
Q13546
Q13546
P54645
P54645
P54645
P54645
P54645
O00560
O00560
P19367
P19367
P09467
P09467
Q9QZH4
Q9QZH4
Q9QZH4
Q9QZH4
Q15436
Q15436
O75143
O75143
P80385
P80385
P80385
P08237
P08237
P06733
P06733
J3KNL6
A2RUS2
A2RUS2
Q8NEB9
Q676U5
Q9Y6D9
Q9C0C7
Q9C0C7
Q13045
Q9Z1T6
Q9Z1T6
Q9Z1T6
Q9Z1T6
Q9Y4P1
Q8IVP5
P08235
O15027
P54619
P54619
P54619
O43741
Q8NFG4
Q8NFG4
Q8NFG4
Q8TDY2
Q8TDY2
Q8TDY2
Q9BSB4
Q9BSB4
Q15437
O60238
P58004
P58004
Q6ZNE5
P30305
P30305
O15530
Q15910
Q99683
P23588
P23588
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q14680
Q6RSS1
Q6RSS1
Q91VY9
P30305
P30307
P30291
Q13131
P10636
P10636
Q8TDC3-2
Q8TDC3-2
P19332
Q9NRH3
P23258
P23258
Q8K3M6
Q5CZI7
O95863
Q13621
Q13621
Q13621
Q9Y6R1
P55011
P55011
P55011
Q9H2X9
Q9H2X9
Q9Y666
Q9Y666
Q9UHW9
Q9UHW9
Q9UHW9
Q9UP95
Q9UP95
P55012
P55012
P55017
P55017
P55017
O15392
O96013
P09651
P09651
P09651
P09651
P23246
P23246
O43597
O43597
P06730
Q9NP80
P63073
P63073
P09651
P09651
P09651
P09651
Q15149
P23246
P23246
O43597
O43597
P06730
Q04207
O88522
O88522
Q9Z1E3
Q9Z1E3
Q9R0T8
Q04207
P68433
P68433
O35618
Q08297
Q80YR7
P48964
P48964
P48964
P48964
P48964
P48964
Q8C0Q4
O55047
Q04207
P46414
P46414
P46414
P46414
P46414
P45481
P45481
Q60855
Q60855
P35569
P51450-2
Q9Z1E3
Q9Z1E3
P84244
Q9CXV9
Q3UKC1
Q3UKC1
Q04207
Q8N7N6
P42225
P42225
P31750
P31750
Q9Z1E3
Q9Z1E3
Q9R0T8
O35207
P70671
P70434
P06493
P06493
P39951
P06493
P04049
P04049
P15387
P00523
P00523
Q14847
P12003
P23743
Q91YM2
O42254
Q00944
Q00944
Q00944
Q13507
Q13507
Q13507
Q13507
P49024
P49024
P49024
P05625
P05625
P17785
Q01406
Q01406
Q01406
Q01406
O73612
O73612
O73612
ENSGALP00000036444
ENSGALP00000036444
ENSGALP00000036444
ENSGALP00000036444
Q63767
Q63767
Q63767
Q63767
Q63767
Q63767
Q63767
Q63767
Q63767
Q63767
Q63767
Q9ESN9-2
Q9ESN9-2
Q9ESN9-2
P11939
P11939
Q9PUM6
Q9PUM6
Q63767-2
Q63767-2
Q63767-2
Q63767-2
Q63767-2
Q63767-2
Q63767-2
Q63767-2
Q63767-2
Q63767-2
Q63767-2
E1C282
E1C282
E1C282
E1C282
P06493
P67999
P52631
P67999
P67999
P67999
Q63531
P09951
P35465
F1M7Y5
Q9EQG6
P19332
P19332
P19332
P19332
Q06226
P09217
P09217
P47196
P27791
P05696
P68403
Q63484
Q9QY78
P63319
Q9WTQ0
P09216
P47197
P12368
Q64617
O08874
Q8R4U9
Q8R4V0
Q6NUF4
Q96GX5
Q96GX5
Q96GX5
Q96GX5
Q96GX5
Q96GX5
Q96GX5
Q96GX5
Q9DF50
Q8AXF4
B7ZR30
B7ZR30
B7ZR30
Q6DDV8
Q91618
P70032
P70032
Q6NUF4
Q6NUF4
Q6NUF4
Q91636
Q91636
Q91820
Q91572
Q52KN7
Q9PTG8
Q9PTG8
Q9PTG8
O14965
P70166
Q9JJ11
P02340
P30306
Q07832
P97427
P97427
P84244
Q8K4R9
Q8K4R9
Q7TSJ6
Q99NH2
Q61142
Q61142
P70188
Q14203
Q14203
Q14203
P35241
P15311
P26038
P49023
Q8VI36
Q9H2G2
Q9H2G2
P46937
P46937
P46937
P46937
P46937
Q9NQS7
Q8NHZ8
O95835
O95835
O95835
P46937-2
P46937-2
P46937-2
P46937-2
P46937-2
P04049
Q02241
Q02241
Q8N122
Q16584
Q4VCS5
Q9GZV5
P11908
P60891
P46938
P46938
O94885
P46937
P46937
P46937
P46937
Q02241
Q02241
Q15208
Q15208
Q96QF0
O14980
P46937
O95835
O95835
O95835
O95835
O95835
O95835
P04150
P04150
P04150
P04150
P68433
P68433
Q13188
Q13188
P00519
P17252
P17252
Q7L9L4
Q7L9L4
Q7L9L4
Q9H4B6
Q9H4B6
Q9H4B6
Q9H4B6
Q9H8S9
Q9H8S9
Q9H8S9
P51955
P51955
P51955
P51955
Q9GZQ8
Q9CQV6
P46937
Q96QF0
O60285
Q9Y2H1
P46937
P46937
P46937
P46937
P46937
P15311
Q9P289
Q8TAE6
Q9BUL8
Q9BUL8
P70196
P70196
Q8TDY4
Q9Y4P1
Q91636
Q91636
Q91636
Q91636
Q91636
Q91636
Q91636
Q91636
Q91636
Q91636
Q9HC77
Q8NHV4
Q8NHV4
Q8NHV4
Q8NHV4
Q8NHV4
Q8NHV4
Q9UPN4
Q9UPN4
Q9UPN4
O00444
O00444
O00444
O00444
P61160
P61160
Q64279
Q64279
Q969U6
Q15154
Q15468
Q15468
O43303
Q96T49
Q8TDX7
O96004
O96004
Q8NHV4
P02666
P02666
P02666
Q8TDX7
Q8TD19
Q8TD19
Q9HC98
Q9GZQ8
Q9ERR1
P02340
P02340
P53350
P35241
P15311
P26038
P10275
O00303
O95835
O95835
Q15797
P04150
P04150
P35241
P15311
P26038
Q16584
P42858
P42858
P04049
P04049
P04049
Q8VBU5
P48787
P48787
O70405
P49674
P13405
Q8BJ56
P53996
P27546
Q8BYJ6
Q8BYJ6
Q8BYJ6
Q8BYJ6
Q8BYJ6
P23693
P23693
P23693
O88447
P33778
Q60949
Q60949
Q60949
Q60949
Q60949
Q60949
Q60949
Q5SWU9
Q9UQ84
Q4JK59
P54310
Q80T41
Q9CUN6
Q8CI51
Q6PCP5
Q6PCP5
Q8CIN4
P10853
P47856
Q9Z1T6
Q9Z1T6
Q6PCP5-4
Q6PCP5-4
Q9D142
P55014
P62897
Q5SNZ0
Q61037
O88597
Q8K4Q0
Q8K4Q0
Q8BKJ9
Q8BYH7
Q91X44
P04049
O60716
P15923
P15976
P15976
Q9P286
Q6RBX8
Q9ULA0-2
O15079-2
O15079-2
O15079-2
O15079-2
O95831
P09619
P07550
P07550
P32245
P32245
P32300
P32300
P18841
P18841
P18841
P46935
P06241
Q02248
P05480
O70161
Q08481
Q08481
P25911
P19091
P19091
P19091
P19091
P19091
P19091
P19091
P19091
P19091
P19091
P19091
P58252
P58252
P39688
P06240
Q02496
P24941
Q9UPZ9
Q9JKV2
P11416
P33242
P30285
P08775
P24788
P24788
P24928
P24928
Q86VE9
Q01094
Q01094
Q6P9Z1
P16951
P16951
P16054
O54992
Q8R0S1
Q8R331
Q15797
P04150
P04150
P04150
Q62432
Q15797
P42858
P42858
Q9NQB0
Q15208
Q8TAE6
Q9Y6E0
Q7L7X3
Q9Y2H1
P61006
Q5F2E8
Q6ZQ29
Q9WVH4
Q9WVH4
P02340
P02340
P14602
Q96J92
O60229
Q15382
P47713
Q921J2
P48787
P48787
P48787
P48787
Q9JI11
Q9JI11
Q9JI11
Q9R1E0
Q9Z1E3
Q9Z1E3
P10853
Q64475
Q6ZWY9
Q64478
Q8CGP1
P10854
Q8CGP2
Q64525
Q64524
Q9D2U9
Q8CGP0
Q8BPB0
Q8BPB0
P48787
P48787
P48787
P48787
P48787
Q8CIS0
Q8CIS0
Q8CIS0
P18265
P16951
P16951
P16951
Q9WTU6
P31750
P26645
P26645
P26645
P48168
P35991
P20444
P61979
P68404
P68404
P68404-2
Q96SU4
P29474
O15553
O15553
Q64337
Q60855
Q60855
Q60855
Q61097
O43318
Q62073
Q64337
P42227
P31750
P31750
Q9Z1E3
O88351
O88351
P56477
P70671
P70671
P70434
Q3UMB5
Q8VCF0
Q3TBT3
Q3TBT3
Q64337
Q5EG47
Q5EG47
Q5EG47
Q5EG47
Q91YI1
O88597
Q9DB70
Q6PAM0
Q6PAM0
Q6PAM0
O54950
O54950
O54950
A2RT67
A2RT67
Q9R0M6
O00418
Q14457
P04792
P04792
P04792
Q6JBY9
Q6JBY9
P05783
P35900
Q8N5C8
Q9UC36
Q9UC36
Q9UC36
O70405
P02340
Q8BYJ6
Q60949
Q60949
Q60949
Q5SWU9
Q9NZQ7
P47856
Q8R0I0
P34056
O88351
O88351
O88597
Q8BYH7
P08151
P08151
P08151
P08151
P08151
P08151
P45985
P45985
P53805
P53805
Q9ERK0
Q99759
Q09014
Q8N122
P24844
O43293
O43293
O43293
O43293
O43293
Q9UIK4
Q8N122
Q8N122
Q8N122
Q14457
Q86WV6
J3KNL6
A2RUS2
A2RUS2
Q8NEB9
O15027
P13405
P13405
P13405
P13405
P13405
P81122
P48985
P84022
P84022
P84022
P53566
P25976
Q8BUN5
Q8BUN5
Q8BUN5
P13405
P13405
P13405
P13405
P13405
P53566
Q14457
Q14457
Q9Y5P4
P84022
P07948
O14654
Q14457
Q14457
P15387
O88498
Q9Z1K9
Q2MJT0
Q2MJT0
P48966
P48966
A0A096MJY4
A0A096MJY4
P27049
P49950
Q62857
Q62857
P50575
P50575
P09216
Q66H84
Q66H84
Q66H84
Q8R4T2
Q8R4T2
P97784
Q9PU52
Q9PU52
Q04982
Q9R194
P46414
Q99801
P25322
P25322
Q99N13
P46414
P46414
Q01147
Q01147
Q60670
Q9Z2V6
Q9Z2V6
Q9QZS3
Q9QZS3
P81269
Q05512
Q05512
Q05512
Q05512
Q8K1M6
Q80XI3
Q64332
Q3UYC0
P15056
P15056
Q92934
Q92934
Q92934
Q92934
Q02750
Q02750
Q05639
P36507
P36507
P33981
P33981
P68104
P68104
P19634
Q9H9S0
Q13878
P27546
P27546
Q3LRT3
P45481
Q91YS8
Q8BW96
P08414
P02340
P02340
P02340
P68433
P68433
P68433
P68433
P20152
P20152
P20152
P20152
P20152
P20152
P20152
P20152
P20152
Q9WU62
P31001
P31001
P31001
P84244
P84244
O70201
Q9D7F7
P03995
P03995
P03995
Q922S8
Q1HFZ0
Q9WVM1
Q9WVM1
P42209
P42209
Q9D0F1
Q922U2
Q7TSY8
Q7TSY8
Q8VDJ2
Q8VDJ2
Q78E59
Q78E59
P29594
P02340

O35618
O35618
O08696
P48964
P48964
P48964
P48754
P61290
P02340
Q14934
Q14934
P23443
O00327
O00327
O00327
Q8K120
Q8K120
O54918
O54918
O54918
Q60700
Q60700
P27661
P15037
P46938
P46938
P46938
P84244
P20263
Q9WVI9
Q9WVI9
P28700
P28700
P28700
P28700
Q99KG5-2
Q9Z131
B2RS91
P02340
P10415
P10415
P10415
P10415
P97287
P97287
O54918
O54918
O54918
Q60700
Q60700
P05627
P28738
P12023
Q9WVI9
Q9WVI9
Q9ESN9-2
Q9ESN9-2
Q9ESN9-2
P02340
P02340
P02340
P39689
P39689
Q9DBR7
Q9DBR7
Q9DBR7
O08738
Q8BYR2
P02340
P02340
P02340
P16951
P38432
O54962
O54962
O54962
Q5SU73
P02340
O54962
O54962
O54962
Q5SU73
O70343
Q01147
Q04887
Q9Z1S8
Q9Z1S8
Q9R1E0
Q9R1E0
O35099
Q8CFH6
O35491
Q99104
P97474
Q60949
Q9Z1T6
Q91V92
Q61409
P35821
Q9WV06
Q7TPS5
Q9WV89
O43765
O35326
P70460
P20152
P31001
P31001
P31001
P26645
Q9Z207
Q9Z207
Q9DBR7
Q9DAW9
Q9DAW9
Q9ESN9
Q9ESN9
Q9CQ19
O54784
O08586
O08586
O08586
Q99NH2
P03995
P03995
P03995
Q922U2
P62962
P53668
P12023-2
O54785
Q6P9Q4
P70460
Q99LM3
E9PZQ0
Q9DBR7
Q9DBR7
P23819
Q9JMB0
P55088
Q64213
Q8BRK8
Q5EG47
P54645
Q91YS8
Q8BW96
Q90Z72
Q9Y6Q9
Q8IW41
Q16659
P46695
O95551
Q02248
P70444
Q80Z64
Q80Z64
Q02248
Q61083
Q61083
P04177
Q01986
Q01986
P63086
P63086
P21708
P21708
P63085
P63085
Q63844
Q63844
P49950
O08679
P06685
P06685
P31977
O08679
O08678
P12928-2
P21272
P13084
P13084
P33568
P10361
P10361
O35923
P51952
Q63528
Q9JK11
P05197
P06211
P06211
Q5XIP6
P09416
Q63449
P84025
P84025
P84025
P12928-2
P33568
P12928-2
Q8C2B3
Q62101
Q8BZ03
Q8BZ03
Q8C2B3
Q3U182
G3XA57
P70188
A2AHC3
Q8C2B3
Q61097
Q61097
Q08874-8
Q3UVC0
O43432
Q9R1U5
P56720
P56720
P56720
Q157S1
Q3LRZ1
Q99P99
Q99P99
P42227
P49023
P49023
P33671
Q8VHK2
Q8VHK2
P08034
P42227
P42225
P42230
D3Z194
D3Z194
D3Z194
D3Z194
Q61458
Q61458
P42227
Q9DBR7
Q9CQ19
Q3THE2
Q3THE2
O54784
P19253
P51667
P08733
P42227
Q9ESJ7
Q9ESJ7
Q9ESJ7
Q9ESJ7
Q9ESJ7
Q9ESJ7
Q9ESJ7
P42227
Q01986
Q01986
P31938
P53349
P53349
P42227
Q8BSK8
Q8BSK8
Q8BSK8
Q8BSK8
Q8BSK8
P42227
P42859
Q60929
P27782
P27782
O88974
Q924A0
Q924A0
O54949
P15127
P47196
P47196
O54924
O54924
O54924
O54924
O54924
O54924
O54924
O54924
O54924
O54924
O08623
Q63746
Q9QY78
Q9QY78
Q66HG9
F1M391
P31995
Q62418
Q62418
P12318
P12318
P12318
P31994
Q8N884
P16277
O15524
P19174
Q06187
Q13094
P51813
Q08881
P42680
Q9UL17
Q96LC7
Q96LC7
Q9H4E7
Q9H4E7
Q8TDQ0
Q62077
P10747
P10747
P10747
O75791
P19174
Q13094
P42681
P42681
P16410
Q96P43
Q9GZY6
Q9GZY6
P10721
P10721
P10721
P10721
P10721
P10721
P10721
P10721
P35232
Q13239
Q13239
Q13239
P22681
P05132
O70161
P42567
Q91V17
P97813
Q01279
Q01279
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
P35821
Q02496
P31809
P19157
P17918
P97428
Q60992
Q60992
Q60992
P56959
P56959
P05132
P26618
P05132
P05480
P05480
P26040
P26040
P26450
P35235
P35235
P35235
P35235
Q06124
Q06124
P28867
P28867
P05622
Q02496
Q02496
Q62985
Q91ZM2
Q62985-2
F8WI90
Q80XU2
Q06187
Q13322
P51813
P51813
P15655
P15655
P15655
Q08881
Q99952
Q99952
Q99952
Q99952
P09038-2
P42680
P42680
P09038
Q92606
Q9UC54
P10636
Q13470
Q3U182
Q3U182
Q3U182
P10636
Q9UKV3
P78362
O54781
Q99538
Q9UHW9
Q9UHW9
Q9UHW9
Q9H4A3
P55016
P55016
P55018
Q9UHW9
Q9UHW9
Q9UEW8
Q9UEW8
Q9UEW8
Q9UEW8
Q96PU5
Q96PU5
Q9H4A3
Q9H4A3
O95747
O95747
Q9H2W4
Q9H2W4
O94913
O94913
Q6P9R2
P55012
P59158
Q9Z1W9
Q9Z1W9
P55017
P55017
P55017
Q96J92
Q96PU5
Q96PU5
O95471
P59158
Q9Z1W9
Q9H2W4
Q9H2W4
Q15759
Q15759
Q16539
Q16539
P53778
P53778
P46734
P46734
P70618
P70618
Q9Z1B7
Q9Z1B7
O15264
O15264
Q15759
Q15759
P47811
P47811
Q16539
Q16539
P52564
P52564
P53778
P53778
Q9NQU5
Q9NQU5
Q9ULV5
P70618
P70618
Q9Z1B7
Q9Z1B7
O15264
O15264
Q6NUN9
Q6NUN9
Q9JK66
Q9BXM7
Q9BXM7
Q9BXM7
P62988
P62988
Q8IXI2
O60260
Q0VBL6-2
Q07817
P68104
O95140
O95140
O95299
P62987
P62979
P0CG47
P0CG48
O95202
Q80U16
P62991
P62991
P49411
Q9JK66
Q8R500
Q8R500
Q561S0
P62986
P62982
P0CG51
Q63429
Q92934
Q92934
Q92934
Q02750
Q02750
Q15599
Q02750
Q02750
P10085
P00536
P00536
P00536
P00536
P50753
Q10728
Q01986
Q01986
P36506
P36506
P18654
Q61851
P14602
P14602
Q96J92
P22893
P22893
Q9D312
P05784
Q571K4
P04792
Q01130
Q01130
Q01130
Q01130
P08138
P53667
P49137
P49137
P49137
P49137
Q15835
P02699
P02699
P02699
P02699
P02699
Q61146
Q61146
P41145
Q5NUL3-2
Q5NUL3-2
Q5NUL3-2
O54942
Q5NUL3-1
Q5NUL3-1
Q5NUL3-1
P08100
P08100
P08100
Q9UPN4
Q7TQF7
O76039
O76039
Q9HCJ2
Q66K74
Q8TDM6
P54748
P18265
P17431
P17431
P17431
P42930
P42930
P20689
Q5BJY9
P47973
P47973
P53669
Q13546
Q13546
Q13546
Q13546
Q13546
Q5VWQ8
Q01147
Q60680
Q9WTK5
Q9WTK5
Q60855
Q8K1M6
Q3UHC7
Q60855
Q5EG47
Q9QZL0
Q9QZL0
Q9D2Y4
Q9D2Y4
Q9D2Y4
Q9D2Y4
Q6PHZ2
Q9Z2A0
Q9Z2A0
Q9Z2A0
P35569
P35569
P35569
P35569
P35569
P35569
P35569
P35569
P81122
P81122
P81122
P81122
P81122
P81122
P81122
P81122
P97465
Q60770
P04117
P49817
P31809
P31809
Q9JID9
Q9Z2A0
Q9Z2A0
O35099
O35099
O08785
O08785
Q3UHC7
Q9CPV9
Q04759
P19484
P46940
Q8IVH8
P35569
Q9Z1X4
Q9Z1X4
P11440
Q6ZWX6
Q03963
Q9UEW8
Q9UEW8
Q9H4A3
P54132
P30304
P30304
P30304
P68433
P68433
P68433
Q8VDJ2
Q8VDJ2
Q78E59
Q78E59
O88445
Q6Y685
P68433
P84244
Q8VDJ2
Q78E59
P84228
P02301
Q06486
P18031
P18031
P18031
O60829
O60829
O60829
O60829
O60829
O60829
O60829
O60829
P49760
P49760
Q15173
Q15173
Q15173
Q15173
Q15173
Q15173
Q6PD28
Q6PD28
Q6PD28
Q6PD28
Q6PD28
Q6PD28
Q13043
P22455
P22455
P22455
P06400
P06400
P06400
P18266
P29294
P29294
P29294
Q09YN6
O77507
Q9ES52
Q9ES52
P27361
P09215
P27870
P27870
P27870
P43403
P43403
P24161
P24161
P24161
P24161
P24161
P24161
Q811D0
Q08481
Q08481
P09793
P09793
P63085
P28867
Q9QVP9
Q9QVP9
P43404
P06240
P06240
P31809
P31809
O88839
O88839
Q03526
Q02111
Q9EQR5
Q9EQR5
Q8R5A3
Q8R5A3
P97756
P54645
P13234
P13234
P13234
Q63450
P07550
P07550
P21731-2
P21731-2
P42866
P42866
P42866
P42866
P41143
P41143
P30680
P30680
P30680
P30680
P70658
P70658
P33534
P51681
P51681
P51681
P51681
P30874
P30874
P41146
P41146
P41146
P41146
P07550
P07550
P43249
P43249
P17870
P33567
P10637
P30306
Q8K3M6
P83887
Q8VCK3
P47810
P10637
O88643
Q04735
P47810
P10637
O88809
O88809
P20357
P70188
P10637
Q90623
Q90623
P26932
P26932
P26932
P26932
P26932
ENSGALP00000016789
F1NA71
P07949
P34152
P34152
P34152
P34152
P35546
P35546
Q10728
Q10728
P10361
P10361
O35397
P00523
P09324
P00523
Q9WUD9
Q9WU82
Q9WU82
P15207
P15207
P15207
P15207
P15207
P15207
P15207
P15207
P15207
P15207
P15207
Q5I6B8
P05197
P05197
Q07014
D3ZMK9
D3ZMK9
D3ZMK9
Q6P6U0
Q62101
Q62101
P16951
Q61146
Q9WTQ1
Q9WTQ1
Q63943
Q8CFN5
Q8K120
Q8K120
Q9WVS8
Q9WVS8
Q9WVS8
Q9WVS8
Q60929
Q60929
Q9WVC6
Q00756
Q00756
P54288
Q95212
P30957
P30957
Q9TTT5
Q60875
Q8R001
Q8C052
Q8C052
P02687
P02687
A7MB78
A7MB78
A7MB78
A7MB78
P02687
Q3T0C7
Q3T0C7
Q08DJ8
Q0P5A7
O77628
O77628
O77628
O77628
Q5E9X2
Q5E9X2
Q08DC7
P02687
P02687
P02687
P02687
P02687
P08487
P08487
P04409
P05126
P05128
P02687
P08955
O88479
O88479
O88479
O88479
P08955
O88479
O88479
O88479
O88479
P08955
P01099
P11845
P33674
P33674
P33674
P33674
O46480
O46480
O46480
Q95330
P01099
Q9MZ19
Q9MZ19
Q9MZ19
Q9MZ19
Q95330
P62755
P52947
P62630
P23693
P23693
P23693
P23693
P48436
P54645
Q09137
P13234
P13234
P13234
P13234
P13234
Q63450
P21818
P21818
P08592
Q9R237
Q9R237
P27699-2
A3KGV1
Q9D411
Q9Z2Z9
P23441
Q6ZPF3
P70304
P98161
O43541
Q60817
O55222
Q60817
P70670
Q8R4S0
P19419
Q63622
Q8CGX0
P47942
Q9WU82
Q62950
Q6X936
Q6X936
Q6X936
Q6X936
Q9R044
Q9R044
P97924-6
P97924-6
P52631
Q99PD6
Q03114
Q9JM80
Q4V7G1
Q4V7G1
P37377
O35119
O35119
Q05764
Q66H76
Q66H76
Q9WU82
Q9WU82
P52631
Q91V33
Q91V33
Q91V33
P81128
Q08775-5
Q08775-5
P27361
P27361
P63086
P63085
P63085
P29678
P29678
P29678
P29678
P29678
P29678
P29678
P97287
P70447
P70447
P23204
Q8VI36
Q9Z1E4
Q8VCB3
Q8VCB3
Q8VCB3
Q8VCB3
Q99LW6
Q3TTA7
Q3TTA7
P09951
P09951
P12023
P55258
P61027
P35283
Q6PHN9
P63011
Q9CZT8
P62823
P35276
Q8CG50
P61028
P16951
P15172
P15172
P38532
Q9Z131
Q922Y1
Q9ESY2
P70531
Q9WTQ1
Q9WTQ1
Q13164
Q13164
Q64279
Q64279
Q9QXW2
Q64702
Q64702
Q64702
Q64702
Q64702
Q64702
Q64702
Q64702
Q64702
Q64702
Q64702
Q64702
Q64702
Q9WTU6
Q9WTU6
Q91Y86
Q9WTU6
Q91Y86
Q9Z1B7
Q61831
Q9WTU6
Q9WTU6
P47811
P47811
Q9WUI1
Q9WUI1
Q91Y86
Q91Y86
Q9Z1B7
Q61831
P45983
P45983
Q16539
Q16539
O35099
O95382
Q99683
P35465
Q63802
Q63686
P35465
P55018
P35916
P35916
P35916
P07737
P02584
P35968
P35968
P35968
P35968
P35968
P35968
P35968
P35968
P35968
ENSP00000261937
ENSP00000261937
ENSP00000261937
P35916
P35916
P35916
P35916
P35916
P35916
P35916
P35916
P29353
P29353
P29353
ENSP00000261937
ENSP00000261937
P30411
P30411
P30411
P18901
P18901
P32298

P32298
P32298
P32298
P32298
P32298
P32298
P32298
P32298
P13863
P13863
Q16832
Q16832
Q16832
Q13322
Q13322
P05480
Q9QWY8
Q8VI36
Q9QVP9
O88351
O88351
Q9QY53
Q9QY53
Q9WUN2
Q8CHT1
Q00535
P54764
P54764
P54764
P10686
P10686
P05696
P68403
Q4KM52
Q4KM52
Q4KM52
Q4KM52
Q4KM52
P63319
Q920L0
O70601
P10686
P10686
Q63604
Q63604
Q63604
Q63604
Q63604
P13595
P13596
P10686
P0C0K5
P10686
Q60598
Q60598
P28867
P28867
Q04736
Q04736
P42866
P42866
P42866
P42866
P42866
P42866
P42866
P42866
P33534
P33534
P33534
P56726
P56726
P56726
P56726
P56726
P56726
P56726
P26040
Q62406
Q07139
Q6P1M3
Q15334
Q3TIR3
P23528
P45592
P60981
Q9Y281
P23528
P45592
P60981
P23528
P23528
P23528
P45592
P23528
P23528
P60981
P18760
Q63572
P37173
P37173
P37173
P37173
P37173
P37173
P36897
P36897
P36897
P36897
P36897
P36897
P17813
P17813
O75604
O75604
O35346
O08816
Q63767
Q63767
Q63767
Q9Z1P2
Q9QZC5
Q9QZC5
Q66HL2
Q66HL2
O35346
G3V9H8
G3V9H8
G3V9H8
G3V9H8
Q91YM2
Q921Q7
Q4JIM5
Q4JIM5
Q4JIM5
Q4JIM5
P05622
P05622
P05622
Q9Z2U0
O54926
O00401
Q9QUI0
Q7TSE6
Q91VJ4
Q00610
Q9H3D4
Q9H3D4
Q60610
P15209
P15209
P15209
P15209
P15209
Q91WJ0
Q91WJ0
P29066
P50503
Q63754
P08559
Q15118
P36888
P36888
P36888
P36888
P36888
P36888
P36888
P36888
P36888
Q07497
Q07497
O75874
Q6TEQ7
Q6SLL5
Q6SLL5
F1PAA9
F1PAA9
F1PAA9
O46550
P60952
Q9TSZ6
Q5PU49
Q5PU49
Q9TU19
P50281
Q5RJI4
Q5RJI4
F1LM64
F1LM64
P30040
P30040
P45452
P03956
P45592
P31750
Q91YD9
Q91YD9
P19091
P19091
Q91WL8
P0C0S8
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43683
O43684
Q12834
Q12834
Q12834
Q12834
Q12834
Q12834
O75531
Q7KZI7
Q9P0L2
P61587
P61587
P61587
Q4VCS5
Q2EJA0
Q2EJA0
Q2EJA0
Q62406
P47811
P47811
Q9WUI1
Q9WUI1
Q61084
P25322
Q9Z1B7
P47811
P47811
Q9WUI1
Q9WUI1
Q9Z1B7
P47811
Q9WUI1
O54957
O54957
O54957
O54957
Q9D7X3
Q9D7X3
Q9QWY8
Q8VI36
Q9QVP9
Q13882
Q13451
Q9H3Y6
P15655
P24604
P54843
P54843
P54843
P13084
Q63802
P30277
P28023
P97691
P97691
Q62871
Q4V8G7
Q4V7C8
Q5XI51
Q5XI51
P63029
P63029
F1M5M3
P18031
P18031
P18031
P00519
Q96I25
Q96I25
Q96I25
Q96I25
Q96I25
Q96I25
Q96I25
Q96I25
P08621
Q569Z6
Q01986
Q01986
Q01986
Q01986
Q01986
P17325
P17325
P17325
P17325
P17325
P01237
P01237
P01236
P11345
P11345
Q9WTQ1
P27704
Q4G050
Q4G050
Q01986
Q01986
P10085
P63085
P63085
Q63844
Q63844
O88643
D4A5A6
P15207
Q641Z4
Q641Z4
Q641Z4
Q641Z4
Q641Z4
Q641Z4
Q641Z4
P17325
P17325
P10361
P53563
P48965
P48965
O35800
O35800
P34058
Q06413
Q8NEB9
Q6PHR2
Q6PHR2
Q6PHR2
Q6PHR2
Q157S1
Q5FVC2
Q5FVC2
O43353
O43353
O43353
O43353
O43353
O43353
P78324
P78324
P07948
Q92630
Q92630
P15923
P15923
P15923
P15923
P15923
P17813
P17813
P17813
P17813
P17813
P17813
P17813
P17813
P00519
P39428
P26645
P26645
P26645
P23927
P23927
P47708
P47708
O35099
Q9UBF8-2
P46938
P46938
Q91VJ4
Q3UHJ0
Q8R361
Q6IMP4
Q68EF0
Q8R4B8
O35054
Q03145
Q03145
Q03145
Q8R4B8
P70340
P83268
P05198
P05198
P68101
P83268
P05198
P05198
Q9Z2B5
Q9Z2B5
P05198
Q9Z2B5
Q6ZWX6
P68101
P68101
P29317
P29317
P29317
P29317
P29317
P29317
P29317
P29317
P29317
O14493
P07947
P25274
O88809
ENSMUSP00000029545
Q3U182
Q9Z2V6
Q9Z2V6
Q91X84
Q91X84
Q91X84
Q91X84
P97943
Q6NZM9
Q6NZM9
Q9WTN3
Q9WTN3
Q9WTN3
Q01063
Q01063
O60829
O60829
P51608
P51608
P46933
P08592
Q63768
Q63767
Q63065
Q03114
Q5XIS9
Q5XIS9
P97680
Q2EJA0
Q05030
Q05030
Q05030
P41350
P63245
Q9Z158
ENSRNOP00000012056
Q8CFI0
P46097
P46097
Q6P9R2
Q6P9R2
Q8CFI0
Q80UE6
Q9Z1W9
Q9Z1W9
P19332
P42858
P02810
Q13200
Q95107
Q95107
Q01314
Q64010
Q60751
Q60751
Q60751
Q60751
Q60751
Q60751
Q9EPK5
P46938
P46938
P46938
Q8VHG2
Q9EPK5
Q9EPK5
P46938
P46938
O94916
O43602-2
O43602-2
O43602-2
Q91Y80
O35147
P84245
Q9R237
Q9R237
Q05343
Q05343
Q05343
Q05343
Q2EJA0
Q2EJA0
Q2EJA0
F1M787
NP_001258431
Q00944
P49024
P05094
Q9Y621
Q9Y621
Q9Y621
P06730
P63073
P47713
Q9D2E1
P46734
Q09014
Q91X84
Q91X84
Q91X84
Q91X84
O35426
O35426
Q9WVS6
O95202
P62991
Q80U63
Q80U63
Q99LC3
P62984
P62983
P0CG49
P0CG50
Q13309
Q13309
Q13309
P50750
P25118
P25118
P25118
P25118
P25118
P25118
P25118
P97377
Q9JKD8
Q62077
Q8VIM0
Q03526
P09793
Q62077
P42682
P42682
P33568
P84025
P84025
P84025
P33568
Q6LED0
Q5XIN1
P48965
P48965
P48965
P48965
P48965
P48965
P33568
P10361
O54952
P97691
Q5XIN1
Q5XIN1
P48965
P48965
P48965
P33568
Q9CXH7
Q9D0F1
Q60952
Q60952
Q6NWW5
Q6NWW5
Q8CIM1
P70618
P26932
P26932
P61587
P61587
P61587
O55131
Q9UL54
Q9Z340
P10361
O54952
P0C279
P48966
Q62673
Q4V8J7
Q4V8J7
Q64122
Q64122
P26041
Q5E9E2
A7E3S4
A7E3S4
Q08DP0
Q5E9E2
Q5E9E2
Q5E9E2
Q4A1L4
Q5BIN5
Q5E995
Q5E995
P32850
Q5KR49
Q5E9E2
Q5E9E2
P61635
A4IF97
A4IF97
P21708
P21708
P63085
P63085
Q63844
Q63844
Q62077
Q62077
Q8BSK8
P18708
Q9JIA3
P97680
Q05030
Q05030
Q05030
P81128
P59692
P47809
P47809
O35763
P31977
Q62985
Q05030
Q05030
Q05030
Q05030
P41499
P41499
O35147
O55173
O55173
Q8K4S7
P13838
O88506
P46193
P08487
P08487
P08487
P08487
Q9N179
Q8WML4
P28801
Q3ZBW4
O46471
Q06806
Q99MC0
Q63433
Q63433
Q63433
Q63433
Q63433
Q63433
Q63433
Q63433
P04274
P16573
P16573
P70600
P70600
Q9QYV0
Q9QYV0
Q9WTQ0
P16573
P20417
Q5I6B8
P07150
Q9QX70
P04906
P04961
P51432
P10361
P10361
Q9R1T1
Q9R1T1
Q9R1T1
P10361
P42930
Q62639
O57342
O57342
Q01097
O08586
Q922K9
P02699
P02699
P02699
P28327
P28327
P28327
P28327
P28327
P06836
P35722
P04256
P04256
P04256
P04256
P63074
P36225
Q08092
Q08092
Q08092
Q08092
Q08092
P02543
P02543
P26042
P29269
P29269
P26044
M3TYT0
P47196
P15207
P15207
O08816
O08816
O18734
Q8MIK9
Q9BUL8
Q9BUL8
Q9BSQ5
O00506
P70196
P70196
P63073
Q8VIJ6
Q8VIJ6
P49312
P49312
P49312
P49312
Q6LED0
P84245
Q6LED0
P84245
O35491
O35491
O35491
P35821
P35821
P35821
P18666
Q07497
Q07497
Q07497
Q07497
Q07497
Q07497
Q07497
Q07497
Q07497
Q07497
P07948
Q9CQ19
Q9CQ19
Q9CQ19
P31938
Q62925
Q62925
P08487
P08487
P24135
P24135
P24135
P24135
Q5U2Y1
Q5U2Y1
Q5U2Y1
Q02763
Q02763
Q02763
Q02763
Q02763
Q02763
P07333
P07333
P07333
P07333
P07333
P07333
P07333
P07333
Q15303
Q15303
Q15303
Q15303
Q15303
Q15303
Q15303
Q15303
Q15303
Q15303
Q62432
Q62432
Q8BUN5
Q8BUN5
Q8BUN5
P10126
Q63961
Q63961
P29678
P29678
P29678
P29678
P29678
P29678
P09741
P29678
P29678
O02822
O02822
O46480
O46480
P06186
Q8VI36
P46460
Q96SN8
Q96SN8
P30622-2
P30622-2
P30622-2
P30622-2
P30622-2
P30622-2
P30622-2
P30622-2
P30622-2
P30622-2
P30622-2
P51150
Q9BYX4
O43768
P56211
P49757
Q96CW1
Q9BXS5
P84091
Q96CW1
P51956
O95721
O95551
O95551
O95551
O95551
Q9JJX7
Q9NVP2
Q9Y294
P54753
O55131
O70548
O75460
Q8NEV4
Q8NEV4
Q8NEV4
Q8NEV4
Q8NEV4
Q9Y6R4
P42532
O75716
O75716
O75716
Q9Y295
Q9Y295
P17948
P17948
P17948
P17948
P17948
B5A923
B5A923
B5A923
B5A923
B5A923
B5A923
O14936
O14936
P58400-1
P58400-1
P58400-1
P00528
P23645
P23645
P23645
Q07171
Q07171
Q07171
P08928
P20240
P16371
P23226
P08928
P20240
P08995
P16056
P16056
P16056
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
Q9QYY0
Q03385
P19619
P80031
P19620
M3TYT0
Q2QLE2
Q2QLE2
Q007T2
Q29243
O97930
O97930
O18868
Q0QF01
P23437
P35567
P97813
P97813
P97813
P97813
P49710
Q8K2B3
Q03017
Q9NFU0
Q06943
Q06943
Q06943
Q08605
P13098
P02836
P02836
P02836
P02836
Q24150
Q24150
Q08605-2
Q08605-2
Q03017
Q03017
Q03017
Q03017
Q03017
Q03017
Q99323
Q99323
P04412
P23654
P23654
P23654
P23654
P29320
P29320
P29320
P29320
P29322
P29322
Q07494
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
P55162
P23645
P23645
P98081
P98081
P98081
P98081
P98081
P98081
P98081
P98081
P98081
P98081
Q8T4F7-2
Q8T4F7-2
Q8T4F7-2
Q8T4F7-2
Q8T4F7-2
Q8T4F7-2
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
Q8T4F7
P55162
O73612
O73612
O73612
P28693
P28693
P54763
P54763
P54763
P54763
Q5FWH6
P43407
P43407
P09581
P09581
P09581
P09581
P09581
P09581
P09581
Q29502
Q29502
Q29502
Q29502
Q29502
Q29502
Q29502
Q29502
Q9JLM8
A2AJI0
A2AJI0
A2AJI0
Q91820
Q91820
Q91820
Q91820
Q91820
Q91820
P79923
P79923
P79923
P79923
P79923
P79923
P79923
P79923
Q98TW0
Q98TW0
Q9Y2K2
Q9Y2K2
Q9Y2K2
Q9Y2K2
P25911
Q03137
Q03137
Q03137
Q03137
P49615
O09127
O09127
P35918
P35918
P35918
P35918
P35917
P35917
P35917
Q02858
Q02858
P46097
P46097
Q7TPK6
Q9JIH7
Q9JIH7
P29101
O35613
ENSGALP00000016789
ENSGALP00000016789
ENSGALP00000016789
F1NA71
F1NA71
F1NA71
ENSGALP00000016789
ENSGALP00000016789
ENSGALP00000016789
F1NA71
F1NA71
F1NA71
ENSGALP00000016789
F1NA71
C50F4.11
C50F4.11
G5EFM0
G5EFM0
C09G9.6.1
C09G9.6.1
G5EC86
G5EC86
P34808
Q9XUB2
C09G9.6.1
P34707
G5EC86
G5EC86
Q23359
Q95V25
Q9NH55
Q94527
Q94527
P18824
Q00168
Q00168
Q00168
Q02280
CG1708-PA
CG1708-PA

O16844
O16844
P22813
Q01842
P22813
Q01842
P18432
P18432
P40423
P19107
P19107
P08630
P19538
P19538
P19538
CG6975-PA
CG6975-PA
Q95V55
Q95V55
Q95V55
Q24119
Q24119
Q9VW83
Q9VW83
Q10666
Q10666
CG6757-PA
Q9NCC3
P34707
P34707
Q8IPH9
P45594
CG3981-PB
Q9W525
CG4005-PB
Q45VV3
Q5E9F8
Q5E9F8
P84227
P84227
P68432
P68432
Q6J1J1
Q5E9F8
P84227
Q3SZB8
A5PK61
P68432
A5D7P0
Q2HJ21
A7MBD1
A7MBD1
A7MBD1
A7MBD1
A7MBD1
A7MBD1
Q2KJ94
P27925
A5PK26
Q08E52
Q3T169
Q2YDF1
Q32PF2
Q24K09
E1BPQ1
E1BPQ1
E1BPQ1
Q95KV1
A7E3S4
Q08DI6
Q5E9P3
Q5E9L6
O97790
O97790
O97790
Q27ID4
P67808
P27925
E1BPQ1
E1BPQ1
E1BPQ1
Q27994
P46196
Q3SYX0
Q3SYX0
Q3SYX0
Q3SYX0
Q3SYX0
P27925
P62157
P27925
Q32PF2
E1BPQ1
P27925
Q0VCX4
Q0VCX4
Q08DA8
P50148
Q62910-5
Q62910-5
Q62910-5
P97588
P97588
P97588
P02544
Q00366
Q00366
Q00366
P02544
P02544
P02544
Q00366
P37882
P02541
P02541
P02541
P48968
P48968
O09181
P02544
Q00366
Q00366
Q00366
P02541
P02541
P02541
O88529
O88529
Q60528
Q60528
Q60550
Q60528
Q60528
Q60528
C0HJG9
O88479
O88479
Q0QF17
P20460
P20460
P20460
Q29000
P56432
P56432
P56432
Q7YR76
Q7YR76
Q7YR76
Q7YR76
Q7YR76
Q7YR76
Q7YR76
Q7YR76
Q27HV0
Q27HV0
P84024
Q29031
Q29031
P56432
P56432
P56432
P56432
P56432
P62802
P56432
P56432
P56432
P56432
Q9TUB2
O77737
Q29029
Q29029
P56432
Q9TUB2
Q19S50
Q29031
Q7YR76
Q7YR76
Q7YR76
Q7YR76
B2DCZ9
Q6DUB7
Q6DUB7
O97930
O97930
O97930
O97930
B5KFD7
B5KFD7
B5KFD7
Q7YR76
Q7YR76
Q7YR76
Q7YR76
B2DCZ9
Q6DUB7
Q6DUB7
O97930
O97930
O97930
O97930
B5KFD7
B5KFD7
B5KFD7
Q5R9H0
Q5R9H0
Q5R9H0
Q5R9H0
Q5R4T2
Q5R4T2
Q5RAK8
Q5R9Y6
Q5R9I9
Q5R9H0
Q5R9Y6
Q5R9H0
Q5R4R8
O19002
Q7YRZ9
O19002
O19001
O19001
O19002
O19001
O19001
O19001
O19002
P68271
O19002
P41685
P41685
Q7YRZ9
A7MB78
A7MB78
A7MB78
A7MB78
Q08E02
Q08E02
O02755
O02755
Q0VCX4
Q0VCX4
Q0VCX4
Q0VCX4
Q0VCX4
Q8WML4
O02675
Q9XTA5
Q9XTA5
Q9XTA5
Q08DJ8
Q05688
O77627
O77627
O77627
Q5E9A1
A7MB78
Q27ID4
Q2HJ27
O02675
O77627
P61635
Q0P5A7
Q0P5A7
A7MB78
P68103
Q5E995
Q5E995
A0QNG6
P12023
Q8BFP9
Q00342
P46938
P46938
P46938
P46938
P19091
Q99J95
Q99J95
Q99J95
Q99J95
Q99J95
Q99J95
Q99J95
O55201
O55201
Q9Z255
Q3T1H5
G5EE37
G5EE37
Q08E52
Q3T169
Q2KI14
Q95KU9
Q95KU9
Q95KU9
Q3T169
Q3T169
Q8WML4
P18246
E1BPQ1
Q3B7L6
Q95KV1
A7E3S4
A7E3S4
A7E3S4
A7E3S4
A7E3S4
A7E3S4
Q3T0C7
Q3T0C7
Q0P5A7
O77628
O77628
O77628
O77628
Q08DC7
A0JNE3
A8E4N3
P53781
A7E3S4
A7E3S4
O77627
O77627
O77627
O77627
O77627
P62803
Q58D94
A7E3S4
Q9VW83
Q9VW83
Q96GX5
Q96GX5
Q96GX5
Q96GX5
Q96GX5
Q96GX5
Q96GX5
Q96GX5
Q0IHQ8
Q0IHQ8
Q0IHQ8
A4IH24
Q9JIX8
P35821
P35821
P35821
P62754
P62754
P20417
P20417
P20417
P20417
P20417
P20417
O54748
Q3T1J9
P11345
Q8VDF3
Q8VIJ6
Q9Z265
Q9Z265
Q5U4C9
Q5U4C9
Q9TUB2
B2DCZ9
Q9TUB2
Q9TUB2
Q9TUB2
P02543
Q29277
Q60495
P79307
O18868
O18868
O18868
O18868
A2ICN5
A4UTP7
Q28969
Q9WUR6
Q9WUR6
Q9WUR6
Q9TUB2
Q9TUB2
Q9TUB2
Q9WUR6
Q9TUB2
Q9TUB2
Q29029
P61291
Q9TUB2
P79387
Q9TUB2
Q5S1U1
Q5S1U1
Q9TUB2
Q9TUB2
Q29101
Q9TUB2
B2DCZ9
Q9GLN5
P02540
P02540
P02540
P02543
Q6DUB7
Q6DUB7
O77737
A4L7N3
Q29029
Q29029
Q29029
Q29029
Q29029
Q9BDP6
Q52NJ2
Q0Z8U2
Q767L7
P02554
Q9TUB2
Q9TUB2
P84024
P84024
P84024
Q29040
Q29040
Q29031
F1SRY5
P87074
P24339
Q09825
P40380
P40380
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q7LL22
Q09933
Q09933
Q09933
Q09933
Q09933
Q09933
O14216
O14216
O14216
O14216
O14216
P41891
Q09826
P13681
P41004
Q91572
Q91572
Q91572
Q52KN7
Q52KN7
Q52KN7
P20911
Q8AXF4
Q8AXF4
Q8AXF4
Q8AXF4
Q8AXF4
Q8AXF4
Q8AXF4
Q8AXF4
Q8AXF4
Q8AXF4
Q8AXF4
P28025
Q6GNV6
Q6GNV6
P12965
Q4F9K6
Q91618
Q91618
Q91618
Q91618
Q91431
P70032
Q8JGN5
Q4R1J6
Q50L39
Q804H7
Q9YHY6
Q9YHY6
Q9YHY6
Q6NTJ3
Q6NTJ3
Q6NTJ3
Q6NTJ3
Q6NTJ3
Q6NTJ3
Q6NTJ3
Q91783
Q92021
P79943
Q8QGV2
Q864U1
P67939
Q2TA25
Q864U1
P67939
A5D7P0
Q2HJ21
Q2HJ21
A7MBD1
A7MBD1
A7MBD1
P67939
P61283
P61283
P61283
P67939
P67939
Q3T0P5
P67939
P61283
P61283
P61283
P67939
A5D7P0
A5D7P0
Q9XTA5
Q9XTA5
O77627
O77627
Q76LV1
A7MBD1
A7MBD1
P67939
Q04752
P67939
Q3T149
Q3T149
Q56JV3
B2DCZ9
P29269
B2DCZ9
P48966
P83888
Q63802
P48966
P48966
O55173
Q6J1J1
Q24141
Q24141
Q24141
O70201
Q9GLN5
Q9GLN5
P02540
P02540
P29269
Q9JHY7
Q6AXW0
Q6AXW0
Q63538
Q63538
Q9WTY9
Q9WTY9
Q63538
Q63538
Q9WTY9
Q9WTY9
O48814
O48814
O48814
O48814
O48814
O48814
O48814
O48814
O48814
Q9LSI9
Q9LSI9
Q9LSI9
Q9LSI9
Q9LSI9
Q9LSI9
Q9LSI9
Q9LSI9
Q9LSI9
Q9LSI9
Q9FL28
Q9FL28
Q9FL28
Q9FL28
O48814
O48814
O48814
O48814
P06803
P04909
P53323
P53323
P06104
Q9FGM1
O49686
P21192
P21192
P21192
P21192
O95238
O95238
O95238
Q9DCH4
P22204
P22204
Q12158
Q12158
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P32944
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P38859
P38859
P38859
P36165
P36165
P21651
P21651
P22216
P22216
P22216
P38634
P38634
P38634
P38634
P38634
P38634
P38634
P32944
P32944
P32944
P32944
P32944
P32944
P32944
C7GVI6
P97310
P97310
Q3KNJ2
Q1LZG6
Q3B7M6
Q3B7M6
Q3B7M6
Q3T160
Q08DJ8
Q2KIW5
Q29RT6
A6H750
A6H750
A0JNH1
Q17QG2
Q17QG2
Q5E984
Q5E984
F1MJR8
A5D7P0
Q0VCD2
Q32KM1
A5D7P0
A2VDZ3
A2VDZ3
Q2KIA0
Q2KIA0
Q0IIB6
Q0IIB6
Q3SYZ2
Q3SYZ2
Q3SYZ2
Q24JY4
Q3T160
Q3T0G8
Q76LV1
A8WJR8
Q9XTF3
G1UB61
Q5ABC6
Q5ABC6
Q5ABC6
Q5ABC6
Q5AL49
G1UB61
P51953
P51953
P51953
Q1W668
Q1W668
P68103
P11440
P97377
P11440
P97377
P11440
Q5RAH9
Q5R7D8
Q5R7H4
Q5R7H4
Q5RBH3
Q5RBH3
Q5RBH3
Q5RBH3
Q5RBH3
Q5RBH3
Q5R8T7
Q5R8T7
Q5R8T7
Q5RBG3
Q5RC43
Q5R465
Q5R943
Q5RAH9
Q5RAH9
Q5RAH9
Q5RBS5
Q5RA72
Q5RA72
Q5RA72
Q5RBH3
Q5RBH3
Q5RBH3
Q5RBH3
Q5RBH3
Q5RBH3
Q5R8T7
Q5R8T7
Q5R4K3
Q5R4K3
Q5R4K3
Q5RES4
Q5RES4
Q5RCZ5
Q5R5M7
Q5R5M7
Q5R5M7
Q5R5M7
Q5R5M7
Q5R5M7
Q5RC43
Q5R8Z3
Q5R465
Q5R465
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P43618
P32380
P32380
P32380
P33419
P35734
P53267
P53267
P53267
P53267
P36131
P38991
P38991
P40460
P09959
P09959
P09959
P09959
P09959
P09959
P38634
P39743
P39743
P39743
P03069
P41818
P27472
P27472
Q12246
Q12246
P24867
P24867
P07270
P07270
P07270
P07270
P07270
P20052
P20052
P43565
Q96UT3
Q9QUL6
Q3SYU2
Q3SYU2
Q0VCX4
Q0VCX4
A0JNB0
Q8WML4
Q2HJ27
Q60439
P09445
O09185
O09185
Q60439
Q80ZH1
Q80ZH1
Q60439
Q60439
Q60439
Q9Z2Q8
Q9Z2Q8
Q60439
Q60439
O09185
Q08301
Q9JI55
P69893
P48670
Q60439
O09185
O09185
O09185
O09185
Q7SIA2
P48670
O09185
O09185
O09185
O09185
O09185
O09185
O09185
O09185
O09185
O09185
O09185
P48670
P70096
O09185
Q9QZJ5
Q9QZJ5
Q00366
Q00366
Q00366
P70118
Q00366
Q00366
Q00366
Q00366
Q00366
Q00366
Q00366
P48968
P48968
Q00366
Q00366
Q00366
Q00366
Q00366
Q9ESJ1
P81269
P09416
Q6DEB4
Q6DEB4
Q6GQG3
Q6GQG3
P20911
P20911
Q7ZXH9
Q7ZXH9
D3YN49
Q91618
Q91618
Q91618
Q91618
Q91431
Q91431
Q6DEB4
Q6GQG3
Q7ZXH9
Q63699
Q63699
P39951
P35426
P46892
P46892
P50569
Q63699
P39951
P84024
P84024
P84024
P84024
P84024
P84024
P37176
P37176
Q0VCX4
O02675
Q02399
Q3T0G8
P79100
P79100
Q0VCX4
Q0VCX4
P61635
Q9TUM3
A2VDZ3
A2VDZ3
A2VDZ3
Q2KIA0
Q2KIA0
Q2KIA0
A7MB74
P06494
P06494
P06494
P06494
P06494
P49446
P49187
P49185
P49186
Q9WTY9
Q9WTY9
P49187
P49185
P49186
Q9WTY9
Q9WTY9
P34112
P39951
P39951
Q5EAB2
Q5EAB2
Q5EAB2
Q5EAB2
Q5EAB2
Q5EAB2
Q5EAB2
Q5EAB2
Q21338
Q21338
Q5ZI08
Q5ZI08
Q9DDT5
Q9DDT5
Q99J95
Q641Z4
O80588
Q700C7
Q700C7
Q700C7
Q700C7
Q700C7
Q700C7
Q700C7
Q700C7
Q700C7
Q700C7
Q700C7
Q700C7
Q700C7
Q5BPF3
Q5BPF3
Q5BPF3
Q5BPF3
Q5BPF3
O81108
O80673
Q9ZUZ2
Q9SG12
Q9LET1
O80673
Q9ZUZ2
Q9SG12
Q9LET1
Q9SG12
Q9LET1
Q9TY95
Q39250
Q9MB58
Q9MB58
Q9M7Q2
Q1PDV6
Q1PDV6
Q1PDV6
P48964
P48964
P48964
Q8LAS7
P19456
Q8LAS7
O81445
Q9LTB8
Q05085
Q7FRS8
C7GVI6
P23561
P23561
P23561
P02294
Q92995
P48349
P48349
P48349
P48349
Q07014
P80639
O88597
P52631
Q3SWT0
P52631
Q9QYV0
Q9QYV0
P52631
Q9QXN1
Q9QXN1
Q04964
Q04964
Q04964
Q9V3D5
Q9V3D5
Q9NR20
Q1JQA2
Q1JQA2
Q1JQA2
Q1JQA2
P51866
P51866
P61635
Q6ZWX6
Q9Z2R9
Q9Z2R9
B6V8E6
B6V8E6
Q6URC2
Q6URC2
Q6URC2
B6V8E6
Q9TT90
Q9TT90
Q9TT90
Q9TT90
Q9TT90
Q9TT90
Q9TT90
Q9TT90
Q9TT90
Q9TT90
Q9TT90
Q28923
B6V8E6
Q95MM9
Q95MM9
Q95MM9
B6V8E6
B6V8E6
Q9TUX8
Q29537
Q29537
P60483
P60483
P60483
Q29537
P60483
P60483
P60483
Q5XFN2
Q5XFN2
P50551
Q28514

P08034
P29319
P29319
P29319
P11627
P11627
A2VDV2
P22328
A0MLS5
A0MLS5
Q8MJ26
Q8MJ26
Q8MJ26
Q8MJ26
Q8MJ26
Q8MJ26
Q8MJ26
Q8MJ26
Q8MJ26
P56424
B8XIA5
Q8MJ26
G3V735
Q63065
Q63065
Q63065
Q63827
Q63827
Q63827
Q63827
Q63827
Q63827
Q63827
Q63065
A1YB07
P39743
P39743
P39743
Q02399
P79132
Q28824
Q28824
Q28824
P63243
Q2KJ94
Q5E9Y2
Q02399
Q3I5G7
Q3I5G7
Q03114
P58772
P49139
P10830
P10102
P05772
P10829
O19111
P67998
Q9XT18
Q6TYA7
Q6TYA7
Q08DJ8
Q3ZBT0
Q3T149
Q3T149
Q3T149
A6QQQ9
P53781
P53781
P69341
Q08DJ8
Q08DJ8
Q3ZBT0
Q32KW2
Q08DJ8
O77627
O77627
Q3ZBT0
O02718
O02718
O02718
A7YY54
Q0VBZ9
Q0VBZ9
Q0VBZ9
Q5EAD3
Q5E9A1
Q9BMK9
Q9BMK9
Q9SIZ2
Q9FE78
Q38997
P92958
Q38997
P92958
P15409
P15409
Q91ZZ3
Q9Z0F7
P51682
P51682
P51682
P51682
P25023
P25023
O08565
O08565
O08565
O08565
Q5XFN2
Q5XFN2
Q5XFN2
E2RH47
Q6SLL5
Q865S3
Q8I009
E2RJI4
Q29537
Q5XFN2
Q5XFN2
Q5XFN2
Q8I009
Q29537
Q29537
Q29537
Q921Y0
Q8BYR2
Q8BYR2
O35942
O35942
Q8VHJ5
Q05512
P52785
P52785
P52785
P52785
P52785
P52785
P52785
P52785
Q28055
P68210
Q5ZLY8
Q5ZIF8
Q1L8X2
P56212
P60840
Q28GU6
Q6NVR1
Q28GU6
Q28GU6
Q6NVR1
Q6NVR1
Q5RAK8
Q5RAK8
Q5RAG2
Q5REW7
Q5R444
Q5R7I1
Q5R8P5
Q5R9Y6
P61146
Q5R9Y6
Q5RA10
Q5RA10
Q5RBA4
Q5RBA4
Q5R9I9
P02299
P70118
P56423
P56423
Q4R4S7
Q38PU5
P56423
P56423
P56423
P53601
Q9BGX5
Q4R4X4
P56423
P56423
P56423
P56423
P56423
Q4R4T5
P56423
P56423
Q4R407
Q4R407
Q4R407
P56423
P56423
Q4R562
P56423
P56423
Q4R381
Q4R4S6
Q4R4S6
Q4R4S6
Q4R712
Q4R712
Q4R5B3
Q60HC2
Q4R4X8
Q4R4X4
O13759
O13759
O13759
O13759
P34244
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
C0LGQ9
Q2KJE0
Q2KJE0
Q91974
Q91974
Q9XTN2
Q9XTN2
Q9XTN2
O55173
O55173
Q6P730
Q91615
Q91615
Q91615
Q91615
Q91615
Q91615
Q91615
Q91615
P84770
P84770
P84770
P84770
P84770
P84770
P84770
P84770
P61635
P61635
P61635
Q6TJY3
Q2LGB3
Q2LGB3
P31976
Q9MYX7
Q764M5
O18868
A2ICN5
A2ICN5
A4UTP7
A4UTP7
Q29029
P07313
P07313
P07313
P42930
P42930
Q5BJY9
P02646
P02646
Q6RX08
Q6RX08
P02646
P02646
P02646
P34908
P34908
P70218
Q66L42
Q80XI6
Q8VDG6
O08852
O35182
P36887
P25344
Q5XIS9
Q8CHI5
Q8CHI5
Q8CHI5
Q9P7I2
Q5R733
Q5R733
Q5R997
Q5R997
Q9MZL5
P20428
P20428
P20428
A7MB80
A7MB80
A7MB80
B9DGI8
B9DGI8
B9DGI8
Q93V58
Q5HZ38
Q9FFH3
Q9FFH3
Q9FFH3
Q0WNX9
Q94CL9
Q39204
Q6X5Y6
Q6X5Y6
Q12343
P06242
Q8C8K9
Q9TXJ0
Q9Y899
A0A0K3AV08
A0A0K3AV08
P41823
Q3SZL0
Q95KV0
Q95KV0
Q32LL2
P41110
P09741
P09741
P09741
P09741
Q00969
Q00969
Q00969
Q00969
Q6P6T5
Q6P6T5
Q6S9C0
E2RH47
E2RH47
Q99P96
Q6RX08
P18246
Q9C5Z2
Q24324
Q24324
P20689
Q3B7M7
Q9P7J8
Q12706
Q9DDT2
Q9DDT2
Q9DDT2
Q9YGC1
Q9YGC1
Q9YGC1
Q9YGC1
Q9YGC1
Q9YGC1
Q8JH64
Q8JH64
Q8JH64
Q14258
P80192
P80192
P80192
P70340
P70340
P20794
P20794
P15991
P15991
Q3ZBT0
Q3T149
Q3T149
Q3T149
A6QQQ9
Q3ZBT0
P56211-2
Q60805
Q8JHV9
Q8JHV9
Q8JHV9
A9ULZ2
A9ULZ2
Q91790
Q90W58
O73932
O54992
O54992
Q2EJA0
Q2EJA0
Q2EJA0
P09216
Q9GRU1
Q9GRU1
Q9I8T7
Q3T0N5
Q3T0N5
Q3T0N5
Q3T0N5
Q3T0N5
Q3T0N5
Q3T0N5
Q3T0N5
Q9DGE2
Q9DGE2
Q9DGE1
Q9DGE1
P53670
Q62838
Q62838
Q62838
Q62838
Q62838
Q9QVP4
Q9QVP4
Q8K3H5
Q8K3H5
Q8K3H5
Q8K3H5
Q1EG27
Q1EG27
Q1EG27
Q1EG27
Q1EG27
P70270
Q60932
Q19S50
Q19S50
Q95242
Q95242
Q19S50
Q9TUZ0
Q19S50
Q19S50
Q19S50
P29269
Q19S50
Q9ES70
Q9ES74
Q8IY84
Q03414
Q03414
Q9PVX8
Q7ZXK3
P22211
P22211
P22211
Q8BYR2
Q95ZQ4
Q9C5H5
Q9C5H5
Q9C5H5
Q9C5H5
Q9C5H5
Q9C5H5
P42818
Q39030
Q9LSF1
Q9XF67
O19001
O19001
O19001
O19001
O19001
A0M8S6
A0M8S6
Q8HZP6
Q8HZP6
O19001
O19001
Q6I6F4
Q864S8
O19001
Q864S8
Q53AD2
Q53AD2
P68271
P41685
P57759
P57759
P33435
P53690
P11792
P12688
P12688
P38070
P11792
P38070
P18961
P24583
P9WJB4
P9WJB4
P9WJA8
P9WKD0
P9WKD0
P9WJB5
P9WHW5
P9WHW5
P9WIA1
P9WJB5
P9WHW5
P9WHW5
P9WHW5
P9WHW5
P9WJA9
P9WKD1
P9WKD1
L0T905
P64898
A0QYG2
A0QNG3
A0R2D3
A0QYG2
P9WJA8
P9WJA9
P9WLZ7
P9WLZ7
P9WLZ7
P9WLZ7
P9WLZ7
P9WLZ7
P9WLZ7
O33361
P9WMF8
P9WMF8
O53380
P9WMF9
P9WMF9
O53789
P9WKE5
Q9N5K3
Q9N5K3
Q8AXF4
Q8AXF4
Q8AXF4
P13351
P13351
P30311
Q5R710
P61146
Q5R710
Q0VCE2
Q0VCE2
Q4KLI9
P97832
P97832
Q12518
Q12518
P34758
P34758
P34758
P26630
P26630
P26630
Q99PW1
Q99PW1
F1LM93
F1LM93
P48598
P25044
Q8R5F7
Q9Z2P5
P97431
P97431
P97431
Q2HJ49
P26042
P29269
P29269
P29269
P29269
P29269
Q4A1L5
P42639
P29269
Q62190
Q62190
Q62190
Q78DX7
P46196
P46196
P46196
P46196
Q4R4Q3
Q4R4Q3
Q4R4Q3
Q4R4Q3
Q4R4Q3
P61589
P61589
Q5U2Y1
Q5U2Y1
P32491
P06782
Q9LD83
Q9LD83
Q9LD83
Q9LD83
P07978
P07978
P07978
P07978
P02319
P02319
Q12124
P04386
Q8BG48
Q8BG48
Q8BG48
Q8BG48
Q8BG48
Q8BG48
Q8BG48
P06784
P32233
Q9Z2W1
Q9BYT3
Q5R8M1
A4K2T0
A4K2T0
A4K2Q5
A4K2Q5
Q10S82
Q9SHR7
Q9S7J7
Q9XF87
Q9STF2
P43063
Q8T0S6
Q64729
Q64729
Q64729
Q64729
Q64729
Q64729
Q5CD18
Q5CD18
Q5CD18
Q5CD18
Q5CD18
P80204
P80204
P80204
P80204
P80204
Q9CQE6
Q9CQE6
Q9DAP7
Q9UJT2
Q9UJT2
O54887
O54887
Q8BHX3
P55144
P55144
O08775
P02700
P02700
P02700
P02700
P02700
P02700
P02700
P02700
P02700
P02700
B3SV56
B3SV56
B3SV56
Q9MZA9
P51664
P35567
P24033
P35567
P24033
P24033
P33886
P33886
Q06151
P39008
P14680
Q55D99
P28025
P28025
Q91783
Q91618
Q91618
P12950
P12950
P12950
P12950
P12950
P12950
P27347
Q9LEF5
Q9LEF5
Q5AEB8
P07663
P40917
Q05116
Q05116
Q07192
Q07192
P25323
P25323
P25323
P11837
Q9FEV9
Q869N2
Q91822
Q91822
Q91822
P70032
Q9XTY6
Q9XTY6
P34815-2
P34815-2
P34815-2
P34815-2
Q7T2H4
O34507
O34507
O34507
O34507
O34507
O34507
O34507
O34507
O28471
O30245
P24799
P24799
Q91604
A4K2Y1
A4K2M3
A4K2M3
A4K2P5
A4K2S1
Q9W596
Q9W596
Q8CE90
Q8CE90
Q92040
P24801
Q92123
P13406
P84233
P84233
Q6PI79
Q6PI79
P02302
P02302
Q8HZM6
A5A6M2
Q5REL2
Q5R8R5
P51662
Q08DA8
Q5RBS5
Q5RBS5
Q5RBS5
Q5RBS5
Q6SLL5
Q6SLL5
Q6SLL5
Q6SLL5
Q6SLL5
Q6SLL5
Q6SLL5
Q5FBR4
Q6A548
Q6SLL5
Q6SLL5
Q6SLL5
Q28350
Q29537
Q29537
Q9GLW0
E2RK09
P46529
P46529
P46529
P46529
P46529
P46529
P46529
Q764M9
Q764M9
Q764M9
Q764M9
Q9GLX8
Q9GLX8
P0CY46
A1Y2K1
Q9GKL7
Q9GKL7
Q9GKL7
Q9GKL7
Q9GKL7
Q9GKL7
Q9GKL7
Q9GKL7
Q9GKL7
Q9GKL7
Q9GKL7
E5RQA1
Q9TTY8
Q4QRF4
Q6PI20
Q28D37
Q28D37
Q6P823
Q6P823
Q28D37
Q6P823
Q71LE2
Q80ZH1
Q80ZH1
Q60416
Q60416
Q60416
Q5R902
Q5R902
Q5R902
Q5R902
Q5R902
Q5R902
P56424
P56424
P56424
P56424
P56424
P56424
P56424
P56424
Q6J6I9
P56424
P56424
P56424
P56424
P56424
P56424
P56424
P56424
P56424
P56424
Q6J6I9
P56424
P69895
P56424
P56424
B8XIA5
P61258
A4IFH6
P61013
Q9XTL9
P19889
P11972
Q9MZA9
Q9MZA9
Q9MZA9
Q9MZA9
Q7YRL2
Q7YRL2
Q7YRL2
Q7YRL2
Q7YRL2
Q9MZA9
P51664
P51664
Q9MZA9
P51664
P51664
P51664
Q28647
Q28647
Q28647
Q28647
Q28647
Q28647
Q60495
Q60495
P53601
P53601
Q4R7Y4
Q5IS80
A2T6Y4
Q5R1W8
Q5IS80
Q5IS80
Q2QLF2
P79307
P79307
Q6RVA9
P63246
P58108
P58108
P58108
Q08DY8
Q09138
Q09138
Q09138
Q09136
Q09136
Q09136
Q28948
Q5RDH5
Q5RD00
Q5RDH5
Q5RDH5
Q5RDH5
Q5RDH5
Q5RDH5
Q5RE28
Q5RBA5
Q98TY9
Q9U389
P10731
F1MRK3
Q9TT90
Q9TT90
Q9TT90
Q8MIK0
Q8MIK0
Q8MIK0
Q8MIK0
Q8MIK0
Q8MIK0
Q8MIK0
Q8MIK0
Q8MIK0
Q8MIK0
Q8MIK0
Q8MIK0
Q8MIK0
Q8MIK0
O97952
O97952
O97952
Q6QT55
Q6QT55
Q6QT55
Q6QT55
Q6QT55
Q6QT55
Q6QT55
Q6QT55
Q6QT55
Q6QT55
Q6QT55
Q6QT55
Q6QT55
Q6QT55
O97775
O97775
O97775
O97775
O97775
O97775
O97775
O97775
O97775
O97775
O97775
O97775
O97775
O97775
Q9GKL7
Q9GKL7
Q9GKL7
P49699
P49699
Q5R5A0
Q5RAX1
Q5RAX1
Q5RAX1
Q2IBD6
Q2IBD6
Q5R4K9
Q5R4K9
Q5R4K9
Q5R5M7
Q5R5M7
Q5R616
A2SW69
Q09YJ1
Q09YJ1
A1YES6
A1YFZ3
Q865S3
Q865S3
Q865S3
Q9GLW0
Q865S3
P24643
Q865S3
Q865S3
Q95153
Q29537
Q2KIG1
Q17QJ0
A6ZZR4
A6ZZR4
Q5R9C9
A5A6N3
Q5IS70
Q5RBU9
Q5RBU9
Q5RBU9
Q5RBU9
Q5RBU9
Q5RBU9
Q6R755
Q6R755
Q6R755
Q9JJV8
Q9JJV8
Q9JJV8
Q5R878
Q5RBA4
Q5R4L2
P17120
Q28H51
Q28ER3
B1WAR9
B2GU58
Q8I009
Q8I009
E3SCZ8
E3SCZ8
Q9WUR6
E3SCZ8
E3SCZ8
Q9WUR6
Q9WUR6
Q9WUR6
Q6I6F4
Q6I6F4
Q6I6F4
P41685
P41685
A9JTP3
A9JTP3
A9JTP3
O70526
O70526
Q28642
Q28642
Q95153
Q29537
Q6J6I8
Q9GKK8
Q9GKK8
Q864S8
Q864S8
P41685
Q5RDC8
Q5RAD2
Q6YNX6
Q5R440
Q5R4K3
Q5R4K3
Q5R4K3
Q5RES4
Q5RES4
Q07DV9
Q2QLG6
A0M8S7
Q2IBF0
Q2QLB0
Q108U7
Q2QL90
Q07E25
Q07DY2
Q2QLH7
A0M8R6
Q2IBD7
Q2IBC1
Q09YH8
Q6B3Y2
O02827
O02827
Q07DW0
Q07DW0
Q2QLG7
Q2QLG7
Q2QLD3
Q2QLD3
Q2IBF3
Q2IBF3
Q0MQI8
Q2QLB1
Q2QLB1
Q108U8
Q108U8
Q07E26
Q07E26
Q2QLH8
Q2QLH8
Q2QLF3
Q2QLF3
Q0MQI9
A0M8R5
A0M8R5
Q09YN7
Q28685
Q9MZ19
Q2IBC2
Q2IBC2
Q09YH9
Q09YH9
Q08301
P37882
Q3ZBL9
Q3ZBL9
Q4R7U4
Q9R1A0
Q9R1A0
Q4R4R6
Q8HXW3
P48734
P48734
P48734
Q5E9Y0
P48734
P51958
Q9DGD3
Q5RCH1
Q5RCH1
Q5RCH1
Q5E9Y0
O55076
P48963
Q05826
Q5BQN8
Q5BQN8

P61145
Q8AYC9
Q6BBL6
Q8QGQ6
Q8QGQ6
A8X6H4
P37803
P37803
P37803
Q9GK38
Q9GK38
Q9GK38
Q9GK38
Q9GK38
Q08E26
Q0IHT3
Q9XSI1
P42072
Q6TYA8
Q6TYA8
Q29101
Q0Z8U2
Q0Z8U2
A6XKM2
A6XKM2
P25930
P25930
P25930
P25930
Q8HZU1
Q8HZU1
Q8HZU1
Q8HZU1
Q3LSL6
Q3LSL6
Q3LSL6
Q3LSL6
O62747
O62747
O62747
O62747
P56498
P56498
P56498
P56498
Q28474
Q28474
Q28474
Q28474
P79394
P79394
P79394
P79394
P61072
P61072
P61072
P61072
P56491
P56491
P56491
P56491
Q6P730
P14607
P14607
P02541
P02541
Q3MHP5
P62629
Q66RN5
Q66RN5
A2Q0Z0
A2Q0Z0
Q5R1X2
Q5R1X2
A2T756
Q5R4R8
Q5R7C0
Q5R7C0
P68105
A0SXL6
A0SXL6
A0SXL6
P49032
Q5R8Z3
Q5R8Z3
P55245
P55245
P81623
P81623
O77656
Q9GLE4
P28053
P52555
P52555
P23097
Q10739
Q9TV98
Q9TV98
P79892
Q8HZQ5
Q95209
Q8HZQ5
Q5RF31
C8BKD0
Q28566
P51664
P51664
P03969
Q60487
P48798
Q5IS69
P48799
P13109
Q9Z2Q8
Q9Z2Q8
Q9Z2Q8
Q9Z2Q8
Q63980
Q9Z2Q8
Q9Z2Q8
Q9Z2Q8
Q9Z2Q8
Q8HZP6
Q8HZP6
Q8HZP6
Q8HZP6
O02761
O02761
Q6S9E0
O02761
O02761
Q810W5
Q810W5
Q810W5
Q810W5
Q810W5
Q810W5
Q810W5
Q810W5
Q810W5
Q2EF73
Q810W5
A4L7N3
A4L7N3
A4L7N3
B5KFD7
A4L7N3
A4L7N3
A4L7N3
A4L7N3
A4L7N3
Q5RA72
Q5RA72
Q5RA72
Q5RBA4
D2HXI8
Q5RCC9
P84246
P62801
P62796
Q5RCS7
Q5R7U1
Q5R5M7
Q5R5M7
P62799
Q28DR4
P57100
P57100
Q28555
Q28555
Q0PGG7
Q0PGG7
Q9GKX8
Q9GKX8
Q4R4T5
P61142
P42929
P42929
P42929
P42929
P42929
P42929
P42929
P42929
Q5S1U1
Q5S1U1
Q5S1U1
Q5S1U1
Q5S1U1
Q5S1U1
Q7YR42
Q7YR42
Q7YR42
Q9XT09
A7X8B3
Q9N0T5
P09867
P09867
P09867
P09867
Q08353
Q764M6
Q7YS99
B8XX90
Q95KV0
Q95KV0
Q4JF28
Q58DJ0
Q58DJ0
Q2KI99
Q6P4Y6
Q6P4Y6
Q6P4Y6
Q6P4Y6
Q8MJ44
O62732
P25321
Q9MZD9
Q9JHJ9
Q9JHJ9
Q76II0
Q76II0
O97799
O97799
Q28317
Q28317
Q28889
Q28889
Q2HWD6
Q2HWD6
P10102
P05772
P10829
Q4R4U2
Q5R4K9
Q5R7A7
Q5R4K3
Q5R4K3
Q5R4K3
Q5REW7
Q5REW7
Q5R444
Q5R444
Q6TJY3
Q00655
Q5PXS1
Q9N261
Q6ZPK7
D3ZG83
Q66HA1
P25188
P83487
P06906
P81558
P56950
Q7YRZ8
P56951
Q60524
A2ICN5
A2ICN5
A2ICN5
A4UTP7
A4UTP7
A4UTP7
Q5REW7
Q5REW7
Q5REW7
Q5R444
Q5R7U1
Q5RBA4
Q5R5M7
Q5R5M7
Q5RA03
Q5RA03
Q5R7U1
Q5R5M7
Q5R5M7
Q9N272
Q9N272
Q95NE7
Q95NE7
Q9N272
Q9N272
Q95NE7
Q95NE7
Q9N272
Q9N272
Q95NE7
Q95NE7
Q9N272
Q9N272
O02812
O02812
O02812
O02812
O02812
O02812
O02812
Q95NE7
O18927
Q9XSZ5
O62806
Q95220
P13943
Q9XT90
P21692
Q5RES1
Q9DGE0
Q9DGE0
A7MBD1
A7MBD1
A7MBD1
Q29029
Q29029
P35566
P35566
P35566
P49032
P49032
Q28350
Q6A548
Q28350
P68271
P41685
B8XIA5
A1YG22
A1YG22
A7X8B5
P23583
P23583
A7X8B3
P23583
Q28566
Q28566
Q5RBA4
Q5RBA4
Q5RBA4
Q5RBA4
Q7YS81
Q7YS81
Q7YS81
P49812
P49812
P49812
Q4R630
P34942
P63048
P62992
P0CG53
P0CH28
Q0MQB6
P0CG67
P0CG66
Q0MQB7
P0CG65
P0CG64
P0CB89
Q5RBF2
Q5RBF2
Q5RBF2
Q5RBF2
Q5RBF2
Q5RBF2
Q8WNU8
A2BD05
P59895
D3ZBE5
Q5R1P3
Q5R410
Q28269
Q28269
Q2T9U2
Q5R829
Q6AYX5
Q861Q8
Q5R923
Q5RBA5
P67938
P67938
P67938
P67938
P67938
P67938
P67938
P67938
P67938
P67938
P67938
P67938
P67938
P67938
P67938
P67938
Q29537
Q29537
Q29537
Q29537
Q29537
Q5FBR4
Q9WUR6
Q9WUR6
Q9WUR6
Q9WUR6
Q9WUR6
Q9WUR6
Q9WUR6
Q9WUR6
Q9WUR6
Q9WUR6
Q9WUR6
Q9WUR6
Q9WUR6
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q8SPZ3
Q29480
Q29480
Q29480
Q29480
Q29480
Q29480
P41685
P41685
P41685
P41685
P41685
P41685
P41685
P41685
P41685
P41685
P79892
P79892
P79892
P79892
P79892
P79892
P79892
P79892
P79892
Q95330
Q95330
Q95330
Q95330
Q95330
Q95330
Q95330
Q95330
Q95330
Q95330
Q95330
Q95330
Q95330
P06186
P51664
P51664
P51664
P51664
P51664
P51664
P51664
P51664
P51664
Q5RC51
Q5R7I1
Q5R7I1
Q5R8S3
A1YF08
A1YF08
A1YG85
A2T756
Q6QNF3
Q6QNF3
Q6QNF3
P83509
P00949
Q4R383
Q4R4K6
Q4R4K6
Q8R4R9
A7X8B7
A7X8B7
A7X8B5
A7X8C7
A7X8C7
A7XW16
Q5RFD3
A1YF19
A2T767
Q7JJU6
Q8WP14
Q5R1W8
Q8MKI8
P70099
P70099
O12944
Q5R5M7
Q5R5M7
P24406
P50551
P50551
P50551
Q5REY6
P63050
P63052
P63053
P0CG68
P0C276
P0CG55
Q28521
Q28521
Q28521
Q28521
A5A6H4
A5A6H4
A5A6H4
A5A6H4
Q5R4N9
P62978
P0CG54
Q4R4K6
Q4R4K6
Q4R633
Q9XT18
A6ZYV5
A6ZYV5
A6ZYV5
A6ZWC8
C7GJ78
Q9V460
Q9V460
O97676
O97676
O97676
Q1JPZ3
Q9TUM3
Q9TUZ0
Q9GKL2
E1C7U0
A4K2W5
Q4R712
Q4R712
Q7SIA2
P61140
P61140
P61143
P61143
P61144
P61144
P61145
Q9GKK5
P43347
A5A6K2
A5A6K2
P61288
P61288
P43348
P43348
O46680
O46680
O46680
O46680
O46680
Q8MKD5
Q8MKD5
Q8MKD5
Q8MKD5
Q697L1
Q697L1
Q8MKD5
Q863B6
Q863B6
Q863B6
Q863B6
Q863B6
Q5PYI0
Q5PYI0
Q5PYI0
Q5PYI0
Q5PYI0
P50751
P50751
P50751
P50751
Q697L1
Q6R5A3
Q6R5A3
Q6R5A3
Q6S9E0
Q6S9E0
A7YWI9
A7YWI9
Q8MKD1
E7EZF3
P45879
Q9MZ16
Q9TT15
Q9Z2L0
P48670
P48670
Q4R4X4
Q4R4X4
Q5R1W8
Q5R1W8
Q5R1W8
D6C652
D6C652
D6C652
D6C652
Q32NJ6
D6C652
D6C652
D6C652
D6C652
Q32NJ6
Q1L8J7
Q1L8J7
Q1L8J7
Q1L8J7
Q1L8J7
Q1L8J7
Q1L8J7
Q1L8J7
H2LBU8
H2LBU8
H2LBU8
H2LBU8
H2LBU8
H2LBU8
H2LBU8
H2LBU8
Q24JY4
O43736
Q9HCU5
Q6PDL0
P51150
Q9CXC9
Q9NRM6
Q80UG8
Q80UG8
Q80UG8
Q80UG8
Q80UG8
Q14679
Q8BVP5
Q8BVP5
P0DN41
Q1WK23
O02722
Q05655
Q13153
P31749
P31749
P05132
Q02156
Q02750
P18654
P18654
P18654
P36507
P17612
O00141
O00141
Q63531
O15530
O15530
O15530
O15530
O15530
O15530
P05106
P05106
P08559
P08559
P08559
P31750
P23443
P23443
P23443
P23443
Q16513
Q16512
Q99683
Q9HBY8
Q06226
P31751
Q05513
P09217
Q96BR1
Q9Y243
Q15418
P00558
P29804
P29804
P29804
P29803
P29803
P29803
P35486
P35486
P05132
P18654
P08559
P31750
Q9D2E1
P35486
P35486
P35486
P35487
O00141
O00141
P08559
P08559
P08559
P29803
P29803
Q96SU4
P35486
P09215
Q06226
P09217
P26284
P26284
P26284
O08874
Q63433
P08559
P08559
P29803
P29803
P31946
P35486
Q04917
P08559
P08559
P08559
P29803
P29803
P35486
P35486
P29804
P29804
P29804
P29804
P29804
P29804
P11960
P11960
P11960
P11960
P12694
P12694
Q00972
P21953
P35486
P35486
P35487
P35486
P35486
P35487
P35487
P35486
P35486
P35487
P26284
P26284
P26284
P26284
P26284
P26284
Q06437
P16387
A7MB35
A7MB35
A7MB35
A7MB35
A7MB35
A7MB35
A7MB35
A7MB35
A7MB35
Q8HXW9
Q8HXW9
Q8HXW9
Q8HXW9
Q8HXW9
Q8HXW9
Q8HXW9
Q8HXW9
Q8HXW9
A5A6L0
A5A6L0
A5A6L0
A5A6L0
A5A6L0
A5A6L0
A5A6L0
A5A6L0
A5A6L0
Q5R490
Q5R490
Q5R490
Q5R490
Q5R490
Q5R490
Q5R490
Q5R490
Q5R490

In [103]:
len(res_ls)

30752

In [104]:
dat['substrate_seq'] = res_ls

In [105]:
def get_uniprot_entry_2(acc):
    url = "https://legacy.uniprot.org/uniparc/?query="+acc+ "&format=tab&columns=id,sequence"
    try:
        urlData = requests.get(url).content
        rawData = pd.read_csv(io.StringIO(urlData.decode('utf-8')),sep = '\t').iloc[0,1]
    except:
        rawData = ""
    return rawData

In [106]:
get_uniprot_entry_2("P18433-2")

'MDSWFILVLLGSGLICVSANNATTVAPSVGITRLINSSTAEPVKEEAKTSNPTSSLTSLSVAPTFSPNITLGPTYLTTVNSSDSDNGTTRTASTNSIGITISPNGTWLPDNQFTDARTEPWEGNSSTAATTPETFPPSVALSSLLVIVFIIIVLYMLRFKKYKQAGSHSNSKQAGSHSNSFRLSNGRTEDVEPQSVPLLARSPSTNRKYPPLPVDKLEEEINRRMADDNKLFREEFNALPACPIQATCEAASKEENKEKNRYVNILPYDHSRVHLTPVEGVPDSDYINASFINGYQEKNKFIAAQGPKEETVNDFWRMIWEQNTATIVMVTNLKERKECKCAQYWPDQGCWTYGNIRVSVEDVTVLVDYTVRKFCIQQVGDMTNRKPQRLITQFHFTSWPDFGVPFTPIGMLKFLKKVKACNPQYAGAIVVHCSAGVGRTGTFVVIDAMLDMMHTERKVDVYGFVSRIRAQRCQMVQTDMQYVFIYQALLEHYLYGDTELEVTSLETHLQKIYNKIPGTSNNGLEEEFKKLTSIKIQNDKMRTGNLPANMKKNRVLQIIPYEFNRVIIPVKRGEENTDYVNASFIDGYRQKDSYIASQGPLLHTIEDFWRMIWEWKSCSIVMLTELEERGQEKCAQYWPSDGLVSYGDITVELKKEEECESYTVRDLLVTNTRENKSRQIRQFHFHGWPEVGIPSDGKGMISIIAAVQKQQQQSGNHPITVHCSAGAGRTGTFCALSTVLERVKAEGILDVFQTVKSLRLQRPHMVQTLEQYEFCYKVVQEYIDAFSDYANFK'

In [107]:
for i in range(len(res_ls)):
    if res_ls[i] == '':
        print(i)
        res_ls[i] = get_uniprot_entry_2(dat['substrate'].iloc[i])

2
3
830
873
973
2438
2510
2702
2703
2704
2705
2726
2727
2776
3697
4896
4949
4950
4951
4952
5677
5683
5785
7057
7058
7059
7060
8260
8261
8575
8576
8742
8743
8744
8745
8746
10012
10013
10014
10160
10861
11741
12307
13307
13936
15754
15755
16071
16092
16093
16125
17467
17468
17469
19005
20033
20067
20068
20069
20070
20800
21007
21008
21488
21712
22957
22958
22959
26960
27588
27589
27605
27606
27616
27622
27624

In [108]:
dat['substrate_seq'] = res_ls

In [109]:
wierd_accs = []
nan_accs = []
unmap_accs = []
for i in range(dat.shape[0]):
    s = dat.iloc[i,:]
    print(len(str(s["substrate_seq"])))
    print(s["p_ind"]-1)
    if (str(s["substrate_seq"]) == 'nan'):
        nan_accs.append(i)
    else:
        try:
            is_valid = s["substrate_seq"][s["p_ind"]-1] == s["p_aa"]
            if not is_valid:
                unmap_accs.append(i)
        except:
            wierd_accs.append(i)

202
182
1122
258
793
203
793
179
463
301
463
283
1235
611
1235
306
1235
23
296
236
296
229
296
32
296
20
1255
1223
737
725
285
190
285
199
285
280
285
194
390
369
390
302
390
327
390
319
390
358
390
303
390
314
390
378
390
347
610
503
755
634
1270
301
210
142
210
22
210
23
271
216
271
226
585
357
482
472
536
230
484
474
769
757
769
744
676
217
676
502
676
298
676
301
676
644
676
303
676
294
676
140
627
4
871
161
871
174
871
188
483
73
335
245
335
240
645
285
398
30
398
279
398
236
398
184
398
185
750
726
468
128
468
109
468
178
249
234
249
235
87
64
87
41
456
280
550
404
770
23
807
34
912
741
912
737
912
411
1205
1178
2171
1673
2171
1927
2171
527
2171
532
107
43
107
63
212
23
212
78
212
43
212
144
212
45
212
24
597
39
607
325
631
507
631
509
136
44
630
475
630
439
195
146
393
45
1659
312
824
734
394
359
882
789
1242
573
1242
322
1242
306
1242
440
350
333
295
20
147
37
545
209
545
265
638
282
404
82
539
412
918
889
243
5
243
220
440
354
933
565
575
186
473
28
326
317
326
220
834
472
781
714
352
323
352
324
483
20
147
56
86
68
930
447
514
122
770
726
420
8
198
2
736
615
2414
88
452
311
1390
984
394
359
394
360
273
28
273
96
527
166
499
288
536
11
468
170
187
152
690
132
1482
1302
441
292
441
323
441
351
441
257
297
14
933
399
636
288
211
143
1210
677
440
348
1807
938
1807
931
664
21
239
69
382
367
318
160
788
595
815
647
292
76
323
321
339
314
339
153
445
52
496
424
246
59
221
105
351
91
3
1223
201
180
582
70
582
296
367
177
155
130
253
76
253
8
279
209
299
18
299
17
299
13
299
16
446
45
446
63
202
182
1235
611
1235
306
1235
23
296
229
296
148
737
725
737
715
737
4
285
194
285
280
285
199
390
319
390
314
390
327
390
369
390
302
390
358
390
303
390
378
390
347
1270
301
1270
272
210
198
210
22
210
142
210
43
210
41
210
23
585
357
482
472
769
744
769
757
769
759
627
4
468
128
468
141
468
178
807
750
912
737
912
741
912
411
1205
496
2171
1927
2171
1841
2171
527
2171
532
2171
1842
2171
1673
2171
1516
107
43
107
63
212
23
212
43
212
24
212
144
212
45
212
78
136
5
630
475
630
345
630
439
630
346
630
254
195
146
393
376
393
370
393
375
393
377
824
734
350
313
350
337
350
333
350
316
350
331
350
326
147
37
404
82
539
412
933
251
933
242
326
220
326
157
326
317
483
20
147
56
420
8
198
2
198
139
2414
88
1390
984
394
359
394
365
187
152
164
145
164
152
164
144
2139
1643
2139
1896
630
446
630
536
487
477
487
397
487
395
382
363
382
367
382
368
382
371
382
364
382
372
398
362
771
614
771
601
308
256
308
272
308
213
308
289
308
298
798
784
619
3
619
12
619
6
2336
897
2336
773
508
161
508
158
838
501
838
773
838
819
838
703
838
143
838
799
907
848
907
835
466
9
466
4
466
7
466
8
466
6
1234
1104
829
203
829
179
907
857
684
233
684
273
719
497
719
493
719
489
902
861
630
602
630
148
630
276
742
671
1484
1302
1484
1322
248
209
248
232
248
242
906
835
906
833
906
848
441
351
441
257
441
323
441
292
441
304
130
103
529
306
925
7
925
169
1257
1171
478
392
478
385
478
396
478
380
142
71
495
433
495
435
765
20
2005
609
2005
1505
2005
575
259
143
259
125
259
193
259
122
2085
2081
480
472
480
307
551
535
117
63
1480
736
1480
659
1480
794
1480
812
1480
681
1480
640
1480
685
357
132
202
143
1960
1915
2440
69
444
414
427
50
933
399
636
387
920
578
340
196
340
202
648
498
648
42
683
4
683
5
462
156
559
495
1203
494
380
156
1210
677
1255
685
520
460
299
38
756
176
756
180
1214
1151
1214
1144
878
875
878
705
878
709
968
878
498
39
172
9
172
1
172
2
1290
1247
201
30
737
315
737
233
737
367
656
265
424
12
586
566
188
180
1233
317
413
374
413
353
1203
838
415
392
415
327
415
369
415
396
415
328
415
391
726
725
726
712
726
702
285
203
285
82
285
83
476
171
503
91
503
138
503
263
503
135
503
130
503
99
503
397
503
118
503
419
503
133
503
102
503
115
503
283
503
258
4544
4519
4544
4522
4544
4459
4544
4516
92
87
1159
889
1280
660
1280
666
1280
670
709
429
627
178
627
211
627
68
915
861
407
398
474
86
591
454
591
461
553
35
1114
674
1141
291
1141
427
1141
292
1141
311
1141
437
1141
491
1141
464
1141
567
92
82
92
87
92
88
222
192
871
823
533
11
780
38
780
434
171
66
171
74
730
653
730
298
587
432
34350
12021
34350
11877
169
53
169
159
169
108
169
149
169
6
169
130
169
44
169
9
424
390
424
384
424
396
424
378
271
255
346
27
346
26
1023
22
729
298
729
653
2169
1926
92
82
92
87
92
88
908
845
908
867
345
265
345
287
249
235
211
22
211
23
204
33
204
95
1237
1230
509
41
360
200
420
8
235
44
343
330
343
323
343
328
343
336
343
144
199
184
199
179
199
10
1822
1359
1822
1355
1822
1363
1822
1493
839
800
839
501
687
643
374
340
323
179
360
356
279
187
505
120
505
339
505
366
239
69
2326
2255
418
162
332
158
332
166
332
162
332
169
707
9
707
17
756
160
756
164
382
372
382
371
382
367
689
28
1135
1113
1135
1101
391
372
303
276
730
276
427
314
908
867
595
590
339
25
339
11
1034
26
391
200
391
3
391
192
938
878
398
362
398
369
166
23
166
22
760
23
883
879
140
137
419
140
419
84
788
595
435
377
665
574
1599
1184
904
656
358
339
358
161
358
76
358
338
763
722
2016
1502
503
199
1752
1423
976
740
976
745
976
958
976
820
486
40
976
891
209
193
467
345
407
225
407
131
407
233
234
47
489
1
295
289
295
284
434
407
865
91
921
699
921
711
671
58
390
371
590
184
590
460
590
567
864
777
1132
517
1132
173
912
239
486
178
486
27
486
172
486
301
486
299
486
240
486
51
486
177
593
594
593
579
593
590
593
575
490
20
210
184
443
228
443
227
171
66
171
64
1499
1235
1499
1225
1499
1220
372
343
369
342
522
127
245
234
374
275
374
86
1657
1442
617
257
617
258
672
249
672
637
672
656
206
186
126
31
355
15
355
26
452
180
452
172
1382
1063
1382
1061
1382
1374
290
220
336
328
521
337
361
349
361
346
361
356
363
353
323
302
323
321
1007
944
696
164
938
895
938
888
938
896
938
889
359
157
339
314
339
153
1687
506
1687
514
908
867
908
845
333
161
333
165
333
168
333
157
242
40
355
76
320
198
320
196
320
94
320
102
320
230
320
222
320
191
281
127
281
123
281
131
281
134
928
921
301
287
301
215
301
206
301
210
301
296
660
377
660
376
660
364
660
249
660
159
949
928
949
922
1166
930
1166
9
1166
673
1166
567
556
295
556
285
556
327
556
549
556
291
1139
962
508
134
508
144
508
171
737
367
472
134
472
153
580
261
580
164
61
31
298
145
468
229
468
178
206
186
206
137
2099
2086
2099
2081
2099
2076
655
352
655
508
655
117
655
296
400
391
400
350
416
76
271
204
271
203
472
91
103
81
493
38
2818
2807
623
369
206
186
890
730
431
157
431
322
132
7
210
194
272
267
272
270
299
283
367
265
269
156
269
238
458
432
458
439
889
710
889
137
768
23
1072
814
1166
694
1166
1150
1092
1071
523
34
523
99
514
17
514
14
460
280
460
275
460
287
765
741
765
701
297
174
1090
542
1090
489
221
192
635
14
635
20
635
8
635
7
549
27
549
12
549
33
549
51
206
197
449
164
449
157
366
348
366
347
0
21
205
28
211
203
756
34
523
464
523
4
1073
1051
1171
900
654
613
654
614
501
116
852
540
352
37
848
11
848
35
445
52
271
261
480
192
495
433
78
35
915
861
617
365
684
407
783
235
480
472
35213
12883
35213
12741
1386
1329
620
6
620
11
594
305
594
312
496
424
567
330
504
51
349
136
1078
887
1078
874
371
340
371
153
105
99
533
522
533
39
0
21
298
188
298
203
298
207
298
212
298
293
620
321
1216
886
614
39
816
706
350
112
350
116
226
168
330
324
679
407
1241
1124
1241
1119
182
147
853
111
472
65
735
514
735
323
1236
1199
386
327
204
95
201
180
147
37
846
38
894
1
1216
886
224
86
533
528
735
723
421
98
421
95
524
34
994
540
279
135
226
40
613
14
485
414
2725
2623
2725
2622
588
311
588
330
339
25
572
333
572
331
572
299
572
322
572
515
572
517
849
106
849
108
509
144
509
134
509
171
377
365
377
362
377
372
211
22
211
23
211
160
486
312
2726
2624
288
72
2322
2251
486
144
486
163
356
17
356
79
415
173
415
180
415
52
415
297
415
160
415
190
415
175
337
314
337
312
337
315
78
35
352
150
352
322
534
42
332
273
332
298
451
164
562
173
638
88
638
89
404
64
295
9
404
214
302
284
561
224
1214
65
1214
69
270
164
145
57
407
398
785
54
278
9
223
171
1134
1112
1134
1100
472
153
472
134
582
296
582
70
461
411
486
312
763
184
211
190
1977
847
667
483
1122
258
1122
497
285
190
1270
301
2171
1699
2171
1574
2171
1516
2171
438
630
455
147
129
918
781
781
551
781
471
781
331
930
486
555
66
555
69
555
57
2139
1544
2139
1486
2701
149
52
16
52
15
350
90
350
55
1906
1761
1906
1748
630
458
630
437
466
25
466
71
466
38
466
411
466
65
487
141
487
395
487
139
487
397
382
305
382
371
382
372
382
256
382
324
382
295
382
254
382
364
382
363
382
313
382
327
382
368
382
296
382
243
382
329
467
239
467
259
467
109
469
309
469
312
469
245
461
310
2169
1602
398
369
398
265
398
260
2514
2436
2514
2463
2514
2425
2514
2452
478
309
478
313
478
304
478
305
390
179
390
223
396
380
396
381
396
383
396
325
396
384
396
336
396
386
396
392
492
420
478
305
478
285
478
304
708
233
724
72
771
58
771
483
771
25
771
601
771
72
771
634
771
740
771
489
308
272
244
53
706
604
338
179
338
148
338
26
798
787
798
788
1615
240
1615
286
501
34
501
43
501
18
701
693
701
697
262
45
262
213
262
195
261
153
261
154
2166
1569
2166
1511
911
38
911
231
619
12
2336
783
2336
895
2336
2125
167
156
167
160
149
15
31
4
1068
864
488
18
716
297
716
419
716
445
716
298
716
290
716
442
716
418
1199
870
441
284
441
281
441
256
441
250
528
18
528
70
261
212
542
25
542
36
1961
1939
400
267
699
686
521
410
198
9
508
102
508
159
1042
781
1042
807
1154
115
838
501
838
703
4967
2813
4967
2807
481
87
907
848
907
644
466
82
1234
536
829
179
829
203
200
37
907
848
684
273
719
474
719
497
719
658
719
501
719
493
902
861
630
12
1905
1886
1905
1899
31
4
843
738
572
554
327
132
327
141
1873
1574
1308
1137
31
4
2647
2522
4953
2803
4953
2797
742
705
841
437
1482
1302
2120
1500
525
408
497
39
497
18
466
38
699
260
778
188
675
43
1429
846
1484
1302
448
422
446
228
706
604
248
209
248
232
555
14
906
566
674
271
184
106
140
128
441
261
441
415
960
866
478
144
307
90
460
425
406
119
130
115
818
108
818
50
1052
842
529
229
52
16
4966
2806
4966
2812
673
298
1210
1070
1210
767
1210
1080
1210
1165
1210
1069
1255
1171
450
95
450
92
450
89
489
285
327
118
2353
1197
768
336
768
334
1464
1458
724
72
1202
1175
2016
454
2016
483
2016
456
2016
11
2016
60
2016
463
2016
570
2016
527
2016
496
2016
1924
2016
509
2016
10
2016
576
2016
1933
2016
538
2016
515
2016
459
2016
482
2016
16
2016
1919
2016
1884
2016
666
2016
19
2016
1936
2016
1864
2016
2006
2016
1502
2016
470
2016
1997
2016
1002
2016
569
2016
663
2016
41
2016
498
434
289
749
514
397
387
956
361
956
417
956
771
202
30
202
88
202
65
202
86
566
171
1052
842
1340
1134
1340
1161
1340
765
1340
751
1340
1221
1340
1110
1340
1106
1340
1104
1340
779
427
91
427
86
3
2015
3
2798
478
285
2019
570
155
35
1038
1028
970
321
970
82
1434
851
960
470
1980
641
1980
540
1980
560
1980
640
1577
1381
647
554
1464
1458
446
21
446
19
446
20
2564
2253
1122
497
1122
258
210
22
210
149
210
23
335
121
550
400
1205
1178
597
549
393
17
393
19
1242
793
736
636
2414
88
1906
1748
1068
864
198
197
699
260
441
230
441
213
441
355
441
395
441
261
441
421
529
120
169
29
651
509
651
634
1480
736
1480
767
1480
812
617
383
504
60
504
93
636
425
1455
346
270
107
270
173
270
157
270
79
270
176
270
23
270
147
839
760
721
303
721
124
721
117
672
411
596
99
510
74
211
150
559
493
559
387
559
485
559
495
559
182
559
359
470
436
2549
2445
681
242
1203
1176
1203
632
380
277
2346
79
317
292
317
32
1154
517
1154
514
317
49
331
24
1766
1345
1766
1227
442
350
622
544
622
581
529
104
725
397
1051
316
1051
466
1051
776
1051
554
505
465
673
625
673
554
673
178
673
587
673
412
673
398
673
29
1106
407
782
451
311
31
1210
891
1575
670
1575
770
1575
810
1859
1336
1335
791
1335
721
1099
129
524
297
524
335
474
312
416
388
1255
899
798
75
424
352
751
765
921
803
450
387
450
92
450
95
450
89
865
567
1050
637
1050
555
519
469
857
443
857
540
1076
854
486
405
178
172
390
384
629
95
1047
371
1168
595
1168
236
391
307
573
520
940
782
520
460
1203
130
1203
136
606
70
389
100
743
334
440
157
197
196
766
728
991
947
655
648
655
21
635
177
701
658
1809
1388
105
28
2458
221
596
350
440
293
1125
913
1236
721
1014
176
646
70
1212
76
1212
241
465
8
1807
1386
1972
1316
975
794
248
132
521
117
1198
120
1198
118
1198
1113
390
313
390
294
746
310
710
327
685
520
685
256
1478
901
2016
100
605
373
605
407
605
432
424
255
145
57
341
325
517
355
613
591
613
558
1232
800
525
120
424
255
1036
443
956
792
1255
699
1255
230
1255
498
1255
620
1255
252
1255
659
1255
589
351
56
2345
78
846
745
425
313
612
80
1912
96
358
174
400
152
2002
98
522
506
338
166
1632
729
290
194
290
282
419
189
1458
901
277
221
759
558
678
80
587
173
587
551
587
509
587
445
587
143
587
134
587
125
587
493
587
109
318
179
318
179
591
176
464
8
605
81
402
263
804
765
1391
310
1280
350
182
117
1122
497
1122
258
2414
23
149
15
1961
1939
327
132
149
44
327
132
327
118
551
535
920
483
589
543
2442
300
2441
300
299
90
489
331
430
52
2442
301
473
11
473
335
473
12
1084
245
1084
466
1084
631
149
44
149
44
492
26
492
193
492
24
2220
2125
1042
37
1122
497
1122
258
824
378
1074
504
437
218
2346
79
725
397
673
625
673
554
673
178
673
587
673
412
673
398
1106
407
1106
101
1106
1073
782
451
857
443
857
540
1168
595
390
14
390
17
1014
176
367
333
797
537
797
176
1013
176
552
109
375
316
552
365
524
19
756
176
756
180
1307
710
552
171
581
283
581
227
581
494
1972
1316
1198
120
1198
118
1198
1113
390
313
390
294
612
80
201
151
1040
527
619
589
252
149
805
679
342
171
343
44
448
93
1391
310
1122
497
1122
258
755
655
736
636
2414
88
198
156
198
197
271
62
327
118
327
132
2346
24
1076
854
197
169
197
196
920
483
489
331
498
18
498
39
722
293
722
91
722
90
574
52
574
47
543
16
543
21
145
58
646
515
938
478
938
343
938
177
5037
2842
652
293
652
274
436
46
436
173
436
176
436
177
436
268
1585
1155
776
321
172
19
145
58
145
58
1011
219
1011
450
430
52
386
14
473
199
370
176
788
90
788
91
788
92
788
293
783
321
803
693
651
275
651
294
705
8
580
8
3
636
582
9
3
693
1122
278
737
725
390
319
390
327
390
369
390
358
755
655
1270
281
1270
301
1270
306
1270
272
210
38
210
22
210
165
210
23
627
4
871
823
398
219
398
30
398
184
398
185

468
128
468
162
912
420
2171
1927
2171
1699
2171
1626
212
23
212
43
212
24
212
45
393
377
1659
435
147
37
781
674
781
44
781
551
483
20
86
68
930
27
930
68
420
8
198
26
198
37
736
636
536
16
536
418
204
154
204
111
204
135
555
41
555
55
555
62
2139
1896
52
15
1906
139
1906
1761
1906
148
1906
1748
630
551
466
6
487
397
382
367
382
368
382
364
382
372
2169
1573
308
272
244
70
501
43
701
688
619
6
2336
2125
149
62
149
15
1068
862
716
418
716
419
716
442
716
297
716
445
716
298
716
290
528
70
508
158
4967
2030
4967
2807
907
862
466
72
466
38
466
71
1234
1104
907
862
684
233
684
273
902
861
327
128
327
132
1873
1574
2647
2151
4953
2803
4953
2797
742
696
841
454
841
437
2120
1500
525
408
497
39
699
204
699
234
1484
1165
555
14
906
862
674
523
674
271
674
447
674
670
441
213
441
355
441
319
441
261
441
244
441
323
441
315
441
292
441
408
441
415
441
304
529
319
52
15
4966
2029
4966
2806
2364
2158
595
235
595
304
332
154
478
396
142
26
142
82
864
424
864
410
327
132
327
118
628
620
732
89
551
44
551
275
551
41
543
55
1480
752
1480
736
1480
711
1480
659
1480
794
1480
699
1480
767
1480
812
1480
669
2261
1041
2261
2053
737
433
172
169
735
7
351
198
351
177
378
96
1145
360
1145
244
724
88
2440
69
264
10
418
226
400
394
400
386
205
33
142
19
968
828
549
275
427
181
437
238
724
82
403
287
617
174
198
86
163
15
163
70
340
202
648
620
648
42
648
258
537
20
462
368
462
218
437
129
437
363
437
234
465
9
465
10
270
23
721
117
211
22
211
23
681
204
681
234
1203
494
1203
614
1203
1176
1203
632
380
238
380
277
380
156
2346
1200
2346
77
505
465
1106
373
1106
639
1106
559
1106
543
1335
790
1255
685
1076
950
1076
852
1047
313
940
891
520
460
440
143
655
152
655
275
1236
700
1014
464
1014
781
1014
784
797
240
797
255
797
193
375
152
1424
856
1613
1547
498
152
498
39
145
58
145
89
646
515
646
525
436
274
436
268
776
576
145
58
1290
1247
351
338
758
725
758
578
758
530
758
672
1079
1025
473
114
168
74
168
117
168
98
205
77
205
142
205
81
245
57
338
333
338
53
844
139
524
66
586
65
360
43
188
180
577
557
776
683
415
369
437
197
1096
898
1096
1055
1096
756
1096
953
136
9
136
27
602
572
602
74
602
59
928
779
968
336
1505
1269
1505
1214
1505
1236
826
699
826
464
826
454
826
62
826
726
826
691
826
808
826
760
826
759
420
8
184
178
184
179
496
118
496
109
496
152
496
11
1186
902
1186
1141
1186
1112
1186
1096
1186
98
1186
1137
1186
1139
1186
989
1186
109
1186
1035
1186
13
1186
703
1186
815
1186
116
1186
995
1186
1055
1186
1138
372
24
1827
1678
1827
1709
1827
1781
1147
1004
1147
1010
1191
1160
1191
971
1191
172
1191
440
1191
1022
1191
259
1191
161
1191
268
1191
37
1191
963
1191
29
1191
976
1191
1113
1191
245
1191
934
1191
1091
1191
774
403
288
1130
1049
1130
833
1130
1127
743
324
641
417
2527
909
2527
1443
2527
1442
2527
934
198
177
149
62
149
15
975
341
975
366
975
447
280
252
505
51
505
73
505
474
505
107
505
457
285
203
285
61
285
58
780
729
852
484
122
77
506
369
2203
2146
2203
1742
2203
2151
2203
44
2203
120
2203
1963
2203
1787
2203
503
2203
922
2203
857
2203
1943
2203
862
2203
1794
2203
518
2203
516
2203
1815
2203
51
2203
442
2203
2164
2203
48
2203
928
2203
1702
2203
45
1580
979
1580
1005
1580
906
1580
864
1580
848
1580
876
593
188
593
72
282
42
574
524
8799
1388
8799
1365
8799
731
416
98
416
182
416
194
212
208
476
460
476
171
1274
283
1274
310
1274
303
1274
274
442
261
1098
459
227
10
466
50
503
477
503
118
503
133
503
115
503
258
836
826
836
236
1036
1026
4544
4519
753
506
630
551
418
113
564
20
121
11
474
409
474
408
193
187
415
300
1273
926
213
128
655
528
655
529
2169
1926
817
93
92
82
92
87
608
116
608
553
608
585
608
115
584
257
295
196
295
89
295
233
689
684
1551
954
1551
1216
914
332
1546
632
1546
1386
1546
1464
817
93
817
99
817
176
413
261
413
344
413
345
413
260
416
177
1159
1136
1159
889
1159
282
1159
894
886
144
780
774
351
48
351
10
351
139
351
53
351
212
351
325
351
259
351
14
351
338
351
197
1280
666
1280
670
1280
682
377
38
477
385
477
186
559
495
559
505
559
493
559
183
559
507
284
152
432
37
432
6
432
12
432
7
477
215
477
190
477
333
733
700
733
505
321
314
321
292
321
305
321
109
284
54
284
193
284
55
360
287
360
288
579
568
579
463
579
566
579
567
579
134
709
409
205
51
470
16
470
75
470
11
1545
635
1545
631
395
38
395
39
909
561
909
723
627
10
627
423
915
861
419
198
419
411
673
12
673
53
337
217
337
241
791
11
2337
1191
1104
8
1104
16
149
62
292
169
407
331
407
329
2749
1587
2749
1754
394
263
736
259
474
142
474
141
452
15
335
305
335
130
215
125
254
48
1112
317
1112
295
1112
72
106
92
2345
76
591
454
1004
694
1004
848
1004
849
1004
693
943
244
943
268
943
293
553
22
553
35
379
376
235
215
501
400
501
406
501
384
483
425
483
8
483
42
483
416
483
12
483
23
483
36
483
33
483
50
198
26
198
37
1114
695
736
132
449
364
449
392
196
56
1141
427
1141
311
1141
437
459
118
1119
971
1119
85
1119
316
1119
427
446
443
159
40
284
54
284
193
284
275
284
55
92
82
92
87
1032
695
1032
696
222
188
352
319
352
266
352
155
871
823
533
16
663
498
663
489
780
38
780
434
405
402
918
426
918
202
351
197
351
338
351
14
351
53
351
10
351
325
351
139
351
212
351
259
351
48
171
34
171
66
171
74
514
189
514
120
467
183
467
434
467
219
2353
1106
1465
75
730
708
421
96
329
171
789
15
2527
934
204
33
1109
66
427
333
261
145
1203
869
700
369
700
368
372
293
372
199
372
24
568
336
594
90
246
72
246
53
248
118
517
491
517
516
1782
771
1782
697
1782
695
1782
626
708
341
708
388
311
285
541
509
219
158
219
91
219
31
235
216
793
297
246
54
246
55
246
60
246
159
576
320
576
148
576
228
459
300
595
67
595
52
595
565
595
80
587
432
1321
264
453
15
985
884
985
113
34350
4184
34350
4064
34350
4009
971
730
476
315
476
26
287
9
471
32
745
125
1184
412
323
320
896
602
1321
1136
1321
1137
169
32
169
53
169
159
169
108
169
6
169
130
169
9
169
113
495
445
580
558
580
556
1202
631
1202
1175
1202
613
424
384
424
233
641
115
359
147
406
119
550
275
197
92
2750
1588
2750
1755
271
255
346
215
505
73
505
474
535
371
606
12
544
493
544
257
499
448
479
194
815
774
1023
942
2225
1858
2225
1405
2225
1855
1249
112
443
359
422
13
106
38
3
336
3
342
729
707
184
179
1023
942
933
116
933
161
427
424
2169
1926
1849
882
92
82
92
87
474
19
908
714
394
329
394
365
345
287
2225
1405
595
9
595
517
2363
2107
421
96
1575
715
415
198
780
772
923
887
166
34
166
66
249
235
331
171
608
115
608
585
198
9
211
22
211
23
930
68
509
63
509
180
1134
330
1134
331
204
173
559
495
205
203
207
204
207
30
220
191
524
204
717
53
717
11
717
115
165
72
1237
1230
2701
936
450
363
509
41
443
17
490
18
96
72
498
39
531
15
491
127
565
505
221
120
221
170
221
127
221
129
89
55
377
202
467
98
1032
1020
179
96
179
49
431
368
2813
1564
2813
2732
839
308
360
286
477
311
219
35
166
140
1036
294
630
471
630
364
630
490
541
220
420
8
245
83
508
257
507
63
507
210
609
586
330
118
704
626
881
701
355
86
235
44
181
167
181
175
112
103
391
312
391
218
391
43
2871
2848
343
328
343
330
343
323
121
11
2644
434
199
162
926
357
779
474
687
214
687
215
1244
897
682
201
852
195
4303
4251
175
172
1914
1772
1822
1363
126
35
136
49
839
501
1152
723
444
57
4684
4641
265
155
215
98
1092
549
1092
431
109
33
3907
54
3907
42
324
266
483
20
466
457
523
508
265
258
653
600
5035
2843
384
31
1061
528
687
643
271
255
160
15
175
172
462
26
563
20
374
372
371
254
501
384
443
307
293
9
372
336
427
424
425
331
459
442
1140
644
875
101
183
92
484
345
758
527
323
275
332
311
970
334
360
356
394
392
474
142
676
26
1147
337
522
381
510
366
279
187
977
723
284
193
768
336
382
364
382
363
382
372
382
368
140
137
140
71
2221
1980
2221
1534
1009
777
788
408
1202
1175
685
388
370
175
770
678
652
149
652
272
1084
264
1084
265
1084
583
2016
527
2016
523
2016
524
2016
515
588
494
588
510
588
99
1110
307
292
94
292
47
292
87
292
124
372
346
931
69
301
33
730
6
632
321
445
163
1032
581
359
157
206
28
206
186
206
137
206
27
35213
3992
35213
3990
35213
4045
567
332
567
336
455
410
455
416
931
342
1102
1023
1065
794
1322
206
121
108
1321
625
1321
550
1321
468
759
556
770
678
484
115
852
709
854
57
854
712
971
325
971
334
1235
188
112
103
831
551
831
604
184
178
184
179
610
486
973
793
973
795
444
259
444
57
34252
3657
34252
3951
34252
3896
34252
3898
523
212
351
238
294
186
294
4
294
7
294
3
294
84
445
290
445
195
445
194
445
289
1865
1249
308
25
308
38
308
300
608
446
963
192
519
504
422
13
619
152
929
485
929
498
580
464
597
188
597
72
194
252
686
215
395
132
829
358
189
153
1740
684
932
87
459
118
365
336
365
342
1100
258
173
167
266
238
655
585
451
222
780
716
1582
1446
1196
898
714
255
714
473
714
254
714
414
714
417
805
681
805
684
805
685
358
197
908
360
757
441
285
194
285
56
938
896
483
238
1012
734
1012
898
868
2
368
323
470
268
382
213
1545
631
1545
635
588
267
855
2
929
485
929
498
972
334
307
228
99
66
601
224
1122
291
136
10
441
351
441
257
441
213
441
319
1438
311
1210
677
1011
252
409
138
309
162
309
155
309
151
781
207
781
241
942
773
1122
497
1122
258
1270
301
210
22
210
23
210
198
550
347
550
297
912
909
912
741
912
737
912
204
2171
1927
147
37
781
119
781
111
736
636
167
156
167
160
331
62
331
57
327
97
327
132
327
118
480
472
480
307
406
375
264
10
437
257
437
325
724
153
211
22
211
23
380
156
380
321
1210
677
1210
692
552
490
629
290
168
74
168
117
168
98
205
81
1274
303
1159
283
559
493
211
22
211
23
839
116
160
15
654
420
654
418
668
447
304
294
833
170
937
276
937
257
2221
1980
166
2
788
399
611
96
611
330
816
293
591
98
591
473
952
485
952
154
952
357
624
131
1049
977
1049
401
1049
936
1528
1243
858
804
862
406
298
17
724
651
1374
837
1073
91
1073
805
809
241
446
420
801
293
179
4
179
86
550
434
1762
917
373
131
783
350
783
291
530
67
341
99
1752
1735
171
161
1033
290
807
239
839
789
342
171
342
274
342
154
437
257
341
97
3
677
3
692
918
747
918
743
1465
1452
1465
1120
1465
480
1465
477
906
870
906
871
906
868
823
355
3
131
1122
258
2647
1285
473
215
437
336
756
176
756
180
671
319
671
330
671
332
656
320
353
175
923
405
332
2
1198
360
1478
1012
1478
1011
1084
245
952
154
469
32
199
93
199
135
451
333
913
358
334
206
334
210
611
229
444
165
504
456
504
451
504
455
504
452
391
215
606
183
606
191
606
186
606
177
552
171
803
673
803
668
803
674
205
74
462
260
207
71
881
81
184
2
3
191
3
186
421
236
1122
258
441
355
441
261
441
323
1356
872
1356
143
552
365
758
578
581
312
986
185
986
171
986
142
733
553
394
278
394
273
394
275
985
958
985
884
724
560
788
399
1084
245
952
154
315
51
392
57
1826
1409
1826
1380
512
226
692
170
692
274
692
306
317
253
3433
1257
649
233
693
170
693
273
1337
851
1337
143
1122
278
737
723
755
584
755
634
393
45
393
19
393
32
393
14
933
133
326
201
781
245
781
190
770
726
736
615
536
74
187
41
531
36
2336
2015
466
55
841
445
841
426
1429
292
706
552
441
230
441
201
441
198
441
216
441
213
441
395
441
403
441
180
441
261
441
211
441
152
441
204
441
421
441
234
441
408
307
7
307
137
205
72
695
284
695
271
695
275
439
61
507
407
525
446
525
433
572
508
572
521
345
230
345
197
345
218
747
485
920
309
920
82
1052
909
1052
731
721
129
1203
113
857
519
857
654
857
606
857
803
389
367
655
248
1014
785
1014
781
1014
784
572
521
777
202
777
225
777
210

465
130
393
291
1871
1674
1512
885
1512
998
726
700
726
603
726
616
664
391
928
794
928
806
928
810
826
686
496
94
2527
1626
149
37
149
24
335
190
204
74
219
159
219
13
219
17
498
30
1244
730
350
91
557
243
505
295
505
272
505
111
768
282
668
649
668
452
501
251
365
144
1317
33
1247
356
1247
299
864
777
1356
228
591
84
591
243
858
519
858
606
858
655
858
804
1294
540
330
319
270
28
270
32
270
22
770
742
652
245
240
73
473
395
1616
153
887
667
887
158
1528
641
1528
945
1528
556
1528
858
3142
1198
3142
431
3142
1178
1531
134
497
136
467
353
507
429
346
154
346
221
572
521
570
521
605
394
605
438
605
432
846
450
846
460
458
399
502
410
502
428
502
423
267
60
496
39
496
162
496
120
367
30
367
8
931
13
180
67
180
72
505
272
543
20
864
779
521
443
317
231
382
281
382
278
307
7
307
137
443
320
555
490
555
399
716
502
716
473
1503
1449
1333
221
369
326
369
160
572
508
497
136
54
12
401
394
401
396
649
141
171
66
171
5
926
50
926
394
365
144
559
440
559
309
559
396
677
26
677
626
2964
1571
1092
313
836
278
836
248
579
403
245
192
520
74
194
74
328
227
559
317
496
94
1137
870
3110
1149
3110
1169
1767
505
555
399
555
490
711
249
1782
1327
431
78
643
515
2254
2233
171
5
171
66
572
508
253
42
1822
1366
3056
793
862
480
2541
424
372
160
346
16
1189
736
839
406
512
344
292
46
695
667
281
25
367
30
593
571
365
27
365
286
365
288
365
296
695
141
695
341
3
45
3
32
3
14
3
55
593
347
318
232
588
523
1104
323
1237
736
1804
1348
440
349
1241
699
253
107
735
423
735
512
735
501
735
467
735
427
735
431
735
513
735
459
735
447
735
443
735
451
735
509
735
463
735
489
735
455
735
439
735
435
735
466
474
107
422
313
1202
700
403
307
992
76
3
742
3
113
3
885
865
450
865
460
900
10
900
726
1122
497
550
297
968
800
277
170
380
238
380
156
380
321
878
875
205
81
788
399
557
534
591
98
952
180
1049
977
1049
936
801
293
783
291
341
99
1752
1735
191
77
342
171
3
180
1122
277
483
5
136
2
136
9
136
27
136
10
136
28
393
283
393
182
393
214
393
268
393
210
531
44
1906
139
1906
148
466
72
466
71
1976
1846
414
183
317
261
317
31
317
62
172
19
724
451
724
254
142
116
142
33
2115
2054
2115
1810
2115
2046
2115
1968
415
13
415
172
730
109
730
94
730
195
1328
1302
1356
961
603
209
642
48
642
14
642
4
642
54
642
68
642
43
281
175
1113
538
441
239
140
6
340
202
918
493
918
893
918
898
918
71
918
517
918
891
918
58
918
892
918
896
918
897
960
910
960
713
1859
173
136
9
136
27
3256
373
3256
537
1972
1341
2472
2204
344
6
344
231
344
15
669
617
669
648
2896
1012
632
386
632
248
632
409
136
9
136
27
136
28
136
10
928
779
1683
299
1683
750
432
37
432
6
432
12
470
16
470
59
470
11
4684
2885
350
300
252
32
252
125
252
110
252
82
252
158
252
150
252
163
252
114
252
138
252
78
880
861
880
860
5890
157
725
191
725
94
725
114
725
108
725
110
662
593
294
124
1382
584
1382
447
1382
184
683
627
683
38
282
23
282
19
344
75
798
92
798
3
798
142
798
107
4128
510
825
13
825
25
391
325
546
101
546
357
546
142
546
6
292
124
790
543
790
619
790
644
790
539
790
545
790
696
790
542
475
11
331
39
3056
1402
326
144
890
877
126
82
126
77
280
277
280
164
280
274
280
218
280
153
157
146
672
633
126
83
126
78
126
82
126
77
126
83
126
78
126
82
126
77
126
83
126
78
126
82
126
77
126
83
126
78
126
82
126
77
193
78
193
83
193
77
193
82
1103
65
1103
819
1103
195
1103
881
375
66
126
78
126
83
126
77
126
82
356
108
356
99
1232
798
1232
800
1128
951
1128
875
458
109
90
24
90
28
767
138
380
130
856
707
360
254
126
83
126
78
126
82
126
77
160
103
454
260
2342
23
2342
59
1023
892
1023
976
1023
980
233
214
233
209
233
213
126
83
126
78
126
82
126
77
126
83
126
78
126
82
126
77
372
314
372
306
372
247
372
319
372
311
372
252
165
117
599
21
126
83
126
78
126
82
126
77
164
78
164
83
164
82
164
77
1958
129
1958
130
191
91
126
78
126
83
126
77
126
82
679
347
1491
126
390
299
1047
493
257
129
102
32
194
18
194
2
194
3
681
331
479
461
660
591
659
36
390
325
136
9
490
311
136
10
136
28
3
268
3
283
3
182
277
261
277
250
277
249
326
144
471
21
3
11
3
16
3
59
3
28
3
10
136
28
3
116
3
71
3
12
3
6
3
37
233
35
863
113
352
342
452
383
1122
497
550
297
912
737
912
741
761
45
890
734
342
171
1122
497
1122
258
198
156
198
197
1585
1155
172
19
386
14
1122
258
1122
497
2414
23
327
132
559
182
2442
301
473
199
473
12
473
11
794
204
441
354
385
179
370
176
1084
466
1084
631
1122
258
1122
497
1242
793
2514
1390
2514
1382
1147
336
1147
337
1147
401
1084
245
1084
466
783
185
692
170
692
274
692
306
1068
328
619
328
619
161
619
369
619
61
509
495
693
170
634
150
3
150
426
204
1122
258
1235
788
1242
793
724
153
724
540
926
89
926
342
926
357
692
170
619
328
619
161
619
369
619
61
693
170
307
90
2442
2391
2442
2393
634
150
3
150
619
161
1122
641
550
469
781
141
1052
396
1052
576
1052
575
1052
406
450
232
1114
904
233
170
586
30
192
63
836
733
798
757
798
752
546
420
546
465
368
314
870
409
870
164
761
320
1055
396
591
117
591
30
559
117
305
34
305
173
892
11
1205
1175
532
187
532
337
3097
2795
505
255
3
337
3
187
207
190
207
191
793
788
463
233
463
457
463
379
463
229
463
235
463
224
463
71
1255
1228
482
44
676
312
676
333
335
41
750
700
550
485
550
469
550
333
550
420
550
488
912
94
912
501
912
462
912
431
1205
82
393
219
393
125
882
752
882
753
882
754
882
796
933
510
781
332
781
653
781
85
770
704
770
67
770
44
420
215
536
529
536
337
536
418
536
215
468
20
382
264
382
246
441
282
198
88
198
87
198
73
630
46
630
141
706
300
140
124
441
17
1052
406
1052
575
1052
576
1052
924
1052
860
403
154
403
376
403
173
403
314
403
45
403
239
403
67
162
18
162
26
522
397
522
401
1257
1175
595
536
317
41
3
99
3
138
491
280
491
301
732
720
732
196
1960
157
428
330
428
324
428
327
724
300
466
132
297
14
525
61
724
606
403
147
636
27
920
534
648
339
648
340
1052
924
1052
396
1052
860
1052
440
1052
576
1052
1006
1052
193
1052
897
1052
575
1052
406
1052
741
683
224
1038
283
303
16
839
7
839
14
317
227
317
245
317
51
1210
1015
1210
868
1210
726
1210
763
1210
1124
1210
943
1210
914
1210
1091
1210
1109
474
287
474
285
474
22
1255
876
857
689
857
127
857
813
389
103
524
129
756
187
756
198
736
17
736
462
736
274
736
26
736
294
781
653
878
86
261
230
261
191
379
244
323
309
323
293
1265
752
1265
758
317
287
317
303
201
23
201
152
794
693
906
773
906
730
3
427
656
277
1243
1163
1243
1112
1243
1114
859
528
859
392
859
748
586
477
586
145
1871
1798
1871
1764
524
58
524
485
609
529
664
44
986
197
416
250
476
109
4544
4472
4544
4506
193
33
193
65
689
91
689
85
689
12
1159
474
1159
610
254
73
254
58
254
94
1114
904
871
109
871
804
261
170
896
594
346
20
3
343
1023
148
1023
259
2169
2147
204
26
204
155
4303
4236
1914
463
1914
470
839
199
1092
701
1092
451
505
77
418
53
957
247
957
610
479
379
192
63
1153
1054
1153
150
668
648
461
405
218
65
1430
489
1430
490
332
9
496
396
487
432
480
54
382
264
382
246
382
312
2472
1072
2472
1175
1363
829
1363
1062
1363
832
1363
1332
1363
852
1363
1336
189
95
189
63
189
31
955
343
955
106
955
67
955
117
782
464
782
408
782
602
782
85
782
650
836
733
836
742
836
761
689
12
689
91
689
85
1135
99
1135
1133
428
193
428
271
428
194
1464
1324
1464
1183
1464
1422
1464
1266
1464
1386
1464
1291
1056
210
1056
230
1056
124
1144
1048
391
346
391
176
906
883
906
819
906
885
906
859
906
851
303
14
178
13
457
196
457
332
583
426
583
349
583
348
694
241
694
372
694
316
694
626
694
258
692
52
692
50
692
151
692
149
692
79
692
153
692
538
692
145
692
169
692
310
692
435
378
154
588
197
588
219
588
231
711
582
711
316
711
687
798
757
798
752
707
690
707
596
998
248
998
247
299
294
299
296
612
243
612
300
612
299
673
310
673
627
673
63
673
331
673
564
673
371
202
176
202
167
365
79
1303
246
1303
1217
1303
157
432
316
855
735
855
470
855
740
855
739
730
452
730
93
730
450
730
92
730
124
594
66
895
378
895
591
596
279
596
333
596
264
920
79
920
407
920
80
920
149
920
92
920
283
556
375
556
372
556
8
476
54
1164
98
529
437
1436
1325
427
148
427
55
893
889
515
506
515
427
515
111
268
246
784
730
784
684
784
657
727
719
727
723
497
434
908
589
535
423
595
563
595
535
740
528
740
579
740
469
740
643
740
482
740
487
740
706
710
176
339
23
369
353
298
3
298
45
474
340
904
758
400
32
400
246
1317
24
1317
45
865
851
865
827
1130
919
876
91
876
797
876
835
876
174
470
175
1280
1185
1247
1111
1247
1175
1247
1072
917
731
403
249
403
321
403
21
734
721
734
661
734
691
734
649
827
80
827
255
827
59
827
63
827
45
2055
1236
2055
1245
864
230
864
596
661
643
428
162
318
68
318
73
603
444
603
165
362
343
1203
530
760
283
1034
6
1034
9
391
336
198
179
198
196
189
31
722
226
722
160
1290
782
1290
1252
546
420
546
465
546
481
1445
1205
1445
1172
1445
1255
447
141
336
166
336
170
336
150
336
176
684
325
684
359
606
301
606
300
929
904
929
433
929
15
474
412
474
410
593
470
619
191
191
63
368
314
147
113
581
5
329
9
938
227
938
216
938
95
368
314
821
705
821
704
210
117
827
701
1538
1398
1538
1403
870
127
870
652
140
128
680
192
644
267
644
624
644
57
269
262
269
240
322
73
322
271
652
643
652
627
788
772
788
784
1386
488
1496
489
398
335
787
698
787
678
1077
503
937
736
220
44
1337
1319
1337
1310
863
475
1140
1029
903
900
249
192
917
685
2221
2216
217
159
735
334
586
477
931
567
502
385
502
441
847
172
471
217
471
255
471
300
471
256
471
282
471
218
767
201
767
200
166
67
567
283
1198
360
180
173
664
214
1132
706
482
145
761
320
761
283
761
245
315
54
309
306
925
757
925
287
925
711
925
737
1009
401
1009
579
1009
880
1009
578
1055
396
359
318
1499
1104
1124
618
1124
556
193
41
760
19
883
875
883
868
883
872
201
178
559
124
576
395
575
498
575
186
575
134
575
446
911
507
577
395
309
11
720
25
720
664
720
518
822
713
1675
1476
414
32
784
684
938
836
140
128
526
525
1388
721
1591
383
258
253
1356
1174
869
529
418
53
675
565
1149
487
745
643
1075
743
504
378
504
382
1502
1108
591
87
591
39
350
141
594
109
390
288
400
390
858
127
245
178
280
138
845
173
503
360
536
418
490
38
655
107
724
522
339
23
619
93
582
572
425
357
298
194
419
373
619
318
434
43
870
596
620
463
511
155
511
438
511
162
511
36
511
273
511
292
1367
1164
1367
1165
1367
1160
658
611
658
613
1130
392
976
899
395
315
605
575
364
339
863
734
863
714
380
9
380
29
637
323
1499
1104
1499
1086
1657
1509
481
361
573
137
573
425
573
76
573
507
573
89
573
207
573
156
573
95
573
437
573
107
573
236
573
224
573
71
573
324
573
66
573
104
573
531
310
291
765
200
455
359
1591
383
101
86
529
522
1047
459
895
891
1241
1211
191
63
1258
985
1258
986
3
343
596
324
596
255
596
270
596
264
596
279
596
333
594
472
3
463
3
470
3
438
3
27
913
736
913
779
1101
681
1101
251
1101
1005
1101
226
211
79
1052
406
1052
575
1052
576
1052
924
1052
860
3
1228
1368
390
149
99
149
138
155
17
526
492
526
519
2028
2024
2028
2022
365
343
486
76
1134
1132
630
277
454
340
454
393
454
356
695
652
695
686
1388
721
909
906
339
23
561
252
350
141
220
89
220
164
220
61
412
245
900
331
900
42
900
646
900
584
900
110
605
206
605
224
797
194
280
148
280
271
1078
651
252
9
905
759
905
759
537
517
426
198
426
308
189
31
189
63
550
14
467
245
310
285
1311
1148
1311
411
259
246
684
325
684
359
731
551
731
413
731
34
731
599
731
357
1066
99
1066
1064
822
484
822
773
822
524
822
601
440
438
458
428
541
423
890
794
890
412
890
397
279
207
279
267
316
86
646
441
463
283
463
352
296
229
390
347
390
344
483
431
750
726
550
404
550
417
607
379
393
391
393
14
824
734
1242
615
243
41
575
284
575
288
575
376
770
726
420
42

736
615
2414
2038
2414
1037
531
36
164
129
164
97
1906
1767
630
615
630
606
630
601
467
254
467
7
467
249
467
244
467
219
501
34
619
52
149
24
149
37
528
61
198
186
630
615
497
30
441
230
441
201
441
198
441
216
441
49
441
395
441
403
441
180
441
174
441
211
441
152
441
204
441
421
441
234
441
45
529
306
529
325
802
359
802
580
802
699
595
117
595
105
595
103
331
72
331
62
498
350
498
342
498
345
1332
143
409
13
409
275
1531
1360
1531
1246
1531
1353
1531
1392
1531
1212
640
531
651
632
439
61
202
67
477
71
1464
735
464
61
118
64
1215
1034
1215
1030
933
293
772
342
772
567
217
150
1600
1231
198
68
1113
547
1113
541
920
650
920
515
648
288
648
300
648
295
298
159
462
202
454
78
673
293
673
343
673
424
673
11
1210
692
1335
695
1335
862
1335
7
474
147
474
146
474
312
474
261
474
137
474
468
474
165
474
94
474
466
474
141
474
138
474
142
474
166
474
460
474
150
474
264
1255
700
766
400
766
752
766
150
367
358
367
363
1613
1489
1613
1571
968
905
968
309
968
307
770
726
794
779
656
78
777
225
749
726
168
74
393
285
393
291
931
453
524
57
1807
663
1581
1456
1581
1031
1475
515
1475
387
1475
256
1475
337
1475
319
1475
528
1475
333
1475
412
1475
368
1475
521
986
678
1130
279
1130
287
149
24
416
124
476
281
193
87
193
99
689
669
360
110
673
578
943
171
196
23
196
26
196
86
780
570
1203
1157
1203
1154
700
49
745
650
2225
455
345
234
2225
455
331
121
509
58
498
30
1914
1778
1914
977
1914
946
1822
1355
1092
128
462
259
1147
116
350
91
350
162
358
20
175
44
381
173
381
158
381
196
381
299
381
158
381
196
413
25
413
177
384
375
384
345
384
320
505
68
505
70
557
82
557
129
557
125
735
358
735
572
735
362
560
459
465
384
296
178
296
187
296
183
793
758
793
788
685
574
685
607
685
620
384
224
452
221
452
224
1383
687
1383
807
532
179
150
115
345
153
345
151
345
163
239
73
239
55
239
86
483
131
505
132
1216
981
521
311
521
293
521
339
521
42
521
27
521
23
521
313
521
502
521
274
87
21
419
72
643
57
665
611
665
590
665
613
665
440
665
468
2073
131
501
357
501
352
452
256
452
212
428
388
428
382
455
374
280
35
785
58
785
452
785
738
233
154
1441
1178
1441
1184
852
322
1608
1408
1608
1388
2442
92
480
275
480
461
480
299
480
292
480
302
597
347
597
160
741
561
2326
2313
326
321
326
319
252
208
252
78
1132
522
196
64
586
129
261
67
261
180
508
409
508
393
508
391
508
215
508
264
508
182
508
224
508
266
2090
1808
2090
1709
814
335
814
353
814
373
985
958
985
677
528
300
528
318
215
122
882
843
700
49
560
27
560
37
560
526
560
35
560
39
560
529
158
118
654
386
654
613
345
292
345
276
1483
157
821
623
821
627
97
20
97
29
827
734
418
411
379
206
379
203
957
626
957
632
236
69
479
386
284
10
181
80
331
143
519
336
519
351
704
61
704
548
704
66
341
99
1425
775
1425
768
284
231
108
99
768
280
192
107
158
146
820
774
820
775
597
206
1454
985
332
45
487
52
759
373
759
361
759
603
635
322
635
370
935
892
935
811
935
865
935
858
468
314
468
220
579
35
2339
446
2339
410
440
37
441
260
441
104
781
72
822
776
551
475
1097
1043
204
185
538
533
1109
866
199
161
760
685
440
104
724
357
549
252
707
204
1153
744
857
820
380
373
668
649
592
582
592
563
704
510
926
293
595
265
541
458
560
285
676
622
461
141
218
200
451
276
1274
1256
739
536
756
95
382
224
1430
733
413
383
413
243
706
332
706
342
148
37
816
732
1141
454
1141
431
260
25
873
442
429
173
477
325
902
675
304
231
735
249
847
757
847
704
870
671
594
417
594
149
594
475
1164
497
722
241
504
437
552
276
535
530
175
44
431
386
431
380
380
361
380
373
380
330
380
324
380
231
329
187
492
297
1308
1050
1308
698
900
208
900
824
821
779
580
469
695
551
756
95
678
584
292
14
402
375
467
244
467
254
916
761
916
765
916
767
916
762
206
162
984
195
984
262
984
226
984
360
984
286
984
237
938
814
938
861
938
868
938
895
698
98
698
101
698
92
698
91
698
87
742
621
582
506
158
146
1097
860
1097
863
365
271
365
212
365
172
365
188
460
249
460
246
460
18
460
15
209
199
2703
1067
877
219
209
199
398
362
398
394
398
360
398
389
753
691
753
359
753
601
394
385
394
390
2357
592
162
123
410
177
790
263
619
390
396
340
396
305
396
147
284
168
284
75
802
579
802
426
802
422
802
614
802
610
802
576
245
182
3678
3058
326
321
326
319
387
164
369
232
460
249
460
246
460
18
460
15
618
75
579
38
579
380
457
407
580
42
580
524
580
49
457
407
463
215
737
11
737
354
755
634
483
431
550
404
107
77
107
52
393
314
243
220
575
283
575
284
575
288
575
290
326
201
770
726
736
615
2414
2038
2414
1037
531
36
204
127
164
129
771
716
771
681
771
596
771
710
771
687
149
24
149
37
198
186
466
54
466
55
2647
1532
2647
1629
2647
1458
2647
1083
2647
1435
2120
1125
441
230
441
201
441
403
441
211
441
152
441
204
441
234
108
58
108
43
824
208
824
204
824
221
824
288
824
328
824
433
824
429
824
445
824
342
824
311
824
434
824
425
824
363
770
258
770
262
770
266
1332
756
765
393
765
111
747
529
747
539
1531
1360
1531
1246
1531
1353
1531
1392
1531
1212
215
208
327
270
327
269
327
256
327
255
439
370
439
343
480
472
480
307
904
12
904
40
904
26
1863
1190
1863
1496
1863
1188
1863
113
450
171
543
331
543
197
281
132
695
284
695
271
695
275
719
676
391
327
391
276
391
335
391
354
391
291
1015
930
1015
307
1015
331
580
320
580
159
580
49
882
517
270
61
118
69
118
82
587
408
142
33
473
213
473
47
473
121
473
167
473
66
473
129
646
122
646
138
391
369
391
343
391
361
391
359
525
446
525
433
525
443
525
440
919
75
2115
2054
2115
2105
2115
2086
2115
2014
1278
211
504
366
504
142
504
118
504
288
504
137
504
216
504
127
660
549
660
410
660
459
846
838
846
617
846
638
846
328
846
66
846
400
846
401
846
641
846
758
636
85
747
71
747
737
1113
541
1113
930
920
309
920
82
920
515
441
299
441
337
140
67
918
58
1130
489
1130
612
1970
1933
1970
1919
437
331
437
336
462
76
462
460
529
61
529
8
725
358
1051
637
1051
621
1051
652
1051
223
1051
990
1051
628
1051
636
1051
634
1051
982
1210
1025
1335
695
1335
705
389
367
655
248
440
268
440
271
1424
866
1424
727
222
105
168
90
393
285
393
291
1030
472
430
33
233
61
1417
713
1417
765
476
285
476
300
524
282
524
17
524
115
3256
760
3256
1942
1972
1677
1972
1608
2752
1412
2752
865
673
30
673
25
673
5
502
394
380
186
3224
2152
3224
2275
3224
2279
3224
2245
3224
2250
664
18
664
389
664
391
664
21
490
95
1060
119
1060
68
986
959
1152
695
1152
916
1152
900
1152
891
1152
786
279
125
928
372
928
251
928
806
928
248
928
810
896
880
1505
1269
1505
1236
826
667
416
124
466
55
470
6
470
27
470
31
149
37
149
24
2749
798
2749
420
335
245
335
281
335
214
335
227
335
242
335
190
1032
600
1032
431
1032
472
663
483
1782
766
1782
617
219
13
219
17
219
44
219
159
793
638
2363
2072
2813
53
219
17
166
75
704
614
704
611
2644
427
4684
4538
1147
438
350
91
350
63
1383
765
1383
640
239
55
239
86
239
68
521
464
521
450
785
738
785
736
785
719
785
722
1441
1425
480
275
480
299
480
423
480
292
480
302
480
47
252
32
252
125
252
110
252
208
252
20
252
47
252
82
252
158
252
180
252
150
252
163
252
114
252
74
252
138
252
78
508
215
345
292
345
286
345
276
345
270
479
386
181
117
768
282
468
220
857
280
668
649
592
582
451
375
451
219
451
223
451
276
332
247
382
254
382
261
1056
925
556
353
322
8
1132
248
309
303
746
486
746
344
346
169
346
163
914
372
914
845
914
443
914
814
914
341
914
412
517
341
517
43
517
331
517
223
777
250
777
298
777
287
777
147
710
120
710
706
710
640
296
57
296
158
296
279
296
154
292
69
292
234
399
158
399
149
199
89
1334
446
1334
435
1334
572
1334
465
1334
472
1334
566
1334
762
1334
439
1334
450
1334
469
1334
476
1334
570
1334
576
1334
766
435
385
1193
134
1193
248
1447
1369
1294
506
1294
540
1294
1011
1294
1028
1294
1012
699
606
699
609
685
667
831
59
831
678
2758
799
2758
420
576
381
576
356
1370
825
393
291
393
285
550
47
550
66
550
204
550
284
550
137
318
4
318
199
1944
372
1944
546
1944
687
1944
536
1944
376
1944
290
1944
354
1944
554
1944
700
1944
529
545
211
525
446
525
393
525
433
525
443
1858
911
1626
1423
1758
1275
345
244
345
241
345
218
107
77
107
52
107
35
721
687
721
683
721
697
721
704
880
387
880
58
390
19
665
391
665
389
1488
982
1488
582
1488
155
520
494
677
377
515
196
870
763
870
765
746
344
746
486
1758
1275
330
319
463
215
2015
1426
476
76
1726
528
1726
605
1726
535
1726
652
1726
594
812
718
812
610
812
111
293
237
158
70
5890
5762
538
174
538
118
620
111
620
559
620
580
785
312
234
12
1164
1046
1164
416
1164
583
510
284
665
21
665
391
725
536
513
85
513
89
561
345
660
372
660
427
730
463
693
317
164
10
811
109
1686
258
494
460
286
267
586
22
586
392
1497
617
1497
726
1497
727
497
39
1599
1230
963
156
400
284
400
325
400
345
400
89
400
104
1050
1042
1050
542
1050
669
1515
1231
152
119
763
610
763
599
763
619
763
692
991
726
748
595
421
273
421
10
421
386
665
426
665
462
270
28
270
32
270
22
253
179
1085
608
1085
592
662
203
662
322
475
78
1886
1879
331
58
331
55
615
70
615
85
370
139
412
357
412
359
412
282
412
290
412
202
412
216
622
386
1272
767
904
442
904
157
392
78
2620
2603
2620
2046
2620
1615
808
778
464
424
464
427
1478
949
294
69
294
233
294
218
294
236
294
198
1382
588
1382
184
152
93
1087
453
756
101
152
93
152
119
805
795
700
304
700
510
700
589
700
266
252
98
314
77
314
260
984
534
1244
286
1244
381
147
22
566
145
566
306
344
22
344
185
344
149
433
125
433
127
574
375
563
200
962
387
152
93
152
119
389
32
389
19
493
460
568
23
683
622
252
194
243
180
1970
1919
1970
1933
1320
285
611
84
611
87
615
274
1969
381
179
103
179
119
179
92
282
30
505
455
468
7
816
265
1222
760
1222
767
1765
1274
137
110
334
72
334
62
334
245
559
40
559
251
559
111
559
136
287
109
2106
2020
469
27
469
31
469
6
597
561
597
564
597
575
597
555
597
581
961
388
1009
190
1009
912
1009
209
444
171
1765
1274
393
99
1148
517
1148
505
319
38
770
742
387
303
626
591
1087
665
344
75
652
245
358
301
358
279
494
234
480
175
240
73
1071
390
360
15
694
423
749
208
152
93
152
119
202
164
1441
1374
138
43
491
384
320
303
473
395
620
480
620
469
719
120
719
364
3088
2125
425
26
589
410
589
443
1299
29
1250
1062
751
230
313
63
823
551
1616
153
357
342
190
185
1338
390
798
127
330
319
96
41
96
66
661
444
215
122
243
180
810
320
218
203
660
462
505
455
887
158
591
581
763
735
1820
1643
476
285
476
300
239
72
942
536
942
561
942
915
942
532
444
171
205
193
410
398
1717
410
1717
320
1717
334
1717
344
1717
408
1717
411
1717
449
1717
323
1717
335
1717
316
1717
424
1717
322
1717
450
614
273
858
594
546
401
546
410
546
405
177
107
897
846
897
326
951
207
861
257
861
272
861
374
411
162
3418
3290
305
70
305
64
890
866
890
877
890
531
890
6
890
197
890
856
890
20
280
218
356
330
1232
1160
1023
411
679
77
679
163
679
171
679
213
679
223
679
283
679
286
679
376
679
381
679
574
979
209
748
472
748
447
748
411
507
290
1591
1465
864
59
864
711
320
4
320
199
320
200
443
316
202
164
1058
834
1058
3
109
58
109
43
1002
24
1002
36
580
469
631
756
318
102
494
403
494
475
879
874
879
193
3
314
3
33
3
55
522
304
1401
1383
1401
1388
3013
2507
860
148
860
163
860
333
860
384
538
251
538
496
451
171
445
171
445
171
444
171
445
171
446
171
444
171
444
171
743
248
743
252
653
334
653
327
653
338
128
28
128
4
128
54
296
158
296
279
296
57
296
154
828
112
828
83
467
244
467
219
467
254
467
249
145
119
145
141
594
452
594
410
594
548
676
276
676
271
676
420
676
423
479
176
656
33
717
262
2554
2546
1426
171
463
363
1498
1414
916
761
916
765
916
767
916
762
464
382
1544
1455
1544
1327
1208
250
1208
88
108
104
1844
652
852
709
854
712
647
481
647
470
647
456
647
243
916
332
916
47
479
176
473
14
907
507
1086
1015
344
253
966
770
3
711
3
59
3
1643
3
588
3
233
3
236
3
198
3
218
3
386
471
14
471
427
471
449
471
409
109
40
109
34

3
615
3
119
3
68
900
7
900
10
900
726
453
440
453
2
943
733
349
268
694
667
376
231
219
208
290
6
377
231
647
498
463
215
463
283
550
404
393
314
393
391
326
201
770
726
736
615
394
33
429
174
429
18
164
129
467
254
467
249
467
244
149
24
149
37
198
186
441
230
441
201
441
204
595
117
595
105
595
103
595
293
595
340
741
48
2089
1629
2089
340
2089
1067
651
43
480
476
480
478
904
40
904
12
904
107
904
39
904
52
904
138
904
26
1863
1496
1863
113
1863
966
439
61
391
327
882
517
1230
435
587
408
683
166
473
213
933
675
933
212
933
399
933
161
933
189
933
293
919
90
919
50
919
232
919
75
700
486
700
493
700
576
700
443
700
439
700
519
572
508
2115
1775
636
85
747
71
920
95
140
18
298
159
782
508
389
367
655
248
655
297
2843
1359
480
205
931
572
595
590
1910
1000
1910
968
1417
174
476
285
476
300
524
282
3256
356
306
134
706
422
1581
1206
1581
1214
474
243
808
721
609
454
380
186
1060
879
928
355
928
825
928
820
928
372
928
251
928
607
928
806
928
566
928
248
928
810
928
611
496
137
335
227
780
18
467
135
793
660
345
234
219
17
219
145
166
75
355
192
136
132
443
155
350
91
350
63
350
162
350
69
350
120
505
115
793
729
452
224
1441
324
1441
21
1441
487
1441
1178
1441
1425
1441
1184
1441
1005
1441
1032
1441
1270
1441
394
1441
978
1441
568
1441
788
1441
1249
1441
996
1441
1278
1441
1025
480
275
480
299
480
292
480
302
768
282
332
149
332
26
857
467
857
452
857
435
489
215
1012
44
1012
169
1012
193
1012
371
1012
515
1012
365
1012
399
1012
565
955
873
689
669
920
839
1130
476
1130
990
297
188
297
63
502
288
502
308
502
257
502
290
633
312
576
183
746
415
746
344
346
169
346
163
777
250
777
298
777
287
777
147
710
120
710
75
1370
825
550
137
318
199
107
35
870
763
746
415
330
319
812
610
234
12
660
372
660
427
730
463
1599
646
963
156
152
119
748
595
270
28
270
32
270
22
662
203
904
442
904
157
294
69
294
233
294
198
294
124
700
304
700
510
700
589
700
266
574
375
389
32
389
19
611
87
282
30
1009
190
1009
912
1009
209
319
38
319
252
387
303
626
591
1087
774
1087
790
1087
665
652
245
360
15
719
120
719
364
425
26
589
410
589
443
1299
29
1299
592
313
11
313
22
313
63
313
59
1616
153
243
180
810
320
654
244
654
138
654
153
654
47
1432
1132
1432
425
575
176
575
229
575
552
575
166
795
223
795
231
680
490
1493
157
495
98
323
13
407
129
431
18
410
394
410
398
410
386
268
53
268
103
313
282
134
4
1304
210
1304
247
1304
243
1304
141
1304
353
1304
425
1304
312
84
26
424
63
434
113
434
199
434
349
434
134
434
166
434
132
1139
638
1139
1096
1139
687
1139
1079
1139
416
1139
661
1139
951
1139
1067
1139
1043
1139
641
1139
1111
1139
693
1139
412
171
158
858
434
858
594
546
28
546
30
2603
2400
2603
2041
2603
2044
985
672
190
25
190
111
177
45
177
32
781
36
781
44
781
32
781
40
240
151
663
642
663
647
542
364
1193
18
431
386
431
193
514
121
177
120
560
105
560
53
560
73
1824
1351
381
82
292
197
527
494
1025
100
693
432
449
103
897
314
897
846
399
202
195
56
715
521
287
142
951
207
203
20
203
17
1017
554
704
446
704
496
704
489
1162
549
1427
1099
1427
1269
1427
778
1427
774
1427
1349
165
37
496
39
496
162
496
120
496
150
671
562
327
36
1830
135
494
371
863
109
863
31
863
53
403
138
693
339
693
19
1321
585
673
196
673
281
1257
863
1257
1144
1257
1006
1257
1139
1257
1123
1313
762
412
120
451
79
535
474
979
627
938
527
528
156
873
567
437
225
862
2
862
18
862
52
791
223
791
238
577
115
577
225
777
418
119
4
372
89
258
48
861
272
861
374
861
257
172
95
1068
649
1068
639
1068
331
1068
384
1068
761
1068
963
1068
974
1068
987
1068
996
1068
1008
1068
614
1522
847
391
175
236
190
236
181
236
22
443
154
215
151
1817
611
178
46
1729
690
411
162
713
686
1292
835
451
79
5537
5373
221
215
2157
1352
432
153
84
26
1411
721
2285
362
806
673
190
96
1726
1522
1861
135
553
67
978
356
1291
1065
754
431
1096
648
1096
302
1096
773
244
153
7388
7212
620
36
1905
508
1156
49
804
489
367
30
367
8
350
80
639
562
437
172
449
103
581
47
298
214
1861
1563
535
180
352
330
583
142
659
82
425
7
425
178
425
212
425
207
425
203
586
396
3418
3290
3418
76
751
432
367
30
894
381
747
48
747
30
764
388
857
467
879
193
503
101
503
135
3
391
3
314
541
366
926
94
926
110
1208
250
1208
88
344
253
3
124
3
198
1087
966
593
347
845
292
3
178
3
7
3
212
3
627
317
249
317
248
412
390
792
558
463
283
737
357
737
668
737
706
737
354
390
344
483
431
550
404
550
417
1205
115
1205
601
1205
57
1205
45
393
14
393
54
824
734
1242
635
1242
638
243
41
770
726
420
42
736
615
2414
2314
2414
1959
2414
2278
2414
316
2414
2365
2414
937
2414
2038
2414
1037
531
36
164
129
164
97
164
56
1906
1767
630
615
630
606
630
601
467
254
467
249
467
244
467
219
390
340
390
384
724
286
724
289
1615
446
1615
744
149
24
149
37
441
37
528
61
198
9
198
177
198
186
719
497
630
615
2120
1125
497
30
674
663
441
230
441
201
441
198
441
216
441
49
441
395
441
403
441
180
441
174
441
211
441
152
441
190
441
204
441
421
441
234
441
45
529
325
529
302
529
306
545
211
802
359
802
580
802
699
1257
1247
1257
1203
595
117
595
105
595
103
331
72
331
62
498
307
498
295
1332
143
1332
844
409
13
409
275
1531
1360
1531
1246
1531
1353
1531
1392
1531
1212
875
729
551
434
117
44
117
63
117
35
117
81
117
68
360
245
360
189
439
61
439
57
598
430
202
67
1464
735
882
35
882
37
882
402
882
504
264
103
264
81
464
61
118
64
118
69
118
36
118
45
1215
1030
391
361
391
359
525
446
525
433
525
443
525
440
933
293
772
342
772
567
217
150
1600
1231
198
68
1113
547
1113
541
920
515
648
28
648
42
648
288
648
300
648
641
298
159
1970
1618
462
202
465
194
465
186
465
205
465
213
461
202
673
293
673
343
673
424
673
11
1210
692
1335
695
1335
862
1335
7
1255
700
1047
80
1047
92
391
348
766
400
766
752
1014
371
1014
372
367
322
367
295
367
358
367
363
1613
1489
1613
1571
968
905
968
309
968
307
498
30
498
7
794
779
1161
201
1161
206
473
181
656
78
168
74
393
285
393
291
393
385
740
226
740
576
740
385
931
453
319
219
400
8
400
221
400
271
400
24
400
333
524
57
1807
663
360
65
360
92
1871
232
1871
236
1581
1456
1581
1031
1475
515
1475
387
1475
256
1475
337
1475
319
1475
528
1475
333
1475
412
1475
368
1475
521
726
599
726
595
726
591
986
678
826
642
826
640
1147
1004
1147
1010
1130
279
1130
287
149
24
416
124
476
281
360
117
360
110
360
354
673
578
2749
435
2749
1764
736
658
780
570
405
95
405
89
1203
1157
700
49
219
159
219
17
246
176
323
320
169
93
169
96
606
534
2225
455
345
234
2225
455
509
58
509
41
498
30
199
144
1914
1778
462
259
1147
116
350
162
358
20
175
44
381
158
381
196
381
158
381
196
384
375
384
345
384
320
505
70
505
89
557
82
557
129
557
125
735
358
735
572
735
362
560
459
465
254
296
187
685
574
685
607
685
620
384
224
452
221
452
224
1383
687
1383
807
150
115
345
153
345
151
345
163
239
73
239
55
239
86
483
131
505
272
505
111
1216
981
419
72
643
57
2073
131
501
357
501
352
428
382
428
323
428
335
428
352
428
362
428
367
428
388
428
416
428
421
280
35
785
58
785
452
785
738
1441
1178
1441
1184
1441
394
852
322
1608
1408
1608
1388
2442
92
480
275
480
461
480
299
480
292
480
302
597
347
597
160
2326
2313
326
321
326
319
252
208
252
78
1132
522
196
64
586
129
261
67
261
180
508
409
508
393
508
391
508
215
508
264
508
182
508
224
508
266
2090
1808
2090
1709
528
318
560
27
560
37
560
526
560
35
560
39
560
529
158
118
654
386
654
613
97
20
97
29
418
411
957
626
957
632
236
69
479
386
181
80
331
143
519
336
519
351
704
61
704
66
341
99
768
280
158
146
820
774
820
775
1454
985
332
45
487
52
635
322
635
370
935
892
935
811
935
865
935
858
468
314
468
220
2339
446
2339
410
440
37
441
260
781
72
822
776
551
475
1097
1043
204
185
538
533
1109
866
199
161
760
685
440
104
724
357
549
252
707
204
857
820
380
324
380
330
668
649
704
510
926
293
595
265
541
458
560
285
676
622
461
141
451
276
739
536
756
95
1430
733
1430
735
706
332
706
342
816
732
1141
454
1141
431
260
25
873
442
902
675
304
231
735
249
870
671
694
475
694
453
694
311
694
581
694
596
694
380
594
149
594
475
594
417
1164
497
740
528
740
487
443
70
443
57
443
83
685
607
685
574
685
620
525
446
525
443
525
433
345
244
345
218
464
424
464
427
1244
793
1244
1222
433
125
433
127
334
245
401
221
401
70
283
65
283
60
504
437
551
450
315
51
710
708
710
174
710
346
710
286
752
515
268
86
268
103
716
538
629
420
815
778
815
725
815
770
815
722
815
784
815
692
815
769
863
763
863
644
353
13
353
64
542
364
693
237
548
525
548
160
548
250
548
245
390
384
390
340
735
572
269
165
550
65
550
457
2701
2638
2701
2653
2701
2604
2701
2607
224
176
665
445
429
353
429
389
429
336
429
368
429
417
429
422
429
363
429
383
1333
1196
1333
1192
1333
1131
1333
1177
1333
1166
407
314
407
268
359
47
425
207
425
203
425
178
425
212
180
67
341
89
341
99
341
116
651
351
651
358
651
354
853
297
1128
826
590
209
854
264
1445
1186
1445
1266
1445
1177
380
231
380
324
380
330
380
361
380
373
526
232
602
338
602
334
870
322
584
489
2412
2275
2412
2363
2412
2311
454
290
454
268
454
264
454
298
454
272
454
295
454
285
505
111
468
127
507
412
530
86
530
104
861
156
543
20
357
161
357
258
357
273
357
265
118
35
184
73
184
76
417
202
686
292
766
792
630
606
630
615
630
601
749
504
358
187
327
147
2063
883
224
176
564
486
156
17
156
122
156
125
329
187
479
221
479
95
479
214
479
102
492
297
305
51
305
64
523
182
413
175
413
173
413
169
413
25
821
779
443
83
764
200
764
116
598
131
598
125
756
95
402
375
3
752
206
162
912
254
984
195
984
262
984
226
984
360
984
286
984
237
938
814
938
861
938
868
938
895
698
98
698
101
698
92
698
91
698
87
742
621
582
506
326
227
158
146
1447
1177
1447
1186
1447
1266
603
221
671
529
372
3
372
7
1097
860
1097
863
848
802
365
271
365
212
365
172
365
188
460
249
460
246
460
18
460
15
209
199
270
165
270
84
270
174
630
158
2703
1067
877
219
209
199
400
246
3
116
1096
304
1096
621
1096
1064
1096
565
1096
351
413
72
1560
1443
1560
1016
3
149
3
417
3
475
619
390
396
340
396
305
396
147
802
579
802
426
802
422
802
614
802
610
802
576
326
321
326
319
387
164
369
232
460
249
460
246
460
18
460
15
579
38
579
380
457
407
580
42
580
524
580
49
457
407
838
502
651
502
463
352
463
215
483
73
483
431
393
19
393
80
1242
311
1242
306
781
36
781
32
781
40
770
726
204
200
164
129
164
97
164
56
724
294
441
230
441
201
441
395
441
180
529
362
331
72
331
62
331
90
331
92
864
198
864
221
864
231
747
46
747
529
747
26
227
95
227
171
439
70
439
61
598
94
202
67
473
167
1518
1052
504
118
504
137
504
153
504
366
504
411
163
114
920
650
462
460
462
180
462
444
303
171
672
572
673
573
1335
695
1335
862
1335
705
1047
80
1047
92
440
421
1424
866
1424
859
1424
542
1424
23
1424
504
781
190
781
604
427
172
847
706
656
78
777
225
749
726
463
357
463
204
416
67
416
82
416
215
245
183
233
46
233
114
233
61
487
81
149
37
149
24
149
37
943
171
1321
487
179
61
179
72
1036
197
462
259
462
55
462
69
462
81
1147
116
350
63
350
162
350
120
505
68
505
70
505
89
505
52
239
69
239
68
239
86
521
117
428
382
785
277
785
738
233
154
196
64
196
54
236
69
332
45
487
52
487
50
579
35
902
216
902
212
591
177
566
100
566
102
138
55
138
57
138
43
763
735
179
72
401
221
401
70
795
245
504
437
366
331
680
50
347
101
347
103
770
742

163
147
546
28
546
92
546
317
546
390
546
401
546
410
546
490
546
405
663
640
431
424
431
380
431
360
431
365
431
386
431
419
1861
1621
1861
1618
1861
1624
180
59
505
111
184
73
531
364
532
193
695
667
281
262
195
58
711
204
711
102
505
454
505
226
505
229
505
450
196
113
196
99
196
111
196
64
903
239
903
262
903
272
985
512
985
300
985
692
985
586
985
751
985
373
200
119
200
182
200
147
888
532
888
42
1395
1297
1395
1294
1395
1299
1395
1304
1395
726
1190
738
1190
733
248
185
663
519
663
514
663
517
1337
286
1337
265
1337
275
927
169
927
222
927
115
927
109
927
218
927
331
237
49
347
99
464
454
507
91
507
201
507
204
239
8
239
5
334
62
773
152
390
206
390
60
390
305
312
139
355
9
910
102
323
61
246
185
582
314
425
134
373
156
373
345
3
183
467
244
467
254
676
276
676
271
676
420
676
423
916
761
916
765
916
767
916
762
1586
1545
698
98
698
101
698
92
698
91
698
87
295
9
3
212
3
216
454
153
454
316
454
361
724
547
375
61
425
134
352
346
463
352
463
283
296
229
390
344
390
347
483
431
750
726
550
417
550
404
607
379
393
14
393
391
824
734
1242
615
243
41
575
284
575
288
420
42
736
615
164
129
164
97
1906
1767
630
606
630
601
630
615
467
7
467
244
467
249
467
219
467
254
501
34
619
52
528
61
198
186
630
615
497
30
441
180
441
234
441
230
441
49
441
395
441
152
441
198
441
174
441
216
441
204
441
45
441
201
441
403
441
211
441
421
529
302
802
359
802
580
802
699
205
72
595
117
595
103
595
105
498
350
498
345
498
342
1332
143
1332
844
409
275
409
13
1531
1212
1531
1353
1531
1360
1531
1246
1531
1392
640
531
651
632
202
67
477
71
1464
735
1215
1034
1215
1030
933
293
772
342
772
567
217
150
1600
1231
198
68
1113
547
1113
541
920
650
920
515
648
288
648
300
648
295
298
159
1970
1618
454
78
673
11
673
424
673
343
673
293
1210
692
1335
695
1335
862
1335
7
1255
700
766
400
766
752
367
363
1613
1489
1613
1571
794
779
656
78
777
225
168
74
393
291
393
285
931
453
524
57
1807
663
1581
1456
1475
521
1475
515
1475
337
1475
319
1475
528
1475
412
1475
333
1475
387
1475
256
1475
368
1130
287
1130
279
416
124
476
281
193
99
193
87
689
669
360
110
673
578
943
171
196
86
196
26
196
23
780
570
700
49
2225
455
345
234
331
121
509
41
509
58
1914
1778
1822
1355
462
259
1147
116
350
162
350
91
358
20
175
44
381
158
381
196
381
299
381
173
381
196
381
158
413
177
384
345
384
320
384
375
505
68
557
129
557
82
557
125
735
358
735
362
735
572
560
459
465
384
296
178
296
183
793
788
793
758
685
574
685
607
685
620
384
224
452
221
452
224
1383
807
1383
687
150
115
345
153
345
151
345
163
239
55
239
73
239
86
483
131
505
132
1216
981
521
23
521
502
521
313
521
311
521
274
521
42
521
27
521
293
521
339
87
21
419
72
643
57
665
613
665
468
665
611
665
440
665
590
2073
131
501
357
501
352
452
256
452
212
428
388
428
382
455
374
280
35
785
738
785
452
785
58
233
154
1441
1178
1441
1184
852
322
1608
1408
1608
1388
2442
92
480
461
480
302
480
275
480
292
480
299
597
347
597
160
741
561
2326
2313
326
319
326
321
252
78
252
208
1132
522
196
64
586
129
261
67
261
180
508
391
508
393
508
182
508
264
508
215
508
224
508
266
508
409
2090
1709
2090
1808
814
373
814
335
814
353
985
677
985
958
528
318
528
300
215
122
700
49
560
529
560
526
560
27
560
35
560
37
560
39
158
118
654
386
654
613
345
276
1483
157
821
627
821
623
97
20
97
29
418
411
379
206
379
203
957
626
957
632
479
386
284
10
331
143
519
336
519
351
1425
775
1425
768
108
99
768
280
192
107
158
146
820
774
820
775
597
206
1454
985
332
45
759
373
759
361
759
603
635
322
935
865
935
892
935
811
935
858
468
220
468
314
2339
410
2339
446
440
37
441
260
781
72
822
776
551
475
1097
1043
204
185
538
533
1109
866
199
161
760
685
440
104
724
357
707
204
1153
744
857
820
668
649
592
563
592
582
704
510
595
265
541
458
560
285
676
622
461
141
218
200
1274
1256
739
536
756
95
382
224
1430
733
413
243
413
383
706
342
706
332
148
37
816
732
1141
431
1141
454
260
25
873
442
429
173
477
325
902
675
304
231
735
249
847
757
847
704
694
453
694
311
694
581
694
596
694
475
694
380
594
149
594
475
594
417
740
576
552
276
380
231
380
330
380
324
380
361
413
175
413
173
413
169
413
25
764
200
764
116
262
55
580
469
756
95
938
814
938
861
938
868
938
895
158
146
3
116
413
72
3
149
3
417
3
475
790
263
463
352
463
215
164
129
164
97
439
70
439
61
439
57
149
37
149
24
943
171
158
118
331
101
331
143
579
35
770
742
138
57
763
735
795
245
695
667
195
58
711
102
711
204
196
64
1190
738
1190
733
956
175
963
174
458
128
458
37
916
761
916
765
916
767
916
762
3
742
677
667
463
378
136
9
136
10
393
105
393
214
393
314
638
493
638
504
638
282
420
8
466
71
650
290
650
288
595
166
595
304
414
364
448
18
317
35
317
31
317
62
317
261
747
343
904
219
1863
307
172
169
213
71
580
352
968
828
172
169
209
24
572
100
572
101
1518
48
1518
49
1518
32
1518
31
716
47
716
89
716
93
403
66
403
286
403
147
403
265
403
277
403
225
403
15
403
9
403
40
403
97
403
341
403
103
403
82
403
390
403
287
617
174
372
20
2115
1886
2115
1810
2115
2046
2115
2083
2115
1811
2115
1968
2115
1803
2115
2086
2115
1990
2115
1882
462
35
462
34
1278
18
415
13
415
172
504
396
728
382
728
325
730
718
730
195
1328
1302
401
94
1338
466
561
170
561
176
1356
961
660
404
345
250
603
209
846
626
846
724
846
829
846
756
208
202
1088
82
1088
379
636
234
291
84
291
23
647
624
647
304
198
97
198
92
198
93
834
295
642
54
642
43
642
68
747
120
747
124
281
175
163
15
1113
538
920
281
920
292
184
8
1455
164
441
239
631
346
140
6
340
202
340
201
206
193
838
557
299
38
647
507
647
306
430
52
986
885
337
217
298
199
298
130
1193
114
345
250
294
124
897
592
897
326
2701
421
565
85
1232
798
3
314
566
171
501
492
501
441
501
266
262
123
262
108
334
161
410
19
410
18
301
196
199
69
446
326
458
45
3
961
539
252
325
199
325
242
3
352
473
307
1101
572
1235
611
1235
501
1235
98
1235
306
390
347
390
282
390
207
536
530
536
532
750
726
456
253
2171
1703
393
149
393
391
393
154
393
148
393
45
393
5
393
54
882
849
882
852
882
846
2514
2521
2514
2510
771
25
771
72
308
256
308
272
308
213
308
289
308
298
198
82
508
84
508
78
508
82
508
76
327
110
327
128
327
142
327
113
327
107
327
141
1873
1578
1482
1479
140
128
529
141
925
853
925
769
925
854
545
222
108
100
108
103
108
98
108
99
355
28
169
30
169
29
169
13
169
14
750
5
403
379
403
384
403
369
403
382
403
381
802
759
802
756
802
792
802
758
802
757
205
86
205
120
205
121
1476
669
1476
421
1476
1466
162
35
162
22
2364
2109
2364
2158
832
553
832
718
310
85
310
105
310
75
310
66
310
97
310
63
310
153
310
65
310
61
310
299
310
74
310
30
1257
52
1257
692
1257
696
650
290
650
288
1976
1955
1976
1951
1976
1959
1976
1964
1976
1974
824
153
522
403
522
407
522
399
414
378
414
409
414
408
1257
1180
1257
1171
633
487
633
420
633
417
633
415
633
407
633
484
633
474
633
577
633
524
633
409
633
522
633
517
633
408
633
518
633
514
185
50
327
235
595
281
595
166
595
558
754
19
754
17
754
8
332
222
332
123
204
33
204
23
478
75
478
68
501
480
501
479
305
52
906
640
414
117
502
482
502
483
208
148
324
246
324
249
324
263
392
355
392
349
392
354
392
353
431
206
431
389
431
207
431
388
504
265
504
345
504
272
504
346
504
263
504
248
504
264
884
839
884
854
884
852
884
841
884
847
696
694
100
98
100
88
100
7
100
85
100
6
963
277
517
22
517
292
517
100
517
387
517
62
517
12
517
392
1074
610
1074
609
708
687
708
557
708
560
708
648
708
688
424
406
424
403
331
242
331
248
331
230
271
46
271
35
271
40
271
49
271
50
271
15
239
234
239
228
239
232
770
238
770
252
326
109
498
496
498
483
498
487
498
481
498
488
330
42
515
513
515
511
399
384
399
392
741
569
217
132
217
202
217
203
217
131
142
52
630
407
630
526
630
405
630
530
630
409
632
499
394
341
394
348
394
349
394
346
2089
217
2089
401
2089
298
2089
328
2089
219
2089
377
2089
403
2089
330
2089
454
2089
452
2089
300
2089
375
495
481
495
484
495
482
317
313
301
295
301
24
301
18
301
17
301
19
384
346
384
340
384
345
384
344
178
87
741
496
149
101
149
81
149
79
149
117
709
509
709
687
709
656
270
162
270
176
864
424
318
162
1332
742
740
736
740
738
503
200
896
711
896
701
896
710
896
708
896
713
448
8
448
329
448
6
448
334
323
284
323
314
323
275
292
105
426
355
426
346
475
20
475
15
317
35
317
282
317
287
317
292
317
290
317
298
317
31
561
485
561
486
409
381
765
505
765
9
655
554
655
50
655
221
655
725
1289
4
1289
5
1289
6
1289
1280
651
466
651
465
651
467
1941
1920
2005
1123
2005
1125
2005
1111
747
660
747
658
171
145
171
148
1531
1524
1531
1468
1531
1364
1531
1376
259
143
259
125
259
193
395
380
291
193
291
139
291
137
1217
1066
408
365
640
11
640
10
160
34
160
32
215
2
215
1
327
110
327
107
327
96
327
93
961
941
961
583
961
574
961
943
961
739
837
486
837
490
837
484
227
192
227
88
227
94
227
87
227
191
412
382
412
364
412
370
651
169
651
171
713
212
713
186
713
33
875
715
875
92
875
104
361
235
361
334
361
346
3
79
858
508
340
230
491
259
491
268
728
603
728
608
728
611
728
609
659
45
291
283
2085
2072
101
89
101
99
189
185
439
121
732
125
732
120
732
122
868
679
868
696
172
134
480
128
1306
1298
904
40
904
12
904
107
904
39
904
52
904
138
904
26
236
202
236
221
236
232
236
230
236
235
628
597
961
940
845
139
845
108
852
713
852
705
852
664
852
663
668
481
668
483
668
479
732
262
732
35
732
725
732
724
258
126
1863
1571
323
314
450
443
551
528
644
502
644
517
644
504
127
1
249
157
249
203
721
717
721
716
2555
1899
2555
1896
222
220
288
13
2491
2483
2491
2408
782
750
247
229
247
227
785
131
440
21
440
427
705
205
399
60
399
41
543
188
1438
1363
130
115
333
1
333
66
543
472
2472
1301
238
232
117
63
281
161
695
386
695
349
1531
248
1480
510
1480
420
1480
426
1480
421
2261
1254
2261
1242
2261
1241
794
774
794
772
737
648
737
153
737
650
737
682
172
137
172
157
164
72
360
245
360
247
92
62
439
251
439
248
439
249
439
346
439
347
598
151
113
9
357
109
357
155
719
43
719
45
1270
177
269
56
304
29
735
656
202
19
202
17
1960
1942
1960
1915
288
13
391
340
391
386
224
182
474
462
251
243
255
249
255
242
351
203
351
160
280
161
213
42
213
32
213
37
406
303
752
6
439
393
439
391
357
347
477
459
507
288
134
114
1015
974
1015
972
339
12
1613
1578
479
204
486
15
486
22
356
312
356
314
278
267
316
277
316
279
427
327
231
149
639
354
284
231
284
230
336
232
428
423
378
12
361
217
580
186
580
185
1497
543
1497
541
320
152
320
30
320
75
320
76
852
136
852
130
1145
70
1145
109
1145
68
160
1
160
10
724
225
724
254
724
717
288
13
1464
492
1464
498
1464
486
1464
468
882
564
882
559
882
560
882
561
224
213
225
111
225
105
488
393
270
60
2440
2435
452
156
614
498
264
91
255
132
255
48
221
148
418
23
418
113
246
29
1230
857
1230
537
464
260
464
262
479
204
301
17
301
18
301
19
131
18
1210
210
118
111
587
357
461
302
789
76
186
128
400
363
313
123
228
10
228
12
205
96
205
44
205
101
683
493
302
287
282
279
282
281
492
473
492
474
444
387
444
384
866
541
866
608
247
234
142
47
558
184
390
279
359
322
359
323
359
319
1215
457
379
12
308
299
968
811
473
235
482
422
482
420
409
381
466
148
160
112
160
117
372
198
286
8
306
259
1102
17
1089
827
134
114
277
8
549
526
427
207
646
120
632
96
172
137
845
257
391
181
297
38
338
26
525
39
410
382
441
357
933
80
125
118
2224
719
772
323
919
65
700
17
437
428
217
23
447
197
1600
1238
724
607
209
183
1859
296
1859
291
440
402
1255
695
1255
699
560
319
560
320
560
154
560
287
1451
890
1451
897
1451
885
1451
881
1451
883

1451
895
1060
853
641
635
296
221
297
222
130
56
107
102
107
101
1488
209
294
124
96
91
96
90
143
56
3142
12
3142
15
1271
1263
361
334
361
346
626
89
481
130
292
124
417
255
1306
1001
1306
1002
1306
998
1306
1006
245
231
681
677
756
476
1912
309
1912
307
1912
427
460
253
355
337
351
214
451
395
501
480
501
479
786
620
209
193
209
203
209
195
209
186
209
204
209
180
209
196
209
178
209
181
907
901
149
101
149
79
149
81
291
31
540
361
540
357
540
369
540
365
206
152
284
282
1276
664
1276
668
1276
680
155
12
494
123
908
385
908
388
912
389
912
392
187
144
187
167
205
120
205
126
205
121
1166
945
1166
938
1166
937
1166
947
1166
940
760
747
760
573
760
575
473
379
473
382
505
149
534
5
371
45
250
80
940
128
940
93
571
176
805
786
649
52
667
53
667
55
667
54
849
631
984
110
984
458
530
526
530
521
530
439
530
522
530
434
708
654
568
409
551
86
512
294
364
235
449
157
529
434
529
439
529
521
529
522
529
526
3
485
3
486
185
88
526
315
900
103
2386
2383
1235
331
1255
1226
597
334
597
337
393
375
781
36
781
32
781
40
781
22
781
28
770
726
770
713
420
215
736
39
736
43
736
692
536
50
536
42
536
492
536
418
531
327
164
113
164
56
1906
1764
724
18
167
156
167
160
441
268
441
264
508
223
630
47
327
128
140
128
441
230
441
201
441
198
441
399
441
216
441
194
441
213
441
49
441
395
441
403
441
180
441
261
441
174
441
211
441
152
441
204
441
421
441
234
441
408
441
209
441
45
529
302
355
28
403
365
403
361
205
72
832
525
595
101
595
117
595
105
595
103
884
848
331
242
331
238
331
248
651
16
651
12
1531
1360
327
128
327
114
628
595
732
725
732
724
551
467
439
57
439
61
269
166
269
170
735
648
735
640
735
644
735
652
213
67
284
65
284
60
852
682
724
717
264
103
264
95
264
118
264
114
264
99
264
106
264
110
464
57
479
200
118
64
118
69
118
36
118
45
646
210
345
331
340
178
340
177
340
174
437
432
437
402
465
201
465
5
465
6
559
489
559
485
559
481
622
607
1051
414
1051
404
1335
858
1335
862
1335
791
1335
876
1335
721
1809
1376
1809
1384
1809
1380
1809
1372
1613
1489
228
110
228
112
2843
1502
2843
1500
781
36
781
40
781
32
722
211
436
321
776
181
572
508
572
513
572
517
427
179
427
122
427
172
758
547
758
578
758
574
758
551
758
712
758
720
737
652
737
644
737
648
737
640
737
345
292
282
777
403
233
61
1417
170
524
75
1046
2
1046
3
726
612
726
692
968
906
968
902
826
554
826
588
826
550
1130
372
641
635
1274
132
1274
303
295
285
470
31
470
27
591
570
663
524
467
261
467
258
568
332
345
222
345
225
345
230
509
235
355
82
2871
2844
2871
2848
1914
1775
462
48
462
65
462
77
484
341
1147
433
1147
429
1147
425
279
187
350
158
350
120
350
162
296
178
296
183
419
297
419
396
419
404
419
400
785
727
785
731
1425
775
935
457
935
623
935
627
935
465
935
461
935
453
935
635
935
631
595
36
847
788
847
792
402
390
189
147
189
143
189
182
707
686
920
530
268
155
268
154
1247
1077
864
773
938
251
938
309
419
30
419
42
419
7
419
16
297
188
297
184
2078
2021
788
211
746
362
746
366
1708
1694
1708
1234
1193
977
1193
973
1193
936
1193
110
1294
506
1294
498
1294
532
1294
536
1294
502
293
229
293
233
513
85
513
89
497
179
748
473
559
277
559
273
770
742
313
63
313
59
1084
301
1084
297
1367
1277
310
185
310
152
552
264
552
272
552
268
783
181
795
218
710
578
347
254
347
250
900
710
900
221
900
706
376
32
467
352
467
356
467
396
478
99
404
77
404
79
776
261
776
269
776
273
776
278
776
282
776
265
776
256
776
287
1327
981
1327
977
1327
990
1327
986
1026
502
263
230
263
233
1374
301
1374
299
323
9
192
162
534
177
534
181
407
400
407
404
1901
1135
1901
1139
507
152
507
144
507
148
386
153
431
269
431
273
360
326
979
123
979
119
346
229
346
154
410
72
410
394
410
76
866
779
283
267
283
271
1717
1378
1717
1358
1717
1362
1717
1380
268
103
268
95
268
99
268
91
474
308
864
778
614
54
614
58
387
11
570
513
570
517
570
508
769
389
769
163
636
571
415
414
415
341
493
150
493
154
334
155
2464
1259
1110
72
572
517
572
508
572
513
716
534
770
742
313
282
570
513
570
508
570
517
361
255
919
555
239
194
579
572
792
411
792
420
289
279
468
72
1072
492
605
346
605
343
364
37
364
41
226
10
772
378
626
20
626
16
457
302
846
426
252
162
1053
721
567
441
769
269
789
782
851
392
851
384
851
380
325
183
325
179
353
60
353
56
353
48
353
52
7388
7313
7388
7221
7388
7317
7388
7321
7388
7225
7388
7329
7388
7229
7388
7233
7388
7325
7388
7309
180
59
479
179
862
480
245
234
245
242
245
230
245
238
848
722
848
439
848
696
848
726
848
443
848
435
848
688
848
730
848
692
927
214
927
222
927
218
207
190
283
106
283
12
526
404
202
183
202
182
215
158
570
627
570
622
570
631
290
183
290
179
522
68
522
66
522
62
3
547
916
761
916
765
916
767
916
762
3
1226
540
361
540
357
540
369
540
422
540
418
540
365
593
553
3
631
3
627
3
622
329
180
329
184
703
640
703
644
703
648
703
652
966
585
469
31
469
27
938
450
938
454
938
458
938
462
938
625
938
629
938
633
938
637
579
45
902
256
902
262
902
266
902
270
422
93
422
97
408
340
359
52
359
64
359
48
359
60
359
56
895
637
698
98
698
101
698
92
698
91
698
87
475
309
475
307
216
145
214
182
214
186
502
248
502
252
1978
1935
375
177
564
515
653
275
653
187
1423
31
1423
20
237
192
520
398
3
56
433
215
395
243
395
288
440
314
440
315
297
287
297
127
287
283
434
32
270
40
270
139
423
403
522
265
410
371
1235
611
1235
317
1235
497
1235
306
1235
23
1235
569
296
229
296
148
737
725
737
4
390
303
390
302
390
314
482
472
1205
496
2171
1927
2171
527
2171
532
2171
1673
212
43
212
45
630
475
630
439
1242
322
1242
440
147
37
781
44
420
146
420
8
198
2
2531
1790
466
33
466
38
466
55
441
351
441
257
441
323
441
292
403
379
403
382
403
381
1976
1936
1976
1934
1976
1955
522
403
522
437
522
423
522
402
551
310
264
248
504
109
504
108
1113
977
1113
974
756
176
756
180
1424
1058
1424
1032
1424
1041
1424
1063
1424
1113
1424
1066
1424
1047
1424
1061
480
383
480
444
413
374
413
353
726
712
416
143
753
563
1023
15
839
800
785
667
785
680
785
669
785
640
785
650
785
701
788
595
483
246
346
344
976
891
433
427
433
306
795
612
192
183
605
39
436
430
592
559
479
471
749
375
244
209
1337
826
806
485
68
58
1174
256
472
441
246
131
271
36
533
54
533
56
533
77
404
398
295
221
295
10
592
185
592
112
592
559
510
17
257
54
1025
79
1025
90
296
260
531
475
300
284
501
54
307
32
653
294
404
390
125
49
486
455
215
38
215
52
215
180
640
6
640
283
640
264
389
315
356
16
741
210
741
215
304
10
389
315
1235
607
1235
1221
1235
938
1235
459
1235
1171
1235
627
1235
986
1235
894
1383
1185
1383
1361
1383
1189
1383
1190
1383
1355
906
699
906
370
906
773
519
487
519
512
621
617
480
360
480
396
559
8
559
375
559
378
162
26
162
18
346
20
1235
607
1235
938
1235
657
1235
1171
1235
726
1235
627
1235
986
1235
894
1235
788
1068
864
327
132
896
850
896
619
896
574
896
617
896
576
896
855
896
852
896
854
672
397
672
411
672
553
672
586
672
624
1051
316
1051
554
1051
636
1051
776
865
567
606
70
606
279
390
17
797
176
797
537
375
273
375
317
781
551
1233
788
474
312
2345
1199
2345
1214
2345
78
1202
1175
1202
493
1134
388
559
171
559
182
474
312
724
396
541
519
541
522
1202
493
1202
1175
1095
125
692
170
1113
249
1113
487
2412
88
391
14
887
870
270
107
270
24
270
23
1255
230
1255
699
2345
78
759
558
126
36
1095
125
448
87
448
90
448
93
691
170
588
70
588
279
331
24
555
489
738
7
125
36
887
162
887
164
796
175
796
536
724
396
887
162
887
164
448
87
448
90
448
93
738
7
704
7
126
36
126
36
126
36
126
36
126
36
126
36
126
36
126
36
126
36
1335
721
1335
791
1134
388
768
564
2448
211
330
24
864
565
1235
521
243
69
327
118
673
31
673
252
1809
938
1809
1465
420
8
1202
1175
595
314
595
229
249
234
249
235
559
495
483
20
649
23
649
249
649
312
665
403
458
155
205
136
128
104
1339
1179
672
251
672
31
52
15
1100
453
476
279
1622
139
599
432
1998
368
2549
2172
603
394
1108
278
432
49
491
116
491
383
338
89
338
91
338
202
322
99
504
192
648
258
233
105
552
490
255
246
1235
23
770
726
1235
894
1235
1171
597
567
572
31
864
380
781
141
323
309
317
303
733
17
474
412
938
111
223
200
223
217
572
503
789
636
789
637
789
715
789
718
358
259
1482
1471
1482
1069
1482
1251
1482
1038
1482
1108
1482
931
1482
1335
140
124
674
310
674
331
979
933
979
937
933
164
933
469
933
10
933
13
852
347
1009
579
429
313
292
14
537
419
397
324
397
368
1256
1207
355
267
355
290
343
287
343
314
343
334
974
955
974
968
527
419
189
169
189
180
578
565
682
299
682
276
410
306
410
329
410
382
474
440
474
439
474
456
474
391
407
252
125
101
520
292
305
298
670
266
670
426
1235
306
1170
577
243
208
522
480
522
485
211
94
412
30
412
42
412
368
488
374
314
31
314
35
210
119
210
94
1235
23
597
39
382
367
829
179
829
203
907
848
907
857
130
103
357
132
648
618
648
496
211
143
211
22
211
23
211
42
211
44
1210
677
2441
435
209
85
209
14
544
33
285
203
285
83
285
82
466
8
466
65
466
50
466
33
466
41
466
9
466
24
466
25
466
6
466
20
466
38
709
429
918
743
779
576
296
216
296
238
487
102
487
321
487
348
760
23
883
879
480
472
665
198
665
479
665
524
665
4
665
415
665
651
436
430
390
179
590
567
590
460
171
66
206
186
648
498
355
76
301
206
301
210
301
215
301
296
915
861
421
98
421
95
217
208
382
370
382
342
382
337
382
312
382
336
883
879
979
742
979
747
130
102
672
496
672
656
261
124
599
215
348
337
348
333
473
432
473
431
2327
2256
1600
1186
488
145
488
164
92
87
1115
939
587
432
271
165
72
1
452
178
72
2
271
261
271
164
493
38
463
301
287
137
848
34
323
179
689
28
671
499
696
164
467
166
558
416
558
316
1192
759
1235
611
737
725
737
715
390
369
390
358
487
397
382
367
382
368
382
261
398
369
478
285
2336
897
2336
801
2336
895
1199
694
838
799
838
501
829
203
829
179
1484
1302
1484
1322
441
234
441
395
441
403
441
230
495
433
495
435
1480
685
1480
681
1480
640
1480
706
1480
603
1480
789
648
496
648
618
1255
685
1383
1062
1383
1375
299
204
299
208
299
213
299
294
726
712
726
702
92
87
92
82
501
184
196
13
196
62
92
82
92
87
352
314
352
306
595
565
1023
22
1023
15
211
22
211
23
211
44
211
42
2326
2255
332
162
332
166
689
28
339
25
864
794
474
380
474
364
883
879
883
696
883
862
883
660
297
104
297
239
468
12
468
33
468
7
467
345
770
729
358
247
213
103
390
179
864
794
171
64
292
169
474
380
1370
1362
519
502
938
896
938
889
938
895
339
153
928
921
1166
9
508
144
508
134
508
171
206
186
206
137
431
157
431
322
635
20
635
14
635
7
635
8
1171
900
480
472
594
305
594
312
226
168
386
327
224
86
226
40
485
414
531
475
201
187
201
186
339
25
335
54
335
43
309
151
309
155
309
162
887
870
1241
1114
735
723
1074
560
1074
1
1074
146
383
345
383
172
383
337
383
176
410
372
410
230
410
364
410
234
464
55
464
28
464
37
464
11
1464
1415
976
936
421
111
333
12
211
23
211
22
211
160
211
94
189
176
242
219
242
98
242
220
1234
1104
78
35
561
224
561
277
1214
65
1214
69
270
164
270
57
145
57
271
165
72
1
487
102
487
321
487
348
469
131
469
150
215
45
804
30
1036
146
1036
560
1036
1
181
165
181
83
920
893
920
899
731
277
374
333
397
341
376
153
876
713
538
325
538
358
905
878
905
884
474
433
210
119
210
159
210
94
278
266
278
9
271
165
271
58
466
364
187
152
705
691
463
431
463
430
530
479
692
468
692
470
280
37
280
36
672
656
374
335
473
316
419
190
585
502
604
39
1243
1138
907
480
907
487
546
144
546
134
546
171
126
13
1235
356
394
360
394
359
382
367
211
23
211
143
211
22
689
28
673
661
673
504
318
160
245
57
243
5
243
220
246
58
1234
1104
72
1
381
127
335
177

918
747
918
743
482
399
86
77
246
59
1738
1652
1235
317
838
799
722
538
1383
1062
1023
15
1023
22
592
559
480
33
1025
79
1025
90
786
641
786
651
786
670
786
681
793
612
469
438
479
471
757
176
757
180
797
616
436
432
353
16
1235
1099
1242
638
1242
311
1242
615
1242
635
1242
306
204
135
907
857
357
132
614
498
2549
2445
2549
2447
1233
264
1233
301
1233
306
1233
521
1233
631
420
8
489
162
436
430
621
46
469
66
249
235
249
234
724
364
599
170
1708
1134
531
368
1512
998
169
70
535
259
1235
264
1235
301
1235
306
1235
521
1235
631
1235
1099
249
239
249
243
420
8
249
243
249
235
249
239
249
234
483
20
1110
418
1110
417
1110
421
205
136
531
483
531
466
2549
2445
2549
2447
469
66
1235
306
724
294
1233
306
149
37
149
24
179
61
179
72
341
99
334
62
334
72
795
245
427
381
360
330
360
320
360
333
1861
1621
1861
1618
1861
1624
205
128
136
28
1327
347
786
278
786
739
236
68
236
69
236
83
425
134
1183
731
163
147
708
102
708
201
199
119
199
147
199
182
373
156
467
60
467
74
467
86
467
264
469
135
469
332
469
377
1247
443
1233
443
1235
634
1235
301
1235
631
1809
1202
1233
301
1233
634
1233
631
1032
853
1032
696
1032
854
171
19
469
16
469
75
469
76
430
6
430
35
638
504
647
507
448
264
140
137
1235
631
466
38
466
71
1032
696
1032
853
760
531
572
554
171
18
171
19
206
137
577
557
586
566
297
169
297
174
297
179
297
183
297
258
735
444
735
479
1388
413
1235
788
1242
793
1233
788
692
170
619
161
307
90
1235
23
382
367
2336
897
2336
773
838
799
838
501
907
709
907
848
907
835
907
862
466
6
466
8
466
9
466
33
466
38
466
41
466
65
323
179
2005
1505
2005
553
2005
572
2005
575
498
39
1383
1375
1203
838
1203
932
2345
94
92
88
92
87
92
82
1023
15
1023
22
2169
1926
908
845
908
867
883
716
883
682
297
239
1956
1451
171
64
363
353
938
895
938
896
938
889
938
888
949
724
949
760
1166
553
1166
659
1166
916
206
137
206
186
1090
489
1090
542
205
28
533
39
533
522
1216
886
226
40
136
11
136
6
1274
286
335
54
335
43
457
426
283
232
130
102
515
399
515
393
367
332
367
314
309
155
309
162
309
151
889
710
889
137
136
11
136
6
735
723
735
713
1074
146
1074
560
1074
1
557
477
648
496
648
498
365
73
365
109
365
293
365
325
365
341
1654
78
1654
1519
1654
82
349
320
349
321
1978
1494
488
314
346
26
2019
1504
875
706
210
94
210
119
271
165
271
58
705
681
604
39
590
567
236
69
199
92
199
100
199
103
217
208
339
25
78
35
1116
939
444
227
444
353
444
354
444
228
444
351
514
244
3
718
3
137
359
330
359
337
359
347
1220
1115
1243
1138
1258
1112
1203
1101
182
147
503
432
461
1
461
411
469
28
469
443
493
38
795
183
411
351
411
372
245
234
576
555
360
200
248
209
248
232
248
242
637
505
358
47
468
346
2009
1515
1951
1451
1840
1320
1984
1487
50
7
1025
29
1208
1138
1208
1145
1235
788
630
150
691
170
296
227
296
290
296
197
1242
988
1242
895
1242
1178
1242
464
1242
611
1242
631
1242
940
1242
1228
403
173
403
26
317
41
3
99
3
138
724
606
724
367
724
579
906
370
906
699
1321
627
1321
623
694
241
694
446
694
471
694
658
694
372
694
284
694
588
694
626
556
8
556
372
556
375
595
535
309
306
1502
305
435
151
435
152
1338
539
1338
652
1338
674
1338
918
1338
977
1338
1252
786
698
1370
1172
1370
1301
1370
1176
1370
1342
1370
1348
1370
1177
1370
1335
481
397
481
361
690
497
690
502
418
349
418
363
418
140
418
131
418
353
461
340
1382
1347
1382
991
1382
998
1382
1313
1382
1010
1382
1360
1382
1354
1382
1188
1382
1184
1382
1189
592
520
519
487
272
113
225
203
3
99
149
99
149
138
526
492
526
519
2028
2024
724
372
724
241
724
688
724
284
724
471
724
656
724
446
724
618
597
537
1255
1217
1255
1202
536
418
724
507
1106
1020
1106
1008
1106
578
1106
561
1106
739
1106
762
1106
580
1106
856
1106
774
1106
770
1106
750
1106
777
1106
715
1106
588
1089
753
1089
761
1089
1017
1089
987
1052
4
1052
193
1182
271
1182
138
1182
160
1182
438
1182
115
1182
302
1182
309
1182
298
683
224
537
27
1038
634
1290
782
586
145
586
353
593
541
381
173
381
299
452
16
452
26
756
438
1149
244
1149
411
593
545
593
583
593
541
593
579
1047
459
756
438
3
1202
3
1217
597
537
1255
1228
933
295
473
238
473
239
473
316
781
141
781
653
531
147
3
99
3
138
2261
2053
1215
569
482
71
1052
4
1052
193
1210
1015
1210
868
1210
1091
1210
1109
1210
1171
1210
1196
1210
997
450
232
450
351
450
228
440
432
172
155
172
142
379
244
1290
770
1290
782
1290
1252
859
392
586
353
586
145
1871
1798
1871
1764
689
91
689
85
689
12
1159
610
346
20
668
638
428
193
428
271
428
194
694
405
694
446
694
471
694
658
694
372
694
284
694
588
694
626
694
306
673
310
673
331
202
167
202
176
904
857
661
633
1290
782
1290
1252
787
739
787
742
787
724
787
698
471
217
471
255
471
300
471
256
471
282
471
218
309
306
1499
1104
655
135
435
65
2015
970
4128
2608
306
303
306
278
306
216
896
848
217
208
210
7
210
3
210
198
3056
369
537
380
445
233
588
417
512
31
878
141
878
171
878
158
357
319
357
349
357
316
357
346
897
849
304
220
1291
770
1291
471
1291
782
1291
1253
261
210
359
40
359
13
359
54
76
7
746
592
227
102
903
33
716
178
716
152
543
108
1038
450
477
73
3
99
76
7
864
659
1047
459
171
154
777
328
3
659
3
1228
149
99
149
138
526
492
409
286
1037
151
1118
809
1118
716
784
63
2028
2024
317
276
441
107
724
372
724
688
724
405
724
656
724
446
724
284
724
471
724
618
3
1196
3
997
3
1171
3
1091
3
1109
3
1015
3
141
3
158
3
171
354
319
354
154
354
153
444
104
912
3
912
31
432
205
432
55
1255
1242
550
485
912
462
912
501
912
431
781
488
781
653
781
85
736
367
736
265
736
448
1390
1355
1390
1348
527
230
527
385
724
532
198
88
198
87
198
186
481
212
481
427
140
38
140
124
441
393
595
51
595
218
414
253
502
290
331
169
498
149
317
304
765
267
491
393
491
275
491
404
439
73
439
31
391
27
339
314
339
53
488
221
724
687
209
149
2115
1773
504
406
603
216
603
424
603
444
636
98
1106
969
1106
685
1106
933
1182
260
1203
80
317
51
1210
1015
1210
1091
1210
1196
1424
1356
878
437
878
716
427
291
1290
1002
1290
770
201
129
201
23
906
699
659
222
644
136
465
142
614
592
159
75
462
393
462
394
487
432
490
54
490
98
928
804
416
152
416
396
254
166
261
170
346
20
345
77
2644
309
2644
290
1914
1448
1914
1634
1914
610
1914
555
1914
791
1914
463
1914
230
1914
845
1914
1574
1140
181
1140
717
1132
1007
1132
1006
508
212
189
136
178
13
588
219
588
231
673
154
595
535
595
563
318
68
318
73
684
325
684
359
684
631
870
248
1386
488
1077
503
1198
366
1149
411
591
117
591
30
390
300
619
318
360
322
360
181
318
29
318
211
513
293
513
43
491
80
1130
392
1130
69
1130
225
783
35
710
546
505
255
505
174
535
304
535
265
535
219
472
463
472
428
1271
176
1271
359
1271
282
532
466
532
452
532
457
532
456
767
269
531
314
531
289
531
292
527
230
527
385
1183
395
1183
263
536
291
536
432
536
429
805
569
805
512
805
693
805
552
805
593
305
221
680
170
680
289
680
148
304
220
304
250
304
238
530
94
530
98
377
104
763
34
304
220
418
103
1651
1113
1651
1037
1651
1072
303
206
724
367
347
187
347
181
347
172
733
126
248
152
248
105
250
117
250
106
250
78
593
62
593
545
593
583
593
541
593
579
1493
931
395
315
556
507
473
163
151
98
1531
142
203
97
203
95
436
242
338
222
497
149
530
35
1548
159
845
266
845
173
302
156
505
77
505
101
292
14
416
344
329
87
329
82
733
126
365
69
1250
425
1250
455
1250
1225
1292
535
1292
653
1292
1239
875
658
666
58
666
572
666
174
666
49
666
163
540
29
540
70
540
8
502
150
502
485
502
336
502
247
1127
1047
1127
523
1127
609
142
103
417
152
3
1574
3
555
3
845
3
463
3
610
3
230
3
1448
3
1634
3
791
3
260
3
98
3
212
1319
1181
775
749
775
714
775
564
775
755
775
599
775
597
775
654
775
759
775
648
775
596
775
620
775
678
775
676
775
617
775
665
775
592
775
713
775
662
775
598
684
631
684
325
684
359
372
371
451
397
715
656
715
694
715
696
715
664
715
588
715
599
715
555
715
692
715
539
715
512
715
577
715
620
715
695
715
534
715
651
765
475
765
477
279
175
279
96
279
235
279
216
195
145
352
55
1255
1228
473
316
781
85
781
653
536
529
536
418
920
224
920
268
920
308
920
347
920
358
920
363
920
364
920
394
920
534
920
551
920
915
920
533
920
550
920
222
920
306
920
345
920
356
920
266
920
392
920
361
920
362
920
914
537
530
533
526
509
504
668
648
535
534
540
380
858
264
858
372
397
392
543
536
1306
1215
526
410
512
507
529
522
3
504
3
1228
541
534
1255
1228
550
469
550
445
550
485
550
420
550
452
781
141
770
704
468
20
140
124
441
17
502
290
495
452
495
486
572
503
1182
160
1182
173
1182
115
1182
217
1182
260
1182
184
1182
230
537
29
537
27
537
38
537
419
537
213
537
212
537
184
1255
876
781
141
968
111
572
31
436
339
436
349
1265
752
1265
758
1265
742
317
287
317
280
317
303
906
699
906
773
906
730
220
181
758
17
726
488
136
9
1827
66
351
69
1092
701
1092
451
557
117
1464
1117
1464
1324
1464
1245
1464
1104
1464
1186
1464
1266
1464
942
178
13
432
316
594
66
427
159
740
528
740
579
740
469
740
643
740
482
740
487
740
706
1317
24
1317
45
865
851
865
827
474
412
474
410
938
111
938
227
938
95
1337
1319
1337
1310
1009
579
1055
927
526
525
745
132
745
549
724
522
419
373
360
322
461
59
2758
352
770
756
620
463
2016
1493
2016
1494
1130
392
1130
138
1130
127
1130
171
1130
225
1130
114
1130
184
1130
214
1130
69
552
435
1271
176
570
31
572
31
605
575
164
110
164
122
436
364
436
260
436
165
436
155
436
59
738
689
738
712
335
280
335
306
335
326
697
666
1445
1260
1445
1417
593
545
593
541
555
197
555
199
555
231
555
184
836
681
836
773
292
14
297
181
297
260
536
196
536
184
903
419
496
179
783
650
783
624
783
770
783
558
783
594
783
754
783
756
783
570
783
779
133
19
398
381
1287
405
207
187
207
198
359
231
359
294
359
297
359
218
359
270
789
636
789
637
1823
66
1823
49
330
260
3100
2685
525
370
525
373
525
290
789
715
789
637
789
718
789
636
358
259
290
262
290
235
290
204
1252
1211
1252
1170
1252
1227
1252
1151
1252
1152
1252
1193
1252
1203
1252
1126
555
231
555
197
555
184
555
199
604
445
428
162
310
291
578
565
1463
1029
1463
914
1192
693
336
321
410
32
1482
1069
201
187
1241
1192
527
419
226
198
229
206
229
195
370
296
370
341
757
604
757
605
977
958
977
971
775
749
775
564
775
654
775
620
775
731
775
676
775
665
775
714
775
656
775
568
775
648
775
617
775
662
137
26
137
19
1894
1676
1894
1604
1896
1678
1896
1607
483
480
228
194
1988
1481
1988
1480
620
191
244
224
3
958
3
971
3
419
416
99
3
111
471
66
1256
1190
1256
1207
269
139
269
182
555
197
555
199
555
231
555
184
737
725
550
297
136
10
136
11
393
36
393
386
393
17
393
19
393
377
393
14
536
50
536
418
536
529
441
261
2089
522
215
212
551
504
719
626
339
308
580
562
580
229
683
160
473
215
297
207
919
75
1328
1309
603
209
603
136
1088
834
1088
407
636
46
340
37
340
42
340
183
529
53
635
294
393
54
835
472
1173
1080
1609
257
478
91
353
158
196
55
196
11
324
79
1910
1897
1910
1044
1910
864
1910
1893
1556
1319
1417
538
1417
181
1417
645
1417
501
136
10
136
9
136
10
465
123
476
295
476
315
476
290
476
381
476
377
1992
1077
766
742
766
678
638
156
1512
909
684
507
415
327
415
369
415
330
415
396
388
239
281
51
281
11
2109
666
159
139
159
140
1007
838
348
18
372
111
1249
573
524
75
524
123
524
177
524
506
524
278
524
292
3256
1763
410
22
462
301
462
250
1451
330
306
159
1972
1677
1978
374
1463
1126
2752
2279
2752
2251
2752
1498
2752
2387
2752
1496
2997
1226
2230
70
706
692
673
25
437
227
847
194
847
149
847
3
734
632
3664
1058
2472
2204
344
330
425
336
669
626
669
617
669
628
227
54
361
202
2896
660
1096
928
134
126
730
431
1581
703
474
243
474
239
364
114
1651
1128
502
83
1475
296
1475
329
489
366
1034
747
1034
814
1046
19
645
272
148
66
808
159
220
9
726
712
739
699
2039
75
513
446
609
476
205
184
205
186
487
339
4678
3439
4678
3477
619
17
1298
587
1298
484
400
58
859
81
480
405
380
194
306
181
3224
1097
589
343
1489
463
248
211
2229
165
664
306
490
341

490
366
1053
536
1053
510
1060
903
632
202
479
92
772
685
772
749
986
171
386
14
136
30
1152
924
279
125
1268
7
435
42
1512
436
1651
400
1297
1048
1339
915
602
59
364
71
514
118
2718
1748
620
99
536
345
536
373
318
204
459
249
421
62
211
169
538
17
1332
279
928
611
968
327
747
188
1273
433
666
501
896
175
1589
654
1683
1509
287
36
863
53
3418
3386
526
410
204
165
846
745
3
11
489
372
489
373
489
382
971
239
971
325
971
334
971
245
860
394
904
410
737
444
737
479
136
9
136
27
638
504
555
26
555
57
466
71
403
228
403
231
403
379
403
381
403
382
340
162
172
19
172
18
1052
731
380
156
1809
1202
172
18
172
19
572
554
777
518
777
616
1030
852
1030
695
1030
851
647
507
583
563
586
566
577
557
466
71
432
37
432
6
432
12
470
16
470
59
470
76
470
75
470
11
1004
694
1004
848
1004
849
219
31
219
106
219
158
271
268
509
180
394
335
394
392
332
158
1164
1136
1164
1140
1164
1130
140
137
815
652
637
79
1630
1507
1630
1377
292
169
292
258
292
174
292
183
292
179
1171
1069
1171
1060
244
239
244
10
244
217
244
6
1029
693
1029
851
1499
1172
1499
1235
1499
1149
1499
1225
1499
1173
748
390
748
414
748
451
748
436
748
412
748
401
1337
832
171
19
171
18
330
292
330
295
577
557
172
19
172
18
982
645
454
264
454
298
1715
1661
1336
313
1336
363
1336
364
171
17
171
18
494
421
3
37
3
6
3
12
695
654
737
480
737
58
737
435
737
407
737
725
1270
281
1270
272
1270
301
1205
1178
212
24
212
23
204
111
204
154
204
135
501
43
149
15
528
70
838
773
838
115
838
369
838
143
838
819
838
5
838
501
4967
2807
1873
686
1873
1616
2647
2151
525
408
497
39
466
411
441
319
2005
609
2005
572
2005
686
1480
699
1480
659
172
169
205
33
205
136
372
198
172
169
648
42
211
23
211
22
380
238
380
156
743
384
5037
2842
524
66
726
54
726
712
505
107
474
433
655
528
655
509
655
529
780
376
780
774
477
333
1032
695
1032
696
1032
853
1032
854
789
15
246
72
459
300
471
32
1023
942
443
359
595
517
249
234
249
235
249
239
205
203
490
18
490
103
166
140
704
626
704
112
704
627
779
576
126
35
126
31
875
101
505
61
87
34
332
158
234
35
468
7
468
33
468
6
468
12
591
581
467
309
213
35
401
95
210
184
171
18
171
19
204
200
938
896
206
137
172
19
172
18
531
466
531
483
283
232
410
201
410
194
410
234
410
324
410
198
410
204
410
372
410
261
410
230
410
197
587
143
469
80
464
28
464
49
464
34
202
33
1670
1451
1670
1434
892
403
346
215
245
72
108
143
108
142
648
94
648
84
648
425
724
451
591
472
591
490
591
474
558
205
375
32
474
353
351
197
140
89
140
56
140
92
140
91
416
312
608
362
3
262
3
210
155
67
155
118
417
331
417
50
206
146
206
101
206
85
206
14
437
297
165
146
189
176
2639
342
2639
2514
2639
2143
2639
2327
2639
2606
2639
1517
206
190
5450
158
5450
5037
5450
135
211
142
211
76
211
21
211
150
392
367
392
366
392
303
392
301
1979
1762
360
244
376
33
376
199
418
226
418
225
330
117
330
118
263
242
411
44
1952
1818
1952
1430
807
468
807
485
440
374
440
87
1858
173
246
58
377
200
377
34
567
30
225
139
225
105
225
140
491
39
933
224
328
116
797
768
378
302
165
116
95
65
509
487
605
65
605
64
108
56
445
360
445
361
189
154
189
153
364
45
264
58
911
422
1059
667
570
276
1255
776
381
177
2726
2412
632
116
320
70
375
32
737
725
737
715
285
190
285
194
285
199
285
280
484
474
1205
496
212
43
212
24
212
45
212
23
212
144
382
367
559
495
172
2
172
9
172
1
172
19
726
725
726
712
126
35
126
31
87
34
332
158
339
25
724
85
213
35
346
23
346
27
1382
1374
348
333
348
334
348
335
348
337
348
342
242
40
889
710
889
137
594
305
594
312
182
147
182
144
217
208
339
25
283
232
889
137
735
723
735
713
172
1
515
399
515
393
348
268
348
290
590
571
590
565
725
711
725
724
288
205
977
741
977
746
482
144
482
163
600
409
600
410
889
710
412
327
737
444
737
479
390
344
770
722
147
37
638
504
147
56
466
38
466
71
211
22
211
143
211
23
782
559
172
18
172
19
572
554
1030
695
1030
851
583
563
586
566
577
557
1004
694
943
240
1032
853
501
497
329
292
462
431
572
554
815
652
716
481
1029
851
330
292
330
295
572
554
450
445
450
446
2214
2205
206
137
352
13
695
653
166
14
3
38
3
71
717
242
297
169
297
174
297
179
297
183
297
258
451
446
451
447
1388
413
1388
1373
1388
1365
1388
1378
3
444
3
479
285
194
285
190
285
280
285
199
1270
301
210
43
210
41
482
472
483
8
483
23
912
737
912
741
2171
1927
2171
527
2171
532
212
43
212
144
212
45
212
78
630
475
630
439
824
734
147
37
770
726
198
2
1390
984
382
363
382
367
382
368
382
371
382
364
382
372
798
787
798
788
2336
1756
2336
2107
2336
2131
2336
424
2336
421
441
351
441
257
441
323
441
292
522
403
522
402
327
132
327
118
444
414
1210
677
756
176
878
875
878
705
878
709
968
267
737
315
737
728
737
233
737
367
168
74
168
117
168
98
430
52
1233
317
344
226
2203
80
92
82
92
87
92
88
839
501
839
800
394
382
505
51
215
6
822
778
382
367
398
362
497
86
209
188
209
193
489
1
1956
1451
305
77
305
199
305
134
305
78
305
279
530
431
374
275
374
86
235
15
670
503
670
475
670
165
624
601
624
598
355
143
355
43
355
301
1745
167
1657
1442
517
201
517
295
517
428
744
459
744
460
617
258
216
176
3
372
474
364
68
58
1174
368
351
91
849
106
849
108
3
23
3
8
490
8
490
23
490
46
598
313
1232
66
467
365
388
302
285
199
390
347
390
344
483
73
750
726
393
45
393
32
393
14
824
734
326
117
326
87
770
726
420
389
420
388
420
42
164
129
164
97
164
56
630
615
841
435
841
426
441
201
441
421
441
234
441
216
441
198
441
68
441
204
441
180
441
219
441
395
441
49
441
403
441
152
529
306
529
302
529
325
169
78
169
81
802
359
802
580
802
699
595
117
595
293
595
310
202
67
507
191
507
97
507
311
507
318
507
478
507
107
507
222
507
407
507
493
507
452
507
254
580
322
580
374
264
106
473
215
772
195
772
346
772
359
772
342
772
567
920
650
510
89
725
395
1051
756
1051
503
673
6
673
293
673
343
673
424
673
11
1210
1038
1210
692
1210
1040
474
166
424
213
424
208
857
803
857
798
1047
38
1047
401
391
360
1424
866
1424
859
1424
542
1424
504
473
181
737
349
656
78
777
202
777
225
777
210
749
726
483
228
307
217
307
11
307
54
307
27
307
183
307
218
307
186
307
222
307
47
307
9
205
175
647
309
931
332
931
311
859
386
400
221
400
271
400
24
400
333
964
491
964
487
964
486
614
445
614
563
233
61
360
65
360
92
136
9
490
313
1152
695
1152
786
928
251
928
566
928
248
928
840
928
837
476
238
476
281
149
24
943
171
514
189
514
120
323
320
443
95
443
90
443
439
509
210
166
65
420
388
1914
977
1914
946
1147
62
1147
425
505
68
505
70
505
52
465
254
465
249
239
55
239
86
452
256
452
21
428
382
428
388
196
64
586
82
814
335
814
353
814
373
528
318
1483
157
479
346
158
148
597
51
597
48
487
52
487
50
579
35
822
776
902
167
902
169
501
82
382
278
382
281
583
53
583
385
711
691
591
84
858
804
858
799
746
366
619
292
360
179
360
181
360
181
360
179
557
531
513
157
480
191
473
292
473
299
324
27
401
221
401
70
310
152
283
65
283
60
504
422
504
456
504
430
504
451
504
455
504
452
504
437
551
450
315
51
347
78
1374
254
1374
220
1374
354
1374
273
1374
299
636
485
313
282
289
279
458
141
320
155
815
725
815
722
815
728
815
717
535
530
275
74
1462
735
501
366
117
63
117
35
117
44
163
147
416
325
325
28
325
23
350
341
798
262
798
298
798
265
428
76
428
72
358
20
863
763
863
644
289
216
289
33
527
208
335
142
565
537
251
92
251
123
251
152
251
111
251
107
251
145
251
205
251
160
251
176
251
164
681
164
441
386
441
299
441
292
277
149
114
112
353
56
353
133
901
169
901
167
489
1
896
795
514
401
84
26
267
47
267
60
461
105
419
306
3
262
3
260
1978
552
1956
555
1956
550
1411
1391
295
289
295
284
175
58
500
338
784
214
175
58
1056
1037
467
135
154
102
424
63
670
165
546
390
546
401
546
410
546
490
546
405
431
386
431
380
553
240
553
271
586
360
586
67
586
65
586
300
560
496
328
210
617
29
443
83
443
57
163
147
386
319
3
374
3
322
649
567
3
726
3
167
3
169
158
148
523
99
473
181
289
33
289
216
382
200
382
250
382
312
711
335
711
674
711
622
550
79
550
75
748
720
410
210
410
212
626
453
541
50
349
268
185
73
185
76
185
71
390
327
390
303
483
431
249
235
1205
616
1205
1178
136
44
1242
628
243
69
933
174
781
551
483
20
420
8
736
615
2414
1833
531
36
531
201
531
96
204
111
204
135
164
145
164
144
382
368
382
372
198
156
198
197
198
9
198
186
1154
651
1154
557
1154
643
466
38
327
132
2647
2151
441
213
441
211
529
325
529
229
545
20
832
514
650
581
595
166
595
304
332
248
326
315
408
388
327
118
491
165
491
185
491
187
439
272
439
357
480
71
480
245
1863
508
1863
693
598
350
202
120
202
41
202
122
477
384
2440
1449
372
198
646
641
391
12
504
126
728
457
198
86
920
791
920
214
920
212
920
790
184
8
1455
1148
648
258
1052
694
1052
699
298
38
462
95
454
370
672
31
559
495
559
493
1203
614
1203
1176
1203
1178
1051
773
505
465
505
482
673
31
673
252
1210
228
450
294
450
233
1168
595
1168
234
1168
504
1168
626
520
460
197
9
766
364
766
428
655
318
655
255
655
23
655
321
655
324
1809
938
1809
1129
1809
1131
1809
1465
2441
1871
299
90
299
175
797
569
781
551
1290
1247
659
494
659
50
712
99
777
133
168
98
205
81
245
57
338
91
338
202
338
89
1807
1461
1807
938
1807
980
586
566
1871
1416
595
393
324
101
476
279
415
369
159
139
159
140
344
72
487
119
487
386
487
182
1298
317
1298
641
1298
587
1298
750
1298
569
1298
340
1298
567
1298
665
664
403
664
300
490
366
211
105
641
630
416
195
418
113
655
624
413
345
1112
294
1202
1175
2750
2681
815
774
815
775
595
314
595
229
595
9
595
517
415
300
331
89
559
495
1237
1082
1036
4
420
8
483
20
183
88
183
54
413
309
1383
1117
521
199
521
195
521
197
521
27
785
697
785
41
785
678
2442
1870
192
70
820
651
707
226
668
554
676
158
847
673
847
476
402
223
402
261
402
149
402
233
489
162
649
312
544
20
382
372
711
192
594
427
740
18
1247
453
788
778
917
472
1132
226
1132
823
400
34
633
414
633
308
746
20
1205
1178
366
282
1708
1134
710
640
710
706
435
49
665
403
330
319
5890
2851
665
300
665
403
497
86
294
47
147
51
319
117
358
155
494
431
480
400
491
383
491
116
1616
142
661
599
2382
59
299
180
806
351
806
745
806
747
1380
89
1049
825
1528
765
1528
734
1528
1003
1374
82
976
896
371
347
371
331
2098
317
2098
306
399
79
3142
418
3142
420
698
620
436
345
458
211
815
647
815
795
815
702
424
71
457
155
2549
2445
2549
2447
2549
2172
454
40
1522
1158
425
178
2412
1732
2412
1832
530
235
327
59
1400
1393
486
27
836
471
836
628
1091
329
567
125
221
144
535
259
469
66
469
456
276
26
611
421
572
564
476
466
256
245
491
450
522
85
489
278
745
22
126
35
1134
793
272
257
505
261
505
196
505
31
505
450
1365
171
539
32
903
256
400
275
480
272
233
217
233
230
126
36
126
36
126
35
126
36
126
35
239
66
355
337
356
42
186
81
186
79
126
19
2725
2232
2725
2245
508
160
888
303
888
799
888
124
475
465
894
646
253
249
174
167
531
483
531
466
2052
317
2052
104
128
104
257
33
257
218
1690
286
1690
284
1690
1254
1690
1224
1690
224
458
178
597
349
1339
1179
1339
1328
839
519
621
587
268
20
526
515
672
251
672
31
316
309
316
281
1012
264
1012
290
499
33
499
126
406
47
399
279
399
154
481
270
505
31
505
196
1065
865
1065
864
1065
863
2004
368
1341
1179
154
134
740
553
475
65
963
444
474
433
397
308
341
259
1016
535
1016
537
358
354
358
323
1141
290
1141
291
1141
289
467
399
222
151
198
9
623
381
623
386
648
526
371
162
572
141
117
44
562
240
1487
173
1487
384
889
436
382
235
917
472
329
28
1114
798
748
485
548
74
688
491
1239
1083
413
309
592
298
928
601
272
257
1159
896
2047
1193
1080
906
1322
208
962
244
130
115
507
290
2025
377
52
15
288
187
1591
230
698
15
370
368
1269
435
1255
699
1255
230

1255
659
1255
589
1255
498
1255
620
1255
252
723
693
1352
324
1873
695
1873
714
1873
485
1101
454
1101
446
1101
450
290
116
622
89
164
127
164
129
164
121
164
137
164
139
5540
1330
855
844
786
576
786
30
166
34
166
33
754
606
892
303
264
9
264
111
264
87
808
468
464
224
266
105
294
47
517
396
708
77
708
116
522
66
282
219
494
421
819
720
819
719
501
25
879
298
484
115
484
109
293
123
400
95
393
33
136
45
136
44
243
69
3
57
3
1117
153
57
714
684
469
66
1872
714
243
69
496
86
189
124
741
552
447
378
450
283
1603
1529
1226
1032
105
46
959
180
959
172
274
127
274
39
164
145
164
144
1018
612
344
333
421
391
963
245
417
119
329
13
390
347
390
344
390
132
390
137
390
355
390
319
390
369
390
358
390
287
390
152
418
79
418
77
418
85
418
287
418
126
418
292
418
75
418
81
418
69
712
386
712
375
712
208
460
207
460
344
460
5
460
150
460
151
460
208
460
7
460
345
460
113
460
149
460
341
460
351
390
303
390
369
390
327
390
378
390
358
390
319
390
302
390
314
482
472
769
744
769
757
770
23
2171
1927
2171
527
2171
532
2171
1673
107
43
107
63
136
5
630
475
630
345
630
439
630
346
630
254
1242
322
1242
440
350
333
483
20
86
68
420
8
198
2
198
139
2336
2107
2336
421
2336
424
2336
1756
2336
2131
149
24
149
37
1961
1916
1154
558
1154
643
1154
651
1234
1104
719
497
719
493
441
351
441
257
441
323
441
292
522
489
1531
1342
480
472
480
307
1960
1915
444
414
636
387
559
495
659
179
1170
667
1159
563
1159
656
1159
648
1233
317
1203
838
2203
80
1104
1039
1104
1040
474
86
587
432
1321
302
1321
674
346
27
1023
22
1023
15
211
22
211
23
420
8
839
704
505
120
505
339
505
366
505
348
505
321
423
128
583
212
583
138
583
205
339
25
398
362
526
256
586
394
586
404
976
891
301
26
301
29
593
594
593
579
593
590
593
575
490
20
216
176
468
178
468
229
206
186
765
183
765
727
221
192
635
7
635
8
635
14
635
20
480
192
593
80
673
659
691
132
508
284
508
274
508
136
508
160
508
269
508
206
475
460
475
461
475
467
475
465
267
140
267
134
1102
581
1353
1199
1353
1202
588
311
529
526
529
522
894
646
492
225
492
225
3
660
3
634
381
127
510
416
510
417
510
282
117
40
211
190
250
242
390
303
390
327
529
229
766
364
766
428
427
384
859
386
595
9
420
8
1322
206
1322
208
743
718
819
720
819
719
419
377
457
436
457
437
741
552
1226
1032
105
46
755
634
107
35
107
52
107
77
543
112
149
24
149
37
1032
472
533
33
533
45
533
71
179
72
724
357
649
242
292
197
292
216
292
231
292
234
344
149
344
22
344
185
770
742
920
241
920
244
920
802
444
171
205
128
391
312
938
583
243
220
233
61
142
33
469
6
469
27
469
31
646
122
4687
4541
3343
3221
531
248
531
461
531
467
531
490
531
496
531
526
482
389
423
115
329
155
391
343
391
359
391
361
391
369
893
842
1280
211
870
763
759
607
998
36
612
85
612
88
620
70
620
85
851
148
851
163
851
378
345
218
345
241
345
244
615
274
370
139
688
671
1242
381
205
193
218
203
270
28
137
110
445
171
445
171
450
171
445
171
748
239
158
70
774
630
1221
129
1163
15
3
634
1464
579
755
655
2139
1896
1615
412
1068
958
1068
864
1068
862
1068
959
907
862
684
233
902
861
327
132
4953
2020
4953
2797
706
8
441
213
441
261
2005
553
2005
686
2005
572
2005
609
2005
622
142
19
968
800
498
39
420
8
505
457
505
107
92
87
559
495
149
62
149
15
2345
76
2345
1199
92
87
1032
668
789
15
246
72
453
15
323
320
550
275
1023
942
2169
1926
908
855
908
867
559
495
179
49
179
96
2813
2732
483
20
687
643
271
268
271
260
271
263
271
255
372
8
425
326
425
347
425
331
425
311
704
8
440
260
724
498
724
364
544
421
297
104
297
239
1320
310
724
82
772
598
846
1
846
608
846
603
846
766
846
46
846
666
171
34
205
112
205
155
205
136
206
137
504
51
136
9
597
349
597
339
198
9
52
15
887
870
226
205
587
143
1108
301
1280
18
333
217
245
72
831
551
831
604
963
192
929
485
1740
684
363
341
363
356
183
92
416
157
602
236
114
100
114
108
242
219
242
220
242
88
872
674
872
842
125
5
125
28
586
513
504
392
542
435
542
12
542
41
542
2
542
49
522
488
522
502
522
500
522
509
579
8
879
844
419
416
2019
525
2019
528
2671
915
2671
933
2671
1831
541
159
541
220
502
364
162
15
530
119
530
137
1234
1104
291
219
291
114
387
81
736
132
403
102
586
9
887
870
655
228
369
48
1095
460
535
504
929
485
152
127
755
655
327
118
327
132
1429
740
1429
846
706
8
722
90
722
91
722
92
722
293
145
58
652
274
652
293
776
321
172
19
430
52
505
107
505
73
704
8
651
275
887
870
579
8
586
9
603
293
603
274
617
303
374
176
3
274
3
293
641
263
592
263
614
304
755
655
838
115
211
22
211
23
1762
917
918
915
906
870
906
871
906
868
774
350
483
20
755
655
735
7
211
150
211
22
474
312
520
460
197
169
197
82
197
196
1212
76
1233
788
490
341
2345
1214
2345
78
2345
1199
1202
1175
1202
493
211
150
559
495
559
268
559
182
692
170
270
100
270
107
270
24
270
23
270
181
270
95
591
176
210
198
439
292
557
468
1270
32
1270
49
1270
24
1270
281
1270
326
1270
71
1270
104
1270
46
781
392
204
116
140
128
884
839
884
852
884
854
517
22
517
292
517
12
517
100
741
496
858
508
543
188
737
163
1613
1578
231
149
614
498
479
208
479
204
1215
457
632
96
390
388
641
11
641
10
474
58
546
23
297
222
1515
582
1515
971
1515
1154
636
11
636
10
454
347
601
150
195
57
314
292
525
141
403
369
461
302
924
284
924
286
229
183
1293
991
1293
987
1293
990
1293
995
1293
997
1293
993
1293
989
1293
992
492
474
492
473
492
472
358
22
626
89
382
376
382
374
191
11
191
12
191
13
191
10
191
96
488
393
272
147
141
29
2368
2362
2368
2360
1270
301
1270
272
1270
46
1270
104
1270
281
1270
306
1270
289
1270
64
539
213
930
27
204
111
204
154
204
135
1906
139
1906
148
149
62
907
848
907
862
843
838
572
554
2647
2151
555
14
674
523
4966
2806
327
118
327
132
551
275
737
433
357
132
205
33
549
275
648
42
648
258
648
620
462
368
211
22
211
23
1076
949
1076
852
1076
950
1076
854
797
240
776
576
351
10
351
338
351
197
209
14
209
85
285
203
285
58
285
61
466
50
466
38
466
24
466
6
466
65
466
46
474
408
193
187
2169
1699
2169
1926
817
93
559
495
321
109
321
305
321
314
321
292
2749
1754
2749
1587
394
263
943
244
943
268
514
189
514
120
1109
47
517
516
517
491
576
320
576
148
595
565
595
67
595
52
896
602
474
19
219
35
1036
294
541
220
420
8
779
576
3907
42
324
266
384
217
160
15
474
142
977
723
440
260
549
230
1320
310
1084
264
1084
265
309
151
309
162
309
159
309
155
1380
972
1380
992
1033
290
366
46
436
430
390
223
630
37
630
551
194
33
171
34
1715
781
1715
1561
1715
748
206
137
648
232
519
448
196
82
1482
1471
1482
1302
355
76
460
265
460
280
460
287
460
272
460
275
931
586
897
600
1274
278
1274
306
380
361
343
24
343
70
343
231
343
278
343
117
343
71
759
558
759
556
759
650
548
346
276
170
1262
915
1262
744
1262
821
351
238
162
15
2726
2624
502
364
723
264
723
295
203
78
169
57
568
273
451
65
451
11
451
108
916
333
373
342
373
300
1369
550
1369
492
1369
608
463
154
1089
66
1641
1043
452
57
373
169
517
222
517
80
517
276
521
185
521
181
521
286
1096
93
1096
95
263
234
827
170
648
639
648
402
392
168
392
303
392
367
392
170
4293
4158
323
320
2363
345
373
169
590
497
52
15
52
16
807
56
136
49
263
155
1095
245
1099
857
426
101
1320
1206
1320
1115
848
22
444
57
136
49
227
10
349
217
596
517
596
9
793
101
362
348
513
122
558
365
558
416
558
404
558
429
558
305
558
316
558
339
451
358
564
265
305
160
1270
409
1270
46
1270
209
1270
24
1270
281
1270
49
1270
379
1270
289
1270
301
1270
306
1270
104
1270
272
2139
1544
2139
1486
350
90
492
420
338
148
338
26
1961
1939
1042
781
1042
807
829
203
829
179
907
848
907
857
327
132
327
141
960
866
4966
2812
130
115
543
57
357
132
561
170
672
297
149
15
466
82
474
408
474
433
1109
47
246
35
246
105
246
72
246
5
246
53
474
392
474
380
474
394
620
12
620
3
620
11
620
1
620
6
224
86
1853
1649
525
229
1052
842
52
16
52
15
742
621
478
304
478
285
478
305
2019
570
1038
1028
366
116
1145
1076
670
604
1043
37
798
787
798
788
354
215
287
13
917
779
960
672
1270
301
4966
2806
4966
2812
1113
487
52
16
1270
301
184
106
4966
2806
4966
2812
1113
487
52
16
52
15
184
106
289
13
1270
301
211
22
211
23
938
177
938
343
938
478
918
743
918
747
918
915
918
202
211
22
211
23
952
485
952
154
952
357
530
67
763
339
1113
249
1113
487
839
116
1210
679
1210
694
875
872
827
170
1270
272
1270
301
211
42
211
44
211
23
211
22
770
726
1161
1002
1161
101
918
743
918
747
707
17
707
9
673
504
474
364
309
162
309
151
309
155
839
502
839
800
737
367
501
116
480
307
480
472
744
459
798
787
798
788
918
743
918
747
490
8
490
23
210
128
210
30
210
142
210
50
920
650
920
649
465
443
673
230
673
231
673
214
673
242
673
208
450
107
655
211
655
217
655
233
655
234
427
74
427
252
777
681
777
561
777
667
777
745
344
231
487
182
487
366
487
352
649
205
487
326
199
89
199
182
199
17
1130
734
143
138
216
34
216
11
126
13
126
14
126
14
126
14
126
14
126
14
193
14
126
14
126
14
126
14
126
14
126
14
164
14
126
14
1181
1179
627
88
126
14
126
14
126
14
488
111
233
13
125
49
125
49
1042
998
945
427
1130
1078
210
149
771
701
771
671
907
862
648
337
648
338
393
297
721
188
1254
405
587
185
544
420
544
138
544
49
210
23
172
18
172
19
172
18
172
19
473
79
205
43
171
17
171
18
271
264
271
229
271
222
2171
1927
2171
527
2171
532
2171
1673
136
9
1242
1100
404
82
539
412
198
2
690
132
1154
558
1154
643
1154
651
441
292
441
257
441
323
441
351
729
715
168
74
168
98
1030
852
583
563
1170
667
586
566
559
531
559
503
706
218
360
245
360
43
1159
563
1159
656
1159
648
1871
1689
797
183
595
590
457
431
188
180
577
557
1233
317
503
487
1499
959
982
281
413
374
413
353
545
322
545
308
545
310
545
324
547
517
1203
838
776
224
776
487
556
500
556
528
556
240
556
63
619
314
619
492
619
318
619
125
359
157
400
354
451
30
482
472
550
260
198
2
198
139
2414
88
907
835
466
33
466
38
466
55
441
351
441
257
441
323
441
292
1356
826
1106
303
1106
242
712
65
480
383
480
444
168
74
168
117
168
98
586
566
753
563
785
58
707
9
707
17
586
566
788
595
1084
535
1084
749
1084
537
746
486
746
689
746
344
483
246
346
169
710
65
371
67
346
344
914
358
605
39
651
294
651
6
651
275
764
411
1354
1333
1354
1332
1354
1336
1354
1023
1354
1340
412
33
198
173
482
472
770
23
2171
1927
2171
527
2171
532
2171
1673
107
43
107
63
630
475
630
345
630
439
630
346
630
254
393
45
350
333
483
20
420
8
198
2
382
367
706
552
706
550
1234
1104
902
861
441
351
441
257
441
323
441
292
495
433
495
435
732
114
732
424
732
602
444
414
462
156
1203
838
474
86
198
9
198
33
382
367
689
28
398
362
582
566
921
560
635
7
635
8
635
14
635
20
496
424
504
51
200
92
200
103
803
517
803
760
356
124
371
349
427
276
493
38
902
861
446
63
446
45
482
472
549
310
442
350
2441
435
1307
594
781
44
1233
317
918
743
918
747
309
162
309
155
309
151
436
430
839
800
1337
826
501
116
271
36
592
559
300
284
653
294
757
176
757
180
784
641
784
651
784
670
784
681
1104
966
1104
969
165
15
795
612
776
592
488
457
479
471
753
563
353
16
766
23
769
734
473
316
473
238
473
239
468
152
403
314
403
239
595
536
502
290
495
452
495
486
317
41
466
55
724
687
729
353
729
393
629
316
629
341
629
345
1290
782
1290
770
1265
752
1265
758
1265
1196
1265
1216
1265
742
794
693
906
699
906
773
906
730
533
144
533
112
533
127
586
145
706
89
509
504
509
393
551
417
551
535
551
383
551
386
551
380
873
727
2472
1175
1436
1325
595
563
595
535
735
334
309
306
1009
579
1009
578
280
138
845
141
845
159
845
173
298
194
619
314
619
492
619
177
619
473
619
491
619
318
619
125
619
291
619
68
641
540
641
539
641
428
641
94
641
173

641
352
360
322
548
535
620
511
199
193
724
367
724
687
845
159
845
141
845
173
431
341
164
141
164
152
164
82
164
122
164
110
164
71
389
289
389
279
389
304
389
259
178
63
164
141
388
24
388
22
364
339
364
357
306
303
306
278
306
216
436
364
436
260
436
35
738
712
851
689
218
206
218
188
335
306
863
714
863
734
905
221
158
131
158
132
2472
1175
697
666
697
596
697
690
225
220
225
203
1306
1215
878
171
878
141
878
158
220
190
575
272
488
479
3
393
526
492
526
519
244
224
3
734
3
714
398
372
398
192
398
267
398
293
295
253
289
256
289
225
289
281
289
242
769
744
769
757
912
737
912
741
483
20
420
8
198
139
522
402
522
403
878
875
878
705
878
709
1203
838
420
8
505
51
593
594
593
579
593
590
593
575
683
27
683
31
490
20
210
184
210
42
676
506
545
422
480
472
480
307
756
180
351
197
758
469
758
497
758
514
758
515
758
518
758
521
758
528
758
533
758
547
758
551
758
712
758
720
758
738
737
565
393
221
740
226
740
576
740
385
706
537
400
225
351
197
431
255
431
421
735
220
668
447
870
323
673
504
556
392
556
240
556
409
556
512
556
24
556
395
740
226
788
778
788
776
390
292
390
299
390
231
480
307
525
251
525
411
525
426
525
393
984
815
942
772
942
773
1380
844
1380
972
1374
965
1374
837
367
252
430
255
481
308
592
409
752
380
485
227
592
409
496
319
479
304
502
228
268
167
673
75
673
183
673
196
673
255
673
281
673
627
735
220
417
242
683
512
672
496
733
217
705
550
596
411
671
499
3
521
3
547
3
551
3
469
3
738
3
491
3
515
3
49
3
518
3
533
3
45
3
514
3
720
3
528
3
712
3
497
697
513
3
255
404
214
427
252
676
373
770
704
1390
1348
920
224
781
141
572
498
572
478
586
477
586
353
586
145
694
626
546
420
546
465
546
481
822
713
822
614
745
549
738
689
738
712
744
82
727
678
434
151
3
712
3
689
627
4
491
165
416
52
416
35
627
4
483
20
420
8
491
165
420
8
903
449
903
384
1269
435
1269
817
3
449
3
384
736
317
871
252
198
87
403
239
414
7
414
382
414
253
502
290
486
221
486
377
486
396
391
254
1182
230
1182
115
1182
184
1182
160
1182
217
1182
173
1182
260
303
16
635
322
635
347
635
525
635
351
635
524
756
187
756
198
498
312
498
334
629
316
911
903
911
20
911
7
911
358
323
309
436
339
436
349
1265
742
317
303
317
287
317
280
243
118
243
109
243
135
243
117
243
94
794
693
906
370
220
181
659
222
659
550
178
127
178
106
178
105
178
85
178
79
835
516
835
448
835
457
595
535
1827
66
261
170
479
379
479
447
692
52
692
50
692
151
692
149
692
79
692
153
692
538
692
145
692
169
692
310
692
435
202
176
202
167
432
104
432
316
1436
1325
595
535
595
563
470
175
1009
579
1009
578
280
138
419
373
631
518
719
599
1130
392
1130
138
1130
127
1130
171
1130
225
1130
114
1130
184
1130
214
1130
69
1271
176
556
530
556
499
335
326
196
160
196
91
496
179
496
116
604
119
310
291
512
396
512
507
897
881
897
821
897
465
897
467
674
154
674
51
674
564
160
130
160
21
883
875
768
126
768
556
659
550
386
71
1746
634
351
334
351
263
508
367
226
187
229
206
229
195
1101
681
1101
130
1101
251
1101
658
1101
383
1101
226
211
79
345
295
228
194
416
69
416
36
416
92
359
6
359
38
428
68
428
95
631
594
631
624
386
71
691
644
871
823
327
118
327
132
672
313
327
118
327
132
372
24
975
341
975
447
975
366
489
162
1144
902
1144
732
652
23
652
252
652
318
1839
476
1004
395
1004
476
626
336
358
26
397
77
710
609
745
22
745
179
371
329
371
331
371
347
710
229
509
273
394
329
394
345
394
355
394
365
394
331
829
658
483
73
420
215
529
325
414
152
414
154
360
184
360
186
933
293
648
337
331
121
505
132
379
209
379
206
379
201
379
203
318
155
358
184
358
182
380
204
380
202
358
184
358
182
648
337
380
202
380
204
410
382
802
579
802
426
802
422
802
614
802
610
802
576
852
792
852
672
852
694
483
73
360
184
360
186
379
201
379
203
483
431
393
14
930
280
930
193
930
767
930
219
382
281
382
278
382
254
345
244
345
218
462
202
672
292
1575
1031
1575
1458
751
789
606
246
596
67
596
18
596
54
390
17
390
72
390
82
498
30
1161
201
1161
206
749
726
319
219
1871
232
1871
236
1233
611
136
9
826
642
826
640
149
37
149
24
817
14
817
204
2749
435
2749
1764
329
121
985
679
1321
652
498
30
541
230
541
243
413
25
296
187
793
788
150
115
483
131
505
111
501
352
501
357
428
382
2326
2313
2326
2264
326
321
326
319
326
199
326
119
326
229
821
623
821
627
236
69
331
143
158
146
487
52
935
811
935
858
935
865
935
892
579
35
440
40
440
37
441
104
380
324
926
293
926
344
218
200
739
536
873
259
873
273
873
442
661
644
443
70
443
57
443
83
525
433
665
21
652
474
652
428
652
412
652
414
652
556
652
325
652
245
652
294
652
283
652
466
309
112
1442
733
366
325
366
331
366
335
366
338
2464
1783
863
358
863
644
251
164
901
675
390
340
390
384
429
389
429
383
429
324
429
336
429
353
429
363
429
368
429
417
429
422
590
209
602
338
602
334
454
298
454
272
454
268
454
264
530
86
530
104
357
265
357
161
357
258
357
273
630
615
454
162
382
281
382
278
382
254
1337
1115
330
292
358
184
1544
884
648
28
648
42
648
288
648
295
648
300
648
641
196
111
196
54
196
64
196
99
1337
265
1337
275
1337
286
334
245
393
291
393
385
597
141
393
291
380
324
380
330
380
361
380
373
367
314
594
573
594
240
733
593
733
647
598
128
598
131
598
184
598
125
1210
694
592
264
592
556
551
275
748
504
468
71
386
319
168
77
672
637
612
80
1266
610
1266
878
243
220
243
41
136
27
784
454
784
737
808
327
885
44
885
46
885
514
885
539
425
178
425
203
425
207
1052
909
1082
663
490
79
477
145
477
138
477
142
477
93
526
179
707
343
1447
1177
1447
1186
1447
1266
367
358
367
363
773
342
773
567
2225
455
216
150
523
182
516
269
389
142
166
24
551
528
1162
155
523
515
779
724
741
459
1371
444
1371
462
449
64
1223
350
1072
750
1072
277
5656
5566
5656
4889
5656
216
5656
4878
5656
2984
5656
694
5656
4905
1462
609
2114
1316
2057
694
519
103
449
103
1889
1050
589
263
979
248
1213
258
1684
272
598
184
598
128
598
131
598
125
2618
1435
2776
2181
2776
1805
486
398
2431
2204
2431
2222
2431
2183
1574
528
1574
967
513
138
916
708
409
112
272
261
937
365
1096
650
1128
584
1403
1238
1245
330
219
136
951
438
388
359
461
140
1132
963
770
509
2075
397
983
113
1588
561
1107
863
2158
1216
2158
1001
2158
608
1570
1259
219
37
1906
1220
1720
130
1720
1024
1344
1279
306
209
344
255
684
513
724
368
1865
1771
493
473
97
29
1691
654
1856
1560
1684
1015
1291
29
1734
1336
2472
1717
449
103
444
251
966
949
787
690
2243
1953
1128
1002
214
100
220
117
745
368
1921
1278
991
386
398
389
398
394
352
105
224
176
3
286
3
265
3
275
384
345
384
375
384
320
451
224
483
73
483
431
243
41
441
37
507
452
933
344
198
68
360
110
345
234
350
162
654
386
654
613
224
176
425
178
425
203
425
207
749
504
2063
883
1336
264
1336
274
1336
285
526
179
580
469
586
246
365
325
365
331
365
335
365
338
593
265
593
557
394
385
394
390
822
628
596
18
596
54
596
67
565
254
565
267
483
431
630
455
147
129
467
239
308
272
798
788
798
787
149
15
528
18
528
39
528
70
261
212
4967
2813
466
82
466
38
1234
536
200
37
2647
2522
497
30
699
260
675
392
675
348
906
566
906
848
184
106
441
261
441
355
529
229
52
16
522
470
1257
1180
747
658
747
660
327
132
327
141
327
118
559
182
1210
1165
1210
1070
1210
1080
1210
767
1210
1069
991
897
758
732
430
52
420
8
630
458
630
437
432
37
432
16
432
12
345
324
490
18
483
20
384
217
2221
1602
904
231
233
137
130
115
558
286
705
567
705
604
166
23
351
56
351
91
127
123
3
38
3
732
497
150
666
286
666
381
3
286
3
431
902
861
364
85
364
136
364
167
1144
1075
479
401
244
222
1194
626
1042
37
116
60
1995
1939
1873
1574
356
334
335
236
136
9
136
27
136
44
781
551
529
229
595
166
326
315
327
118
1210
228
655
23
299
90
299
175
586
566
503
397
503
153
632
248
1112
294
595
9
665
387
665
210
668
554
711
192
497
86
1338
364
1338
1148
1338
305
1338
576
1374
82
2098
317
436
345
458
211
2412
1732
2412
1832
745
22
269
85
382
342
931
357
356
42
186
81
186
79
126
19
499
342
449
289
2725
2232
508
160
352
70
360
98
1000
196
888
303
888
799
888
124
1853
1649
207
30
317
89
499
343
917
472
2025
377
1101
454
317
89
1500
1423
1500
1465
1500
1462
747
62
747
178
747
190
747
179
747
126
747
117
747
64
747
170
747
81
747
60
747
68
747
173
747
53
747
184
747
56
747
165
747
188
747
187
747
83
747
59
747
120
747
58
747
118
747
55
3
377
741
552
1226
1032
105
46
395
201
395
179
750
700
781
141
403
239
740
528
740
487
806
723
806
647
806
646
806
769
806
759
806
576
632
155
632
14
2002
1901
750
748
1242
311
243
208
317
35
317
31
551
130
551
44
551
260
551
535
551
467
551
310
551
41
439
66
439
70
549
544
549
533
549
466
636
470
673
643
520
268
756
669
756
671
577
512
427
403
427
395
427
397
427
401
427
404
729
171
498
445
671
5
671
24
1499
1253
968
922
968
931
968
926
968
79
193
9
193
105
193
95
419
30
419
42
419
67
419
375
419
84
1164
486
1164
510
724
689
3142
15
3142
12
3142
2
680
50
680
42
579
471
131
57
454
453
619
556
619
525
619
515
380
307
716
455
156
7
481
445
481
438
481
449
481
442
956
431
956
440
956
438
956
435
956
443
956
421
956
417
412
374
412
368
455
380
596
438
596
434
210
119
210
94
233
133
233
140
233
137
233
143
233
135
716
171
540
441
282
219
334
200
334
204
3119
12
235
208
790
380
1401
582
1401
854
1401
106
1401
404
288
30
333
147
333
145
333
167
211
94
646
84
775
380
750
707
750
744
483
20
925
854
650
555
595
166
317
35
317
31
480
472
480
307
551
535
551
467
549
533
504
418
673
643
418
79
418
287
418
292
418
75
427
385
427
395
427
397
427
401
555
221
555
310
555
208
555
146
503
476
503
470
503
471
503
478
749
707
749
746
749
743
943
323
943
160
943
116
943
150
680
158
497
429
662
101
3142
12
851
403
325
218
325
214
325
220
952
413
115
45
501
10
716
500
288
16
731
146
750
726
224
76
224
78
224
86
960
672
750
700
550
420
473
316
473
238
473
239
140
132
140
135
140
124
441
17
1480
511
486
377
486
396
635
351
635
347
635
524
635
525
629
316
629
341
629
345
911
903
911
20
911
7
911
358
323
309
323
286
436
339
436
349
1290
770
1290
782
456
95
456
83
456
177
456
71
456
188
1265
758
317
303
317
280
317
287
519
360
519
363
243
232
243
192
243
135
629
519
629
518
201
23
794
693
906
699
906
773
906
730
351
330
1161
417
1161
363
1161
435
220
196
193
143
185
137
185
37
659
550
178
127
178
106
178
105
178
85
178
79
758
17
3
427
533
112
533
127
540
104
509
191
833
380
583
426
583
348
583
349
870
665
870
663
788
784
1009
401
805
418
805
443
805
458
409
288
672
657
113
90
113
101
671
661
561
173
561
182
561
447
697
674
398
267
398
293
398
372
398
192
585
516
198
192
458
428
750
726
136
9
323
4
323
303
2555
2512
2555
2510
2555
2515
437
374
465
194
465
186
465
205
465
213
770
726
749
726
425
207
425
178
425
212
793
778
850
263
249
243
249
239
249
235
249
234
1242
635
1242
1100
1242
306
1242
526
1242
269
1242
311
420
8
907
857
441
213
441
261
441
211
595
166
708
596
632
499
614
498
725
365
1106
83
797
567
797
571
1233
1096
1512
998
421
382
421
384
535
371
2225
1858
420
8
668
554
668
552
489
162
366
282
1708
1134
525
411
611
421
371
349
371
331
680
559
2549
2445
2549
2447
409
286
409
285
409
290
221
144
535
259
469
66
469
456
611
421
841
520
343
82
150
35
790
21
790
6
790
20
126
35
205
136
621
46
688
493
294
48
426
124
3
382
3
384
249
234
249
235
393
17
393
19
393
268
1484
1302
529
229
925
653
925
769
925
7
925
673
925
670
925
666
925
763
172
19
288
187
288
187
163
70
450
118
172
19
418
38
808
159

1430
307
1430
288
1430
312
588
510
203
76
1442
307
284
282
454
298
454
308
454
310
454
311
454
317
454
325
1482
1302
3
282
249
234
249
235
735
640
284
151
283
150
462
431
1323
1164
1323
1160
1323
306
334
48
550
404
550
417
550
112
136
9
781
674
781
551
394
260
204
111
204
135
149
37
149
15
466
55
2647
2151
2647
2291
2647
2369
545
198
545
143
545
422
545
203
545
56
595
304
264
245
403
341
403
287
372
20
415
208
603
48
648
338
648
337
440
157
766
445
646
525
172
19
168
74
168
117
168
73
168
98
168
133
393
297
647
507
3664
3567
3664
3485
986
885
986
884
136
10
1032
696
595
517
204
173
204
100
204
175
1036
197
1036
658
1036
162
1914
1771
557
271
985
884
761
507
761
699
591
257
371
206
721
188
725
191
725
110
304
40
376
262
268
250
177
27
716
478
716
487
716
186
716
185
793
778
562
466
621
419
355
15
452
245
452
172
1512
66
633
248
633
100
244
127
244
64
254
22
254
117
1032
738
1134
793
647
337
647
338
595
537
595
151
595
152
356
59
356
126
648
337
89
87
430
146
547
171
147
37
1606
1106
587
185
355
15
987
886
2647
2151
631
100
253
117
909
384
275
100
3
886
445
247
445
381
550
445
770
704
843
781
1822
1563
822
653
822
652
822
153
822
765
822
462
822
582
822
584
822
729
822
279
822
604
822
306
332
9
332
82
299
17
740
706
870
127
870
326
870
305
870
248
870
409
390
300
436
135
436
242
436
243
1377
594
1377
679
1377
682
1377
556
1377
501
1377
728
1377
604
779
106
531
104
537
380
537
93
427
406
623
372
508
195
508
305
508
348
508
391
508
435
508
470
344
278
344
89
3
462
3
765
3
652
3
584
3
729
3
653
3
582
414
41
550
469
550
420
550
485
536
418
140
124
732
348
732
45
1052
406
1203
656
233
170
1009
401
314
202
461
59
1205
658
1147
307
1147
781
1202
655
685
360
119
47
119
17
119
4
119
10
1009
401
770
722
204
169
149
15
460
425
522
470
2353
1197
558
318
558
279
224
76
224
78
224
86
3
286
912
396
912
400
724
286
911
208
911
441
911
157
149
24
149
37
441
216
441
395
441
403
441
211
441
201
441
421
441
234
441
68
441
204
441
219
441
49
441
152
529
306
529
302
529
325
725
395
725
358
440
268
440
271
292
282
416
107
149
24
918
402
918
406
918
202
918
254
918
205
918
747
513
157
461
105
286
56
286
271
286
112
349
268
1205
82
1388
721
339
23
648
339
648
340
580
555
1044
456
380
9
380
29
1039
283
882
752
882
753
882
754
162
18
162
26
191
63
895
891
155
17
249
192
665
215
481
54
1205
115
466
55
450
171
445
171
444
171
445
171
444
171
243
220
624
218
386
307
142
33
470
6
470
27
470
31
427
119
391
343
391
359
391
361
391
369
190
185
749
628
866
759
617
464
883
744
477
47
477
67
477
122
477
168
477
217
659
548
294
199
294
218
613
274
370
139
202
164
218
203
149
24
149
37
446
171
786
644
1205
115
386
307
386
384
294
124
294
199
348
235
858
594
596
103
596
105
380
186
439
61
410
22
981
629
1205
115
466
55
706
552
706
550
171
66
330
319
386
14
386
32
318
232
307
7
307
137
781
190
781
245
492
399
202
74
365
144
1205
1178
706
550
351
197
401
211
480
307
544
421
431
255
756
180
672
496
671
499
682
498
527
251
944
775
2171
1927
212
23
212
24
147
37
930
68
204
154
487
397
487
395
149
62
508
158
630
275
4966
2806
545
20
380
238
380
277
380
156
1076
852
375
152
375
234
5037
2842
205
81
205
142
205
77
205
14
776
683
420
8
184
178
1147
1004
442
261
193
187
780
774
780
376
205
51
915
861
407
331
407
329
1004
666
1004
693
235
215
1032
695
1032
696
261
145
34350
4184
34350
4098
34350
4091
34350
4009
34350
11877
2750
1588
2750
1755
346
215
415
198
343
330
126
31
875
101
957
742
957
370
998
783
998
411
1164
1130
381
100
862
14
551
226
551
524
931
69
931
321
301
33
213
35
848
10
730
6
632
521
639
19
211
45
211
63
865
91
704
63
1159
1083
921
250
671
64
145
18
950
433
950
408
35213
4079
1141
653
121
108
639
19
3
411
3
783
977
238
112
103
155
67
155
118
34252
3985
34252
3657
904
688
862
14
966
826
966
718
793
205
793
346
208
103
208
103
686
64
686
80
850
277
850
281
690
63
2171
1927
2171
532
2171
527
101
24
101
6
1480
659
1480
699
380
156
380
238
1147
1004
1147
1010
126
35
126
31
160
15
875
101
883
696
213
35
632
521
639
19
204
200
1687
613
648
425
155
118
155
67
392
367
392
303
392
366
392
301
330
117
330
118
411
44
1952
1815
1255
776
978
390
978
762
193
187
383
159
383
241
383
280
904
688
904
669
671
44
671
64
671
26
671
72
671
50
671
516
671
84
671
58
380
99
334
240
418
256
90
28
358
90
366
105
1249
934
107
35
107
52
107
77
327
256
781
32
781
36
445
427
450
248
450
271
450
274
984
765
984
767
984
954
212
32
212
52
212
144
624
181
126
14
126
14
126
14
212
23
212
24
212
43
212
45
770
726
478
8
478
23
212
151
648
337
648
338
597
334
597
354
597
337
597
341
597
346
597
350
420
215
439
57
572
513
572
508
852
519
632
16
632
20
1051
404
1051
414
781
22
781
36
781
44
781
28
781
119
781
40
781
32
159
111
968
902
968
906
733
496
733
493
733
490
733
695
733
553
733
687
420
215
779
181
215
158
296
178
296
187
296
183
331
139
935
453
935
457
935
461
935
465
935
623
935
627
935
631
935
635
489
239
489
253
615
54
615
58
263
230
263
233
534
177
534
181
474
308
636
571
2464
1264
2464
1259
567
441
769
269
251
164
251
160
630
615
295
285
295
287
292
282
863
479
863
484
737
345
334
251
334
241
334
245
592
552
592
556
1373
1279
855
426
403
365
971
909
630
601
570
508
738
640
704
640
704
644
704
648
704
652
982
479
982
475
408
340
502
248
502
252
836
563
836
567
836
601
795
218
776
211
2187
2130
576
45
1046
2
1046
3
1165
945
946
261
1044
1019
181
33
1123
750
608
131
2473
2090
2473
2065
2473
2067
2473
2071
395
243
395
288
402
255
402
259
440
315
440
314
597
39
390
17
770
726
209
85
209
14
1233
317
918
743
918
747
245
57
309
162
309
155
309
151
382
367
246
59
674
504
674
642
591
571
126
13
328
169
243
5
630
598
463
301
394
360
802
34
697
513
513
9
469
28
384
128
1024
532
339
153
607
536
204
127
466
55
357
273
357
267
357
289
357
283
357
132
357
155
345
241
345
244
197
186
655
248
390
311
149
24
149
37
466
55
2749
420
2749
798
535
73
661
644
297
63
318
199
318
4
545
211
880
58
880
387
665
391
746
344
812
718
812
111
615
274
469
6
469
27
469
31
444
171
319
38
652
245
292
197
292
216
292
231
292
234
862
6
862
108
862
31
862
86
862
18
359
192
359
20
171
66
1029
472
450
171
270
28
1123
568
1123
546
1058
3
1886
1879
580
469
1970
1615
1970
1618
465
54
140
33
580
144
580
23
646
122
464
63
464
5
464
21
107
35
107
52
233
61
3329
3213
1058
594
480
388
430
122
346
163
1392
1374
1392
1379
391
343
391
359
391
361
391
369
1281
211
190
185
729
462
870
763
913
443
913
845
724
357
760
607
3020
2515
865
726
513
89
1774
1597
1104
541
1104
922
626
85
648
76
648
252
648
255
648
346
648
540
447
65
447
191
858
148
858
163
858
384
1323
435
1323
446
1323
465
1323
472
1323
572
1323
759
660
549
2094
1996
2094
2068
2094
2084
1023
32
1023
83
1243
381
4691
4545
885
527
603
469
205
193
218
203
538
251
538
496
275
61
451
171
445
171
445
171
444
171
445
171
447
171
770
256
770
260
770
264
767
273
767
277
773
264
158
70
782
638
215
208
330
319
4687
4541
297
14
96
52
3
391
541
73
303
135
2541
1588
136
9
317
31
317
261
317
62
142
19
918
893
918
891
918
892
136
10
136
28
805
227
880
861
880
860
136
10
136
28
3
28
3
10
136
28
276
170
3
227
136
2
136
9
136
3
136
10
393
17
331
72
331
62
390
17
390
20
505
61
505
72
505
54
576
183
130
119
89
1
89
3
89
2
396
354
396
375
396
385
434
349
3
17
136
9
391
327
391
354
1258
314
1258
140
1258
13
136
9
1242
1100
352
338
736
636
204
154
204
111
204
135
164
145
164
144
439
328
2531
2151
198
156
198
197
491
165
491
185
551
275
439
292
286
125
286
105
415
148
415
154
415
150
415
152
920
850
920
214
1203
632
673
31
673
252
168
74
524
115
826
454
360
287
360
288
943
244
943
268
943
153
943
150
943
152
943
338
943
334
943
255
943
256
943
337
943
277
394
329
870
434
787
730
1338
1148
1374
82
431
421
234
185
234
194
234
195
234
88
234
184
514
379
514
371
424
71
424
416
424
63
806
310
359
345
256
245
729
94
729
89
729
95
655
361
908
360
221
211
221
213
389
195
1603
1529
277
225
277
185
277
191
136
9
331
72
331
62
1050
468
1050
532
1050
494
199
31
684
456
253
249
136
2
136
3
136
3
136
3
3
3
136
3
135
3
136
27
543
67
1132
1079
800
161
800
164
800
160
3
67
3
160
3
164
136
11
393
19
147
11
147
37
770
726
164
144
491
165
491
185
172
19
172
18
450
89
172
18
172
19
1030
695
1992
311
1004
694
1004
848
1004
715
203
76
171
19
171
18
454
305
454
310
454
179
454
224
454
264
454
298
166
14
172
19
172
18
594
483
1349
862
136
9
386
174
386
261
386
276
142
116
471
11
471
16
471
59
466
71
344
231
136
40
1242
988
1242
631
1242
940
1242
661
1242
895
1242
731
1242
1178
595
218
413
131
413
140
556
375
556
372
339
23
1367
979
1367
1164
1367
1160
1367
1279
1367
1165
1367
1280
1367
981
1367
1345
1367
972
504
495
504
469
261
249
261
59
261
132
593
493
136
9
2169
1573
2169
1698
2169
1625
101
6
453
15
505
73
505
474
468
7
468
33
468
6
468
12
653
650
363
356
363
341
363
338
288
253
351
10
351
338
1685
617
136
9
326
303
781
36
781
44
781
32
781
40
2514
2417
2514
2409
2514
2406
595
117
317
35
317
31
551
535
439
66
439
70
549
533
403
287
673
643
197
182
1424
856
671
5
671
24
968
922
968
931
968
926
295
285
2442
1381
2442
1385
193
9
724
689
900
871
900
114
900
98
900
122
900
107
900
869
900
865
579
471
495
375
470
425
457
106
457
110
607
277
651
89
131
57
2549
1414
2549
1417
747
623
747
592
2453
2344
2453
2347
454
453
619
556
619
525
619
515
1298
1042
334
200
334
204
789
592
789
665
947
819
947
816
947
813
237
40
646
84
393
370
393
375
393
377
393
391
393
32
595
117
904
4
904
40
904
12
904
3
904
107
904
39
904
58
904
52
904
138
904
26
904
6
782
89
614
498
297
160
920
515
795
594
795
481
795
487
298
167
298
159
298
45
298
164
326
176
629
156
1970
1615
1970
1620
1970
1618
1970
1877
462
76
950
438
437
432
437
402
462
76
462
460
462
202
303
171
465
205
350
29
454
78
454
76
1490
892
461
202
1203
632
1203
1176
743
384
1581
1456
928
779
928
806
928
810
360
11
261
145
346
163
346
169
1087
783
1087
774
1087
781
1087
772
372
174
632
156
1970
1618
3
32
783
469
783
475
3
481
3
487
542
255
393
19
918
781
466
50
466
55
466
82
466
38
501
43
501
18
528
70
528
18
528
39
508
102
508
84
466
38
466
50
466
82
466
55
327
132
497
18
497
403
497
39
674
271
529
120
651
521
327
132
327
118
491
156
491
165
480
472
580
168
580
322
580
374
580
352
473
215
603
325
603
382
725
376
450
89
520
460
307
183
740
226
740
385
305
83
209
85
209
14
205
77
205
14
205
81
647
322
1243
574
416
178
416
243
265
135
931
332
931
311
245
57
319
51
319
177
859
386
211
19
430
52
430
50
400
337
964
370
964
350
338
91
338
202
338
53
373
106
1083
46
1083
77
431
12
151
76
588
549
588
551
639
556
844
146
614
197
524
18
524
66
295
64
671
319
544
33
835
472
330
194
330
242
339
251
339
203
560
365
233
61
1807
1253
327
132
327
118
424
12
656
320
656
335
886
151
360
92
360
110
1203
1157
745
132
382
254
382
278
382
281
740
385
380
50
380
250
380
114
678
66
334
176
467
254
467
249
712
505
326
59
326
185
266
203
266
135
641
240
390
328
3
39
3
18
3
77
3
14
3
81
393
8
393
17
393
19
882
843
882
845
781
44
441
201
441
395
441
403
441
204
414
392
414
409
414
332
414
394
414
402
414
403
414
388
414
316

414
408
414
291
414
91
414
304
448
329
448
326
491
350
491
219
491
385
491
261
491
341
491
259
491
165
491
349
491
418
491
372
491
171
491
289
491
117
491
364
491
252
491
175
491
120
491
228
491
268
491
239
491
278
491
382
491
245
491
241
614
498
444
387
444
384
646
211
834
779
834
803
488
383
390
8
390
3
390
5
390
11
390
6
1255
661
1255
667
1255
664
1424
600
736
142
736
223
1613
1489
2843
1506
2843
1504
2843
1509
2843
1503
781
46
878
243
826
246
793
94
169
108
736
593
736
594
736
596
736
591
736
590
402
395
351
324
351
327
351
346
351
344
351
338
351
310
351
333
351
308
351
330
260
71
260
14
260
73
260
10
870
527
870
382
501
497
489
239
489
237
489
243
649
318
649
315
755
321
234
35
1647
34
1647
30
1621
1129
499
361
669
223
669
272
669
219
669
276
393
214
781
674
528
70
200
9
595
304
510
45
647
507
986
142
986
895
557
271
985
884
591
473
799
758
799
761
216
134
630
214
179
49
268
253
268
157
453
206
505
483
505
484
734
26
393
365
393
36
393
17
393
19
393
377
393
14
326
117
326
99
326
87
531
99
441
261
633
183
633
209
633
283
1863
987
213
110
882
116
473
215
1088
445
1088
407
1088
171
1088
379
918
90
795
751
437
363
450
92
450
89
835
472
560
509
560
142
560
476
1417
181
465
123
524
123
524
177
524
278
524
292
344
330
490
341
490
366
928
611
169
63
169
32
169
149
169
16
169
17
169
147
857
287
763
375
748
360
324
67
324
25
324
118
324
27
543
32
543
434
543
259
543
139
543
515
543
34
543
67
543
18
543
386
543
378
543
431
543
119
543
224
543
382
511
330
254
246
824
116
213
91
213
35
213
54
213
166
213
88
247
61
3130
1074
542
19
3418
3386
3
382
3
386
3
378
3
19
3
116
434
250
437
231
393
391
441
355
441
261
297
3
1233
306
52
50
52
47
898
187
898
314
551
241
551
161
551
82
551
254
551
450
551
88
551
292
551
87
551
89
551
445
551
100
551
257
551
5
315
48
315
51
315
51
486
27
894
187
894
314
1056
917
393
391
393
14
164
79
545
108
403
379
403
382
403
381
747
614
747
731
747
668
488
126
559
182
559
173
776
181
753
214
753
210
753
233
559
182
736
173
559
182
926
174
794
204
788
207
661
210
552
171
3
220
168
64
431
328
431
418
552
76
628
207
433
427
433
401
433
335
433
362
433
184
433
188
783
181
651
166
778
188
778
204
752
213
795
214
765
172
637
131
637
143
637
138
1321
162
1321
220
634
150
393
54
140
128
1215
21
1613
1489
577
65
134
117
413
395
413
410
413
354
413
392
413
400
413
355
413
383
413
406
418
411
398
374
590
484
590
483
590
9
369
345
706
647
362
351
362
349
3
54
393
376
393
303
736
594
441
152
441
148
441
204
441
230
441
262
441
168
441
180
441
211
480
472
440
137
583
563
586
566
577
557
2527
2030
2527
423
2527
1966
2527
1466
2527
1848
2527
1484
2527
1401
2527
1356
2527
1852
2527
2256
2527
523
2527
2482
2527
1502
2527
1291
2527
1403
2527
1911
2527
837
2527
1347
2527
1456
2527
1123
2527
1490
2527
1442
2527
1469
2527
832
2527
4
2527
1342
2527
1331
2527
2034
2527
1968
2527
1444
2527
1252
2527
1344
2527
1646
2527
1507
2527
825
2527
2031
2527
1912
2527
1443
2527
1535
2527
2523
2527
775
2527
1451
2527
1282
2527
1367
2527
2
2527
1409
2527
1611
2527
1402
2527
954
2527
972
2527
934
2527
909
2527
1291
136
116
215
83
704
338
704
336
770
742
215
5
215
83
1374
837
1374
824
497
95
497
469
450
106
158
45
158
27
158
53
445
106
744
644
145
135
444
106
445
106
444
106
435
155
200
72
244
105
201
71
220
85
219
85
227
93
219
85
212
81
216
84
203
70
203
71
207
71
207
71
913
569
204
71
1176
292
207
71
200
72
243
104
666
597
204
70
393
14
140
86
441
201
441
198
441
216
441
395
441
403
441
211
441
204
441
421
747
529
695
309
695
292
695
294
695
311
737
521
735
640
1970
1615
1970
1618
1106
407
655
328
568
74
568
28
568
8
416
124
295
285
943
260
943
408
943
402
943
277
315
74
716
538
252
246
252
166
1304
272
1304
433
251
192
251
245
686
292
454
162
248
237
248
226
248
233
763
528
763
320
520
337
520
368
520
329
116
27
134
26
292
282
960
307
864
856
521
250
1464
1047
593
557
344
302
567
28
393
36
528
18
497
18
497
403
497
39
725
376
673
214
673
252
673
550
673
554
205
77
205
81
483
191
483
162
2986
486
340
170
340
150
340
148
184
129
3
36
3
77
3
81
393
391
393
32
393
314
261
216
261
210
747
46
491
165
1464
492
1464
498
1464
486
1464
468
920
82
920
80
1970
1615
1970
1620
1970
1617
1970
1618
1970
1524
1970
1539
950
438
465
194
465
186
465
205
465
213
928
794
928
806
928
810
169
163
169
96
219
186
152
119
559
324
1087
813
1087
783
1087
805
1087
774
1087
798
1087
767
1087
790
1087
665
1087
781
1087
772
372
185
372
361
372
352
372
362
372
346
372
353
372
349
372
356
215
182
425
207
425
178
425
212
505
111
542
255
393
45
781
32
781
36
2414
2278
198
9
271
197
770
288
770
285
770
238
747
681
747
26
327
270
327
256
2555
2510
284
268
284
210
284
213
428
373
882
35
882
7
882
37
440
421
390
54
390
57
345
234
345
75
1198
879
1198
881
1198
360
1198
363
1198
837
1198
826
1198
923
1198
847
1198
933
1198
667
107
77
107
52
107
35
96
66
96
41
324
27
324
67
324
118
324
25
283
267
680
490
663
368
422
372
422
303
422
280
1013
796
1013
794
1013
982
453
248
453
272
453
275
345
77
345
249
345
223
345
110
345
70
345
107
345
100
345
91
345
215
445
427
605
84
605
53
560
496
560
494
1196
360
3
45
3
37
3
7
486
215
486
79
616
267
3
275
3
248
3
272
393
17
393
19
393
36
882
843
781
44
382
324
382
327
382
329
396
381
396
386
396
383
396
325
396
392
1154
614
140
86
140
128
414
378
414
392
414
409
414
386
414
346
414
115
414
394
414
272
414
402
414
374
414
403
414
90
414
388
414
24
414
1
414
408
414
291
414
241
414
91
414
341
414
406
414
182
414
3
414
253
414
368
414
376
414
304
414
349
414
87
271
46
271
35
271
40
271
49
271
50
515
513
515
511
327
110
327
155
327
113
327
107
327
141
327
99
327
96
327
93
732
725
732
724
551
315
288
20
439
251
439
66
357
115
357
112
357
120
357
155
735
10
735
7
213
71
852
686
724
717
614
498
205
136
306
252
306
298
306
259
208
193
655
324
655
321
440
348
390
17
390
8
390
3
390
5
390
20
390
6
390
11
1613
1492
1613
1489
1613
1606
1613
1571
2843
1506
2843
1504
2843
1509
2843
1503
911
302
911
41
465
377
465
100
245
231
859
830
859
833
859
827
859
823
859
829
1499
1247
1499
1243
324
175
524
81
524
78
490
288
641
635
359
150
501
497
382
324
382
327
382
329
557
534
530
70
530
73
530
67
250
5
250
11
1531
157
1717
1378
1717
1358
1717
1362
1717
1380
716
463
781
44
479
44
479
45
479
43
479
37
479
38
479
36
530
507
409
286
409
285
409
148
409
262
409
290
256
62
560
436
699
521
489
18
245
231
858
470
858
463
858
501
858
527
1075
210
1075
214
1075
206
1075
209
1075
203
842
17
842
19
586
567
241
7
241
5
195
60
292
158
196
184
874
5
245
174
245
173
770
35
770
33
505
264
505
267
523
99
688
496
1591
328
708
208
708
34
916
761
916
765
916
767
916
762
824
572
939
267
939
268
412
242
778
703
393
45
770
726
441
211
529
362
529
306
529
319
529
325
529
322
331
242
2555
2510
439
61
735
640
264
103
118
64
118
100
572
521
345
335
572
521
729
526
758
528
524
282
524
320
524
106
524
17
524
87
524
319
524
155
524
184
136
44
1132
456
147
40
147
29
147
31
324
67
324
25
324
118
324
15
324
27
360
305
716
538
570
521
1544
384
1544
1010
491
41
491
108
491
132
418
24
570
635
365
305
721
543
1586
387
1586
1010
3
635
528
482
528
483
528
31
528
487
528
81
528
308
528
496
528
32
528
488
393
19
393
45
770
726
164
129
164
97
164
56
630
615
441
230
441
201
441
216
441
180
441
211
331
72
331
62
651
199
439
70
439
61
473
167
504
118
504
137
504
153
504
366
504
411
163
114
303
171
781
190
781
604
473
181
233
46
233
114
233
61
149
37
149
24
462
259
462
55
462
69
462
81
1147
116
505
68
505
70
505
89
345
153
345
151
345
163
239
73
239
86
239
69
239
55
158
118
1483
157
332
45
487
52
487
50
579
35
451
276
902
216
902
212
138
55
763
735
283
65
283
60
795
245
504
437
467
319
467
318
360
330
360
320
360
333
457
352
163
147
440
273
1075
164
1075
162
695
667
281
262
195
58
711
102
711
204
505
454
505
450
196
64
334
62
163
147
676
276
676
271
676
420
676
423
3
212
3
216
454
153
454
118
454
316
454
137
454
361
352
346
455
350
757
26
507
388
507
360
393
19
140
128
403
365
403
369
522
470
331
72
331
62
1531
1342
543
472
724
717
473
197
473
190
233
48
524
79
524
512
524
518
134
117
826
575
826
656
505
68
505
70
479
272
396
341
294
3
433
132
543
72
543
61
255
207
315
43
315
195
315
253
315
59
315
176
140
128
3
72
3
61
3
19
3
1342
393
14
327
132
502
290
317
304
317
288
1265
752
1265
758
1265
1216
1265
1196
519
213
519
214
659
222
659
550
957
247
957
461
957
356
998
397
998
502
998
247
675
215
675
223
620
179
631
205
793
693
1265
1216
1265
752
1265
758
1265
1196
221
105
221
186
221
85
622
363
622
413
3
397
3
502
3
247
393
391
393
14
164
145
441
355
441
261
1130
463
1030
471
1030
444
1030
909
159
140
159
77
293
256
3
391
3
14
393
14
3
14
393
19
393
17
732
114
1079
11
1417
1295
1417
143
1417
1289
1152
927
1152
926
857
361
857
741
857
287
857
32
857
804
857
11
857
79
857
823
857
563
857
848
857
36
857
805
857
674
857
362
857
794
857
844
857
685
857
820
857
675
857
359
857
581
857
435
857
810
857
846
857
14
857
676
857
320
857
370
857
6
1050
1042
1050
434
1050
542
1050
669
823
414
823
553
823
551
543
67
1130
734
718
21
718
609
718
61
718
7
718
597
718
715
718
322
718
623
605
491
280
93
280
168
280
87
280
237
280
229
679
61
679
64
2063
1006
2063
943
2063
750
147
111
857
675
857
685
393
8
3
8
393
14
382
281
382
278
498
30
1871
232
1871
236
136
9
826
642
826
640
149
37
149
24
498
30
483
131
501
352
501
357
428
382
2326
2313
326
321
326
319
236
69
487
52
440
40
440
37
380
324
525
433
602
338
602
334
530
86
530
104
630
615
382
281
382
278
330
292
358
184
393
291
477
145
477
138
477
142
477
93
166
24
551
528
393
32
781
604
724
286
724
289
911
208
911
441
911
157
441
395
441
403
441
421
441
201
441
234
441
198
441
68
441
204
441
194
441
211
441
110
441
49
441
152
529
306
529
302
529
325
732
594
292
282
416
107
1147
62
1147
425
505
70
513
157
904
442
904
157
904
208
913
458
458
141
457
352
367
2
461
105
320
200
320
199
505
192
505
200
455
350
297
199
522
268
522
271
393
314
439
113
642
164
1455
350
561
13
561
506
294
69
294
87
858
594
593
220
2442
2416
2442
2420
2442
2063
445
240
445
174
445
396
445
178
445
427
445
169
445
170
445
401
445
355
903
34
903
40
903
35
903
44
323
306
323
317
716
14
716
642
716
279
716
696
290
193
290
209
1368
620
1368
621
670
660
681
351
3
506
3
13
393
17
603
209
390
17
390
20
390
17
576
183
89
1
89
3
89
2
1055
679
1055
744
1055
726
3
17
351
298
351
296
393
17
393
19
140
128
906
651
906
654
906
657
1531
1105
504
399
504
402
655
321
655
324
1424
600
1613
1419
1613
1429
1613
1492
758
518
758
521
758
712
758
720
245
231
826
246
260
10
260
14
260
71
382
324
382
327
382
329
770
205
425
417
862
74
862
76
862
216
862
468
256
62
245
173
245
174
1301
258
233
1
393
248
164
97
164
129
2647
2151
2647
1458
1863
631
415
355
340
202
655
248
222
105
1807
1451
1807
1216
524
39
490
313
928
779
928
355
928
825
928
372
928
794
928
251
928
607
928
806
928
787
928
810
928
611
928
248
442
104
1321
1225
1321
387
521
464
441
159
351
308
1130
476
763
509
763
488
763
610
763
507
763
3
763
521
763
599
763
626
763
619
763
450
763
703
763
34
1616
126
1616
953
654
244
654
138
654
153
654
47
806
663
806
508
407
129
1139
400
1139
671
1139
1034
1068
963
1068
974
1068
368
1068
639
1068
649
425
207
425
203
425
7
425
178
425
212
359
192
521
97
521
109
342
263
342
305
342
4
920
786
486
301
486
301
476
466
476
330
476
141
476
113
764
483

344
253
3
212
3
7
3
178
837
271
837
371
374
5
575
245
579
570
579
72
579
61
393
248
326
201
531
36
164
129
198
9
198
186
2647
2151
2647
1458
520
466
520
462
1807
1451
1807
1216
928
779
928
825
928
820
928
794
928
806
928
787
928
810
928
611
480
275
480
299
480
292
480
302
480
47
480
423
763
509
763
488
763
610
763
507
763
521
763
599
763
626
763
619
763
450
763
703
294
198
407
129
1139
400
1139
671
1139
1034
486
301
531
36
476
466
476
330
476
141
476
113
3
198
575
245
393
54
487
397
467
196
398
374
400
376
140
128
896
711
896
701
896
710
896
708
896
713
412
363
412
359
412
364
412
354
450
419
450
408
450
443
1106
1103
583
563
586
566
577
557
134
117
413
395
413
410
413
354
413
400
413
355
413
383
413
406
407
238
407
356
332
328
332
329
398
369
398
374
398
375
398
378
360
122
1367
1277
350
338
350
327
350
333
350
330
350
331
350
337
350
335
350
328
372
362
372
357
372
360
444
419
444
408
372
362
466
310
466
286
466
293
466
249
466
287
466
250
466
282
466
309
466
233
466
285
466
289
466
270
466
308
466
231
466
306
466
301
466
281
450
443
369
352
369
355
369
353
369
340
369
342
369
358
115
104
115
101
380
337
380
338
881
107
229
204
256
94
375
23
375
6
375
52
359
353
359
352
583
563
352
335
352
336
352
341
352
348
370
345
370
350
370
362
370
361
427
390
427
392
427
396
427
395
427
403
427
402
522
519
522
516
522
518
522
515
572
333
572
331
572
299
572
322
572
515
572
517
364
332
418
354
418
355
706
647
362
351
362
349
127
123
115
101
115
104
87
61
3
335
3
341
3
336
3
348
882
843
781
44
414
409
414
408
414
378
414
402
414
403
614
498
264
103
264
106
118
40
118
49
416
322
416
406
416
407
416
367
416
404
416
333
416
336
416
324
416
43
390
8
390
3
390
5
390
11
390
6
1255
661
1255
667
1255
664
1255
479
458
181
1214
838
1424
101
736
142
736
223
1613
1419
1613
1430
1613
1489
228
110
228
112
568
348
568
445
568
115
1291
713
2843
1278
2843
1391
695
138
695
141
781
44
781
40
878
243
968
267
662
428
662
468
662
469
662
542
681
680
716
310
716
632
716
638
716
611
716
641
716
635
716
610
716
642
716
279
706
647
939
267
1290
120
1290
121
1290
125
1242
1100
611
405
531
453
429
40
429
32
204
154
204
135
204
111
164
144
164
145
439
328
2531
2151
529
119
439
328
439
292
559
466
520
477
787
730
917
472
338
143
908
360
520
477
338
143
1242
1100
204
154
204
111
204
135
2531
2151
439
292
168
74
787
730
908
360
1242
23
781
717
781
59
466
82
466
55
466
335
466
458
466
326
466
338
2120
1398
2120
1362
140
128
529
215
529
418
403
379
403
382
403
381
824
208
824
204
824
433
824
429
824
445
824
434
824
425
414
38
708
687
708
648
2089
19
2089
3
2089
846
1531
1342
1531
1524
1531
1336
491
259
439
434
852
209
1863
1163
2555
1790
2555
2438
1438
1363
1438
311
1438
194
543
472
439
61
339
13
580
126
580
264
580
512
580
290
580
403
580
464
580
49
580
166
580
374
580
57
580
208
580
396
580
352
852
125
142
19
142
20
473
74
473
197
646
52
1518
896
2115
1046
2115
1768
2115
1771
2115
1788
2115
1833
1278
178
504
76
660
636
660
425
660
381
660
396
208
193
636
26
647
288
163
64
465
406
465
6
465
182
756
739
756
749
756
732
736
205
781
59
577
176
465
377
393
221
393
217
233
61
1972
1617
134
117
400
225
400
221
632
169
632
163
632
213
632
259
632
156
632
148
1339
29
641
632
641
630
466
82
466
458
663
524
1244
574
1244
759
1244
70
1244
610
1244
780
1244
853
252
150
252
114
479
304
857
45
857
32
857
593
857
320
857
107
857
457
857
11
857
332
857
290
857
370
857
675
857
209
857
213
857
361
857
344
857
563
857
36
857
362
489
257
1287
1107
1287
1115
447
148
447
144
435
285
435
392
1294
1091
1294
1052
1294
1026
1294
1033
1944
519
1944
372
1944
546
1944
687
1944
376
1944
290
1944
354
1944
700
1944
529
1944
685
1858
860
2015
1816
620
111
1164
578
1164
467
725
714
725
631
725
632
725
620
1497
436
1050
1007
1050
791
1050
679
1050
675
763
738
763
729
748
723
808
778
464
435
294
3
1382
87
1382
160
1382
86
1382
685
433
132
433
125
433
127
433
146
611
56
559
496
559
500
597
561
597
564
597
555
1441
1358
491
14
491
17
491
315
620
615
620
614
1250
1062
823
329
823
485
823
385
661
479
661
475
216
134
543
67
543
163
543
204
543
209
543
25
4128
3204
825
58
552
171
1327
981
1327
929
1327
838
1327
977
1327
1127
560
36
1025
600
897
692
897
722
897
730
577
187
726
563
328
225
328
116
328
140
328
109
328
316
3336
1220
3336
1240
3336
1208
3336
1234
172
63
172
45
268
254
268
122
268
247
268
137
268
255
268
252
268
248
268
134
268
138
718
679
718
21
718
28
739
540
739
538
739
545
552
334
552
379
552
547
706
553
517
145
517
72
565
50
565
56
565
63
565
16
565
22
565
29
1388
1132
1388
966
1388
1098
1388
1373
720
434
720
222
1377
302
1377
308
1377
304
863
156
673
124
673
203
673
200
673
199
790
573
593
456
1045
717
440
188
3418
206
3418
204
3418
192
3418
202
3418
205
475
81
475
76
360
43
360
26
360
23
360
46
360
276
605
287
418
77
418
76
331
273
331
325
836
502
843
310
2537
43
499
494
499
425
3034
2740
3034
2751
3034
2749
677
449
677
269
953
903
953
904
2214
237
365
330
456
238
198
154
673
378
421
123
421
127
336
301
1307
350
890
527
499
169
679
393
679
394
679
396
679
470
679
581
679
585
979
209
172
45
172
63
3
26
656
548
1498
1418
916
137
966
9
966
288
3
3
638
94
1097
1029
757
331
1308
776
1308
835
1308
325
1308
319
1308
780
1308
782
1308
406
2316
874
513
233
631
174
631
453
721
685
721
694
1486
793
1486
1163
1486
920
1486
631
1486
1009
905
903
2537
43
1111
480
3
791
3
675
3
1007
3
378
213
203
1249
776
1249
835
1249
325
1249
319
1249
780
1249
782
1249
406
1531
90
853
743
853
42
274
101
1242
1100
204
135
559
531
559
503
706
218
1159
563
1159
648
1159
656
457
431
1233
1096
583
563
371
331
358
49
982
281
556
320
395
346
707
218
1447
1270
1447
1271
371
331
1242
611
1242
895
420
55
1390
1355
1390
1348
1390
1364
1390
1233
1390
1229
1390
1234
1052
924
1052
4
1052
396
1052
860
1052
576
1052
193
1052
575
1052
406
1014
906
193
41
583
426
694
626
694
588
694
284
694
306
694
658
694
372
694
405
694
471
694
446
322
73
1400
1352
1400
1359
1400
1237
1400
1238
1657
1509
1382
1184
273
30
1242
23
2749
2655
1321
1097
1321
555
292
3
172
63
172
45
3034
2740
3034
2751
3034
2749
525
414
525
215
953
904
953
903
631
23
628
149
628
157
628
164
628
170
646
51
430
129
1281
178
760
726
760
735
648
364
648
438
648
553
660
396
660
425
660
636
2094
1753
2094
1770
2094
1815
603
598
486
368
1033
717
1052
664
1052
780
1052
997
410
73
462
433
887
526
668
124
668
203
695
390
490
416
490
485
2014
1878
1450
430
1822
607
147
37
147
56
172
19
172
18
480
472
1004
694
1004
708
1004
494
165
72
166
2
2078
1905
480
472
452
342
215
42
638
504
172
19
172
19
647
507
1732
402
1732
233
1732
239
1732
1002
3
239
3
233
3
221
638
504
782
559
172
19
1030
695
324
5
324
278
1711
1107
440
341
403
369
403
365
390
22
524
518
524
512
487
52
334
72
546
70
546
81
403
365
403
369
233
48
447
212
447
219
514
502
514
508
836
588
836
667
724
717
473
316
473
238
473
239
911
7
185
137
185
37
533
144
533
112
533
127
364
322
233
225
233
190
233
170
233
131
233
126
676
613
583
426
583
348
583
349
1290
782
1290
1252
619
314
619
492
619
491
619
318
619
125
619
291
619
597
619
596
430
333
430
343
360
322
641
540
641
539
641
428
641
94
641
173
641
352
360
322
548
535
364
322
223
200
223
217
575
272
473
316
781
141
770
704
756
752
471
217
471
255
471
300
471
256
471
282
471
218
790
489
790
673
790
674
790
750
790
669
790
784
796
679
796
680
796
495
796
790
796
675
3
790
3
495
3
680
3
679
3
675
473
316
1052
396
504
396
420
215
546
465
546
481
803
619
874
667
501
252
1052
427
1052
396
977
772
892
11
535
186
535
340
1083
427
781
653
297
14
1255
1221
1255
876
1255
1111
1255
1220
1255
1247
1255
1138
1255
1195
1255
1022
193
171
193
151
193
57
2135
1707
2135
1731
2140
1256
332
9
781
141
781
332
781
330
781
63
770
704
480
325
480
314
557
117
557
30
403
249
870
663
870
164
787
698
1502
1108
591
117
591
30
451
446
451
341
451
60
451
12
451
113
451
350
451
65
443
434
443
439
443
442
1450
230
1499
1104
443
434
443
439
443
442
781
111
781
28
781
101
529
141
633
487
633
484
633
522
633
517
633
518
655
554
655
50
1217
1066
215
2
215
1
323
314
378
12
614
498
313
123
379
12
636
26
234
88
234
92
781
36
781
32
781
40
483
278
770
726
770
713
164
56
572
513
441
230
441
395
441
403
441
261
441
234
529
302
331
242
331
238
480
311
439
57
968
75
559
489
1424
508
1424
504
1613
1543
1613
1489
1613
1606
1613
1571
572
517
427
179
427
122
427
172
737
652
233
61
470
31
470
27
591
570
1321
483
394
341
394
361
394
351
350
158
296
178
296
187
296
183
419
297
1425
775
724
390
847
788
847
792
1708
1694
293
229
293
233
313
63
313
59
1053
1006
310
185
310
152
795
170
263
230
263
233
410
394
866
779
864
778
572
517
572
508
572
513
572
521
851
392
851
384
851
380
353
60
353
56
353
48
353
52
454
401
454
405
180
59
295
285
846
506
846
502
846
603
846
666
359
221
359
225
530
507
401
47
401
44
479
4
479
46
468
279
290
278
290
282
467
244
467
219
467
254
467
249
916
761
916
765
916
767
916
762
540
361
540
357
540
422
540
418
540
365
703
640
703
644
703
648
703
652
569
199
966
585
469
31
469
27
160
34
892
309
360
326
781
674
465
73
465
90
465
242
465
269
427
172
399
256
399
260
786
183
390
207
781
141
403
239
710
176
217
159
821
768
3
465
3
655
3
768
3
587
3
656
3
585
781
44
611
503
208
193
271
255
803
346
250
5
1075
183
1075
164
1075
179
1075
176
1075
185
1075
180
224
49
166
37
166
23
781
63
781
63
781
141
770
704
821
523
821
533
821
496
1499
1104
443
434
443
439
443
442
591
30
591
117
411
249
352
323
352
324
352
329
352
338
522
470
1613
1489
413
354
413
355
391
372
391
374
358
289
576
483
576
484
352
307
358
288
1367
1320
418
354
418
355
352
338
352
329
1613
1489
359
330
359
331
359
336
359
345
380
368
380
356
380
355
380
362
392
373
392
375
930
68
204
154
375
273
375
152
474
433
160
15
193
187
862
14
998
411
998
783
425
387
425
308
263
155
159
71
159
122
1144
872
1144
1111
1144
691
686
80
686
57
686
64
671
58
671
84
159
71
159
122
865
91
930
280
930
193
930
767
930
219
345
218
462
202
672
292
1575
1031
1575
1458
390
17
498
30
749
726
740
385
1233
611
149
37
149
24
329
121
1203
1157
985
679
169
96
498
30
413
25
296
187
483
131
428
382
827
734
236
69
284
231
158
146
487
52
935
811
935
858
935
865
935
892
579
35
380
324
926
293
873
442
480
307
525
443
525
433
525
446
652
325
863
358
863
644
251
164
901
675
429
389
429
383
429
324
429
422
429
336
530
104
530
86
630
615
382
281
382
278
171
66
330
292
196
111
196
54
196
64
196
99
334
62
334
72
393
291
393
385
393
291
380
324
380
330
380
361
380
373
591
129
591
82
367
314
594
573
594
240
580
469
748
504
468
71
386
207
386
319
672
637
136
27
784
454
784
737
1052
909
419
170
477
145
477
138
477
142
477
93
2703
1067
367
358
367
363
773
342
773
567
216
150
166
24
589
263
344
255
724
368
444
251
1128
1002
591
562
334
206
334
210
1700
969
1700
160
533
25
491
57
770
726
418
79
418
77
418
85
418
287
418
126
418
292
418
124
418
75
418
81
418
69
712
386
712
208
420
289
770
726
770
704
525
411
641
65
431
376
431
421
1056
1032
938
889
346
160
525
402
525
52
525
411
1726
590
1726
821
1139
658
890
753
890
882
890
239
890
682
890
243
913
787
458
254
458
168
908
360
269
251
981
143
770
704
480
472
480
307
794
693
787
698
999
748
999
753
999
752
471
375
770
704
536
418
480
472
480
307
537
419
794
693
509
393
727
719
727
723
787
698
543
425
526
410
512
396
720
712
471
375
894
858
894
771
894
813
894
778
894
865
894
820
770
704
380
38
770
704
502
136
502
104
502
353
707
292
1183
395

217
159
593
545
593
583
593
579
593
541
1620
1277
1620
1282
1620
1281
1620
1603
592
103
547
201
770
704
781
141
770
704
546
481
546
420
546
465
727
716
727
701
727
678
823
714
770
726
467
249
595
103
595
117
595
105
595
166
399
165
399
131
399
199
399
264
399
154
507
311
504
127
1335
862
655
328
1424
856
1424
859
1424
542
1424
23
1424
866
1424
504
770
726
552
137
552
8
1291
975
619
211
619
200
425
207
527
297
770
704
596
585
420
8
372
3
372
5
725
365
205
77
205
81
430
52
366
282
1708
1134
420
20
420
215
420
8
198
156
198
197
327
132
441
213
832
662
317
31
327
132
327
118
491
165
360
28
672
31
673
314
673
252
673
31
424
352
766
364
766
363
655
255
655
23
655
318
655
321
756
180
758
213
1243
1200
1243
1189
1243
1216
1807
980
1807
1129
1807
1461
1807
938
1807
1797
1807
1131
1298
317
1298
569
1298
750
1298
340
1298
641
1298
567
1298
587
1298
665
975
341
975
366
975
447
871
823
394
345
394
355
394
329
394
365
394
327
394
331
394
363
431
421
707
226
391
43
1708
1134
147
51
2382
59
710
609
1839
476
371
347
371
329
371
331
371
345
711
610
709
436
561
39
427
158
427
159
504
98
1004
476
1004
370
1004
395
509
273
1222
1195
1222
1168
447
212
626
165
626
336
2098
317
399
79
752
524
3142
418
3142
420
698
620
745
22
745
179
834
662
626
336
626
165
5540
1330
153
57
3
364
3
213
3
165
3
447
420
8
420
8
2414
2038
2414
1037
531
36
149
24
149
37
529
306
529
325
331
72
331
62
118
64
462
202
474
147
474
146
474
312
474
261
474
137
474
468
474
165
474
94
474
466
474
141
474
138
474
142
474
166
474
460
474
150
474
264
766
150
367
358
968
905
968
309
968
307
749
726
1581
1031
986
678
149
24
2225
455
498
30
1092
128
413
25
505
70
296
187
532
179
882
843
827
734
236
69
181
80
704
61
704
548
704
66
341
99
284
231
487
52
579
35
441
104
549
252
380
373
926
293
451
276
870
671
1164
497
504
437
535
530
175
44
431
386
431
380
380
373
329
187
492
297
1308
1050
1308
698
900
208
900
824
821
779
695
551
678
584
292
14
402
375
467
244
467
254
916
761
916
765
916
767
916
762
206
162
698
98
698
101
698
92
698
91
698
87
1097
860
1097
863
365
271
365
212
365
172
365
188
460
249
460
246
460
18
460
15
209
199
2703
1067
877
219
209
199
398
362
398
394
398
360
398
389
753
691
753
359
753
601
394
385
394
390
2357
592
162
123
410
177
2414
11
441
201
441
421
441
234
441
216
441
198
441
68
441
204
441
211
441
180
441
110
441
49
441
395
441
403
441
152
529
306
529
302
529
325
580
248
437
432
437
402
725
395
1210
1038
1210
1040
1335
770
1335
862
474
166
222
78
222
105
364
240
364
260
572
115
572
112
473
181
483
50
737
726
737
720
737
652
737
644
737
349
656
78
292
282
777
225
777
210
749
726
483
228
1147
62
1147
425
505
68
505
70
513
157
514
401
461
105
154
102
541
50
1390
1234
545
152
1052
924
1052
860
1052
440
1052
576
1052
1006
1052
193
1052
897
1052
575
1052
741
1038
859
1038
858
822
653
822
652
870
11
675
215
675
565
675
223
211
107
708
388
708
399
1390
984
1234
1104
1234
25
832
662
832
553
832
606
1106
711
1203
494
1203
1176
1203
632
1210
692
1255
685
205
142
284
98
284
54
284
55
261
145
235
1
235
44
235
92
595
556
595
555
595
552
863
640
145
18
590
481
204
200
405
376
889
667
1138
258
1390
1355
1390
1348
1390
1233
1390
1234
1400
1359
1400
1238
1400
1352
1400
1237
283
242
1390
1233
1390
1234
527
230
527
385
798
782
441
309
441
393
441
196
1106
685
1106
933
1106
969
1182
260
1182
438
427
291
345
77
189
136
175
33
400
320
783
35
527
230
527
385
305
221
304
220
763
34
248
152
250
117
250
78
593
278
593
62
593
583
593
579
203
97
203
95
1499
1104
359
160
3
567
3
260
3
271
3
682
3
438
536
418
1089
1017
1089
987
1089
571
1089
573
1089
767
1089
753
1089
761
1089
741
1089
730
1089
719
2028
2024
536
418
829
824
1052
576
1052
860
1052
924
1052
406
1052
575
884
754
884
755
884
756
317
41
1210
1091
1210
868
197
73
197
87
781
85
781
653
729
178
770
704
220
181
220
192
586
477
559
8
559
375
559
378
577
557
1114
904
896
594
665
192
665
602
579
348
480
54
588
231
588
219
588
197
299
296
299
294
893
889
535
423
535
526
710
176
661
643
546
481
546
420
546
465
546
484
546
474
938
227
938
301
938
295
938
111
938
279
938
290
938
95
938
256
398
335
903
900
567
283
784
684
1388
721
480
325
480
314
1147
307
746
695
976
899
727
701
1302
782
648
339
648
340
1482
1471
674
154
674
310
674
331
674
186
380
9
380
29
591
117
591
30
178
13
162
18
560
252
874
667
874
168
874
390
874
270
874
195
874
182
874
330
874
413
874
252
874
131
874
290
874
237
874
375
874
309
874
365
594
472
1009
579
1009
880
1009
401
1009
578
1210
870
1373
1167
1373
1351
1373
1166
1373
973
1373
1162
1373
980
906
851
906
883
530
504
913
736
1941
451
631
24
3
392
1052
575
1052
576
1052
924
1052
406
1052
396
857
127
630
603
1259
1152
521
487
521
514
664
214
228
205
228
194
411
249
559
182
559
173
559
445
695
681
905
759
905
759
1055
283
339
23
651
541
496
339
191
63
854
470
854
734
854
738
854
739
517
510
150
113
155
17
595
263
595
278
595
332
248
191
311
125
311
141
311
145
311
151
767
200
767
201
1363
829
1363
832
1363
1062
1363
1332
1363
1336
199
193
346
14
501
11
759
396
759
397
862
754
337
171
158
131
158
132
345
327
345
322
259
74
259
95
315
54
1366
1018
440
438
536
529
382
264
382
246
1482
1471
1482
1335
857
127
2169
1786
2169
1737
391
336
827
701
704
300
380
9
380
29
382
264
673
310
673
331
596
264
596
279
596
333
864
596
864
230
827
701
767
200
767
201
1055
576
1055
927
883
875
350
141
536
529
490
38
656
206
2472
1175
474
410
474
412
519
487
519
512
1210
870
429
313
648
339
648
340
870
596
870
230
517
510
770
704
968
225
968
507
509
444
509
447
1009
578
1009
579
424
313
559
8
559
375
559
378
162
18
162
26
1209
869
1388
721
1040
283
339
23
886
756
886
757
886
758
497
340
191
63
155
17
248
191
1363
829
1363
832
1363
1062
1363
1332
1363
1336
770
553
770
292
835
66
835
348
842
186
842
190
842
201
468
467
426
307
178
13
484
38
536
418
1257
1228
218
65
201
178
201
190
333
303
1260
1231
841
352
731
309
187
108
441
197
441
213
441
355
441
284
441
29
441
323
441
288
441
190
441
304
595
304
317
35
480
472
480
307
551
535
437
331
2549
2158
1335
876
440
402
440
365
756
176
756
180
418
79
418
287
418
292
418
75
577
176
577
472
577
512
937
795
937
401
427
403
427
385
427
395
427
397
427
401
427
384
427
174
427
172
427
404
555
221
555
208
555
146
503
476
503
470
503
471
503
478
207
184
207
197
207
187
207
132
207
186
207
189
847
406
729
171
498
292
498
157
770
753
1383
1033
379
357
379
365
584
186
1992
311
480
472
480
307
525
446
525
443
497
429
662
180
662
182
662
239
662
268
662
428
662
437
662
441
662
455
662
519
662
541
662
542
3142
12
3142
15
302
201
851
403
2549
2158
596
512
596
493
318
227
318
227
540
441
288
16
731
146
1335
876
712
209
942
348
942
353
942
689
942
751
942
861
942
356
942
727
942
820
942
88
942
112
942
819
942
47
942
152
117
87
117
86
147
95
147
92
3
176
1349
416
285
252
285
202
285
244
285
210
755
441
429
18
429
174
439
61
198
186
921
560
197
186
655
248
655
297
390
311
390
388
928
794
149
37
345
75
296
187
926
399
926
397
451
276
489
215
318
199
746
344
319
38
319
252
589
410
781
44
781
32
781
36
781
40
292
197
704
580
704
266
704
489
704
395
704
496
704
407
704
454
704
523
704
282
704
521
704
442
704
518
704
446
862
18
862
2
862
52
425
178
425
212
425
7
270
22
765
388
765
483
335
250
1971
501
503
101
503
135
3329
3213
346
163
346
169
729
462
885
527
845
191
845
190
568
273
858
594
1481
157
599
107
599
109
378
184
1420
770
1420
772
1420
1095
1420
1263
1420
1342
425
7
425
178
425
212
446
23
446
41
979
627
204
111
439
7
648
620
648
258
648
337
648
358
648
267
480
92
168
74
168
117
168
98
1166
745
1166
753
1166
749
1166
743
393
221
393
217
299
213
463
20
1030
695
400
221
298
212
204
154
204
111
211
23
211
22
327
132
296
216
436
430
204
200
204
127
204
111
864
221
864
231
864
198
737
521
737
45
390
33
770
726
193
143
749
726
463
357
463
204
1233
306
505
70
505
111
236
69
236
68
236
83
331
143
487
50
487
52
902
212
902
216
525
433
366
331
347
101
347
103
626
519
626
591
626
526
901
212
901
216
429
383
341
99
196
72
196
54
196
64
196
111
200
182
200
119
200
147
237
49
334
72
334
62
334
90
334
92
143
138
409
358
409
364
163
147
488
103
488
351
488
396
136
27
784
279
784
737
373
156
1335
695
1335
705
1335
862
352
346
1175
723
557
27
557
106
707
102
707
200
425
134
1916
1455
467
264
467
60
467
74
467
86
575
287
163
147
179
61
179
72
541
51
507
388
507
360
724
547
204
154
204
111
204
135
598
350
198
86
462
95
672
31
2549
2172
1051
773
673
252
197
186
197
196
1307
323
1307
347
1307
576
1307
594
1307
648
1307
757
781
551
327
118
327
132
595
393
1233
324
1233
357
1233
301
1233
264
159
139
1298
594
1298
649
559
495
576
350
420
8
413
309
489
162
487
386
863
860
480
472
1202
1175
545
20
746
20
665
403
652
23
652
252
652
315
476
279
1380
89
454
40
490
20
256
245
621
454
1544
229
397
77
648
258
888
583
888
658
931
357
499
33
499
126
475
465
458
178
839
519
268
20
505
31
505
196
505
261
475
65
648
526
1114
798
272
257
1255
228
1255
488
1255
498
1255
620
1255
696
1255
589
2097
317
2097
306
2097
47
464
224
243
69
1338
1178
1091
454
1873
1416
745
22
2003
368
371
347
371
349
371
331
658
600
1408
1142
1100
272
432
49
154
134
681
484
497
116
497
389
338
89
338
91
338
202
1814
938
1814
1464
322
99
722
692
469
66
469
456
1872
695
1872
714
496
86
392
67
136
9
1327
573
261
125
249
235
551
428
551
409
3
594
3
648
3
347
3
576
3
757
3
323
441
175
52
16
850
674
652
23
652
252
1092
567
192
183
450
283
435
323
204
116
1482
1479
332
222
332
123
149
79
149
81
149
117
149
101
395
380
408
365
340
230
288
13
255
249
255
242
221
148
379
12
525
39
390
388
2345
28
943
186
107
101
107
102
334
62
334
72
716
711
716
712
226
191
226
94
226
87
226
95
226
190
226
88
375
243
375
305
375
300
375
250
375
31
375
302
375
242
450
443
149
101
149
79
149
81
667
54
667
53
667
55
530
434
530
439
461
302
429
386
429
173
429
387
1235
346
1235
347
786
668
110
12
110
13
110
7
976
948
976
945
543
103
543
195
543
300
543
377
543
147
502
16
773
740
773
746
1259
1182
421
111
410
396
410
404
410
400
160
10
160
1
333
66
333
1
201
138
279
1
529
434
529
439
204
25
549
466
549
533
672
642
656
5
656
24
1233
306
267
147
267
47
412
30
412
42
412
368
412
374
412
157
412
146
412
147
412
155
210
94
210
119
314
35
314
31
717
171
757
691
757
704
757
180
757
681
757
700
757
696
757
688
757
678
243
208
971
929
971
934
729
171
497
433
497
444
235
208
486
372
467
289
204
111
204
135
466
65
466
50
466
72
466
38
466
25
372
20
545
20
793
778
648
337
648
338
172
19
147
37
89
87
599
308
2647
2151
583
185
720
188
562
466
631
100
244
64
244
127
204
111
439
372
439
357
439
399
1123
617
1123
618
648
337
648
338
334
1
334
7
334
88
334
92
334
288
427
38
427
33
583
185
720
188
204
111
204
135
985
142
985
894
505
272
172
19
593
475
204
111
648
337
204
111
204
135
197
196
159
139
1380
89
213
203
213
205
2318
1672
204
111
439
328
159
139
2318
1672
204
111
204
169
204
172
204
95
204
93
204
154
204
135
2318
1672
204
111
393
221
393
217
1029
693
648
620
301
215
204
111
204
135
204
154
401
221
401
225
393
217
393
221
164
152
735
640
1210
554
136
44
295
287
1113
269
134
26
629
420
629
272
629
270
631
248
1304
433
234
185
234
184
116
27
164
97
740
175
740
183
427
182

427
184
556
397
556
393
268
205
268
153
268
39
360
179
360
181
1374
837
1374
841
1374
812
1374
965
334
206
399
260
347
217
350
174
350
178
477
317
477
313
1189
727
282
73
282
238
282
69
282
234
164
145
264
202
504
126
504
60
504
108
504
163
504
396
1088
834
918
893
85
6
488
126
488
108
488
380
488
60
488
163
960
813
960
715
1335
605
1149
196
1084
174
400
88
400
310
395
88
779
158
247
58
318
284
318
284
488
381
488
111
1126
175
265
246
164
54
467
244
390
17
559
356
576
166
576
320
556
353
1380
844
552
342
425
203
105
75
426
95
350
187
164
129
1051
756
390
17
770
726
777
133
749
726
483
228
576
320
576
371
474
292
474
299
505
70
505
68
296
187
158
148
487
50
487
52
480
307
480
472
360
181
360
179
513
157
652
556
652
325
652
283
652
466
652
412
652
294
652
474
652
428
636
485
275
74
325
23
325
28
428
72
428
76
863
358
863
644
289
33
289
216
901
169
901
167
267
47
267
60
461
105
419
306
175
58
443
307
630
606
737
349
927
78
749
721
386
207
386
257
386
319
168
77
168
80
136
27
1978
552
490
437
490
79
712
403
712
59
647
309
773
342
773
567
1223
874
5656
4905
5656
5565
5656
5554
449
103
449
103
473
181
154
102
384
202
384
252
384
314
257
162
257
172
257
186
464
130
435
125
447
65
447
67
195
180
241
145
240
115
240
105
766
182
766
184
224
92
953
272
3053
2504
242
30
242
41
412
218
271
260
651
139
655
648
439
61
345
335
770
726
325
15
325
28
325
68
325
119
1544
384
1544
996
570
521
717
539
738
640
491
41
1122
446
555
472
441
38
186
128
205
44
205
101
427
207
401
74
401
76
202
41
202
44
202
101
149
101
149
79
149
81
149
117
422
128
2139
782
2336
2015
441
230
441
395
441
403
441
201
441
180
572
508
572
521
345
218
345
241
345
244
345
197
345
230
197
9
197
186
390
17
390
14
781
245
770
726
149
37
466
55
817
16
733
687
733
496
733
490
474
395
498
30
236
69
544
210
588
523
1317
33
1247
356
1247
299
661
644
821
477
586
234
545
211
366
288
366
296
366
27
366
286
366
338
366
331
366
325
863
479
317
231
382
281
382
278
307
137
307
7
443
320
555
480
555
469
555
384
555
514
555
483
555
490
555
475
555
549
555
399
171
5
926
50
926
394
365
144
1092
313
520
74
194
74
328
227
496
94
1782
1327
431
78
171
66
1189
735
512
344
1482
1115
307
7
307
137
393
285
591
243
821
477
594
573
1493
279
770
742
855
450
855
460
1052
731
3119
1158
3119
1178
857
519
857
606
1534
134
887
158
304
19
383
168
383
179
1340
856
1340
816
1340
787
1340
742
1340
789
205
188
377
168
377
179
271
245
472
371
367
172
367
7
367
83
365
16
461
417
1262
736
198
88
1864
1553
3
523
2701
149
390
223
521
410
4967
2807
4967
2813
52
16
52
15
4966
2812
522
470
34350
12021
34350
11877
34350
11921
34350
11931
34350
11968
676
481
676
483
655
568
605
498
1084
209
464
458
464
456
2016
515
2016
593
1053
1010
52
16
660
553
499
286
499
306
224
175
52
15
52
15
52
16
263
98
263
145
52
16
350
55
350
90
706
567
706
604
555
14
130
115
737
648
737
650
327
118
327
127
466
38
466
82
498
39
296
275
357
335
467
239
484
420
52
16
1145
1076
396
259
1852
1574
200
37
1087
601
123
119
1906
1796
1906
1748
1906
1798
1906
1764
1906
1763
1906
1736
1906
1756
211
42
211
44
211
143
172
19
171
19
171
18
172
18
172
19
171
18
171
17
466
71
136
28
136
10
136
28
136
10
136
10
136
28
386
174
386
261
386
276
142
116
470
11
470
16
470
59
428
6
428
12
428
33
367
247
367
306
367
314
466
38
466
71
1388
413
172
18
172
19
572
554
297
169
297
174
297
179
297
183
297
258
581
561
577
557
583
563
382
254
441
37
439
61
507
311
507
318
507
354
882
408
882
402
514
179
431
77
816
730
816
495
816
773
816
420
816
27
816
771
816
769
816
432
816
732
902
167
902
169
904
157
473
386
473
418
441
386
901
169
901
167
380
31
380
231
521
179
244
178
244
207
448
141
448
148
448
128
448
136
3
167
3
169
3
77
382
278
382
281
382
254
1068
899
117
63
439
61
498
30
149
24
149
37
467
135
1023
15
2225
455
179
72
179
61
532
179
785
452
785
738
704
61
704
548
704
66
341
99
768
280
1097
1043
549
252
380
324
380
361
380
330
380
373
451
276
344
255
334
245
2106
1722
591
562
427
381
1830
135
1861
1621
1861
135
1861
1624
735
572
425
207
380
207
453
248
453
265
599
97
599
480
531
526
786
453
786
739
756
95
938
814
938
861
938
868
938
895
985
679
158
146
367
358
367
363
216
150
650
622
761
5
761
46
761
759
761
36
638
612
340
331
764
200
764
116
381
196
1765
389
1733
389
236
69
347
104
457
8
400
294
382
278
382
281
382
254
1068
899
117
63
117
44
117
35
117
81
117
68
439
61
390
340
390
384
498
30
498
7
416
124
817
14
817
204
149
24
149
37
179
72
179
61
785
452
785
738
196
64
704
61
704
548
704
66
341
99
1097
1043
440
104
549
252
380
324
380
361
380
330
380
373
451
276
544
210
297
188
393
291
393
285
393
385
795
245
795
170
427
322
427
334
427
351
427
361
427
366
427
381
427
387
427
415
427
420
454
121
735
572
425
207
1445
1177
1445
1186
1445
1266
358
187
358
184
358
182
224
176
358
184
453
248
453
265
678
584
588
246
599
97
599
480
243
41
648
28
648
288
648
295
648
300
648
641
345
218
345
244
688
671
923
292
923
343
425
178
425
203
425
207
365
325
365
331
365
335
365
338
786
453
786
739
594
264
594
556
756
95
330
142
938
814
938
861
938
868
938
895
369
58
369
71
526
179
985
679
158
146
367
358
367
363
443
83
590
209
216
150
320
220
458
592
650
622
761
5
761
46
761
759
761
36
638
612
340
331
396
367
396
379
396
205
764
200
764
116
381
196
211
202
505
111
395
386
395
391
822
624
822
628
530
86
530
104
441
37
454
224
596
18
596
54
596
67
752
504
382
254
430
77
495
303
495
310
495
346
473
418
382
372
382
329
382
327
382
324
292
158
875
243
382
367
1531
1342
382
367
382
261
838
799
838
501
430
52
483
8
483
23
211
42
211
44
1956
1451
770
726
1234
1104
72
1
585
502
490
8
490
23
382
367
902
861
938
889
585
502
788
775
788
778
382
312
382
264
382
266
382
246
586
117
586
30
536
418
461
59
1144
307
1009
401
1132
1006
1132
1007
461
59
467
464
467
463
467
466
465
464
465
462
465
461
467
464
467
463
467
466
271
17
658
648
658
645
462
299
425
421
425
422
425
424
851
830
586
67
586
65
467
416
467
466
467
464
467
463
706
550
706
604
706
8
331
7
331
1
331
285
331
88
331
92
439
372
439
357
439
399
648
337
648
338
524
401
524
191
524
140
524
196
172
19
1147
990
1147
438
595
517
793
743
793
713
591
271
591
273
721
188
1599
894
1130
618
1130
617
1606
1106
103
46
103
47
204
33
204
100
303
29
303
238
303
172
427
33
427
38
587
185
227
206
831
792
909
384
475
291
475
3
475
42
475
40
467
219
545
83
1099
104
1099
117
1099
119
1099
94
1099
99
1212
206
1212
229
1212
202
1212
211
1212
216
1021
59
1021
72
1021
45
1021
54
544
83
425
178
469
219
469
224
398
260
398
265
478
285
478
313
478
252
478
304
478
305
478
278
724
72
706
604
501
43
501
18
911
38
911
231
1199
870
528
18
528
70
481
87
907
848
907
831
327
132
327
141
1308
1117
1308
1137
1308
1120
1308
765
1308
779
1308
1072
1308
764
1308
1113
4953
2803
4953
2797
1482
1302
497
18
497
39
1429
846
706
567
706
604
441
230
441
395
441
403
441
261
441
234
406
119
1210
767
1210
1069
1210
1165
1210
1070
1210
1080
1255
1171
498
18
498
39
524
18
524
66
466
82
466
38
474
433
474
408
655
548
817
99
817
98
149
15
352
314
352
306
2169
1602
345
324
490
18
384
217
704
602
704
565
474
392
474
380
474
394
752
726
770
728
749
514
655
568
1166
138
224
86
651
275
383
345
383
172
383
337
383
176
410
230
410
364
410
372
410
234
116
60
561
170
992
388
992
690
992
946
421
111
1740
1510
1740
684
1740
693
1740
780
602
236
742
621
617
303
542
286
542
253
542
314
246
64
246
59
2959
76
474
332
474
340
474
331
474
336
977
929
526
476
526
475
979
858
979
975
979
891
1490
826
1490
825
1059
1011
473
405
357
335
2167
782
614
304
478
285
478
313
478
252
492
420
262
195
262
45
262
213
911
231
911
38
327
132
327
141
1308
1117
1308
1120
1308
765
1308
1072
1308
764
1308
1113
498
18
420
8
817
99
817
98
817
115
559
182
483
20
704
602
704
565
992
388
992
690
992
946
1740
1510
1740
693
542
326
542
399
542
286
542
306
542
381
542
253
542
333
542
370
542
310
542
362
542
319
542
342
542
314
542
380
542
400
542
324
542
327
542
279
542
330
542
320
542
305
542
332
542
396
542
366
542
357
977
929
1490
1391
1490
826
1490
825
1059
1011
357
335
2167
782
499
50
390
340
390
384
149
24
149
37
802
699
882
35
882
37
882
402
882
504
772
342
772
567
648
28
648
42
648
288
648
300
648
641
367
358
367
363
428
323
428
335
428
352
428
362
428
367
428
388
428
416
428
421
668
649
560
285
594
417
380
324
380
330
380
361
380
373
156
122
156
125
523
182
443
83
938
814
938
861
938
868
938
895
326
227
158
146
1447
1177
1447
1186
1447
1266
603
221
671
529
724
18
327
128
439
57
722
211
776
181
776
185
586
125
768
282
297
179
297
184
297
180
297
176
334
241
334
245
334
251
199
107
776
256
776
261
776
265
776
269
2464
1264
2464
1259
572
513
572
517
716
534
1072
492
781
22
781
28
781
44
781
32
781
36
781
40
1036
2
1036
3
738
648
615
54
615
58
862
426
365
331
594
552
725
597
725
691
704
640
704
644
704
648
704
652
330
138
827
479
827
484
626
16
626
20
825
549
825
553
825
587
1370
1278
938
456
938
460
938
464
938
468
938
626
938
630
938
634
938
638
522
460
578
45
793
218
771
701
771
625
771
692
771
657
771
72
172
19
172
18
172
18
172
19
1030
140
166
14
172
19
771
671
771
701
771
596
771
681
771
687
771
710
771
716
148
37
464
5
464
21
464
63
881
742
972
282
771
701
771
671
546
149
546
112
546
281
393
297
648
337
648
338
393
297
1265
405
586
513
583
185
720
188
395
332
397
334
580
558
596
517
706
550
351
197
740
576
740
385
740
368
740
226
559
243
559
515
559
398
733
695
733
493
733
496
733
687
654
418
654
420
480
307
545
422
592
409
525
251
737
565
592
409
672
496
757
180
671
499
697
513
707
537
479
304
724
220
431
255
683
512
481
308
401
211
733
217
946
777
983
814
367
192
496
319
706
604
706
8
572
554
382
367
542
314
463
301
187
152
697
654
697
673
701
673
911
121
911
208
911
441
911
446
911
157
911
430
904
121
904
208
904
157
457
352
457
422
505
192
505
200
1978
552
297
199
911
121
911
208
911
441
911
446
911
157
911
430
918
202
918
402
918
406
904
121
904
208
904
157
724
357
167
156
167
156
149
37
198
9
1424
1061
1424
1066
304
298
639
79
639
81
248
130
705
437
973
945
149
37
197
9
979
951
250
244
231
127
1068
864
2005
1965
247
225
735
648
735
640
735
644
735
652
213
67
420
8
329
180
1068
864
2005
1965
247
225
735
648
735
640
735
644
735
652
213
67
420
8
736
345
1046
2
1046
3
329
180
441
282
198
88
198
87
198
73
674
53
674
445
674
42
378
297
378
3
1052
924
1052
860
303
16
1255
876
261
230
261
191
572
478
906
773
906
730
906
699
1092
701
1092
451
339
23
605
575
543
425
1241
1192
211
79
528
18
674
271
529
120
580
322
725
376
205
77
205
14
205
81
211
19
400
337
339
251
1807
1253
699
671
629
158
1335
907
1132
1079
632
158
198
9
620
480
744
568
381
82
341
335
744
568
198
87
197
87
906
773
906
699
852
635
918
468
1132
1007
1132
1006
318
68
318
73
546
465
482
360
318
29
318
211
366
69
366
124
532
457
532
452
532
456
532
466
763
34
304
220
497
149
530
218
530
264
530
303
454
190
1182
260
1123
392
1123
225
695
681
773
266
674
310
178
13
874
252
710
546
1098
684
1098
932
1098
968
281
119
1250
1225
1250
425
1250
512
1250
455
338
222
328
82
326
78
326
83
473
163
770
756
811
512
811
552
811
569
811
593
811
693
913
697
875
438
875
717
1941
225
1941
451
1941
779
1941
1470
1941
1596
1941
1656
631
90
434
240
415
343
248
152
317
51
339
53
420
104
1290
324

1290
420
1290
1237
301
155
870
653
501
150
501
247
501
336
501
484
488
391
178
13
292
14
541
295
734
216
679
478
618
317
3
392
1266
1241
707
277
1014
828
198
87
197
87
629
129
629
341
629
345
629
316
323
309
317
303
794
693
595
563
595
535
871
252
546
465
507
487
507
502
648
340
272
258
272
113
674
564
674
154
674
51
674
331
674
310
659
550
386
71
1009
578
1009
579
512
396
512
507
429
385
429
413
429
106
424
380
424
408
424
313
630
517
269
241
269
260
354
6
354
38
435
68
435
95
841
793
841
823
150
95
329
279
412
275
412
303
412
350
86
64
86
75
309
306
715
90
508
158
52
15
1154
555
1154
557
533
375
847
280
457
151
833
164
954
261
1036
302
322
253
908
360
533
375
838
405
1429
292
307
7
307
137
205
74
857
519
857
606
857
654
857
803
498
30
543
112
2203
1946
817
16
467
135
179
72
586
272
704
550
768
282
864
773
864
777
1055
731
536
74
393
285
330
319
1548
151
507
429
770
742
781
245
496
162
496
120
496
39
1830
135
1861
135
369
326
369
160
497
136
171
5
579
403
496
94
3110
1149
3110
1169
1767
505
555
490
1822
1366
695
667
391
14
508
218
508
144
594
573
594
157
495
399
1292
1143
496
94
688
671
317
231
862
450
862
460
365
27
365
286
365
288
365
296
1088
315
473
395
1190
735
365
144
1339
870
1339
1119
1464
1231
1805
1494
1805
315
1574
1159
1257
1175
1056
925
464
130
707
141
827
118
695
667
1654
1589
509
218
509
144
435
44
907
862
420
8
1234
25
1234
1104
863
640
762
444
762
113
762
109
907
862
706
550
706
604
706
8
648
337
211
150
393
297
1265
405
648
337
648
338
720
188
544
49
544
420
544
138
466
458
466
457
393
217
393
221
343
49
343
2
200
9
491
157
491
185
920
578
440
99
440
157
647
507
445
163
444
345
907
862
863
640
904
688
904
669
762
108
762
444
762
96
762
113
762
109
762
91
762
116
762
125
907
848
907
857
544
33
285
203
285
83
285
82
709
429
261
124
92
87
1115
939
587
432
630
275
1030
691
1030
694
323
110
145
18
684
131
684
351
684
606
639
19
366
105
883
716
5038
2842
843
781
822
652
822
582
822
584
822
653
822
604
822
462
299
17
806
598
434
135
434
240
434
241
772
106
508
195
508
305
508
348
508
391
508
435
508
470
843
781
471
217
471
255
471
300
471
256
471
282
471
218
575
161
575
498
575
162
575
160
822
515
822
701
822
705
822
706
822
816
1591
828
843
781
572
554
172
18
1233
631
1233
634
466
38
466
71
586
566
166
2
1388
413
1029
693
1029
850
330
292
330
295
577
557
583
563
450
445
450
446
735
444
735
479
735
723
172
18
172
19
172
19
297
169
297
174
297
179
297
183
297
258
2215
2206
782
559
327
118
249
234
249
235
649
23
269
85
1100
453
1108
278
338
91
324
96
327
132
327
128
467
135
586
125
570
508
572
513
572
508
716
534
1830
135
1861
135
1861
1621
1861
1624
468
279
738
648
1100
445
1100
449
205
72
704
640
704
644
704
648
704
652
330
138
327
132
327
118
327
132
742
621
917
779
149
44
149
44
149
44
1076
244
1076
464
1076
628
586
540
327
118
1429
846
3
44
920
483
179
49
651
275
149
44
617
303
474
436
474
336
474
340
474
332
474
331
149
44
149
44
1077
244
1077
465
623
577
1134
551
1134
544
614
304
327
118
391
43
649
23
649
249
649
315
711
610
427
159
427
158
358
26
397
77
427
158
427
159
509
273
831
660
394
331
394
355
504
98
504
74
504
72
1308
378
1308
384
1308
448
1308
465
1308
835
1308
839
1308
841
1308
894
1244
70
1244
574
1244
610
1244
759
1244
780
1244
853
292
3
1822
1343
1822
1347
140
128
724
717
1496
643
1496
805
1496
932
1496
1021
1496
1174
4953
2797
4953
2803
655
548
597
498
704
602
2016
593
2016
515
655
568
52
16
604
497
533
286
1482
1302
288
187
249
234
171
19
448
116
448
303
448
305
448
306
448
312
448
320
284
282
1482
1302
466
71
171
19
391
180
391
266
391
281
136
10
136
10
142
116
288
173
232
209
469
11
469
16
469
59
430
6
430
35
671
40
366
246
366
305
366
313
778
188
722
207
776
181
559
182
552
171
793
214
797
210
735
174
746
172
393
380
1429
846
448
208
448
201
448
241
448
211
448
410
448
402
441
201
441
198
441
197
441
426
441
196
441
421
441
415
758
513
758
514
758
515
758
518
758
732
758
738
758
743
3
743
3
515
3
738
3
732
3
514
3
518
3
513
706
567
706
604
1166
138
325
116
706
550
706
604
706
8
1032
696
179
49
704
8
704
602
544
20
544
421
544
197
544
202
544
143
393
297
171
19
205
136
633
100
633
248
1493
66
648
337
648
338
586
513
918
202
909
384
647
507
720
188
562
466
706
437
169
163
976
948
195
189
706
8
325
116
749
649
270
62
555
14
130
115
737
648
327
132
466
38
466
82
484
420
542
286
674
445
674
53
674
42
486
221
486
396
391
254
1052
924
1052
396
1052
575
729
353
729
393
419
373
656
595
656
534
780
543
780
664
780
70
540
473
605
575
529
411
674
94
674
53
674
42
502
290
636
27
1182
173
1182
160
1182
260
1182
115
1182
184
1182
217
1182
230
729
353
729
393
794
693
727
719
727
215
727
17
727
394
727
510
787
698
1077
503
1149
88
1149
244
1130
392
1130
138
1130
127
1130
171
1130
225
1130
114
1130
184
1130
214
1130
69
1271
176
863
714
863
734
1182
438
526
410
526
521
526
208
1123
392
3
27
3
50
3
410
3
714
3
734
140
128
724
717
1338
588
1338
594
603
136
636
47
1499
643
1499
805
1499
932
1499
1175
134
117
1273
576
1273
625
1273
778
1273
799
827
793
707
175
707
348
707
24
294
3
255
207
315
43
315
195
315
59
3
3
1804
1325
1804
1329
1343
384
1343
448
1343
465
1343
835
1343
839
1343
841
1343
894
140
128
292
3
1782
1304
1782
1308
140
128
1340
378
1340
384
1340
448
1340
465
1340
835
1340
839
1340
841
1262
70
1262
580
1262
616
1262
765
1344
576
1344
582
724
717
1496
643
1496
805
1496
932
1496
1021
1496
1174
441
230
441
355
441
319
441
395
441
261
441
323
441
292
441
421
441
304
758
578
1152
1072
1152
940
666
501
1827
1678
952
154
472
380
392
57
683
591
366
46
365
46
365
114
3
621
3
609
3
578
3
640
3
672
441
230
441
395
441
403
441
234
352
314
352
306
383
345
383
172
383
337
383
176
410
324
410
180
410
194
410
261
410
230
410
197
410
364
410
368
410
204
410
183
410
372
410
201
410
198
410
234
441
403
441
201
737
521
735
640
770
726
420
355
467
353
454
162
594
478
592
556
339
302
763
320
441
230
441
198
441
395
441
403
441
201
441
216
441
180
441
211
441
204
441
421
501
258
501
201
501
195
136
44
864
794
864
856
864
777
136
45
501
258
501
201
501
195
594
556
763
320
763
218
763
318
763
110
763
96
441
261
441
323
441
292
441
355
752
572
1861
1681
365
46
365
114
1057
914
441
261
441
323
441
292
441
355
722
274
722
273
722
57
752
572
691
170
691
273
441
261
735
7
279
1
279
169
279
176
387
30
1237
971
1237
1006
1237
984
843
14
441
403
441
395
706
134
742
46
742
83
742
80
742
44
742
41
742
79
701
697
545
173
2555
2512
2555
2510
2555
2515
357
45
357
118
545
422
646
641
559
182
758
528
758
578
1807
1386
496
11
204
173
3
578
545
203
545
132
163
137
559
182
1106
1088
1106
393
847
280
847
276
399
256
399
260
347
217
347
221
716
244
397
258
397
254
545
108
559
182
552
171
559
182
559
171
559
182
559
495
559
268
779
181
545
108
436
335
436
365
658
211
552
257
552
171
552
490
735
174
795
214
776
207
753
210
752
213
748
172
431
418
778
188
403
335
1863
1551
380
231
802
699
507
254
580
322
580
374
473
215
324
27
158
148
289
33
289
216
382
200
382
250
382
312
205
86
1613
1489
199
82
199
162
341
32
341
36
341
66
341
70
341
72
341
82
341
287
341
294
205
71
473
215
758
578
986
150
666
501
473
221
952
154
392
57
692
274
729
600
729
597
729
605
729
601
950
473
832
662
1257
544
1233
611
1233
634
398
375
398
369
398
374
398
378
372
360
380
356
380
355
418
354
418
355
87
61
793
596
793
641
793
598
793
559
793
593
793
643
793
647
1257
658
1257
661
1257
530
1257
801
1257
979
1257
798
1257
537
1257
769
1257
1236
1257
996
1257
997
1257
775
1257
524
1257
762
1257
865
1257
806
1257
91
1257
90
1257
1237
1257
621
1257
795
1257
83
1257
932
1257
70
1257
623
1257
696
1257
543
1257
857
1257
796
1257
792
1257
553
1257
757
1257
799
1257
68
1257
544
1257
970
1257
938
1257
617
1257
867
1257
980
1257
527
1257
963
1257
692
781
44
781
46
489
239
489
243
489
237
875
243
521
83
521
4
521
81
1620
145
1257
658
1291
120
1291
121
1291
125
1291
713
1291
660
1291
662
194
129
875
243
924
486
924
482
1620
145
522
470
595
117
595
105
595
103
331
72
331
62
271
62
2555
2512
2555
2510
2555
2515
1230
435
928
806
928
810
902
258
542
95
297
188
502
308
633
312
595
536
1059
899
595
117
913
568
913
585
332
153
332
154
1032
696
171
19
172
18
172
19
136
11
770
726
501
238
501
252
502
290
480
175
920
364
920
268
920
534
1038
283
1321
1113
414
286
103
87
505
241
505
255
3
286
501
238
501
252
502
290
1270
177
1123
392
674
522
674
310
524
408
524
49
631
24
864
715
864
735
727
17
727
215
727
394
727
510
727
719
503
387
503
28
517
212
517
213
659
222
793
693
659
550
659
374
659
616
659
222
998
247
998
397
998
502
1265
752
1265
758
1265
1196
332
288
517
356
517
359
629
129
629
519
629
357
629
518
629
341
629
345
629
316
629
624
629
289
629
623
193
143
457
71
457
83
457
95
457
177
457
188
1302
770
1302
782
659
550
451
431
672
657
603
489
603
226
603
217
811
419
811
444
811
459
913
736
486
387
486
404
827
378
671
661
697
674
559
173
559
182
559
445
585
516
577
558
577
569
603
226
603
217
603
489
424
406
424
403
424
182
208
193
423
184
423
182
422
220
427
182
427
184
384
182
464
220
365
179
365
181
3
182
424
184
364
179
364
181
462
248
423
184
423
182
422
222
427
182
427
184
384
184
464
222
360
179
360
181
399
256
399
260
367
184
384
182
384
283
384
184
384
227
384
376
365
179
365
181
3
184
424
184
480
314
360
186
724
202
1052
924
1052
860
1052
576
1052
575
1290
782
364
181
1114
825
1114
980
1114
1014
1114
808
1114
1028
1114
1089
1114
686
1114
805
1114
1095
1114
899
1114
904
1114
1061
379
203
427
184
556
8
360
181
481
397
351
113
351
118
351
106
351
114
818
53
331
72
331
62
317
35
317
31
544
380
544
176
544
378
544
191
544
330
544
361
544
174
544
351
271
17
658
645
658
648
462
299
425
421
425
422
425
424
851
830
586
67
586
65
495
433
495
435
427
50
498
30
1383
1062
505
339
505
366
451
252
492
225
309
151
309
155
1234
1104
72
1
474
433
187
152
585
502
563
428
671
641
671
634
671
323
671
16
671
15
671
313
671
660
178
13
1103
685
1103
933
1103
969
864
345
864
410
420
8
1271
435
740
667
552
171
671
160
835
472
559
182
471
356
471
357
471
359
486
231
486
230
472
348
472
344
472
346
518
226
518
181
518
198
509
134
740
667
208
193
323
110
1032
692
1032
695
2750
1755
2750
1588
883
716
358
90
366
105
304
19
317
35
317
31
756
176
756
180
327
141
327
113
327
127
327
99
394
237
394
201
394
236
515
485
515
277
515
39
515
7
900
869
900
865
577
557
745
175
745
179
586
566
655
308
655
32
655
325
655
586
248
218
248
224
248
208
248
222
248
214
248
210
248
212
248
206
248
220
248
216
248
226
248
204
186
77
186
83
186
81
186
79
364
308
174
167
174
165
747
529
327
132
737
521
1424
1329
136
44
256
245
747
46
747
26
480
307
559
182
559
182
473
199
441
354
385
179
370
176
588
84
552
171
587
481
1531
1524
1531
1212
904
4
904
40
904
3
904
107
904
39
904
52
904
138
904
26
904
219
904
30
904
6
344
235
1339
1128
1339
66
1339
259
1339
109
1339
1146
1339
703
1339
264
1339
720
1339
743
710
120
710
75
294
136
294
198
574
317
574
215
574
238
574
284
574
276
574
296
574
295
439
115
674
311
674
280
674
272
530
205
495
433
209
193
209
195
209
186
209
180
209
196
209
178
209
203
209
204
209
181
1531
1353
1531
1360
1531
1392
1531
1246
1531
1212
1970
1615
1970
1618
524
133
524
168
327
132
327
118
118
69
297
160
603
209
603
136
427
179
427
174
427
122
427
187
427
172
393
221
393
217
583
563
586
566
577
557
476
344
400
225
400
221
1599
1146
294
198
1130
734
334
206
347
217
735
379
126
31
1234
536
467
140
467
442
327
132
327
118
724
254
829
94
327
118
327
132
737
521
586
367
491
165
390
19
740
385
209
14

209
85
265
135
319
315
319
177
319
79
319
81
319
51
319
84
319
249
319
248
319
175
319
263
319
57
319
265
319
104
319
83
431
12
330
242
656
335
656
320
296
187
168
80
168
77
305
83
525
120
338
53
338
91
338
202
641
240
423
51
647
322
624
542
305
83
716
509
318
183
3
242
439
113
1056
1032
525
411
1648
55
1648
1219
1648
1216
1648
606
1648
1218
868
552
172
18
172
19
172
18
172
19
171
19
171
18
1586
148
172
18
172
19
136
10
172
19
1442
307
1482
1302
172
19
172
18
172
19
448
303
448
305
448
306
448
312
448
320
249
234
249
235
448
116
165
72
288
187
480
307
471
375
480
307
473
181
587
195
732
390
732
623
724
88
1585
1155
732
37
297
14
298
13
298
14
479
182
297
14
732
262
117
98
117
110
735
656
724
254
724
225
401
76
401
74
149
117
149
101
149
79
149
81
429
173
429
387
429
386
458
142
1938
2
1938
1
551
535
1613
1478
2843
1506
2843
1504
2843
1509
2843
1503
512
12
721
543
735
640
2555
2510
208
193
353
13
353
64
419
270
419
274
393
291
1438
311
1210
677
117
63
117
99
334
245
572
521
716
538
439
61
365
305
770
726
325
15
325
28
325
68
325
119
491
41
1125
446
1480
736
330
319
330
319
843
14
737
521
236
68
236
69
236
83
901
212
901
216
429
383
341
99
488
103
488
351
488
396
784
279
784
737
373
156
1335
695
1335
705
1335
862
352
346
1175
723
557
27
557
106
707
102
707
200
425
134
360
184
360
186
379
201
379
203
1209
1195
1270
246
727
716
727
701
486
387
486
404
822
712
735
648
735
644
735
652
735
640
462
431
351
263
351
334
213
104
213
174
213
201
213
167
213
99
213
111
213
182
642
164
395
308
283
192
747
571
572
335
339
314
193
65
193
33
261
170
1132
1007
1132
1006
1130
256
1130
252
1130
231
1271
176
1271
359
1271
327
1271
282
418
103
303
206
151
98
217
208
281
119
1613
1489
341
66
341
70
341
72
341
82
341
287
341
294
1613
1578
1215
457
390
388
546
23
601
150
461
302
924
284
924
286
229
183
1613
1489
398
374
380
368
380
356
380
355
380
362
371
347
133
116
590
483
590
484
486
377
486
396
1271
245
1271
282
1271
176
1271
278
1271
275
572
31
744
82
822
810
822
712
727
716
345
340
3
712
486
221
391
254
656
595
656
534
780
543
780
664
780
70
517
510
517
399
770
704
486
221
391
254
629
316
629
345
1055
576
1055
575
505
466
505
444
505
453
512
507
512
396
1009
579
1009
578
424
106
424
313
744
696
744
726
744
696
744
726
613
565
284
268
781
32
781
36
770
726
327
256
422
372
422
280
422
303
1196
360
107
35
107
52
885
16
885
44
885
46
96
52
269
195
486
79
445
427
451
248
451
272
451
275
982
768
982
770
982
952
484
79
284
151
249
234
249
235
738
640
462
431
378
338
504
226
839
760
839
13
559
359
559
367
442
408
442
404
1051
179
1051
1046
1335
854
1335
858
1335
791
1335
876
1335
862
450
29
450
336
450
95
450
14
450
278
440
402
937
399
937
665
937
561
937
491
379
365
465
107
671
336
671
295
671
334
671
290
671
344
671
356
671
388
671
319
671
332
671
345
671
261
559
367
559
396
559
485
559
487
559
359
298
5
298
59
917
363
917
123
338
87
338
62
271
38
271
67
271
37
271
172
765
206
765
404
517
354
517
388
330
261
330
259
330
268
780
73
780
761
434
114
434
281
3
845
1198
471
1198
489
887
248
607
277
718
545
1298
634
1298
464
1269
63
2097
326
2097
1547
2097
709
2097
308
393
315
155
16
984
842
2357
845
331
260
331
262
331
269
272
68
579
405
579
536
579
541
1594
985
1594
942
1594
1322
218
202
218
10
767
185
219
34
480
253
480
72
492
28
580
168
580
322
556
353
746
219
1374
837
611
405
611
421
651
366
651
538
651
386
651
493
651
504
651
406
651
430
651
397
651
166
651
170
651
404
651
335
651
342
651
390
651
408
651
162
651
355
651
252
651
437
651
528
651
55
3
322
3
168
476
250
580
374
473
215
646
641
559
182
758
528
758
578
794
208
794
204
752
572
451
130
451
130
451
384
957
44
3
578
264
202
1099
104
1099
94
1099
99
1079
64
1212
206
1212
202
1212
211
1139
5
1139
1031
1083
972
1083
979
1150
1047
1150
95
1150
159
1085
982
1085
4
1205
204
1205
209
1021
59
1021
45
1021
54
142
33
591
290
372
191
372
363
372
362
372
361
707
282
707
7
315
111
315
120
217
208
782
510
217
209
217
208
372
191
372
361
372
362
372
363
4684
4641
707
282
707
7
315
111
315
120
217
208
549
533
412
374
412
368
314
31
314
35
717
171
549
503
136
11
136
10
489
366
339
308
1315
892
514
74
514
122
514
171
514
270
514
283
514
496
628
273
718
695
549
533
197
182
197
11
197
177
197
41
197
174
2441
1382
2441
1386
656
5
656
24
1233
306
495
375
314
31
314
35
136
9
237
40
814
618
814
692
549
466
555
310
749
707
749
743
480
307
480
472
314
31
314
35
717
171
114
44
419
387
457
430
297
13
297
14
297
14
297
14
648
340
648
339
857
127
533
415
533
435
261
170
1135
1133
735
334
1499
1104
576
395
1053
575
1053
576
1053
925
921
213
921
135
921
36
921
137
559
39
559
30
559
87
647
339
647
340
339
23
563
498
563
476
563
429
563
482
334
311
334
330
334
316
836
93
836
452
836
450
836
92
968
484
968
346
968
276
968
225
968
384
968
403
968
364
968
289
968
507
968
331
968
262
1305
568
1305
662
1305
615
367
9
367
29
2357
814
2357
803
874
168
874
131
874
413
874
237
874
390
874
195
874
309
874
182
874
270
874
252
874
290
815
92
815
450
815
452
815
93
297
14
525
411
770
726
525
411
525
251
525
411
735
220
704
550
544
421
596
411
1762
917
752
512
752
706
752
714
752
515
430
255
592
559
592
409
480
307
351
197
672
496
671
499
479
304
757
180
697
513
707
537
737
565
481
308
401
211
683
512
985
816
367
192
496
319
716
203
879
874
879
859
879
74
879
596
879
597
879
872
879
511
879
551
1285
933
651
32
950
481
950
485
950
489
715
203
548
423
598
325
598
259
716
93
716
47
716
89
730
195
730
718
407
294
568
173
568
173
931
32
931
619
931
625
403
287
561
170
631
346
390
311
576
350
603
209
572
100
572
101
136
10
808
606
808
796
1042
81
1333
957
262
108
262
123
793
101
1278
144
1278
145
1278
146
583
563
586
566
577
557
591
249
591
249
1235
182
1235
188
504
126
504
60
504
108
504
163
504
396
918
893
85
6
1130
673
1130
908
1130
1048
488
60
488
108
488
126
488
163
488
380
648
258
960
813
960
715
1335
605
847
476
1084
174
400
88
318
284
318
284
488
111
488
381
1247
406
504
60
504
163
504
126
504
108
960
813
960
715
465
443
465
280
476
287
1071
1054
504
126
1130
908
1130
1011
1130
966
1130
1078
1130
871
1130
1059
777
681
777
561
777
667
777
745
136
9
136
27
491
179
491
377
1130
734
672
225
672
227
216
73
216
34
216
11
383
35
383
268
383
25
383
26
216
34
216
11
216
73
445
405
445
364
445
437
445
355
125
49
125
49
504
126
476
287
661
210
464
281
504
93
504
82
504
76
504
40
504
109
586
566
416
177
165
72
212
42
212
38
530
470
530
493
903
544
393
382
730
195
730
718
730
252
730
228
730
161
730
160
730
195
730
109
730
176
730
94
1338
594
660
337
660
403
660
324
660
22
660
302
660
567
1083
77
1083
204
1083
20
970
21
970
169
970
304
970
176
394
237
394
236
216
106
216
108
566
150
2024
371
1287
1115
1287
427
1012
97
567
68
302
203
215
106
215
108
660
376
224
156
224
71
224
138
302
194
979
943
979
209
313
205
125
49
345
335
390
11
390
8
603
209
583
563
586
566
577
557
920
309
357
45
1130
463
1130
1078
465
321
777
561
777
518
583
563
586
566
577
557
847
737
3142
12
3142
2
648
268
648
620
648
258
721
303
211
150
211
22
1051
554
416
388
921
803
486
405
178
172
1125
913
1307
594
1307
763
1307
710
1307
347
1307
576
211
150
211
22
211
23
541
519
126
35
1255
699
1255
230
1255
498
1255
620
1255
252
1255
659
1255
589
2345
78
846
745
1912
96
759
558
940
782
731
147
591
176
291
128
291
145
524
19
126
35
697
258
2097
306
2097
47
218
128
218
145
222
140
1095
125
105
28
1873
244
1814
1387
448
90
1335
721
1335
791
402
263
645
167
587
480
648
337
968
287
654
38
413
160
413
186
719
572
3
287
475
108
538
58
538
63
538
55
538
62
613
280
1106
1103
413
354
413
355
332
328
332
329
372
362
372
357
515
403
515
407
515
409
887
469
537
530
781
85
535
534
661
643
727
701
727
678
512
507
899
217
899
261
899
301
899
340
899
351
899
356
899
357
899
387
899
513
899
530
899
894
858
264
858
372
537
530
509
504
630
603
298
159
632
156
629
156
462
76
462
202
303
171
1970
1618
784
470
784
476
1970
1615
1970
1618
423
359
437
402
437
432
483
228
487
50
487
52
737
349
473
181
413
50
154
102
465
321
777
561
777
634
777
523
467
323
465
321
3142
12
3142
2
619
176
465
443
165
72
443
189
1001
439
464
441
207
71
1001
439
1240
474
672
549
672
553
390
36
390
33
209
85
1243
574
2986
486
184
129
748
725
184
129
211
31
211
51
211
129
211
143
487
176
487
386
487
182
652
208
314
35
314
31
126
14
126
14
126
14
126
14
126
14
126
14
126
14
126
14
126
14
126
14
126
14
216
11
216
34
211
22
211
23
211
143
211
42
211
44
1159
563
1159
648
1159
656
483
20
487
102
487
321
487
348
423
128
480
472
309
162
309
151
309
155
496
424
659
179
672
496
463
301
671
660
671
499
673
659
736
286
1203
1178
781
207
781
241
442
350
656
320
656
333
656
331
873
391
606
186
579
191
442
404
770
726
480
307
480
472
314
35
757
176
757
180
497
156
419
378
419
387
457
430
935
793
503
417
378
356
378
364
442
404
559
359
559
367
559
396
559
487
516
353
448
13
155
16
271
37
271
38
271
67
330
259
330
261
330
268
1274
553
1274
571
201
178
725
376
450
89
205
14
205
77
205
81
416
178
416
243
430
50
424
12
712
505
3
77
3
14
3
81
1051
554
390
17
1307
710
1255
699
1255
230
1255
659
2345
78
290
282
697
258
805
679
437
218
757
180
757
176
448
90
645
167
1106
200
1106
967
1106
203
1106
242
1106
1073
1106
1077
399
256
399
260
252
162
252
166
786
183
626
525
390
207
1335
720
172
19
454
298
454
264
454
305
454
310
454
49
370
317
1335
791
1335
854
1335
858
450
29
379
365
3
845
1198
471
1198
489
887
248
2357
845
921
818
921
803
921
242
921
245
921
799
1321
387
351
308
425
178
425
212
425
7
359
192
765
483
425
7
425
178
425
212
921
818
921
803
921
242
921
245
921
799
359
192
450
408
450
405
624
131
425
417
512
12
1257
858
450
92
450
89
857
803
196
64
827
734
495
303
495
310
574
318
574
369
473
292
473
299
158
148
236
69
168
77
168
80
289
33
289
216
737
349
384
202
384
252
384
314
325
23
325
28
606
246
477
64
477
45
766
789
592
264
197
9
234
184
295
287
295
285
588
239
197
169
197
196
327
118
327
132
779
321
1113
249
1113
487
653
275
653
294
269
62
776
90
776
91
776
92
776
293
742
642
1579
1149
586
9
513
209
766
613
766
372
168
74
168
117
168
98
168
133
393
221
393
217
463
20
400
225
400
221
857
280
857
435
462
87
462
20
815
652
305
67
3
372
1125
1045
1125
913
920
178
2441
300
374
176
385
179
469
195
390
179
390
265
390
280
136
9
136
27
136
28
136
10
466
71
466
72
466
64
466
24
466
65
466
38
466
6
466
46
466
86
880
859
469
11
469
16
469
59
136
10
136
9
140
116
232
209
430
6
430
11
430
34
721
91
757
138
628
387
628
410
366
305
366
313
642
54
580
30
1164
520
1164
599
3
10
3
28
3
10
3
28
452
383
390
22
489
340
489
366
760
373
514
122
514
270
514
283
1812
970
254
246
390
33
902
212
902
216
525
433
626
591
626
519
626
526
901
212
901
216
196
72
196
54
196
64
888
532
888
42
143
138
468
71
488
103
488
351
488
396
136
27
352
346
707
102
707
200
467
264
467
60
467
74
467
86
575
287
463
353
656
197
390
33
239
86
239
69
239
73
239
55
331
101
331
143
196
72
196
54
196
64
888
532
888
42
334
62
956
175
770
742
707
102
707
200
1305
254
1305
243
1305
233
390
17
390
388
390
14
159
77
159
140
1029
444
1029
471
1029
908
276
238
1129
462
390
17
390
14
390
20
487
54
576
183
89
1
89
2
89
3
570
183
390
20
89
1
89
2
89
3
570
183
797
569
327
118
507
180
665
387
665
210
652
23
652
315
1380
89
931
357
499
342
1853
1649
317
89

1255
589
2097
317
1091
454
1100
272
432
49
328
67
1016
196
557
98
313
304
269
85
375
152
466
71
469
16
469
75
469
76
309
151
1171
1069
1171
1060
1029
693
330
292
330
295
1337
314
1337
364
172
19
448
264
403
379
403
381
403
382
1333
829
430
6
430
11
430
34
580
159
140
137
647
507
695
654
638
504
1197
1173
375
234
459
300
5035
2843
1029
689
1029
692
883
716
366
105
323
110
653
19
552
171
559
182
559
182
374
176
385
179
458
181
1424
856
473
181
721
188
156
17
362
59
781
44
195
60
305
130
305
129
781
674
619
519
619
282
498
30
393
217
393
221
358
182
358
184
380
204
380
202
358
184
358
182
380
202
380
204
236
69
722
538
1023
15
1023
22
586
566
722
207
793
214
543
112
297
188
292
124
292
197
920
559
391
312
391
389
3343
3221
329
155
270
22
1163
15
858
594
600
108
600
110
380
186
439
61
923
398
425
7
425
178
425
212
543
112
920
812
543
112
938
203
918
915
875
872
875
710
938
177
692
170
512
226
793
59
1581
1463
938
177
873
296
873
391
419
172
959
483
1585
1155
776
185
1134
330
1134
331
1134
394
630
150
691
170
1077
244
1077
465
770
704
591
117
591
30
442
440
1430
295
1430
335
283
242
770
704
749
726
793
724
850
301
850
302
850
249
850
247
323
4
323
303
770
726
1029
693
172
19
172
18
172
19
448
264
203
76
166
14
166
14
770
726
259
233
259
62
259
235
259
245
259
60
259
54
259
240
770
726
393
221
393
217
393
291
1493
1392
1493
1380
770
726
525
411
525
52
525
393
525
397
525
402
770
726
3119
119
498
309
397
152
397
163
1307
992
459
177
459
188
527
297
1383
1033
480
307
480
472
716
27
716
669
716
312
716
91
716
92
716
30
716
365
716
504
716
275
716
151
439
401
314
35
757
176
757
180
507
421
379
365
323
309
436
339
436
349
317
303
317
287
317
280
310
291
522
214
499
382
211
79
1290
782
659
222
533
172
675
215
620
179
631
205
535
529
697
666
697
596
631
221
631
209
301
264
1302
782
220
208
220
217
220
190
330
44
1290
782
533
144
527
419
527
90
223
200
3
200
243
109
243
117
976
552
976
702
976
569
976
567
976
546
976
935
976
822
976
720
272
258
276
272
276
119
276
257
906
370
351
330
661
633
897
849
227
102
933
10
1210
1068
1210
1196
695
659
695
589
695
284
695
372
695
406
695
627
695
306
695
472
695
447
432
65
630
603
521
487
210
3
261
210
201
166
868
141
868
158
868
171
518
5
518
296
351
330
1089
1017
351
330
535
143
535
137
586
145
586
353
724
507
593
545
593
583
593
541
593
579
593
541
593
545
674
331
674
310
1098
855
630
577
630
592
756
438
756
438
670
438
3
137
3
137
659
222
594
66
675
215
675
223
154
80
154
110
154
122
620
179
460
280
460
388
460
302
460
353
155
81
631
205
631
518
288
214
3
66
3
214
758
578
666
501
692
170
692
274
692
306
758
213
1341
1179
688
493
681
484
433
225
1150
1047
1150
95
1150
990
2382
381
1095
100
1095
95
1002
57
1150
1047
1150
990
545
230
545
370
545
372
545
232
975
341
975
448
2382
381
2382
377
527
324
527
184
3
448
3
341
1555
119
1555
120
527
324
1205
204
1002
57
556
246
556
242
1021
49
1021
45
1021
54
1243
334
975
341
975
448
211
205
1002
47
556
381
3
448
3
341
364
179
364
181
360
179
360
181
367
184
367
182
347
217
347
221
360
179
360
181
366
181
366
179
365
179
365
181
364
179
364
181
360
179
360
181
360
179
360
181
334
206
334
218
367
184
367
182
681
565
681
563
492
470
360
179
360
181
366
181
366
179
365
179
365
181
644
321
644
612
465
64
581
401
581
256
581
227
3
64
3
65
618
155
465
64
307
11
233
61
462
395
757
110
757
441
355
249
128
64
156
64
229
64
685
64
739
191
1078
45
3
64
3
65
452
218
465
64
757
110
757
441
355
249
128
64
156
64
305
64
810
64
168
74
168
117
168
98
393
221
393
217
337
302
393
221
393
217
318
236
343
278
343
71
343
24
343
231
299
213
1032
696
393
221
393
217
400
221
400
225
740
528
801
640
209
14
209
85
1243
574
319
51
319
177
431
12
423
51
716
509
205
142
221
120
221
170
221
127
221
129
427
302
647
507
400
221
400
333
400
271
400
24
563
20
348
342
348
333
348
339
348
341
348
337
521
381
521
506
380
357
361
349
361
346
361
356
218
206
377
365
377
362
377
372
348
337
348
333
348
342
1083
34
686
292
960
170
960
168
640
630
1059
899
1919
1114
844
146
483
20
338
53
338
91
338
202
206
14
206
85
610
167
423
51
320
52
320
178
647
322
671
14
671
165
671
19
671
13
671
160
1189
727
327
118
745
175
899
864
899
868
656
165
742
621
1189
727
656
160
559
182
486
231
486
230
472
344
472
346
472
348
472
351
499
286
559
8
559
375
559
378
1233
459
1233
607
1233
627
1233
890
1233
934
1233
982
1233
1172
1233
1219
1321
623
1321
627
1321
535
1321
670
1321
910
1321
969
1321
1241
1321
1302
482
396
592
520
132
19
178
13
521
487
521
514
621
617
559
396
559
400
1380
844
1380
848
855
844
855
842
1189
727
347
344
706
537
476
2
1657
479
894
169
1233
306
898
187
898
314
297
3
315
51
515
413
545
353
545
370
2382
381
1417
337
524
87
524
81
524
78
136
9
136
28
136
10
3
10
3
28
3
10
3
28
276
170
774
227
136
3
136
3
3
3
3
3
136
3
136
3
415
369
435
242
435
49
435
241
102
93
102
6
102
50
102
72
102
8
102
78
102
70
102
84
499
97
499
141
497
31
497
34
497
43
497
45
497
46
497
47
497
31
497
47
497
45
497
43
497
46
497
34
487
432
802
753
802
642
802
641
928
794
928
806
928
810
420
8
1147
680
1147
806
1147
866
178
13
339
53
1191
917
1191
1020
379
203
673
310
845
159
845
173
845
141
619
492
619
491
164
122
164
71
164
141
164
152
164
82
164
110
905
221
727
678
727
701
223
217
223
200
358
184
674
310
1009
579
1009
578
618
313
509
504
509
393
521
487
521
514
864
715
864
735
625
516
707
89
269
241
269
260
670
266
670
426
505
23
559
182
474
436
474
199
474
195
374
176
413
354
413
355
407
238
407
356
398
369
398
374
398
375
398
378
372
360
372
362
369
352
369
355
369
353
369
358
359
353
359
352
380
368
352
336
352
341
352
335
352
348
369
340
369
342
370
362
370
345
370
350
370
361
413
354
413
355
590
483
590
484
418
411
134
117
733
553
576
371
957
44
451
130
451
130
646
641
733
553
545
422
496
11
646
641
733
553
366
46
366
114
1828
1679
793
59
733
493
1004
849
1004
694
292
183
292
258
292
174
292
169
292
179
1084
694
1084
694
1114
1061
1052
575
1052
576
1052
614
1052
613
1115
1015
1115
1062
1032
471
1032
911
391
14
391
389
277
239
533
526
541
534
533
526
536
529
781
85
781
653
902
220
902
264
902
304
902
343
902
354
902
359
902
360
902
390
902
516
902
533
902
897
688
670
858
264
858
372
512
507
1368
237
1368
342
1368
390
517
510
918
743
918
747
487
33
521
401
918
747
918
743
514
179
474
419
901
169
901
167
806
763
806
722
806
765
806
759
498
316
498
352
431
77
1109
47
1109
47
632
525
184
135
4969
2808
4969
2814
655
568
985
121
326
221
973
811
973
785
169
96
169
93
736
640
736
644
736
648
736
652
169
93
149
24
149
37
525
306
118
64
380
324
380
330
380
361
380
373
334
206
334
210
223
156
169
163
169
96
169
125
169
132
169
66
1291
770
1291
782
672
657
671
661
682
659
169
66
2225
455
381
325
381
331
381
362
381
374
2225
455
381
325
381
331
381
362
381
374
2225
1858
166
66
205
72
391
343
391
359
391
361
391
369
345
218
345
241
345
244
391
312
166
66
858
519
858
606
858
655
858
804
391
14
249
234
283
150
462
431
211
42
211
143
211
42
211
143
509
180
559
182
552
171
474
195
474
10
474
7
474
352
474
14
374
176
179
61
179
72
770
742
708
102
708
201
245
83
830
94
328
196
682
201
372
8
1715
748
724
82
4303
4165
496
434
215
42
452
342
215
42
2187
2014
164
71
428
416
852
347
577
395
572
31
781
141
572
503
789
636
789
637
789
653
789
603
1252
1203
1252
1152
1654
1652
1654
590
770
704
461
59
292
14
424
313
354
266
354
289
140
124
977
958
977
971
725
488
586
30
586
117
781
63
781
141
770
704
443
434
443
439
443
442
1499
1104
528
325
528
318
379
203
379
201
358
182
358
184
358
182
393
22
393
23
393
24
393
298
393
217
393
299
393
297
331
139
263
230
263
233
468
279
591
125
738
640
704
640
704
644
704
648
704
652
179
165
982
475
982
479
704
338
704
336
770
742
207
71
200
72
243
104
201
71
220
85
219
85
227
85
219
85
210
79
207
71
487
52
320
200
320
199
525
325
463
353
297
199
520
466
724
357
918
402
918
406
816
220
816
218
216
106
216
108
573
150
925
284
925
296
925
281
925
294
925
292
925
302
925
304
925
290
925
299
925
300
925
297
925
288
925
291
423
182
423
184
384
184
423
182
384
182
366
179
464
220
423
182
423
184
360
179
360
181
364
179
364
181
384
182
384
184
366
179
464
222
427
182
427
184
360
179
360
181
1380
844
1288
805
1374
837
544
421
646
641
496
11
544
83
1002
57
1363
1264
1363
1229
1363
1230
140
128
140
128
1356
950
1356
995
1356
1058
1356
1053
1356
1174
1356
1213
1356
1318
1356
1304
1356
1308
1363
1230
1363
1229
1363
1264
1363
1230
1363
1264
1363
1332
1363
1362
1363
1067
1363
1062
1363
1336
1363
1229
583
426
583
348
583
349
1363
1336
1363
1362
391
365
391
374
391
372
446
427
446
430
578
418
578
9
578
138
578
429
578
425
578
248
578
243
578
484
578
255
303
14
303
14
855
740
855
735
855
739
594
475
594
149
535
423
1147
307
591
30
1009
401
757
187
757
198
687
45
687
303
729
178
710
176
292
14
986
601
986
595
986
778
1290
770
1290
782
672
657
671
661
457
71
457
83
457
95
457
177
457
188
697
674
525
127
241
233
1290
1252
1290
782
821
514
821
700
821
704
821
705
821
815
1115
733
858
743
1290
782
282
256
1290
782
546
420
546
465
674
331
674
310
541
423
541
31
398
375
398
369
398
374
398
378
398
375
398
369
398
374
398
378
380
368
380
356
380
355
793
596
793
641
793
598
793
559
793
593
793
643
793
647
586
566
710
65
913
358
1020
652
1064
662
530
500
166
2
166
2
165
2
166
2
166
2
166
2
165
2
166
2
166
2
166
2
166
2
166
2
166
2
165
2
166
2
628
214
567
423
567
408
567
335
567
212
567
258
567
415
503
184
503
188
503
186
503
190
503
185
503
199
658
634
658
633
605
206
605
224
1055
396
501
252
968
262
968
761
968
763
892
11
535
186
535
340
509
383
509
428
1055
576
1115
1062
1115
1096
1115
905
1115
1015
1499
1104
763
34
1182
438
1182
271
1182
567
1182
683
1098
684
1098
932
1098
968
248
152
175
33
505
255
193
25
464
441
465
443
1675
605
680
45
680
280
1591
828
821
514
821
700
821
815
821
705
821
704
492
416
492
454
418
411
368
344
137
117
390
300
436
242
993
954
993
725
993
968
993
590
993
841
993
598
993
588
993
596
993
571
1002
593
1002
600
414
390
339
23
198
73
198
87
885
755
885
756
885
757
162
18
191
63
892
888
674
309
674
331
565
553
582
398
492
147
492
176
970
321
970
82
261
63
261
65
471
365
469
359
166
2
480
175
501
238
501
252
899
261
899
357
414
286
130
119
1085
588
1085
562
1085
509
1085
666
1085
678
1085
172
1085
968
1085
959
1085
453
1085
147
1085
551
1085
212
1085
510
1085
617
1085
175
1085
751
1085
524
1085
197
1085
418
328
18
499
71
499
40
499
160
499
156
499
152
499
91
89
3
788
207
795
214
244
209
244
217
244
239
1084
174
469
111
469
145
469
362
710
208
360
179
360
181
364
179
364
181
626
525
295
287
366
179
360
179
360
181
364
179
364
181
366
179
360
322
364
322
242
135
242
194
242
234
242
174
185
37
185
137
1147
307
591
30
1009
401
451
446
457
53
488
379
154
80
630
517
370
20
370
130
370
91
292
3
646
51
423
122
1280
178
759
725
759
734
638
94
410
72
462
433
664
124
664
203
172
45
172
63
1443
430
435
242
435
49
435
241
1130
734
401
221
401
287
401
201
401
265
401
290
401
47
401
203
401
61
437
225
951
242
393
291
393
285
393
217
393
221
393
297
334
1
334
7
334
88
334
92
334
288
226
177
226
205
227
206
648
337
648
338
918
202
720
188
413
21
413
26
393
217
393
221
318
155
358
184
358
182
380
202
380
204
545
83
1970
1615
902
60
372
346
372
349
372
352
372
353
372
356
372
361
372
362
334
62
334
72
391
19
233
48
525
513
525
519
825
574
825
656
724
717
473
79

887
248
472
299
472
383
472
349
472
463
630
214
985
142
985
894
540
173
540
175
540
177
540
180
540
473
540
179
504
452
504
428
512
507
601
380
601
448
654
358
654
378
654
354
654
340
654
351
658
639
658
653
658
648
658
645
658
645
658
648
658
653
658
639
1130
734
409
138
309
151
309
162
309
155
175
44
175
58
681
270
681
233
1380
844
801
276
488
381
488
111
465
280
959
634
645
306
677
513
428
239
1033
131
210
208
977
735
977
594
977
772
1033
724
465
321
52
50
315
51
315
48
315
51
52
47
315
51
315
48
1114
560
1114
614
315
51
1114
979
315
51
315
48
315
51
976
771
976
920
976
959
976
574
976
693
976
587
976
593
976
627
976
734
209
207
543
425
168
162
366
46
692
170
692
170
1113
249
1113
487
619
161
619
369
619
61
619
328
509
495
1076
244
1076
464
1134
330
1134
331
1134
394
747
140
747
135
102
50
102
8
486
215
486
79
711
547
770
756
304
220
968
346
434
240
292
14
875
438
875
717
774
34
469
372
1097
684
1097
932
1097
968
178
13
317
51
301
155
733
126
1004
370
422
385
422
201
527
324
527
184
1004
370
1222
1195
556
242
556
382
752
512
3142
2
166
23
908
360
505
241
505
255
480
175
304
220
1373
1167
1373
1351
1373
1166
1373
973
1373
1162
1373
980
395
88
488
148
488
381
488
111
1126
175
395
88
395
305
488
148
488
381
1531
157
360
330
360
320
360
333
457
352
205
128
136
28
708
102
708
201
467
60
467
74
467
86
467
264
469
135
469
332
469
377
1247
443
1233
443
1053
396
559
117
893
12
757
591
757
391
757
285
217
208
217
208
748
725
268
165
347
217
390
207
619
328
619
161
619
369
619
61
267
60
267
47
464
64
739
191
3
64
757
110
757
441
355
249
128
64
156
64
305
64
734
64
424
416
424
63
424
71
372
185
454
272
454
285
454
298
454
295
454
264
454
290
454
268
346
159
530
524
1302
782
281
255
625
185
223
200
1302
782
527
90
527
419
920
817
425
7
425
178
425
212
920
603
136
11
490
367
525
75
525
123
525
177
525
282
525
295
525
507
920
603
391
19
1817
974
759
374
490
341
490
367
525
123
525
282
525
295
920
802
517
496
642
164
2414
2388
2414
2392
1356
614
1356
615
670
660
360
322
292
183
292
174
244
209
244
217
244
239
436
424
1235
180
1337
961
391
312
1817
305
561
170
574
348
603
209
262
108
262
123
171
18
171
19
577
557
172
19
648
337
648
338
562
466
172
18
172
19
172
19
448
116
163
70
249
234
249
235
288
187
284
282
172
19
172
19
770
726
171
17
171
18
380
202
380
204
358
182
358
184
380
202
380
204
1302
770
1302
782
525
411
744
568
359
160
774
34
1097
684
1097
932
1097
968
1499
1104
177
33
397
258
397
254
577
557
586
145
756
438
1097
1019
1097
577
1097
749
1097
714
593
541
593
579
205
136
559
503
559
531
938
281
378
329
553
317
346
20
1291
471
1291
770
1291
1253
1291
782
617
412
580
555
210
3
261
210
202
167
1134
1112
147
37
946
576
946
503
946
63
946
376
946
578
946
533
946
777
946
611
418
131
519
487
519
512
1009
578
1009
579
864
716
864
736
707
89
519
487
432
65
688
634
346
20
1209
1195
210
3
261
210
1234
536
391
8
391
17
89
1
89
2
89
3
391
38
206
85
184
129
286
56
286
112
1482
1069
403
335
512
393
348
342
348
339
348
342
561
4
561
7
561
488
561
487
561
20
242
40
78
35
320
191
320
309
320
310
320
311
217
208
1072
886
297
169
297
174
297
179
297
183
297
258
466
38
466
71
577
557
172
18
172
19
583
563
1388
413
480
175
902
264
902
360
501
238
501
252
147
37
147
56
212
42
212
38
444
383
426
173
530
493
530
470
217
208
699
7
699
274
320
191
320
309
320
310
320
311
136
10
136
10
136
3
136
3
499
97
499
140
499
98
432
49
432
241
432
242
172
18
1002
600
1002
593
1002
795
1002
611
1002
617
1002
610
1002
617
1002
611
1002
610
1002
795
512
12
172
18
172
19
172
19
393
291
1493
1392
1493
1380
1291
782
1291
782
1265
1216
1265
758
1265
1196
1265
752
979
247
979
378
979
483
1124
991
1124
1107
1124
1047
1124
1101
1124
1112
1124
859
972
808
972
560
972
698
972
545
972
922
972
722
972
707
972
968
1308
1055
1308
1257
1308
1201
1308
1241
1308
1034
1308
1187
1308
1149
1308
1283
1308
874
1308
1161
467
464
467
466
425
421
425
422
425
424
462
299
653
640
653
643
393
217
393
23
393
221
393
71
393
221
393
217
301
215
393
385
393
291
390
340
390
384
345
218
345
244
930
292
591
249
744
568
1893
101
1893
139
1392
35
1392
1224
1392
190
1392
12
1392
1317
1392
1383
1392
1098
1392
458
1392
1189
1392
1187
1392
26
207
71
1025
827
121
66
112
61
651
101
435
155
423
143
435
155
435
155
506
164
258
104
362
87
362
91
362
91
362
87
370
98
202
197
204
191
998
613
436
424
167
156
977
627
1616
918
1616
183
1616
177
1616
907
1616
187
1608
1493
31
4
305
196
305
197
305
184
367
100
367
99
1338
1326
1338
1168
1338
1212
1338
1332
1338
1241
3
1212
3
1241
3
1332
3
1326
3
1308
3
1168
926
150
926
154
442
423
442
427
442
424
552
433
696
272
696
383
696
477
798
89
798
611
798
661
622
41
424
53
730
257
1185
282
622
41
424
53
271
261
1379
1231
1379
1227
1379
1232
695
659
695
589
695
284
695
372
695
406
695
627
695
306
695
472
695
447
852
751
346
20
207
2
339
23
1388
721
162
18
162
26
191
63
877
873
380
9
380
29
858
127
664
214
297
159
302
160
933
164
933
469
933
10
933
13
486
221
664
603
500
467
684
408
111
101
111
100
111
109
581
387
179
158
552
401
552
400
552
396
552
393
370
117
370
119
519
387
519
377
500
44
500
143
500
182
500
292
500
318
500
394
2057
2020
2057
2021
1426
901
846
27
846
74
846
102
846
168
983
778
983
601
983
595
983
700
1005
838
1005
615
984
593
980
514
980
455
980
273
980
498
980
674
980
473
980
649
980
825
980
624
980
424
980
606
980
665
1126
481
696
366
696
609
2224
111
2224
482
2224
1603
2224
1608
2224
1642
2224
1645
2224
1654
2224
1680
2224
1767
2224
1904
684
328
684
529
684
353
684
310
684
128
684
369
980
514
980
455
980
273
980
498
980
674
980
473
1126
481
334
311
334
330
334
316
1004
613
1004
619
986
609
986
603
986
601
986
595
849
360
202
179
202
191
977
973
977
720
977
920
977
806
977
705
977
696
977
558
524
401
524
191
524
196
524
140
524
18
524
19
524
54
524
164
756
381
846
307
846
314
846
274
407
289
407
348
407
290
407
290
407
289
407
348
521
294
521
503
521
119
521
136
521
189
521
294
521
136
521
189
517
354
517
358
1321
550
1321
468
1321
492
1321
410
512
507
986
927
986
778
986
601
986
595
292
14
1004
837
1004
614
1345
1211
1345
948
1345
1056
1345
1051
1363
1229
1363
1264
1363
1230
1122
1099
1122
1105
422
201
422
385
1222
331
2126
377
2126
381
422
201
739
668
1084
715
1084
848
1084
694
1084
694
1084
715
1084
848
1084
494
1084
694
1084
708
1084
494
1084
708
1084
694
1084
694
1084
694
679
671
679
522
679
522
679
671
407
238
407
301
407
238
407
301
472
91
468
185
407
338
623
393
407
238
407
338
393
326
1140
424
3
283
971
528
971
527
843
55
530
286
530
306
530
305
1174
786
1201
571
1201
930
1201
571
1201
930
691
377
732
126
691
377
732
126
222
66
222
65
174
21
401
365
401
365
786
676
1397
883
1397
851
1397
887
1847
1517
1847
923
613
43
613
189
613
258
1022
672
1022
709
1847
923
1847
1517
438
117
438
126
565
55
565
55
623
163
623
429
515
53
148
2
474
142
474
142
366
167
395
167
136
28
136
10
136
28
136
10
136
10
136
28
142
19
136
3
136
3
136
3
136
3
136
11
477
219
491
367
525
74
525
122
525
176
525
278
525
292
525
507
339
308
325
116
745
554
544
20
243
69
277
27
1091
454
1611
142
624
23
624
225
624
288
740
22
648
258
154
134
382
235
487
386
1165
231
1165
501
1165
623
1125
230
324
101
325
116
624
23
624
225
624
291
509
273
360
28
384
327
384
329
384
331
384
345
384
355
325
116
149
44
325
116
1091
454
624
23
325
254
781
32
781
36
270
196
359
52
1292
1171
1292
1058
1292
1017
468
324
468
324
468
324
465
54
396
14
396
32
396
46
465
38
465
70
465
54
396
317
429
121
469
6
469
27
469
31
420
63
420
197
158
70
465
70
396
185
396
271
396
286
469
11
469
16
469
59
626
16
626
20
676
648
676
650
210
3
676
645
676
650
676
650
199
22
381
9
381
29
551
156
70
51
70
51
70
51
304
224
331
238
331
242
331
248
933
444
933
448
933
452
933
456
933
620
933
624
933
628
933
632
1046
2
1046
3
425
203
439
57
439
61
331
1
331
7
331
88
331
92
331
285
103
47
331
62
331
72
331
62
331
72
386
19
233
48
502
216
502
223
331
242
386
46
770
726
439
61
933
809
933
856
933
863
933
890
961
652
149
24
149
37
380
324
380
330
380
361
380
373
589
144
589
412
589
470
933
809
933
856
933
863
933
890
961
652
149
24
149
37
380
324
380
330
380
361
380
373
589
144
589
412
589
470
737
640
737
644
737
648
737
652
625
16
625
20
846
426
572
513
215
158
737
640
572
521
737
640
462
431
164
113
350
158
164
144
198
156
198
197
164
144
198
156
198
186
198
197
164
144
439
328
164
145
386
14
386
384
350
158
736
640
736
644
736
648
736
652
613
54
613
58
348
226
348
231
781
22
781
28
781
32
781
36
781
40
580
553
572
513
823
550
823
554
823
588
525
302
640
550
335
242
335
246
335
252
215
158
736
640
1125
449
439
61
572
521
335
246
770
726
118
64
118
100
736
640
462
431
249
234
249
235
155
76
770
756
434
240
1000
591
488
381
488
111
488
111
488
93
899
60
372
346
372
349
372
352
372
353
372
356
372
361
372
362
1082
768
1082
777
152
119
366
94
622
597
622
598
544
83
243
208
235
208
419
30
419
42
419
375
243
5
243
220
580
550
383
368
624
298
345
304
740
175
648
28
648
42
648
288
648
295
648
300
648
641
149
24
149
37
118
64
380
324
380
330
380
361
380
373
223
156
608
222
606
330
324
226
648
337
648
338
335
1
335
7
335
88
335
92
335
289
103
47
420
26
648
337
1847
923
1847
1517
879
874
879
859
879
74
879
596
879
597
879
872
879
511
879
551
951
482
951
486
951
490
709
205
1338
1178
432
49
432
241
432
242
249
234
249
235
432
49
432
241
432
242
432
49
432
241
432
242
491
179
216
73
648
337
370
368
699
284
546
67
546
76
599
378
599
446
386
307
961
859
386
14
386
32
386
46
466
55
137
73
770
742
770
742
858
519
858
606
858
655
858
804
507
407
463
385
1205
115
391
14
391
32
391
45
386
14
386
384
386
17
391
17
386
17
386
19
502
244
254
246
386
32
461
202
386
36
207
79
207
83
386
46
386
46
382
367
386
307
961
934
142
33
471
6
471
27
471
31
466
55
149
24
149
37
233
61
662
255
502
39
502
59
502
114
502
193
502
242
121
96
205
193
243
220
444
171
445
171
386
307
386
384
425
7
425
178
425
212
595
103
595
105
439
61
982
630
778
214
1085
1010
514
235
230
61
230
57
462
378
462
410
462
235
462
254
462
139
462
205
462
343
462
170
462
288
462
194
462
256
462
70
462
239
462
220
462
112
462
102
462
436
462
398
882
278
882
550
882
292
882
299
882
555
882
589
337
98
337
59
337
73
337
86
337
153
500
49
408
332
327
315
1324
18
568
137
568
209
568
247
568
137
568
209
568
247
352
169
651
72
651
238
651
251
651
42
651
156
651
96
651
266
651
212
651
544
651
550
651
640
1067
936
856
804
856
805
359
2
802
143
548
409
548
413
548
443
548
477
610
103
598
339
160
42
160
42
157
46
157
46
1364
1313
1364
1347
1364
1352
887
220
887
243
887
362
887
464
887
653
887
676
887
747
1067
936
609
102
254
59
595
185
1849
307
386
307
602
207
1849
981
386
19
477
219
491
341
491
367
525
122
525
278
525
292
386
17
89
1
89
2
89
3
386
14
386
384
293
256
386
17
89
1
89
2
89
3
386
19
477
191
477
198
823
575
823
653
335
62
335
72
724
717
525
513
525
519
386
32
461
202
386
36
201
73
201
77
184
129
961
859
172
19
961
869
574
369
451
130
646
641
574
165
574
318
559
356
142
33
401
123
401
124
401
125
140
33
142
19
142
33
471
16
471
76
172
19
142
33
288
87
288
93
367
182
367
184
366
179
366
181
367
182
367
184
366
179
366
181
395
47
395
70
395
205
395
235
395
236
395
241
395
359
395
361
395
367
605
270
605
282
605
285
605
303
605
329
605
388
605
447
605
461
605
465
605
532
1173
868
1173
905
1173
960
1173
1114
395
88
395
89

395
119
395
128
313
217
132
121
261
186
261
188
172
119
188
76
191
77
770
121
770
435
770
112
770
136
335
237
335
242
335
241
361
51
572
373
572
543
566
174
566
262
819
35
819
101
819
110
819
117
819
130
819
155
819
168
819
224
819
253
819
279
819
378
819
394
819
437
819
609
819
628
819
687
819
44
819
311
819
195
819
110
819
675
819
384
819
35
819
123
819
427
819
372
819
135
819
200
819
283
819
120
819
383
819
265
819
132
819
366
819
261
819
322
819
378
819
126
819
73
819
293
819
684
819
448
819
62
819
609
819
69
819
214
819
104
819
55
819
117
819
101
819
428
819
60
819
253
819
262
819
663
819
691
819
344
819
183
361
1
361
13
361
16
361
20
361
41
361
49
361
51
361
54
361
73
361
90
361
114
361
128
361
138
361
176
361
190
361
191
361
267
1522
16
1522
236
1522
3
910
674
910
889
314
29
314
270
821
773
821
174
821
374
284
44
284
32
284
47
284
68
284
75
284
4
284
79
819
110
819
135
819
311
819
378
819
394
819
437
819
687
1270
356
904
39
904
52
295
244
427
126
659
381
659
425
659
635
294
3
525
414
408
71
888
526
683
124
683
203
727
386
332
274
332
326
172
45
172
63
1493
429
477
219
451
130
451
130
477
219
492
303
492
310
441
292
441
299
168
77
168
80
384
202
384
252
384
314
154
102
294
3
140
128
724
717
815
360
817
361
402
393
313
43
313
50
313
66
313
96
751
583
402
394
344
162
344
162
344
168
467
464
467
466
462
299
297
160
346
159
297
14
346
14
297
14
142
33
190
185
615
70
615
85
685
77
685
171
685
213
685
283
685
286
685
376
345
218
345
241
345
244
370
139
270
28
243
220
444
171
142
19
142
33
142
116
280
164
432
6
432
12
432
37
685
393
685
394
685
396
685
476
685
580
685
591
345
218
345
244
802
359
802
580
802
699
1581
1030
1581
1456
601
222
648
28
648
42
648
288
648
295
648
300
648
641
270
22
858
594
243
5
243
220
361
13
361
16
361
49
361
52
361
73
361
85
361
87
361
90
361
128
361
133
361
134
361
138
361
152
361
173
944
59
944
63
944
67
253
239
292
199
343
19
343
256
343
264
343
291
295
198
367
4
367
259
691
99
803
169
803
742
803
168
803
546
803
714
803
266
284
4
482
298
482
320
482
378
281
164
229
117
705
654
705
667
624
450
624
454
279
38
279
42
312
99
312
113
312
127
312
151
312
222
293
233
293
266
1770
1074
3
164
744
568
858
264
858
372
781
85
781
653
537
530
580
555
439
328
198
186
858
594
393
314
393
391
198
197
1111
249
1111
488
198
9
198
73
198
87
381
9
381
29
198
87
198
186
393
314
429
121
4473
4327
444
171
448
37
198
197
393
8
393
14
393
32
393
46
1511
884
448
37
393
14
393
391
393
17
393
19
393
19
393
32
393
36
393
46
393
182
393
268
393
283
448
53
718
91
393
314
595
102
595
104
396
317
396
394
396
46
283
267
396
8
396
14
396
394
396
17
396
17
396
19
396
19
420
218
420
225
396
32
396
36
396
46
396
46
396
317
568
273
269
62
439
328
117
27
117
98
117
27
117
98
352
169
352
175
125
27
125
98
316
152
548
477
548
409
548
413
548
443
610
218
610
212
117
66
117
66
125
66
298
159
298
159
297
160
303
171
436
122
436
128
462
202
298
14
297
14
425
7
425
178
425
212
425
421
425
422
425
424
653
640
653
643
781
141
572
31
292
14
140
124
979
960
979
973
781
63
781
141
770
704
787
698
492
303
492
310
492
346
441
292
441
299
441
386
431
77
1257
1223
1257
1140
1257
1197
1257
1222
1257
1249
699
694
464
220
411
182
423
182
366
179
366
181
464
222
411
184
423
184
366
179
366
181
296
161
297
13
297
14
372
346
372
349
372
352
372
353
372
356
372
361
372
362
372
185
1208
814
1208
821
1079
766
1079
775
1084
772
1084
781
372
185
372
185
474
65
364
185
364
176
364
185
364
192
364
210
364
213
364
218
364
176
364
185
364
192
364
210
364
213
364
218
262
88
262
144
262
167
262
234
262
245
1014
44
576
332
595
352
594
351
577
333
576
332
595
352
594
351
577
333
594
351
577
333
997
548
139
5
744
219
744
302
431
109
513
243
513
244
513
249
514
77
514
80
514
86
226
215
948
930
226
215
213
200
213
200
590
100
256
246
1270
356
717
285
717
280
717
284
131
10
863
707
248
69
248
111
248
192
248
213
512
507
160
1
448
13
770
704
678
659
770
704
864
716
864
736
770
726
397
152
397
163
104
55
104
57
104
59
722
355
722
357
520
263
465
321
465
321
465
321
465
321
739
688
739
713
770
704
315
48
619
482
619
484
781
32
781
36
107
35
107
52
107
77
781
85
907
227
907
271
907
309
907
348
907
359
907
364
907
365
907
395
907
521
907
538
907
902
539
532
781
141
342
283
342
309
342
333
781
190
781
245
1205
115
381
14
381
32
403
335
403
365
403
369
381
19
403
379
403
381
403
382
469
16
469
75
384
159
210
3
283
242
983
595
983
601
983
778
1260
1231
1260
1231
465
280
351
340
626
16
626
20
737
640
737
644
737
648
737
652
737
640
737
644
737
648
737
652
737
640
393
45
439
61
737
640
773
106
434
135
434
240
434
241
729
682
729
559
729
583
729
672
729
560
729
636
729
607
434
240
721
102
482
298
482
320
482
378
292
14
178
13
1176
709
1176
835
1176
895
317
51
339
53
302
156
292
14
140
124
140
128
292
14
284
282
366
299
736
564
672
496
671
499
697
513
591
408
525
251
431
255
382
367
382
367
525
120
381
178
201
14
201
73
201
77
422
12
324
57
324
183
638
556
525
229
525
326
381
107
297
199
525
358
335
62
335
72
381
67
229
61
229
62
229
76
347
101
198
119
198
147
198
181
374
157
215
42
1001
741
1001
746
344
55
344
55
512
174
512
175
512
174
512
175
348
337
348
333
133
116
123
119
354
337
354
338
354
343
354
350
396
377
396
379
349
320
349
321
349
326
349
335
469
6
469
27
469
31
243
220
198
186
986
959
142
33
883
744
381
302
469
11
469
16
469
59
142
116
381
169
381
256
381
271
216
73
1129
907
1129
1077
443
355
443
435
795
214
776
207
1108
537
1108
529
1108
532
1108
531
1108
537
1108
529
1108
532
1108
531
112
61
121
66
112
61
117
66
124
73
112
61
121
66
117
66
125
66
117
27
117
98
125
27
125
98
846
450
846
460
1104
323
494
397
473
395
591
243
365
144
572
31
140
124
572
554
737
444
737
479
172
18
172
19
215
42
136
3
283
150
393
8
393
45
382
367
902
861
393
14
393
32
393
45
770
742
555
490
466
55
393
14
393
391
393
17
393
17
393
19
724
717
393
36
393
45
491
41
491
108
491
132
393
45
393
54
410
403
393
314
393
314
746
344
347
218
347
241
347
244
149
24
149
37
445
171
450
171
444
171
466
55
632
41
632
53
632
454
632
290
1518
1219
1053
99
1053
101
1053
104
1053
125
1053
261
1053
277
1053
279
1053
280
1053
324
1053
405
1053
409
1053
414
1053
416
1053
433
1053
612
1053
613
1053
615
1053
668
1053
674
1053
677
1053
679
1053
697
1053
698
1053
699
1053
712
1053
715
1053
717
1053
719
1053
720
1053
723
1053
759
1053
763
1053
768
1053
927
1053
1009
1053
1014
1053
1044
1053
1046
1053
1050
1053
1051
817
616
817
693
318
35
318
39
968
410
968
910
968
947
559
396
559
400
996
534
885
256
885
363
885
380
885
581
885
619
885
671
885
833
885
865
1088
459
1088
566
1088
583
1088
784
1088
822
1088
874
1088
1036
1088
1068
770
726
770
726
770
726
527
411
718
208
718
65
581
561
223
200
757
726
858
804
507
311
507
318
463
282
463
289
502
244
608
160
608
160
608
234
206
14
206
85
423
51
211
41
211
43
842
504
842
803
211
21
211
22
211
150
807
789
807
792
827
164
940
261
850
281
1002
286
4293
4155
495
435
351
197
346
41
875
243
1293
120
1293
121
1293
125
335
191
486
96
486
96
262
108
262
123
603
496
287
76
287
78
287
86
978
247
978
376
978
481
314
28
314
293
314
299
396
260
407
259
466
97
466
177
466
181
196
151
195
150
623
562
430
69
430
165
284
236
306
161
3
824
348
178
404
178
1059
354
1059
354
428
122
482
451
756
176
756
180
356
16
1402
987
301
206
301
210
301
215
301
296
487
102
487
321
487
348
487
33
523
403
523
404
382
367
243
5
243
220
238
189
842
803
383
368
337
177
396
236
396
240
610
167
524
360
569
386
436
247
800
422
800
447
800
462
552
90
552
102
552
114
552
193
552
204
552
248
657
548
657
178
657
548
630
11
1104
303
1104
311
1104
307
465
321
465
321
623
156
623
158
213
14
213
89
381
178
201
14
201
73
201
77
422
12
381
107
96
45
994
866
401
234
401
250
401
253
345
240
345
256
369
167
369
167
594
401
473
181
473
181
469
111
469
145
469
362
737
349
363
189
363
191
633
533
366
179
366
181
366
179
366
181
366
179
366
181
366
179
366
181
361
180
361
182
348
180
348
182
638
504
868
811
868
753
868
575
868
754
868
552
175
21
175
22
1613
183
1613
176
1613
331
1613
312
1305
177
1305
170
1305
917
1305
886
1305
1245
747
571
296
205
770
726
770
704
740
691
740
714
770
704
787
698
770
726
770
726
770
726
172
19
770
726
313
205
302
194
436
228
516
342
516
385
769
727
766
724
790
256
790
46
790
356
1129
462
626
242
716
616
716
621
716
657
716
659
716
676
716
684
465
289
471
295
421
234
491
210
198
156
198
197
198
9
198
73
198
87
162
18
162
26
381
9
381
29
198
87
198
186
142
33
3372
3235
198
186
3372
3235
595
103
595
105
439
61
386
384
262
65
262
67
472
366
582
398
824
569
680
503
680
661
525
320
824
569
525
320
677
500
1151
982
155
76
155
35
162
21
491
361
491
436
155
76
514
136
514
173
163
44
155
35
514
136
514
140
514
173
514
289
162
21
491
361
491
436
154
38
162
21
158
20
491
436
132
35
158
19
162
20
162
20
653
53
653
80
653
298
653
389
653
505
653
519
653
567
158
1
217
197
217
204
405
335
217
197
217
204
218
34
472
36
605
268
605
268
651
194
651
643
651
194
392
40
392
52
572
305
724
717
140
128
724
717
218
109
218
111
569
150
216
106
216
108
454
394
454
414
872
415
872
449
872
489
437
387
437
412
437
375
541
31
541
423
541
423
541
31
259
250
335
82
1025
827
478
200
467
89
467
423
467
412
577
557
577
557
172
18
172
19
172
18
172
19
172
19
448
116
284
282
172
19
1378
1174
1378
1293
1378
1264
2340
2266
360
184
360
186
360
184
360
186
394
327
394
329
394
331
394
345
394
355
193
187
193
187
979
392
979
764
506
49
633
209
556
58
556
85
556
112
556
119
107
68
107
7
107
9
107
55
51
8
51
42
431
207
881
698
372
347
372
361
372
9
372
11
372
332
372
350
372
327
515
362
367
99
426
173
514
381
465
280
487
182
487
386
487
182
487
386
492
209
265
39
265
39
266
40
510
450
317
17
669
194
503
184
503
185
503
186
503
188
503
190
503
164
503
184
503
185
503
186
503
188
503
190
501
182
501
183
501
184
501
186
501
188
204
191
204
165
202
197
592
287
592
287
585
280
585
280
289
93
880
755
880
722
1343
1170
348
334
348
337
348
333
348
342
348
335
348
334
348
342
348
333
348
337
348
335
614
54
614
58
614
274
154
55
382
303
302
14
302
14
302
14
302
14
302
160
605
472
605
468
350
65
433
96
807
529
1197
584
1067
542
1067
1045
1067
1045
548
65
548
75
168
80
168
78
168
81
168
82
168
79
168
83
157
148
639
633
639
637
251
247
1224
656
295
195
395
217
395
221
446
303
446
307
295
269
295
250
295
288
699
198
580
578
852
7
323
204
323
3
323
189
598
9
593
64
593
16
591
514
591
461
591
1
591
321
337
17
648
213
648
319
648
312
648
289
648
164
648
162
648
166
648
161
258
107
282
127
379
36
379
375
432
191
487
182
487
182
487
386
487
182
487
182
5495
2799
5495
4949
535
286
535
290
343
20
340
26
1025
15
537
11
136
6
136
11
136
6
136
11
136
6
136
11
346
20
346
20
346
20
210
3
346
20
270
62
280
87
280
93
280
168
280
229
198
156
198
197
198
9
198
87
198
156
198
186
198
197
462
95
1123
226
198
156
198
197
198
186
439
61
381
302
381
379
939
403
981
629
178
156
178
9
178
73
178
87
178
87
178
156
178
156
353
324
353
325
353
330
353
339
367
348
367
350
1292
674
537
530
896
214
896
258
896
298
896
337
896
348
896
353

896
354
896
384
896
510
896
527
896
891
257
67
210
3
136
3
136
3
136
6
136
11
136
6
136
11
136
3
136
3
136
3
1111
249
1111
488
1133
330
1133
331
1133
395
1122
258
1122
497
1122
258
1122
497
1122
258
1122
497
393
8
393
14
393
32
393
45
393
14
393
391
393
17
393
19
1863
986
393
19
393
32
393
36
393
45
393
45
393
54
393
182
393
268
393
283
393
314
1863
306
393
314
444
171
393
314
393
391
439
61
261
210
52
15
52
15
844
14
317
303
698
538
154
38
154
82
154
38
154
71
297
169
297
174
297
179
297
183
297
258
154
55
382
14
382
32
154
71
382
170
382
257
382
272
500
31
500
34
500
43
500
45
500
46
500
47
770
742
770
756
770
742
770
756
317
51
770
742
318
232
466
55
770
742
770
756
178
13
770
742
770
756
178
13
317
51
330
260
330
262
330
269
480
317
330
260
330
262
330
269
385
280
385
288
385
132
552
171
554
177
552
171
554
354
554
362
554
391
554
480
554
482
517
354
440
402
481
308
402
73
972
945
766
106
907
66
907
271
907
365
912
68
912
232
912
276
912
314
912
353
912
364
912
369
912
370
912
400
912
526
912
543
912
907
912
276
912
370
895
64
895
251
895
347
895
64
895
207
895
251
895
291
895
330
895
341
895
346
895
347
895
377
895
509
895
526
895
890
895
251
895
347
911
80
911
221
911
265
911
305
911
344
911
355
911
360
911
361
911
391
911
525
911
542
911
906
911
265
911
361
896
64
896
258
896
354
709
75
709
171
339
23
882
752
882
753
882
754
162
18
162
26
596
264
596
279
596
333
648
339
648
340
664
214
339
23
162
18
162
26
318
232
318
232
986
142
986
895
986
678
939
302
986
678
593
564
986
885
986
885
1878
304
381
302
204
191
202
197
292
199
292
249
483
50
474
317
1186
734
89
1
89
2
89
3
89
1
89
2
89
3
236
68
236
69
236
83
236
68
236
69
236
83
450
118
172
19
288
187
1184
1005
160
42
156
45
890
751
1067
936
142
19
142
33
142
19
142
33
391
312
142
33
142
116
391
180
391
266
391
281
142
19
142
33
142
116
386
261
386
276
365
201
365
215
365
218
372
345
372
347
367
348
367
350
1878
986
381
19
1863
987
1863
307
1863
987
3372
3330
3372
3330
386
19
1000
196
149
44
149
44
592
563
802
359
802
580
802
699
1581
1030
1581
1456
178
13
178
13
178
13
178
13
178
13
178
13
179
13
178
13
178
13
178
13
178
13
178
13
178
13
178
13
178
13
438
96
438
156
162
18
162
26
162
18
162
26
162
18
162
26
162
18
162
26
249
192
162
18
162
26
162
18
162
26
162
18
162
26
162
18
162
26
162
18
162
26
249
192
162
18
162
26
162
18
895
891
858
127
162
18
162
26
162
18
162
26
429
128
429
128
320
4
320
303
323
4
323
4
323
303
191
63
664
214
297
3
297
13
297
14
298
14
297
14
302
14
303
14
297
13
297
14
297
14
298
159
298
14
298
14
328
219
1338
589
1338
595
140
128
476
279
209
207
875
450
875
460
356
178
176
163
176
168
176
173
297
169
297
174
297
179
297
183
297
258
693
273
637
144
223
200
223
200
382
367
382
367
382
367
243
5
243
220
382
367
382
367
353
324
353
325
353
330
353
339
352
323
352
324
352
329
352
338
353
324
353
325
353
330
353
339
352
323
352
324
352
329
352
338
353
324
353
325
353
330
353
339
352
323
352
324
352
329
352
338
352
323
352
324
352
329
352
338
352
323
352
324
352
329
352
338
352
323
352
324
352
329
352
338
996
534
168
77
168
80
469
16
469
76
367
99
462
431
462
299
462
431
462
299
462
431
462
299
462
431
283
150
462
299
467
464
467
466
462
299
858
264
858
372
858
594
438
61
858
264
858
372
1210
677
1210
692
258
60
258
62
471
365
582
397
469
359
260
63
260
65
466
360
582
398
594
103
594
105
280
265
586
566
2213
2204
586
566
369
345
380
186
439
61
382
303
382
380
155
81
170
96
156
82
288
214
137
72
154
80
381
325
381
331
381
362
381
374
393
291
381
325
381
331
381
362
381
374
381
325
381
331
381
362
381
374
195
180
195
186
325
226
195
180
195
186
653
23
653
253
653
316
653
23
653
316
653
23
653
253
653
319
653
246
158
70
653
326
662
23
662
262
662
325
589
422
662
23
662
23
662
262
662
328
662
335
432
6
432
12
432
37
172
19
882
743
136
3
136
3
103
47
103
47
103
47
721
188
648
337
648
338
103
47
103
47
215
106
215
108
204
112
204
114
823
575
823
653
724
717
724
717
724
717
140
128
209
14
209
81
209
85
209
14
209
81
209
85
209
81
209
85
207
14
207
79
207
83
207
14
207
79
207
83
156
17
156
122
156
125
393
291
933
293
217
208
320
191
320
309
320
310
320
311
314
35
419
383
574
176
378
364
756
176
756
180
417
381
499
152
499
293
378
364
654
344
654
397
654
410
654
562
350
196
415
278
351
197
351
197
390
340
390
384
972
736
972
741
979
743
979
748
978
742
978
747
978
741
978
746
972
736
972
741
672
657
671
661
697
674
697
674
596
411
496
319
802
359
802
580
802
699
494
301
494
308
473
292
473
299
527
411
628
315
509
504
386
71
905
887
940
261
850
281
167
161
172
166
171
165
171
165
487
165
491
165
491
165
466
155
507
311
507
318
507
354
463
282
463
289
463
408
494
301
494
308
494
344
473
418
721
188
172
19
648
337
648
338
456
100
456
248
721
188
648
337
648
338
365
179
365
181
360
179
360
181
365
179
365
181
360
179
360
181
365
179
365
181
360
179
360
181
365
179
365
181
360
179
360
181
360
179
360
181
360
179
360
181
360
322
360
322
472
366
469
359
471
365
582
398
468
358
580
396
469
359
582
398
361
233
361
237
525
77
525
80
525
86
502
244
502
244
199
119
199
147
199
181
438
61
438
327
439
61
1123
445
439
328
439
61
386
45
439
328
439
61
439
61
933
399
439
61
439
61
933
399
439
328
439
61
439
328
172
18
172
19
172
19
172
19
224
76
224
78
224
86
224
76
224
78
224
86
642
164
343
237
128
64
156
64
305
64
690
64
355
249
229
64
609
64
355
249
229
64
761
64
355
249
959
345
959
432
959
345
959
432
959
431
959
447
637
272
313
205
313
205
302
194
1485
1302
744
568
521
401
521
402
657
94
680
89
825
89
571
176
527
176
440
402
386
14
386
32
386
14
386
384
386
17
386
17
386
19
386
19
386
36
386
174
386
261
386
276
386
307
386
307
386
307
386
384
381
14
381
379
381
17
381
17
381
32
462
76
391
8
391
14
391
389
391
17
391
19
391
19
391
32
391
36
391
45
391
45
391
45
391
312
391
389
387
14
387
32
387
45
387
14
387
385
387
17
387
17
387
19
387
19
387
32
387
36
387
45
387
45
387
45
387
175
387
262
387
277
387
308
387
308
387
308
387
385
207
57
207
144
207
159
207
190
207
190
207
190
386
14
386
32
386
45
386
17
386
17
386
19
386
32
386
36
386
45
386
45
280
8
280
8
280
8
280
8
280
132
280
219
280
234
280
265
280
265
391
8
391
14
391
389
391
17
391
17
391
19
391
19
391
179
391
265
391
280
391
312
391
312
391
389
930
398
382
14
382
380
382
17
382
17
382
19
382
19
382
32
382
36
382
303
639
556
591
30
591
117
469
66
284
151
284
268
283
150
283
267
1103
685
1103
933
1103
969
1500
1105
562
466
163
70
249
234
249
235
164
71
933
293
933
399
933
293
933
293
933
399
935
399
254
246
202
164
202
164
444
171
444
171
466
55
339
308
339
53
339
308
733
560
648
258
648
337
193
187
384
159
384
241
384
280
193
187
128
64
128
64
128
64
533
64
128
64
305
64
320
191
320
309
320
310
320
311
320
191
320
309
320
310
320
311
650
198
156
64
311
64
249
234
249
235
431
77
431
77
944
59
944
63
944
67
253
239
253
239
1078
814
1078
824
1151
337
1151
338
1151
402
534
73
787
698
787
698
461
202
379
365
487
386
149
24
149
37
1511
997
140
124
140
128
140
124
140
128
140
124
140
128
140
124
451
130
172
45
172
45
172
63
172
45
172
63
172
45
172
63
499
180
499
181
499
182
499
184
499
186
211
22
211
23
211
42
211
44
840
502
840
801
211
150
210
21
210
22
210
41
210
43
210
149
205
16
205
17
205
36
205
38
205
144
287
196
287
201
287
282
287
201
840
801
839
503
839
800
839
800
325
57
325
183
364
87
364
91
305
64
776
648
283
192
283
192
283
192
283
192
448
21
448
53
466
38
466
71
466
38
466
71
466
71
459
29
459
79
459
97
459
133
335
29
459
29
459
79
459
97
459
133
335
29
442
20
442
68
442
86
442
118
442
20
442
68
442
86
442
118
459
20
459
68
459
86
459
118
459
20
459
68
459
86
459
118
154
102
263
34
417
9
492
201
207
71
510
366
502
446
1193
1135
1193
812
1193
814
1193
1138
1193
967
1199
911
415
214
415
210
316
145
383
108
207
177
676
506
545
422
480
307
480
472
351
197
737
565
393
221
740
576
740
226
740
385
400
225
351
197
431
255
431
421
735
220
556
395
556
24
556
409
556
240
556
392
556
512
788
778
788
776
390
292
390
299
390
231
480
307
525
426
525
411
525
251
525
393
984
815
942
773
1374
837
367
252
430
255
481
308
592
409
592
409
496
319
479
304
735
220
417
242
389
230
389
298
389
291
388
297
388
290
388
229
390
231
390
292
351
197
740
226
390
292
480
307
268
167
390
231
390
292
390
299
391
293
431
255
431
421
390
231
390
299
390
292
388
290
388
297
736
286
390
231
673
504
430
255
592
409
390
231
390
292
390
299
985
951
946
777
390
299
390
292
388
290
388
297
246
59
390
292
246
58
390
299
390
292
390
231
388
290
388
297
390
292
390
299
389
291
389
298
389
291
389
298
389
291
389
298
441
332
441
342
441
342
441
332
445
346
445
336
412
51
392
317
390
292
390
299
391
293
390
292
390
299
391
293
391
300
390
292
390
299
391
293
390
292
390
299
390
292
390
299
390
292
390
299
391
300
420
312
390
231
390
292
390
299
390
292
390
299
390
292
390
299
390
292
390
299
390
231
390
292
390
299
390
292
390
299
390
292
390
299
390
292
390
299
390
231
390
292
390
299
390
292
390
299
390
292
390
299
390
292
390
299
390
231
390
292
390
299
390
292
390
299
390
292
390
299
390
292
390
299

In [110]:
len(nan_accs)

376

In [111]:
len(unmap_accs)

458

In [112]:
len(wierd_accs)

20

In [113]:
dat = dat.reset_index().iloc[:,1:]

In [114]:
dat['valid_check'] = "valid"
dat.loc[nan_accs,'valid_check'] = "nan"
dat.loc[unmap_accs,'valid_check'] = "not_match"
dat.loc[wierd_accs,'valid_check'] = "cannot_index"

In [115]:
dat_valid = dat.loc[dat['valid_check'] == "valid",:]

In [116]:
dat_invalid = dat.loc[dat['valid_check'] != "valid",:]

In [117]:
dat_valid.to_pickle("${SPARK_ACQUISITION_ROOT}/kinase_ml/data/interactions/interaction_exp_cleaned_220921.pkl")

In [118]:
dat_invalid.to_pickle("${SPARK_ACQUISITION_ROOT}/kinase_ml/data/interactions/interaction_exp_unmapped_220921.pkl")

In [119]:
dat = pd.read_pickle("${SPARK_ACQUISITION_ROOT}/kinase_ml/data/interactions/interaction_exp_cleaned_220921.pkl")

In [120]:
for i in range(dat.shape[0]):
    s = dat.iloc[i,:]
#     subseq = s["substrate_seq"][start_ind:end_ind]
    kinase_coord = s["kinase_coord"]
    try: 
        kinseq = s["kinase_seq"][int(kinase_coord[0][0])-1:int(kinase_coord[0][1])]
    except:
        print(i)

28306
28307

In [121]:
dat.loc[29158,"kinase_coord"][0][0] = '1'

In [122]:
dat.loc[29159,"kinase_coord"][0][0] = '1'

In [123]:
dat.to_pickle("${SPARK_ACQUISITION_ROOT}/kinase_ml/data/interactions/interaction_exp_cleaned_220923.pkl")

In [100]:
# https://rest.uniprot.org/uniparc/search?query=P18433-2&format=tsv&fields=id,sequence
# "https://legacy.uniprot.org/uniparc/?query="+"P13789"+ "&format=tab&columns=id,sequence"